### ISSUE TITLE
Unable to install web3 on mac

### ISSUE THREAD

**Issue by chainhead** [ethereum/web3.js#1008]
Web3 installation fails due to `lerna`. I have browsed through other posts that mentions some or the other work-around but none of them worked for me. What is the latest suggested work-around?

```
 nsubrahm$ sudo npm install -g web3

> web3@1.0.0-beta.18 postinstall /usr/local/lib/node_modules/web3
> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! installInDir Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir  problem backing up package.json { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! installInDir   errno: -13,
lerna ERR! installInDir   code: 'EACCES',
lerna ERR! installInDir   syscall: 'rename',
lerna ERR! installInDir   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! installInDir   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
lerna ERR! execute Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! execute   errno: -13,
lerna ERR! execute   code: 'EACCES',
lerna ERR! execute   syscall: 'rename',
lerna ERR! execute   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! execute   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:197
    throw err
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/web3/lerna-debug.log.2838640611'
    at Object.fs.openSync (fs.js:652:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:180:17)
    at writeLogFile (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/utils/writeLogFile.js:43:29)
    at BootstrapCommand._complete (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:310:36)
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:292:20
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/commands/BootstrapCommand.js:140:11
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:44:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.18 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.18 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nsubrahm/.npm/_logs/2017-08-24T04_02_59_714Z-debug.log

```

**Comment by jdkanani** [comment]
Don't use sudo.

**Comment by Schaeff** [comment]
This is not web3 related. I'd recommend using something like https://github.com/creationix/nvm to keep your node installation somewhere else, and not use sudo with npm.
