### ISSUE TITLE
.deploy() function causes error in 1.0

### ISSUE THREAD

**Issue by leopoldjoy** [ethereum/web3.js#1014]
I am trying to deploy a contract with version `1.0` using the below code:

    const SampleContract = new web3.eth.Contract(abi, {from: account.address, gas: 1000000, data: bc});
    SampleContract.deploy({
      data: bc
    })
    .send({ // <--- THIS LINE
      from: account.address,
      gas: 1500000,
      gasPrice: '30000000000000'
    })

However, the commented line causes the following error when run:

    Error: Synchronous requests are not supported.
        at Provider.send (/Users/username/projectpath/node_modules/ethereumjs-testrpc/build/lib.node.js:27230:9)
        at RequestManager.send (/Users/username/projectpath/node_modules/web3/packages/web3-core-requestmanager/src/index.js:129:19)
        at sendRequest (/Users/username/projectpath/node_modules/web3/packages/web3-core-method/src/index.js:525:42)
        at Object.send [as getGasPrice] (/Users/username/projectpath/node_modules/web3/packages/web3-core-method/src/index.js:540:13)
        at Object.send (/Users/username/projectpath/node_modules/web3/packages/web3-core-method/src/index.js:531:34)
        at Object._executeMethod (/Users/username/projectpath/node_modules/web3/packages/web3-eth-contract/src/index.js:876:67)
        at Object.<anonymous> (/Users/username/projectpath/contracts/deploy.js:49:14)
        at Module._compile (module.js:573:30)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)
        at Function.Module.runMain (module.js:609:10)
        at startup (bootstrap_node.js:158:16)
        at bootstrap_node.js:598:3

No matter what I try, I can't seem to get the contract to deploy.

**Comment by frozeman** [comment]
Yes, you need to pass in a callback, or use the `.then(function(){})` to catch the deployment.

**Comment by leopoldjoy** [comment]
@frozeman I continue to get the same error with the below code:

    const SampleContract = new web3.eth.Contract(abi, {from: account.address, gas: 1000000, data: bc});
    SampleContract.deploy({
      data: bc
    })
    .send({ // <--- THIS LINE
      from: account.address,
      gas: 1500000,
      gasPrice: '30000000000000'
    }, () => {
      console.log('sent!');
    });

I also tried using the `.then()` function without success.

**Comment by leopoldjoy** [comment]
@frozeman I successfully resolved the error by changing [line 129](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-requestmanager/src/index.js#L129) of `web3-core-requestmanager` to use the `sendAsync` method. I have submitted a pull request with the fix here: https://github.com/ethereum/web3.js/pull/1018.
