### ISSUE TITLE
lerna bootstrap fails on my system

### ISSUE THREAD

**Issue by conwaychriscosmo** [ethereum/web3.js#1033]
[npm-debug.txt](https://github.com/ethereum/web3.js/files/1296489/npm-debug.txt)
I changed the name of npm-debug.log for github to allow the upload.

I have recieved the same failure for npm install web3, npm install --global web3, and npm install with web3 in the package.json.

**Comment by conwaychriscosmo** [comment]
> web3@1.0.0-beta.18 postinstall /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/web3
> lerna bootstrap

lerna info version 2.1.2
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: Cloning into bare repository '/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: fatal: unable to connect to github.com:
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[0: 192.30.253.113]: errno=Operation timed out
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[1: 192.30.253.112]: errno=Operation timed out
lerna ERR! execute npm ERR! Darwin 16.7.0
lerna ERR! execute npm ERR! argv "/Users/i857529/.nvm/versions/node/v6.9.4/bin/node" "/Users/i857529/.nvm/versions/node/v6.9.4/bin/npm" "install"
lerna ERR! execute npm ERR! node v6.9.4
lerna ERR! execute npm ERR! npm  v4.0.5
lerna ERR! execute npm ERR! code 128
lerna ERR! execute 
lerna ERR! execute npm ERR! Command failed: git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e
lerna ERR! execute npm ERR! Cloning into bare repository '/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
lerna ERR! execute npm ERR! fatal: unable to connect to github.com:
lerna ERR! execute npm ERR! github.com[0: 192.30.253.113]: errno=Operation timed out
lerna ERR! execute npm ERR! github.com[1: 192.30.253.112]: errno=Operation timed out
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! If you need help, you may report this error at:
lerna ERR! execute npm ERR!     <https://github.com/npm/npm/issues>
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/web3/packages/web3-providers-ws/npm-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/execa/index.js:236:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:103:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: Cloning into bare repository '/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: fatal: unable to connect to github.com:
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[0: 192.30.253.113]: errno=Operation timed out
lerna ERR! execute npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[1: 192.30.253.112]: errno=Operation timed out
lerna ERR! execute npm ERR! Darwin 16.7.0
lerna ERR! execute npm ERR! argv "/Users/i857529/.nvm/versions/node/v6.9.4/bin/node" "/Users/i857529/.nvm/versions/node/v6.9.4/bin/npm" "install"
lerna ERR! execute npm ERR! node v6.9.4
lerna ERR! execute npm ERR! npm  v4.0.5
lerna ERR! execute npm ERR! code 128
lerna ERR! execute 
lerna ERR! execute npm ERR! Command failed: git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e
lerna ERR! execute npm ERR! Cloning into bare repository '/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e'...
lerna ERR! execute npm ERR! fatal: unable to connect to github.com:
lerna ERR! execute npm ERR! github.com[0: 192.30.253.113]: errno=Operation timed out
lerna ERR! execute npm ERR! github.com[1: 192.30.253.112]: errno=Operation timed out
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! If you need help, you may report this error at:
lerna ERR! execute npm ERR!     <https://github.com/npm/npm/issues>
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/web3/packages/web3-providers-ws/npm-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/execa/index.js:236:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:103:7)
lerna ERR! execute   stack: 'Error: Command failed: npm install\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: Cloning into bare repository \'/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\'...\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[0: 192.30.253.113]: errno=Operation timed out\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[1: 192.30.253.112]: errno=Operation timed out\nnpm ERR! Darwin 16.7.0\nnpm ERR! argv "/Users/i857529/.nvm/versions/node/v6.9.4/bin/node" "/Users/i857529/.nvm/versions/node/v6.9.4/bin/npm" "install"\nnpm ERR! node v6.9.4\nnpm ERR! npm  v4.0.5\nnpm ERR! code 128\n\nnpm ERR! Command failed: git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\nnpm ERR! Cloning into bare repository \'/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\'...\nnpm ERR! fatal: unable to connect to github.com:\nnpm ERR! github.com[0: 192.30.253.113]: errno=Operation timed out\nnpm ERR! github.com[1: 192.30.253.112]: errno=Operation timed out\nnpm ERR! \nnpm ERR! \nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/web3/packages/web3-providers-ws/npm-debug.log\n\n    at Promise.all.then.arr (/Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/execa/index.js:236:11)\n    at process._tickCallback (internal/process/next_tick.js:103:7)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: Cloning into bare repository \'/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\'...\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[0: 192.30.253.113]: errno=Operation timed out\nnpm ERR! git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e: github.com[1: 192.30.253.112]: errno=Operation timed out\nnpm ERR! Darwin 16.7.0\nnpm ERR! argv "/Users/i857529/.nvm/versions/node/v6.9.4/bin/node" "/Users/i857529/.nvm/versions/node/v6.9.4/bin/npm" "install"\nnpm ERR! node v6.9.4\nnpm ERR! npm  v4.0.5\nnpm ERR! code 128\n\nnpm ERR! Command failed: git clone --template=/Users/i857529/.npm/_git-remotes/_templates --mirror git://github.com/frozeman/WebSocket-Node.git /Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\nnpm ERR! Cloning into bare repository \'/Users/i857529/.npm/_git-remotes/git-github-com-frozeman-WebSocket-Node-git-browserifyCompatible-6c68775e\'...\nnpm ERR! fatal: unable to connect to github.com:\nnpm ERR! github.com[0: 192.30.253.113]: errno=Operation timed out\nnpm ERR! github.com[1: 192.30.253.112]: errno=Operation timed out\nnpm ERR! \nnpm ERR! \nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/node_modules/web3/packages/web3-providers-ws/npm-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/i857529/.nvm/versions/node/v6.9.4/bin/node" "/Users/i857529/.nvm/versions/node/v6.9.4/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! web3@1.0.0-beta.18 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.18 postinstall script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/i857529/src/github.com/EaaS/EaaS-Swagger-API/npm-debug.log

**Comment by conwaychriscosmo** [comment]
proxy issues :(
