### ISSUE TITLE
[1.0] Bluebird - a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by lukehedger** [ethereum/web3.js#1054]
Sending transactions causes the following error:
```
bluebird.js:1468 Warning: a promise was created in a handler but was not returned from it
  at PromiEvent (webpack:///./node_modules/web3/packages/web3-core-promievent/src/index.js?:35:24)
  at Function.PromiEvent.resolve (webpack:///./node_modules/web3/packages/web3-core-promievent/src/index.js?:70:19)
  at checkConfirmation (webpack:///./node_modules/web3/packages/web3-core-method/src/index.js?:247:50)
  at eval (webpack:///./node_modules/web3/packages/web3-core-method/src/index.js?:394:11)
From previous event:
  at Method._confirmTransaction (webpack:///./node_modules/web3/packages/web3-core-method/src/index.js?:392:4)
  at sendTxCallback (webpack:///./node_modules/web3/packages/web3-core-method/src/index.js?:469:24)
  at eval (webpack:///./node_modules/web3/packages/web3-core-requestmanager/src/index.js?:144:9)
  at XMLHttpRequest.request.onreadystatechange (webpack:///./node_modules/web3/packages/web3-providers-http/src/index.js?:64:13)
```

I am able to [fix this warning](https://github.com/lukehedger/web3.js/commit/a651f45a87daf82ff0cd92d2b35b331dbd83863e) but it is hard to know whether this will have any unintended side-effects due to [the complex nested `if` statements here](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-core-method/src/index.js#L394).

@frozeman Please let me know if this fix looks OK and I will open a PR - or, if not, let me know what needs to change.

Related issue: https://github.com/ethereum/web3.js/issues/965
Related commit: https://github.com/ethereum/web3.js/commit/8d3d5f88225fa4e560ea7dd5f1a0b6a298f44955

```
Version: 1.0.0-beta.18
OS: macOS Sierra 10.12.4
Browser: Chrome 61
TestRPC: 4.1.1 (ganache-core: 1.1.2)
```

**Comment by frozeman** [comment]
Thanks i incorporrated your fix in the 1.0 branch. Thanks for spotting!

**Comment by Tankerxyz** [comment]
Same issue
```
Warning: a promise was created in a handler but was not returned from it
    at PromiEvent (http://localhost:3000/static/js/bundle.js:70145:25)
    at Eth.send [as getBalance] (http://localhost:3000/static/js/bundle.js:69960:22)
    at App._this.getAccountBalance (http://localhost:3000/static/js/bundle.js:33362:12)
    at App._this.updateActualState (http://localhost:3000/static/js/bundle.js:33385:14)
    at http://localhost:3000/static/js/bundle.js:33380:16
From previous event:
    at App._this.onGenerate (http://localhost:3000/static/js/bundle.js:33374:45)
    at HTMLUnknownElement.boundFunc (http://localhost:3000/static/js/bundle.js:17717:10)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:17723:17)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:17506:22)
    at Object.executeDispatchesInOrder (http://localhost:3000/static/js/bundle.js:17529:6)
    at executeDispatchesAndRelease (http://localhost:3000/static/js/bundle.js:16927:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/bundle.js:16938:11)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (http://localhost:3000/static/js/bundle.js:17822:10)
    at Object.processEventQueue (http://localhost:3000/static/js/bundle.js:17138:8)
    at runEventQueueInBatch (http://localhost:3000/static/js/bundle.js:24841:19)
    at Object.handleTopLevel [as _handleTopLevel] (http://localhost:3000/static/js/bundle.js:24851:6)
    at handleTopLevelImpl (http://localhost:3000/static/js/bundle.js:29862:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3000/static/js/bundle.js:20361:21)
    at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:29779:27)
    at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:19002:28)
    at dispatchEvent (http://localhost:3000/static/js/bundle.js:29937:21)
```

Version: 1.0.0-beta.30
OS: macOS Sierra 10.13.2

**Comment by mryellow** [comment]
@frozeman 

This seems to have regressed again. I'm seeing it in `v1.0.0-beta.34` also.

https://github.com/ethereum/web3.js/blob/v1.0.0-beta.34/packages/web3-core-method/src/index.js#L430

Struggling to find the code in develop or master, a big refactor in progress?
