### ISSUE TITLE
 web3.eth.estimateGas give 'undefined'

### ISSUE THREAD

**Issue by thackerronak** [ethereum/web3.js#1062]
```
var gas = {
    "to": "0x9f1bc421cc620fc6935a4e20f8a81208d0490915",
    "value": "0x38d7ea4c68000",
    "data": "0xf6cb4587000000000000000000000000339a3f3e18afebecd67ba488ded47efadb6e8171"
}                        
 web3.eth.estimateGas(gas,function (err,res) {
                                            console.log(res)//undefined
                                        })
```
```

same response with method estimate gas
contract.methods.challenge(results.challengeUserAddress).estimateGas({from: results.userAddress}, function(error, gasAmount){
                                            console.log(gasAmount);//undefined
                                        });
```
what's the problem with params?

**Comment by frozeman** [comment]
```js
> var gas = {
...     "to": "0x9f1bc421cc620fc6935a4e20f8a81208d0490915",
...     "value": "0x38d7ea4c68000",
...     "data": "0xf6cb4587000000000000000000000000339a3f3e18afebecd67ba488ded47efadb6e8171"
... }
undefined
>  web3.eth.estimateGas(gas,function (err,res) {
...                                             console.log(err, res)//undefined
...                                         })
> null 22681
```

Could you please check if you got an error? Maybe your connection to the node is not working?

**Comment by thackerronak** [comment]
Error: Returned error: Transaction execution error.
    at Object.ErrorResponse (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/smartSense/Ronak Thacker/Node JS/WordwormBackend/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by frozeman** [comment]
Somnthere you go. This is an error from geth i think. Can you check the geth console and see what it spits out?
@bas-vk @karalabe any idea?

**Comment by thackerronak** [comment]
I'm using infura server.

**Comment by thackerronak** [comment]
can you please tell me your web3js version where you got working?

**Comment by frozeman** [comment]
I guess then you have to use a `from`? Where are the keys sitting?
-> web3.js 1.0.0-beta.21

**Comment by thackerronak** [comment]
tried from key but same result.

**Comment by thackerronak** [comment]
:)
