### ISSUE TITLE
Can't subscribe to "syncing" event.

### ISSUE THREAD

**Issue by huangkuan** [ethereum/web3.js#1150]
Hi,

When I tried to subscribe to "syncing" event, I got the error "This request is not implemented yet. Please create an issue on Github repo.". I am on the latest version web3@1.0.0-beta.24. 

Any estimate on when this event will be supported? And thank you very much for all the work you have put into this project. I can't imagine my life without it!!

**Comment by huangkuan** [comment]
A little bit more details: 
I am running Parity@v1.8.2-beta and using web3.eth.subscribe function. Currently, I am still syncing the chain. I tried to subscribe to "newblockheader" event and it didn't throw any error.

**Comment by huangkuan** [comment]
Posting errors I am getting. Can someone help?

Error: Returned error: This request is not implemented yet. Please create an issue on Github repo.
    at Object.ErrorResponse (/Users/Huang/Documents/Dev/node/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/Users/Huang/Documents/Dev/node/node_modules/web3-core-requestmanager/src/index.js:137:36)
    at /Users/Huang/Documents/Dev/node/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Users/Huang/Documents/Dev/node/node_modules/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/Huang/Documents/Dev/node/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Users/Huang/Documents/Dev/node/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Users/Huang/Documents/Dev/node/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/Users/Huang/Documents/Dev/node/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /Users/Huang/Documents/Dev/node/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Fi1osof** [comment]
web3 1.0.0-beta.31 

Run
```
web3.eth.subscribe("syncing",  console.log);
```
Got 
```
String Error: Returned error: unsupported subscription type
```
web3 WebSocket.WebsocketProvider

**Comment by huangkuan** [comment]
I switched to Geth and everything works.
