### ISSUE TITLE
Failure to send any transactions using WebSocket provider

### ISSUE THREAD

**Issue by TrekDev** [ethereum/web3.js#1202]
Ethereum client: `Parity/v1.8.3-beta-b49c44a19-20171114/x86_64-linux-gnu/rustc1.21.0`
Web3:  `1.0.0-beta.26`
Provider: `let provider = new web3.providers.WebsocketProvider('ws://127.0.0.1:8546');`

Can send txs with HTTP provider but get this with websockets:

```
api_1      | Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
api_1      | {}
api_1      |     at Object._fireError (/app/node_modules/web3-utils/src/index.js:56:17)
api_1      |     at Subscription.checkConfirmation [as callback] (/app/node_modules/web3-core-method/src/index.js:383:26)
api_1      |     at /app/node_modules/web3-core-subscriptions/src/subscription.js:296:19
api_1      |     at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:137:20)
api_1      |     at /app/node_modules/web3-providers-ws/src/index.js:76:44
api_1      |     at Array.forEach (<anonymous>)
api_1      |     at W3CWebSocket.WebsocketProvider.connection.onmessage (/app/node_modules/web3-providers-ws/src/index.js:53:36)
api_1      |     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/node_modules/yaeti/lib/EventTarget.js:107:17)
api_1      |     at W3CWebSocket.onMessage (/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)
api_1      |     at WebSocketConnection.<anonymous> (/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)
api_1      |     at WebSocketConnection.emit (events.js:159:13)
api_1      |     at WebSocketConnection.processFrame (/app/node_modules/websocket/lib/WebSocketConnection.js:547:26)
api_1      |     at /app/node_modules/websocket/lib/WebSocketConnection.js:321:40
api_1      |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
api_1      |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

Similar error using IPC provider:
`let provider = new web.providers.IpcProvider('/app/mnt/parity/jsonrpc.ipc', net);`
```
api_1      | Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
api_1      | {}
api_1      |     at Object._fireError (/app/node_modules/web3-utils/src/index.js:56:17)
api_1      |     at Subscription.checkConfirmation [as callback] (/app/node_modules/web3-core-method/src/index.js:383:26)
api_1      |     at /app/node_modules/web3-core-subscriptions/src/subscription.js:296:19
api_1      |     at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:137:20)
api_1      |     at callback (/app/node_modules/web3-providers-ipc/src/index.js:65:40)
api_1      |     at Array.forEach (<anonymous>)
api_1      |     at Socket.<anonymous> (/app/node_modules/web3-providers-ipc/src/index.js:76:51)
api_1      |     at Socket.emit (events.js:159:13)
api_1      |     at addChunk (_stream_readable.js:265:12)
api_1      |     at readableAddChunk (_stream_readable.js:252:11)
api_1      |     at Socket.Readable.push (_stream_readable.js:209:10)
api_1      |     at Pipe.onread (net.js:598:20)
```

**Comment by TrekDev** [comment]
Not a web3 issue. I was not exposing the websocket/ipc api "pubsub" as explained here: https://github.com/paritytech/parity/issues/7178
Big thanks to @tomusdrw
