### ISSUE TITLE
nginx proxy weird behavior with web3.js

### ISSUE THREAD

**Issue by tymat** [ethereum/web3.js#1208]
We have an nginx proxy that sits in front of our RPC provider.  Running curl commands directly works properly but using web3 gets invalid response

##  Using JSONRPC post with `curl` works fine 

```
$ curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":73}' https://demo.ourbox.com:8546
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 01 Dec 2017 17:23:24 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *

{"id":73,"jsonrpc":"2.0","result":"0x4A817C800"}
```

## From web3.js 0.19.0

```
> var Web3 = require('web3')
> web3.setProvider(new web3.providers.HttpProvider('https://demo.ourbox.com:8546'))
> var web3 = new Web3()
> web3.eth.gasPrice
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/Users/aeufemio/node_modules/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/Users/aeufemio/node_modules/web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/Users/aeufemio/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as gasPrice] (/Users/aeufemio/node_modules/web3/lib/web3/property.js:107:62)
    at repl:1:10
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
```

This works when we access HTTP port and the only difference in the response headers between the SSL and non SSL version is the Server header:

```
$ curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":73}' http://demo.ourbox.com:8545
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Content-Type: application/json
Date: Fri, 01 Dec 2017 17:29:32 GMT
Connection: keep-alive
Transfer-Encoding: chunked

{"id":73,"jsonrpc":"2.0","result":"0x4A817C800"}

$ curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":73}' https://demo.ourbox.com:8546
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 01 Dec 2017 17:30:26 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *

{"id":73,"jsonrpc":"2.0","result":"0x4A817C800"}
```

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
