### ISSUE TITLE
A BigNumber Error after a few calls to get past events

### ISSUE THREAD

**Issue by andyfo** [ethereum/web3.js#1227]
Hello!

I am implementing an event getter in a node.js app like this:

```
contractInstance.MyEventName(null, { fromBlock: 0, toBlock: 'latest' }).get(function(err, result) {
  ...
});
```

I am connected to Infura through a zero client provider.

After calling the `get` method a few times in a timeout, I get this error:

```
{ BigNumber Error: new BigNumber() not a base 16 number:
    at raise (/path_to_project/node_modules/bignumber.js/bignumber.js:1177:25)
    at /path_to_project/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/path_to_project/node_modules/bignumber.js/bignumber.js:212:28)
    at SolidityTypeString.formatOutputString [as _outputFormatter] (/path_to_project/node_modules/web3/lib/solidity/formatters.js:220:19)
    at /path_to_project/node_modules/web3/lib/solidity/type.js:246:25
    at SolidityTypeString.SolidityType.decode (/path_to_project/node_modules/web3/lib/solidity/type.js:247:11)
    at /path_to_project/node_modules/web3/lib/solidity/coder.js:223:29
    at Array.map (<anonymous>)
    at SolidityCoder.decodeParams (/path_to_project/node_modules/web3/lib/solidity/coder.js:222:26)
    at SolidityEvent.decode (/path_to_project/node_modules/web3/lib/web3/event.js:150:34) name: 'BigNumber Error' }
```

The contract address is correct, the getter returns the past events a few times, until it crashes.

(I tried implementing the `watch` method first, but on mainnet I am getting a JSON SyntaxError. Just in case someone is interested: https://github.com/MetaMask/provider-engine/issues/201 - therefore I am trying a different approach.)

**Comment by chankruze** [comment]
This is fixed in latest beta version.Try beta 37 there shouldn't be the issue.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
