### ISSUE TITLE
Web3 reference error

### ISSUE THREAD

**Issue by annanoukou** [ethereum/web3.js#1261]
Hello , 
I open terminal and write `npm install solc` then I try  `Web3 = requires('web3')` and it says:

`ReferenceError: requires is not defined
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:442:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)`

Maybe there is an error in package.json? 
I already checked issues with similar errors but the answers didn't help me.

**Comment by mjhm** [comment]
You probably want `Web3 = require('web3')` (not `requires`)

**Comment by annanoukou** [comment]
I tried `require` but I get the same error!

**Comment by ltfschoen** [comment]
@annanoukou If you're getting the same error it means you're still using `requires` somewhere in your code.
