### ISSUE TITLE
Having a network id with an odd number of digits will cause all transaction calls to fail

### ISSUE THREAD

**Issue by villermen** [ethereum/web3.js#1295]
If the network id used with Geth (and consequently the chainId used in genesis.json) is set to an integer with an odd number of digits, every transaction called through Web3 will result in the following error:

```
invalid argument 0: json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes
      at Object.ErrorResponse (node_modules\web3-core-helpers\src\errors.js:29:16)
      at Object.<anonymous> (node_modules\web3-core-requestmanager\src\index.js:137:36)
      at node_modules\web3-providers-ws\src\index.js:76:44
      at Array.forEach (<anonymous>)
      at W3CWebSocket.WebsocketProvider.connection.onmessage (node_modules\web3-providers-ws\src\index.js:53:36)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (node_modules\yaeti\lib\EventTarget.js:107:17)
      at W3CWebSocket.onMessage (node_modules\websocket\lib\W3CWebSocket.js:234:14)
      at WebSocketConnection.<anonymous> (node_modules\websocket\lib\W3CWebSocket.js:205:19)
      at WebSocketConnection.processFrame (node_modules\websocket\lib\WebSocketConnection.js:547:26)
      at node_modules\websocket\lib\WebSocketConnection.js:321:40
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```
It seems to me that the library is seeing an integer value as a hex value. This does not occur in the Mist wallet with the same node, so it has to be a Web3 error.

Having a chainId in the genesis.json with an odd number of digits and a network id with an even number of digits will not cause this error, but will cause other errors in a different process.

Windows 10 x64
web3 1.0.0-beta.26
Geth 1.7.3 stable

**Comment by nivida** [comment]
Could you please provde more informations to this? for example an code snippet?

**Comment by nivida** [comment]
I've closed this issue because of inactivity.
