### ISSUE TITLE
call web3.eth.accounts.signTransaction return The method net_version does not exist/is not available

### ISSUE THREAD

**Issue by chenyunecjtu** [ethereum/web3.js#1299]
var account = web3.eth.accounts.decrypt({......}, 'wallet');

account.signTransaction({
    to:'0x19c4db4e45742a24b139d7cd36109110cdfa93b6',
    nonce:1,
    value:'10000',
    gas: 2000000
}, account.privateKey).then(signdata=> {
    console.log(signdata);
});

Unhandled rejection Error: Returned error: The method net_version does not exist/is not available
    at Object.ErrorResponse (/Users/chenyun/WebstormProjects/test/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/chenyun/WebstormProjects/test/node_modules/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (/Users/chenyun/WebstormProjects/test/node_modules/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/chenyun/WebstormProjects/test/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/chenyun/WebstormProjects/test/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/chenyun/WebstormProjects/test/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/chenyun/WebstormProjects/test/node_modules/xhr2/lib/xhr2.js:469:24)

**Comment by frozeman** [comment]
Which node are you using? `net_version` is part of the RPC  spec and should be supported. If not you can provide it yourself using `chainId = 1` in the signing parameters.
