### ISSUE TITLE
web3 connected to Infura main net created hash for transactions never found on the chain

### ISSUE THREAD

**Issue by Alex1100** [ethereum/web3.js#1304]
```
const infuraEndpoint = process.env.INFURA_ENDPOINT_MAIN_NETWORK;
const Web3 = require('web3');
const EthTx = require('ethereumjs-tx');
const ethers = require('ethers');
const SHA3 = require('sha3');
const web3 = new Web3(new Web3.providers.HttpProvider(infuraEndpoint));
let n = require('nonce')();

const findPrivateKey = async (req, res, next) => {
  try {
    if (req.body.password) {
      const {
        username,
        password
      } = req.body;
      let user_creds = username + password;

      var d = new SHA3.SHA3Hash('256');
      d.update(user_creds);
      const privateKey = `0x${d.digest('hex')}`;
      req.privateKey = privateKey;
      console.log("PRIVATE KEY IS: ", req.privateKey);
      next();
    } else {
      throw new Error('Must pass in credentials');
    }
  } catch (e) {
    console.log("ERROR: ", e);
    res.status(422).send(e);
  }
}


const sendEth = async (req, res, next) => {
  try {
    if (req.privateKey) {
      const { toAddr, fromAddr, amount } = req.body;

      const currentBalance = await web3.eth.getBalance(fromAddr);
      console.log("CURRENT ADDRESS BALANCE IS: ", currentBalance);

      const currentGasPrice = await web3.eth.getGasPrice();
      console.log("CURRENT GAS PRICE IS: ", currentGasPrice);

      const rawTx = {
        nonce: n(),
        to: toAddr,
        gas: 21000,
        gasPrice: web3.utils.toHex(currentGasPrice),
        gasLimit: web3.utils.toHex(50000),
        value: web3.utils.toHex(web3.utils.toWei(amount, 'ether')),
        data: ""
      };

      const estimatedGasAmount = await web3.eth.estimateGas(rawTx);
      console.log("ESTIMATED GAS IS: ", estimatedGasAmount);

      const fromAddrPKey = req.privateKey.slice(2, req.privateKey.length);
      let fromAddrPKeyX = new Buffer(fromAddrPKey, 'hex');

      const tx = new EthTx(rawTx);
      tx.sign(fromAddrPKeyX);

      let serializedTx = `0x${tx.serialize().toString('hex')}`;

      web3.eth.sendSignedTransaction(serializedTx, (err, data) => {
        if (err) {
          throw new Error(err);
        } else {
          req.sentTransaction = data;
          console.log("IT SENT THE MONEY!!!!!$$$$$$$");
          res.status(201).json({sentTransaction: req.sentTransaction, resStatus: 201})
        }
      });
    } else {
      throw new Error("PAYMENT DIDN'T GO THROUGH");
    }
  } catch (e) {
    console.log("PAYMENT DIDN'T GO THROUGH: ", e.message);
    return res.status(422).send(e.message);
  }
};
```

RESULTS IN: 
```
CURRENT ADDRESS BALANCE IS:  33936365000000000
CURRENT GAS PRICE IS:  51000000000
ESTIMATED GAS IS:  21000
IT SENT THE MONEY!!!!!$$$$$$$
POST /api/send-eth 201 4331.346 ms - 104
{
  "sentTransaction": "0xd4ad9af3a1bacaeceecc729368304e0e5b32cd27f0c9fae231aeb13e63db71d7",
  "resStatus": 201
}
```

but never found on the blockchain and shortly after successfully creating a tx Hash, it issues this warning

```
Unhandled rejection Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined!
    at /Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-method/src/index.js:375:45
    at tryCatcher (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Alex/code/lambda-school-prep-review/personal-projects/chit-chat/node_modules/web3-core-promievent/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by Alex1100** [comment]
I have a hunch it could be insufficient gas or gasLimit, please let me know if that might be the case... Also, I tried so many options with the gas and gasLimit I just don't know how to standardize a hard coded value for the algo...

**Comment by DalderupMaurice** [comment]
I switched from hardcoding my gas to using web3.eth.gasPrice instead. This assures me that MOST of the transactions come through, but transaction costs skyrocket. 

However.. due to the high popularity of crypto's, ICO's, crypto kitties etc.. the memory pool is trashed with transactions and memory pools are a finite source. This results in the miners dropping transactions with a low ROI, which end up disappearing forever. 

Reference:
https://blog.infura.io/when-there-are-too-many-pending-transactions-8ec1a88bc87e

**Comment by Alex1100** [comment]
Yup gas and nonce were the issue getTransactionCount was vital for successful transactions
