### ISSUE TITLE
Invalid JSON RPC response: undefined

### ISSUE THREAD

**Issue by sunnycn2013** [ethereum/web3.js#1312]
hello ,I have run example/node-app.js,but I got errors, who can help me!!

```
/Users/Admin/Documents/ETH/demo/web3/lib/web3/httpprovider.js:101
    throw errors.InvalidResponse(request.responseText);
    ^

Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/Users/admin/Documents/ETH/demo/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/Users/admin/Documents/ETH/demo/web3/lib/web3/httpprovider.js:101:18)
    at RequestManager.send (/Users/admin/Documents/ETH/demo/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as coinbase] (/Users/admin/Documents/ETH/demo/web3/lib/web3/property.js:107:62)
    at Object.<anonymous> (/Users/admin/Documents/ETH/demo/web3/example/node-app.js:8:25)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
admindeMacBook-Pro:example admin$ 

```

**Comment by jdkanani** [comment]
Check if your http server (Ethereum node - testrpc, geth or parity) is running.

**Comment by sunnycn2013** [comment]
@jdkanani   I have in my on the deployment of the geth, and opens the RPC service, I use a Java program to access nodes can be (access to the String url = "http://" + "localhost" + ":" + "8545") , but I was installed on the server web3. Js, execute the web3 inside the warehouse under the example of the demo, has been an error

**Comment by littleredhat1997** [comment]
I have a same problem ......

**Comment by jdkanani** [comment]
@sunnycn2013 Do you use `--rpccorsdomain "*"` for your Geth?

**Comment by sunnycn2013** [comment]
@jdkanani  I have use  `--rpccorsdomain "*"` `--rpccorsdomain "localhost"`，but it aways dosn't work.

**Comment by jdkanani** [comment]
@sunnycn2013 I am not able to produce this bug

**Comment by sunchenxian** [comment]
@sunnycn2013 has this problem been resolved, I have no idle about it, help me

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
