### ISSUE TITLE
TypeError: XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by timp999** [ethereum/web3.js#1314]
Web3 is throwing an error when I attempt to make a call to a smart contract on the server side. If I copy/paste the exact same code into the geth console, it works just fine. This is the call I'm using, and below it is the error log that's being thrown. Last week it worked with no issues, and I haven't changed any of the code. What's going on here?

`ContractInstance.Interval(web3.eth.getTransactionCount(web3.eth.accounts[1]),
     var1, var2, var3, {from: web3.eth.accounts[1], value : var3 * 1000000000000000, gas: 500000});`

`W20180122-13:16:49.037(0)? (STDERR) packages/ethereum_web3.js:4318
W20180122-13:16:49.037(0)? (STDERR)     request = new XMLHttpRequest();
W20180122-13:16:49.038(0)? (STDERR)               ^
W20180122-13:16:49.038(0)? (STDERR) 
W20180122-13:16:49.038(0)? (STDERR) TypeError: XMLHttpRequest is not a constructor
W20180122-13:16:49.039(0)? (STDERR)     at HttpProvider.prepareRequest (packages/ethereum_web3.js:4318:15)
W20180122-13:16:49.039(0)? (STDERR)     at HttpProvider.send (packages/ethereum_web3.js:4337:22)
W20180122-13:16:49.040(0)? (STDERR)     at RequestManager.send (packages/ethereum_web3.js:6347:32)
W20180122-13:16:49.040(0)? (STDERR)     at Eth.get [as accounts] (packages/ethereum_web3.js:6250:62)
W20180122-13:16:49.041(0)? (STDERR)     at Timeout.meterOne [as _onTimeout] (server/callers.js:152:69)
W20180122-13:16:49.041(0)? (STDERR)     at ontimeout (timers.js:475:11)
W20180122-13:16:49.042(0)? (STDERR)     at tryOnTimeout (timers.js:310:5)
W20180122-13:16:49.042(0)? (STDERR)     at Timer.listOnTimeout (timers.js:270:5)
`

**Comment by timp999** [comment]
Self-closing... I still don't know why the calls failed in the project I was building, but I put the code into an empty new project and it runs fine. False alarm.
