### ISSUE TITLE
Invalid RLP-encoding produced (web3-eth-accounts)

### ISSUE THREAD

**Issue by holiman** [ethereum/web3.js#1341]
Allows `-1` as `nonce`:

```

var Web3EthAccounts = require('web3-eth-accounts');
var account = new Web3EthAccounts('ws://localhost:8546');

> account.signTransaction({'nonce':-1, "value":0,"gas":21000,"gasPrice":0, "chainId":1},"0x5384837ece911af85b8b2f2a0e6fe73f5f2add257fc25e1efbeebd4ee72226b7")
{ messageHash: '0x71488a00b0ac6c3f13f230787de8e2cde99e018a9037209ae89f81baf7e7f471',
  v: '0x26',
  r: '0xc0d893f83137b9c82d3b1a602edda9a2d9c92f6714f421f96be08fa200a0b7d8',
  s: '0x3fd99522cf6ea496c7bc4ae2de4807e1d9fb136919462bbfb99012979664ff34',
  rawTransaction: '0xf84c81x18082520880808026a0c0d893f83137b9c82d3b1a602edda9a2d9c92f6714f421f96be08fa200a0b7d8a03fd99522cf6ea496c7bc4ae2de4807e1d9fb136919462bbfb99012979664ff34' }
```

But in fact, it produces an _erroneous_ `rawTransaction`: `0xf84c81x1...` with an `x` in the middle of the data payload.

Same with 
- negative `value`
- negative `gas`
- negative `gasPrice`

Using negative `chainId` makes the RLP even more strange: 
```javascript

var Web3EthAccounts = require('web3-eth-accounts');
var account = new Web3EthAccounts('ws://localhost:8546');

> account.signTransaction({'nonce':1, "value":0,"gas":1,"gasPrice":0, "chainId":-1},"0x5384837ece911af85b8b2f2a0e6fe73f5f2add257fc25e1efbeebd4ee72226b7")
{ messageHash: '0xa090f9d4887116465e139c4ce08be7c4835b97cb5ea10866bbf8694ca0d9fd90',
  v: '0x.8',
  r: '0x12',
  s: '0x5a',
  rawTransaction: '0xf94b.801800180808081.8125a03ba111521e2400ce9a0ac20d27082aa7119a8f6a230495202a5cdf704f9a419ba05079ac7d2bfa62c7f1d2ce8a339d8ad76c2ec3faf2a29c04e0992419f6df2c70' }

```

**Comment by holiman** [comment]
Similar error when `data` contains non-hexadecimal data: 
```
> account.signTransaction({'nonce':1, "value":0,"gas":"1","gasPrice":0, "chainId":1, data:"test"},"0x5384837ece911af85b8b2f2a0e6fe73f5f2add257fc25e1efbeebd4ee72226b7")
{ messageHash: '0xeb3ff8a66c50dd7753952ea0bfe6bca048f1bcd1a7f52412581f0838de492294',
  v: '0x25',
  r: '0x7b1f2865156fa5f41ea5a51f4506dd1f05e6897c1a4ee9365e20b4959a6d63c5',
  s: '0x7fe756922323304d414ac5a2742e3263bc3fd4f6396c5be9d0ffb2a8270e4eb4',
  rawTransaction: '0xf84a018001808081st25a07b1f2865156fa5f41ea5a51f4506dd1f05e6897c1a4ee9365e20b4959a6d63c5a07fe756922323304d414ac5a2742e3263bc3fd4f6396c5be9d0ffb2a8270e4eb4' }

```
`0xf84a018001808081`__`st`__`25a07`

**Comment by holiman** [comment]
This behaviour could severely break stuff: 
```
> account.signTransaction({'nonce':1, "value":0,"gas":"1","gasPrice":0, "chainId":1, data:"0xa\"onError=alert(1)//"},"0x5384837ece911af85b8b2f2a0e6fe73f5f2add257fc25e1efbeebd4ee72226b7")
{ messageHash: '0x239b646c9c82b52d675ec7934174895142a2b2b6513b9da969134a365762b579',
  v: '0x26',
  r: '0xcb45b8fa459526710e01952b254a29046c4dd7ca736d361ed87a20525e84ee0b',
  s: '0x12d55681be34fe67b8e2d6cc158bca72cd76683949b2e370f404e3c0bc6b7d0f',
  rawTransaction: '0xf85301800180808aa"onError=alert(1)//26a0cb45b8fa459526710e01952b254a29046c4dd7ca736d361ed87a20525e84ee0ba012d55681be34fe67b8e2d6cc158bca72cd76683949b2e370f404e3c0bc6b7d0f' }
> 

```

**Comment by holiman** [comment]
Executing code within rlp.js: 
```
> account.signTransaction({'nonce':1, "value":0,"gas":"1","gasPrice":0, "chainId":1, data:{map:function(){console.log("hello world")}}},"0x5384837ece911af85b8b2f2a0e6fe73f5f2add257fc25e1efbeebd4ee72226b7")
hello world
TypeError: Cannot read property 'join' of undefined
    at dataTree (/node_modules/eth-lib/lib/rlp.js:30:36)
    at Array.map (native)
    at dataTree (/node_modules/eth-lib/lib/rlp.js:30:23)
    at Object.encode (/node_modules/eth-lib/lib/rlp.js:36:17)
    at signed (/node_modules/web3-eth-accounts/src/index.js:151:30)
    at Accounts.signTransaction (/node_modules/web3-eth-accounts/src/index.js:189:16)
    at repl:1:9
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:73:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:539:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> 
```

**Comment by frozeman** [comment]
fixed in the next release.
