### ISSUE TITLE
got " callback is not a function"

### ISSUE THREAD

**Issue by leochan007** [ethereum/web3.js#1355]
when using node execute the js file directly.
got error:
TypeError: callback is not a function
    at /home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/web3/lib/web3/property.js:119:13
    at /home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/leo/Documents/src_codes/dapp/bcgrp/ico_tools/trezor/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)

--------------------
var fs=require('fs');
var Web3 = require('web3');
var web3 = new Web3(Web3.givenProvider || new Web3.providers.HttpProvider('http://localhost:8545'));

console.log(process.execPath)
console.log(__dirname)
console.log(process.cwd())

var coinbase = web3.eth.coinbase;
console.log(coinbase);
var balance = web3.eth.getBalance(coinbase);
var gas_price = web3.eth.getGasPrice();

console.log(balance.toNumber());
console.log("gas_price:" + gas_price);

var root = __dirname + "/";
var abi_file = root + "abi_mock.json";
var bytecode_file = root + "bytecode_mock.txt";

var symbol = "ABCToken";
var owner_addr = "0xbb65f9eb3a78ff3ebbc91e182ad9f3337b6329db";
var wallet_addr = "0xabfd9fe724a9c2b357e09aed471bb7241fe94949";

var abi_data = JSON.parse(fs.readFileSync(abi_file,'utf-8'));
//console.log(abi_data);

var bytecode_data = fs.readFileSync(bytecode_file,'utf-8');

var token = web3.eth.contract(abi_data);

byteCodeWithParam = token.new.getData(symbol, wallet_addr, {data: bytecode_data});
console.log(byteCodeWithParam)

**Comment by Dan-Nolan** [comment]
I got this as well, if you set a breakpoint in `property.js` just above you'll notice that the `callback` that it is expecting is from the `web3.eth.getGasPrice()` call. If you set a callback inside there you shouldn't receive this error message anymore.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
