### ISSUE TITLE
Can't call standard method transferFrom, Receive error Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by savao** [ethereum/web3.js#1401]
Hello.
I am trying to test the standard erc223 token function - transferFrom with truffle. I'm writing tests on JS. Tell me what I'm doing wrong.
My token:
```
contract Standard223Token is ERC223, StandardToken {
    ...
    function transferFrom(address _from, address _to, uint _value, bytes _data) returns (bool success) {
        if (!super.transferFrom(_from, _to, _value)) throw;
        // do a normal token transfer
        if (isContract(_to)) return contractFallback(_from, _to, _value, _data);
        return true;
    }

    function transferFrom(address _from, address _to, uint _value) returns (bool success) {
        return transferFrom(_from, _to, _value, new bytes(0));
    }

    //function that is called when transaction target is a contract
    function contractFallback(address _origin, address _to, uint _value, bytes _data) private returns (bool success) {
        ERC223Receiver reciever = ERC223Receiver(_to);
        return reciever.tokenFallback(msg.sender, _value, _data);
    }

    //assemble the given address bytecode. If bytecode exists then the _addr is a contract.
    function isContract(address _addr) private returns (bool is_contract) {
        // retrieve the size of the code on target address, this needs assembly
        uint length;
        assembly {length := extcodesize(_addr)}
        return length > 0;
    }
}
```
The contract that I use to send tokens on it:
```
contract ERC223Receiver {
    function tokenFallback(address _from, uint _value, bytes _data) public pure returns (bool ok) {
        return true;
    }
}
```
My request tio transerFrom function of token:
        ...
        let owner = accounts[0];
        let spender = accounts[10];
        let amount = 100;
        let data = web3.toHex('0x42');

        let contract = await token.deployed();
        let receiver = await erc223receiver.deployed();

        await contract.approve(spender, amount, {'from': owner});
        await contract.transferFrom(owner, receiver.contract.address, amount, data, {'from': spender});
        ...
And I take error eith traceback:

```
Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (/usr/lib/node_modules/truffle/build/cli.bundled.js:37859:16)
      at SolidityFunction.validateArgs (/usr/lib/node_modules/truffle/build/cli.bundled.js:315167:22)
      at SolidityFunction.toPayload (/usr/lib/node_modules/truffle/build/cli.bundled.js:315183:10)
      at SolidityFunction.call (/usr/lib/node_modules/truffle/build/cli.bundled.js:315224:24)
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:298965:16
      at new Promise (<anonymous>)
      at /usr/lib/node_modules/truffle/build/cli.bundled.js:298956:18
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

Please help me figure out exactly what I'm doing wrong and where this error comes from.

**Comment by nivida** [comment]
Please ask this question on https://ethereum.stackexchange.com/
