### ISSUE TITLE
Windows error install web3

### ISSUE THREAD

**Issue by ArmanFeyzi** [ethereum/web3.js#1404]
windows 7
node: v6.11.0
npm: 3.10.10

when i try to install web3 i get this error:

`npm i ethereum/web3.js --save`

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit  ethereum/web3.js resetting remote C:\Users\afeyzi\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ethereum-web3-js-git-6339a8c5 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

**Comment by INTERESTING-OMG** [comment]
I hava the same question and I hava no idea, Who can mail me the web3.js module , 3q,I really want the web3.js which the version is greater than 1.0

**Comment by iurimatias** [comment]
@ArmanFeyzi please try ```npm install web3 --save``` instead

**Comment by Jason-Soo** [comment]
Try "Run as admin in your Powershell or Node.js CMD

1) npm install --global --production windows-build-tools

after the installation is complete

2) npm install web3@1.0.0-beta.20 (or any beta version you like up to 36 if i'm not mistaken)
