### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by solohin** [ethereum/web3.js#1443]
Version: `web3@1.0.0-beta.18`

Code for reproduce

```javascript
const Web3 = require('web3');

const host = 'https://ropsten.infura.io/metamask'
const web3 = new Web3(new Web3.providers.HttpProvider(host));

//add account
const privateKey = '5b0e09ec871d7bca4b00474bb84476857ec1037e75b5013af80869295877605a' //nothing to hide
const account = web3.eth.accounts.privateKeyToAccount('0x' + privateKey);
web3.eth.accounts.wallet.add(account);

const sendParams = {
    "from": account.address,
    "to": "0x3112ebb6d4ea69E76122C2aebb7eeA199A694f66",
    "value": "1069932054000000",
    "gas": "100000",
    "gasPrice": "1000000000"
}

web3.eth.sendTransaction(sendParams).then(result => {
    console.log('result', result)
}).catch(error => {
    console.log('error', error)
})
```

returned error
```
error Error: Returned error: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R
    at Object.ErrorResponse (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-core-helpers/src/errors.js:29:16)
    at /Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-core-requestmanager/src/index.js:137:36
    at XMLHttpRequest.request.onreadystatechange (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/solohin/Projects/cryptosender/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by solohin** [comment]
```javascript
sendParams.value = web3.utils.toWei(web3.utils.fromWei(sendParams.value))
```
Is a possible workaround

**Comment by gburtini** [comment]
How did you generate the value string and what do you believe it to represent?

**Comment by solohin** [comment]
It is a value in wei from an external system, @gburtini

**Comment by nivida** [comment]
Does this still happen in the latest release? @solohin

**Comment by nivida** [comment]
Closed due to no reaction of the creator.
