### ISSUE TITLE
Cannot connect to api.myetherapi.com/eth

### ISSUE THREAD

**Issue by michael-jay-arizala** [ethereum/web3.js#1448]
I have been trying this very simple program which makes a call to the web3.eth.getBalance() method. The HttpProvider is api.myetherapi.com/eth since I am trying the balance of a real ethereum wallet account. However, I am getting an invalid JSON RPC response.

It's weird because it works on a friend's pc. The only way it doesn't work is when I ran it on my pc. I am not sure what I'm missing here, maybe a node tools, or perhaps on C++, I really don't know.

Any help would be great! Thanks!

Here is the error:

```
Error: Invalid JSON RPC response: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nRequest blocked.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: wr2U0u_G_UpO2Az4l2EZMOvv__y-kBuCbzouIXwm2KN_7oLe2mZnWA==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>"
    at Object.InvalidResponse (D:\Documents\Projects\Airflo\node_modules\web3\lib\web3\errors.js:38:16)
    at HttpProvider.send (D:\Documents\Projects\Airflo\node_modules\web3\lib\web3\httpprovider.js:91:22)
    at RequestManager.send (D:\Documents\Projects\Airflo\node_modules\web3\lib\web3\requestmanager.js:58:32)
    at Eth.send [as getBalance] (D:\Documents\Projects\Airflo\node_modules\web3\lib\web3\method.js:145:58)
    at showBalance (D:\Documents\Projects\Airflo\routes\balances.js:15:34)
    at D:\Documents\Projects\Airflo\routes\balances.js:32:13
    at Layer.handle [as handle_request] (D:\Documents\Projects\Airflo\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Documents\Projects\Airflo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Documents\Projects\Airflo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Documents\Projects\Airflo\node_modules\express\lib\router\layer.js:95:5)
```

And here is my code:

```
var express = require('express');
var router = express.Router();

var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.HttpProvider('https://api.myetherapi.com/eth'));

var accounts = ['0x29639dd55c3CE0a295e32D93b0736390d84705cB'];

// web3.eth.getAccounts(function(err,acc){
// 	accounts = acc;
// });

function showBalance(addr) {
	var start = Date.now();
    var latestBalance = web3.eth.getBalance(addr, "latest");
    var nonce = web3.eth.getTransactionCount(addr, "latest");
    var end = Date.now();
    var res = {
		"address": addr,
		"balance": (latestBalance/1000000000) + " GWei / " + ((latestBalance/1000000000)/1000000000) + " ETH",
		"nonce": nonce.toString(),
		"time": (end - start).toString() + "ms"
    }
    return res;
}

// Balances page
router.get('/all', function(req, res) {

	var data = {};
	for(var i = 0; i < accounts.length; i++) {
		data[i] = showBalance(accounts[i]);
	}
	res.render('balances', {data})
})


module.exports = router;
```

**Comment by t0dd-kr** [comment]
hi, check this.
https://ethereum.stackexchange.com/questions/24737/myetherwallet-json-rpc-interface-ratelimiting/25113#25113

**Comment by iurimatias** [comment]
closing as per @t0dd-kr reply
