### ISSUE TITLE
beta.31:  Packages seem to have visibility issues between each other. 

### ISSUE THREAD

**Issue by Freydal** [ethereum/web3.js#1462]
I attempted to update to beta.30 to test the 50 block issue.  I lazily ran `npm i web3` and noticed it went to beta.31.  When I attempted to run a project with this version I was getting some webpack errors with Can't resolve module. I attempted try it in another project and had similar results.

In both projects running `node`:
```
> require('web3')
Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
> 
```

In a clean directory I created a new project:
```
npm init
npm i web3@1.0.0-beta.31
node
```
Running `require('web3')` returns successfully.

Any ideas?

**Comment by Freydal** [comment]
I continued attempting to check into this issue.   I was able to eliminate my machine as the issue by attempting to rebuild the docker container.  

I was also able to reset everything to a previous commit and get beta.29 to work successfully again.  I continued to search for the issue.

I updated the version in my project's package.json to both beta.30 and beta.31 inspected the resulting web3 module in the node_modules directory.  I made copies of the resulting directories for further inspection.  I found that the only differences were in the package.json and were only on the lines with beta.31 or beta.30.

For example:
```JSON
{
  "_from": "web3@^1.0.0-beta.31",
  "_id": "web3@1.0.0-beta2",
  "_inBundle": false,
  "_integrity": "sha1-vek+K4jEMWc/JdgSmCIaHsKxqe8=",
  "_location": "/web3",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "web3@^1.0.0-beta.31",
    "name": "web3",
    "escapedName": "web3",
    "rawSpec": "^1.0.0-beta.31",
    "saveSpec": null,
    "fetchSpec": "^1.0.0-beta.31"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/web3/-/web3-1.0.0-beta2.tgz",
  "_shasum": "bde93e2b88c431673f25d81298221a1ec2b1a9ef",
  "_spec": "web3@^1.0.0-beta.31",
  "_where": "/Users/Freydal/RubymineProjects/paradigm",
  "author": {
    "name": "ethereum.org"
  },
  "authors": [
    {
      "name": "Fabian Vogelsteller",
      "email": "fabian@ethereum.org",
      "homepage": "http://frozeman.de"
    },
    {
      "name": "Marek Kotewicz",
      "email": "marek@ethcore.io",
      "url": "https://github.com/debris"
    },
    {
      "name": "Marian Oancea",
      "url": "https://github.com/cubedro"
    },
    {
      "name": "Gav Wood",
      "email": "g@ethcore.io",
      "homepage": "http://gavwood.com"
    },
    {
      "name": "Jeffery Wilcke",
      "email": "jeffrey.wilcke@ethereum.org",
      "url": "https://github.com/obscuren"
    }
  ],
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "Ethereum JavaScript API",
  "devDependencies": {
    "babel-preset-env": "^1.6.0",
    "bignumber.js": "^4.0.0",
    "bn.js": "^4.11.6",
    "bower": ">=1.4.1",
    "browserify": "^14.4.0",
    "chai": "^3.0.0",
    "coveralls": "^2.11.2",
    "crypto-js": "^3.1.4",
    "del": ">=2.0.2",
    "ethereumjs-wallet": "^0.6.0",
    "ethjs-signer": "^0.1.1",
    "exorcist": "^0.4.0",
    "gulp": ">=3.9.0",
    "gulp-babel": "^6.1.2",
    "gulp-jshint": "^2.0.4",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.6.1",
    "gulp-streamify": "^1.0.2",
    "gulp-uglify": "^3.0.0",
    "istanbul": "^0.4.4",
    "jshint": ">=2.5.0",
    "lerna": "^2.0.0",
    "mocha": ">=2.3.3",
    "sandboxed-module": "^2.0.2",
    "underscore": "^1.8.3",
    "vinyl-source-stream": "^1.1.0"
  },
  "directories": {
    "lib": "./src",
    "doc": "./doc",
    "test": "./test"
  },
  "homepage": "https://github.com/ethereum/web3.js",
  "keywords": [
    "Ethereum",
    "JavaScript",
    "API"
  ],
  "license": "LGPL-3.0",
  "main": "./src/index.js",
  "name": "web3",
  "namespace": "ethereum",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ethereum/web3.js.git"
  },
  "scripts": {
    "build": "gulp",
    "lint": "jshint *.js packages",
    "test": "mocha; jshint *.js packages",
    "test-coveralls": "istanbul cover _mocha -- -R spec && cat coverage/lcov.info | coveralls --verbose",
    "watch": "gulp watch"
  },
  "version": "1.0.0-beta2"
}
```

It seems that npm was causing the issue somehow.  I found that I got successful results when ran `npm i web3@1.0.0-beta.31` instead of  updating my package.json and then running `npm i`.
