### ISSUE TITLE
Unable to require web3 in node console

### ISSUE THREAD

**Issue by amand1996** [ethereum/web3.js#1481]
I'm trying to require web3js in nodejs. But the following error occurs every time. I installed the module `xmlhttprequest`, but still the problem remains. Can someone please help me with this?
```
[~/Desktop/votechain-backend/blockchain]$ node> web3 = require('web3');
Error: Cannot find module 'xmlhttprequest'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aman/Desktop/votechain-backend/blockchain/node_modules/web3/lib/web3/httpprovider.js:34:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by amand1996** [comment]
I deleted the node_modules folder and reinstalled. Got it working
