### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by k06a** [ethereum/web3.js#1497]
I got error on throwing error in `web3-utils@1.0.0-beta.30` :)
```
connection not open on send()
C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-utils\src\index.js:49
            error.data = JSON.stringify(error.data, null, 2);
                              ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object._fireError (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-utils\src\index.js:49:31)
    at Subscription.checkConfirmation [as callback] (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-core-method\src\index.js:383:26)
    at Object.callback (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-core-subscriptions\src\subscription.js:292:27)
    at C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-core-requestmanager\src\index.js:106:49
    at Array.forEach (<anonymous>)
    at requestManagerNotification (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-core-requestmanager\src\index.js:104:50)
    at C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-providers-ws\src\index.js:106:17
    at Array.forEach (<anonymous>)
    at W3CWebSocket.connection.onclose (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\web3-providers-ws\src\index.js:104:16)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:126:13)
    at WebSocketConnection.emit (events.js:214:7)
    at WebSocketConnection.handleSocketClose (C:\Users\Head\Desktop\VipCoinMiner-master\node_modules\websocket\lib\WebSocketConnection.js:382:14)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:567:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

**Comment by iurimatias** [comment]
@k06a are you still experiencing this issue in web3-utils@1.0.0-beta.34?

**Comment by DalderupMaurice** [comment]
Same here @iurimatias 
I can't store the web3 instance as it's not serializable due to these circular structures

**Comment by nivida** [comment]
I think thats not a problem that web3.js can solve please ask this question on stackoverflow.

**Comment by k06a** [comment]
@nivida this happens inside your web3 source code.

**Comment by nivida** [comment]
@k06a I've tested the serialization of the web3 object because @DalderupMaurice mentioned it above. I missed that this is not the actual problem here in this issue, sorry for that. But could you please provide more informations to reproducing this issue? I'll reopen this issue now.

**Comment by k06a** [comment]
@nivida sorry, I don't remember what happened. Maybe I subscribed to some topic and when it happened it fails on error serialization...

**Comment by nivida** [comment]
@k06a Okay if you can remember it or the error throws again please create an new issue with detailed informations for reproducing it thanks. :)
