### ISSUE TITLE
Geth v1.8.3 break Web3 websockets

### ISSUE THREAD

**Issue by ekryski** [ethereum/web3.js#1548]
**Geth Version:** v1.8.3
**Web3 Version:** 1.0.0-beta.30-1.0.0-beta.34

I think the recent release of Geth and the change they made to websockets returns some invalid format that Web3 chokes on. It's hard to tell but it looks like Geth shuts down the socket connection.

The error we get client side is:

```
            if(!id && result.method.indexOf('_subscription') !== -1) {
                                    ^

TypeError: Cannot read property 'indexOf' of undefined
    at /node_modules/web3-providers-ws/src/index.js:70:37
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/node_modules/web3-providers-ws/src/index.js:55:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> /node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame /node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

and when I logged out the socket response it looks like this:

```js
_Event {
  type: 'message',
  isTrusted: false,
  _yaeti: true,
  data: '{"jsonrpc":"2.0","error":{"code":-32600,"message":"unexpected EOF"}}',
  target:
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: 'http://localhost:8546',
     _readyState: 1,
     _protocol: undefined,
     _extensions: [],
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection:
      WebSocketConnection {
        _debug: [Object],
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        _pingListenerCount: 0,
        config: [Object],
        socket: [Object],
        protocol: undefined,
        extensions: [],
        remoteAddress: '127.0.0.1',
        closeReasonCode: -1,
        closeDescription: null,
        closeEventEmitted: false,
        maskOutgoingPackets: true,
        maskBytes: <Buffer 55 ed 41 64>,
        frameHeader: <Buffer 81 44 00 ba 00 00 00 01 72 41>,
        bufferList: [Object],
        currentFrame: [Object],
        fragmentationSize: 0,
        frameQueue: [],
        connected: true,
        state: 'open',
        waitingForCloseResponse: false,
        receivedEnd: false,
        closeTimeout: 5000,
        assembleFragments: true,
        maxReceivedMessageSize: 8388608,
        outputBufferFull: false,
        inputPaused: false,
        receivedDataHandler: [Function: bound ],
        _closeTimerHandler: [Function: bound ],
        webSocketVersion: 13 },
     _client:
      WebSocketClient {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        _req: null,
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: false,
        base64nonce: 'Zxd3DNBk5HpdRNOprdZ7fw==',
        socket: [Object],
        response: [Object],
        firstDataChunk: null },
     onerror: [Function],
     onclose: [Function],
     onmessage: [Function] },
  cancelable: true,
  stopImmediatePropagation: [Function] }
```

**Comment by cgewecke** [comment]
@zaro Do you have any other info about when / how this error is being triggered for you? Summary of mine is:
+ 1.0-beta33
+ OS: OSX **and** Ubuntu (Trusty)
+ Geth 1.8.6 (From docker, run with `--dev --period 1` flags)
+ Smaller contracts deploy without problems, method calls and events work as expected.  
+ Larger contract deployments trigger an EOF response from client and client disconnects.

**Comment by zaro** [comment]
Here it is:

- web3 1.0-beta33
- OS: Ubuntu (Bionic in Virtualbox) , cannot reproduce on macOS Sierra with same geth&web3
- Geth 1.8.8
- Small contracts deploy fine, a contract which uses 2511586 gas fails to deploy
- The contract deploys w/o error on geth 1.8.2

**Comment by cz3kit** [comment]
I am facing the same problem. Hee is my summary:

- web3 1.0.0-beta34
- OS: Ubuntu 16.04.4 LTS in HyperV
- Geth 1.8.9 stable
- Contract deploy fine
- Sending large chunks of data to a function causes this problem

I found also this here: https://github.com/DigixGlobal/ethereum-ruby/issues/5
Not sure if it is somehow related.

**Comment by cgewecke** [comment]
@cz3kit Thanks for finding the limit - just opened an issue at Geth, link above.

**Comment by cz3kit** [comment]
@cgewecke Alright, you had been faster then me :) Hope it gets fixed soon

**Comment by ekryski** [comment]
Sorry there peeps. I have not found a solution. Unfortunately we've been forced to run Geth v1.8.2 so far.
