### ISSUE TITLE
Events containing indexed string causes ERROR: The returned value is not a convertible string

### ISSUE THREAD

**Issue by rustyx** [ethereum/web3.js#1566]
**I know indexed strings aren't stored in the logs**

But it is impossible to subscribe to events that contain **indexed string** parameters at all. Any attempt to do so just crashes.

Tested with web3-eth 1.0.0-beta.33.

**Test.sol:**
```
pragma solidity ^0.4.21;
contract Test {
    event Updated(address from, string indexed data);
    function test(string _data) public {
        emit Updated(msg.sender, _data);
    }
}
```

**test.js:**
```
const Web3Eth = require('web3-eth');
const eth = new Web3Eth('ws://127.0.0.1:8546');

const addr = "0x79b79127fcb21120bce34a41d89dd52bd826b552"; // update to match deployed contract
const abi = [{"constant":false,"inputs":[{"name":"_data","type":"string"}],"name":"test","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"from","type":"address"},{"indexed":true,"name":"data","type":"string"}],"name":"Updated","type":"event"}];
const contract = new eth.Contract(abi, addr);
contract.events.Updated().subscribe((err, res) => {
  console.log("Updated", err, res);
});
```

**Crashes with:**
```
Error: ERROR: The returned value is not a convertible string:
    at SolidityTypeString.formatOutputString [as _outputFormatter] (node_modules\web3-eth-abi\src\formatters.js:249:15)
    at node_modules\web3-eth-abi\src\type.js:246:25
    at SolidityTypeString.SolidityType.decode (node_modules\web3-eth-abi\src\type.js:247:11)
    at node_modules\web3-eth-abi\src\index.js:327:49
    at Array.forEach (<anonymous>)
    at ABICoder.decodeParameters (node_modules\web3-eth-abi\src\index.js:326:13)
    at ABICoder.decodeLog (node_modules\web3-eth-abi\src\index.js:371:30)
    at Object.Contract._decodeEventABI (node_modules\web3-eth-contract\src\index.js:371:31)
    at Subscription._formatOutput (node_modules\web3-core-subscriptions\src\subscription.js:123:84)
    at node_modules\web3-core-subscriptions\src\subscription.js:263:44
```

**Subscribing to events containing indexed strings should still work even if the *value* of the indexed strings isn't available in the callback.**

**Comment by jchen86** [comment]
Created PR #1626.

I ran into the same problem using `1.0.0-beta.33`. I agree that subscribing to events containing indexed strings should still work since it's supported by solidity.

**Comment by frozeman** [comment]
This should be fixed once the newAbiLib branch is merged.
