### ISSUE TITLE
Issue with installing web3@1.0.0-beta.34

### ISSUE THREAD

**Issue by Lazhari** [ethereum/web3.js#1568]
I'm under :
System Version: macOS 10.13.4 (17E199)
Kernel Version: Darwin 17.5.0
npm: 5.6.0
node: v8.11.1
python: 2.7.14

```
$ npm install web3@1.0.0-beta.34
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/local/bin/python" in the PATH
gyp verb `which` succeeded /usr/local/bin/python /usr/local/bin/python
gyp verb check python version `/usr/local/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.14\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.1
gyp verb build dir attempting to create "build" dir: /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/build
gyp verb build dir "build" dir needed to be created? /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt60l.dat',
gyp sill build/config.gypi      icu_data_in: '../../deps/icu-small/source/data/in/icudt60l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '60',
gyp sill build/config.gypi      llvm_version: 0,
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_nghttp2: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: true,
gyp sill build/config.gypi      node_use_etw: false,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: false,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: '57.dylib',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      uv_parent_path: '/deps/uv/',
gyp sill build/config.gypi      uv_use_dtrace: true,
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      xcode_version: '7.0',
gyp sill build/config.gypi      nodedir: '/Users/macbookproretina13/.node-gyp/8.11.1',
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      viewer: 'man',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      globalignorefile: '/Users/macbookproretina13/.npm-packages/etc/npmignore',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      shell: '/bin/zsh',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      globalconfig: '/Users/macbookproretina13/.npm-packages/etc/npmrc',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      global_style: '',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      json: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      init_module: '/Users/macbookproretina13/.npm-init.js',
gyp sill build/config.gypi      userconfig: '/Users/macbookproretina13/.npmrc',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      node_version: '8.11.1',
gyp sill build/config.gypi      user: '502',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      editor: 'vi',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      progress: 'true',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      node_gyp: '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      unicode: 'true',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      save_prefix: '~',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      save_exact: 'true',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      group: '20',
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      cache: '/Users/macbookproretina13/.npm',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      user_agent: 'npm/5.6.0 node/v8.11.1 darwin x64',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      production: '',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      umask: '0022',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      tmp: '/var/folders/0w/3yfmzypx2wj9xc7hl06sp8n40000gp/T',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      prefix: '/Users/macbookproretina13/.npm-packages',
gyp sill build/config.gypi      link: '' } }
gyp verb build/config.gypi writing out config file: /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/config.gypi
gyp verb common.gypi checking for gypi file: /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/local/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/macbookproretina13/.node-gyp/8.11.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/macbookproretina13/.node-gyp/8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/macbookproretina13/.node-gyp/8.11.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/macbookproretina13/.node-gyp/8.11.1
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
In file included from ../src/scryptwrapper/keyderivation.c:27:
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:24:2: error: unknown type name 'uint32_t'
        uint32_t state[8];
        ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:25:2: error: unknown type name 'uint64_t'
        uint64_t count;
        ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:26:2: error: unknown type name 'uint8_t'
        uint8_t buf[64];
        ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:46:19: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void SHA256_Final(uint8_t[32], SHA256_CTX *);
                  ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:52:39: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void SHA256_Buf(const void *, size_t, uint8_t[32]);
                                      ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:78:24: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void HMAC_SHA256_Final(uint8_t[32], HMAC_SHA256_CTX *);
                       ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:85:66: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
void HMAC_SHA256_Buf(const void *, size_t, const void *, size_t, uint8_t[32]);
                                                                 ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:92:26: error: unknown type name 'uint8_t'
void PBKDF2_SHA256(const uint8_t *, size_t, const uint8_t *, size_t,
                         ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:92:51: error: unknown type name 'uint8_t'
void PBKDF2_SHA256(const uint8_t *, size_t, const uint8_t *, size_t,
                                                  ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:93:5: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    uint64_t, uint8_t *, size_t);
    ^
../scrypt/scrypt-1.2.0/libcperciva/alg/sha256.h:93:15: error: unknown type name 'uint8_t'
    uint64_t, uint8_t *, size_t);
              ^
In file included from ../src/scryptwrapper/keyderivation.c:28:
../src/scryptwrapper/inc/hash.h:29:26: error: unknown type name 'uint8_t'
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                         ^
../src/scryptwrapper/inc/hash.h:29:50: error: unknown type name 'uint8_t'
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                 ^
../src/scryptwrapper/inc/hash.h:29:68: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                                   ^
../src/scryptwrapper/inc/hash.h:29:78: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                                             ^
../src/scryptwrapper/inc/hash.h:29:88: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                                                       ^
../src/scryptwrapper/inc/hash.h:29:88: error: redefinition of parameter 'uint32_t'
../src/scryptwrapper/inc/hash.h:29:78: note: previous declaration is here
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                                             ^
../src/scryptwrapper/inc/hash.h:29:98: error: unknown type name 'uint8_t'
ScryptHashFunction(const uint8_t*, size_t, const uint8_t*, size_t, uint64_t, uint32_t, uint32_t, uint8_t*, size_t);
                                                                                                 ^
In file included from ../src/scryptwrapper/keyderivation.c:29:
../src/scryptwrapper/inc/pickparams.h:31:18: error: unknown type name 'uint32_t'
pickparams(int*, uint32_t*, uint32_t*, double, size_t, double, size_t);
                 ^
../src/scryptwrapper/inc/pickparams.h:31:29: error: unknown type name 'uint32_t'
pickparams(int*, uint32_t*, uint32_t*, double, size_t, double, size_t);
                            ^
In file included from ../src/scryptwrapper/keyderivation.c:30:
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:20:15: error: unknown type name 'uint16_t'
static inline uint16_t
              ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:23:8: error: unknown type name 'uint8_t'
        const uint8_t * p = (uint8_t const *)pp;
              ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:23:23: error: use of undeclared identifier 'uint8_t'
        const uint8_t * p = (uint8_t const *)pp;
                             ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:25:11: error: use of undeclared identifier 'uint16_t'
        return ((uint16_t)(p[1]) + ((uint16_t)(p[0]) << 8));
                 ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:25:31: error: use of undeclared identifier 'uint16_t'
        return ((uint16_t)(p[1]) + ((uint16_t)(p[0]) << 8));
                                     ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:29:20: error: unknown type name 'uint16_t'
be16enc(void * pp, uint16_t x)
                   ^
../scrypt/scrypt-1.2.0/libcperciva/util/sysendian.h:31:2: error: use of undeclared identifier 'uint8_t'
        uint8_t * p = (uint8_t *)pp;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
8 warnings and 20 errors generated.
make: *** [Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/macbookproretina13/Projects/Udemy/Ethereum Training/test/node_modules/scrypt
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbookproretina13/.npm/_logs/2018-04-20T00_55_06_173Z-debug.log
```

I think the issue is related to [scrypt](https://github.com/barrysteyn/node-scrypt) package, because I tried to install it separately and I got the same error.

**Comment by williamchong007** [comment]
it seems that your gcc/clang installation is broken, so it cannot compile native binary packages
try reinstalling xcode/xcode command line tools, or follow the suggestions in 
https://stackoverflow.com/questions/48029309/cannot-compile-any-c-programs-error-unknown-type-name-uint8-t ?

**Comment by Lazhari** [comment]
Thank you @williamchong007

**Comment by gitpusha** [comment]
Hi everyone,
I posted this under [this](https://github.com/ethereum/web3.js/issues/1588) issue in the ethereum/web3.js repo. But not sure whether it is actually more relevant here, so here goes again:
Suddenly since yesterday I cannot npm install web3 any more. I am using MacOs and hombrew node. The only change that might have caused this is that I think I ran a brew update and brew upgrade recently.
npm -v 6.9.0
node -v v12.1.0

The problem seems to have something to do with sha3 and node-gyp. I saw this issue which seems to be related. Can anyone please help me out or point me to a solution for macOS with my node and npm versions? @onpaws **Could it be that sha3 has an issue with node12.1.0?**

error message:
10 warnings and 12 errors generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at ChildProcess.emit (events.js:196:13)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xyz/Desktop/udemy/udemy-eth-sol/projects/kickstart/node_modules/sha3
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN kickstart@1.0.0 No description
npm WARN kickstart@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules/scrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: node-gyp rebuild
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hmijail** [comment]
In case it helps: I just started finding similar problems after upgrading brew - but in my case it was while building scrypt@6.0.3. Not sure what happened, and I'm too new to the JS ecosystem.
After some googling looks like there are various reports of node-gyp failing with node 12 on macOS 10.14.5. In my case, going back to node@10 in brew allowed me to install web3.

**Comment by gitpusha** [comment]
hi @hmijail . I did the same as you and used brew to go install and link node@10. That seems to resolve the issues I have had with node --version 12.
