### ISSUE TITLE
How to use web3.js with TypeScript?

### ISSUE THREAD

**Issue by max-block** [ethereum/web3.js#1597]
Here is a minimal code for testing:

    import * as Web3 from "web3"
    
    const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:7545"))
    
    const main = async () => {
      const blockNumber = await web3.eth.getBlockNumber()
      console.log({ blockNumber })
    }
    
    main().catch(err => console.error(err))

The module typings are wrong. If I try to compile it, there are some errors:

    maxblock@mbp t10-web3-typescript *$ npm run build
    
    > t10-web3-typescript@1.0.0 build /Users/maxblock/projects/test/t10-web3-typescript
    > rimraf dist && tsc
    
    ../../../node_modules/web3/types.d.ts(1,27): error TS7016: Could not find a declaration file for module 'bn.js'. '/Users/maxblock/node_modules/bn.js/lib/bn.js' implicitly has an 'any' type.
      Try `npm install @types/bn.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'bn.js';`
    ../../../node_modules/web3/types.d.ts(2,21): error TS7016: Could not find a declaration file for module 'underscore'. '/Users/maxblock/node_modules/underscore/underscore.js' implicitly has an 'any' type.
      Try `npm install @types/underscore` if it exists or add a new declaration (.d.ts) file containing `declare module 'underscore';`
    src/index.ts(3,14): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
    src/index.ts(3,32): error TS2339: Property 'providers' does not exist on type 'typeof "/Users/maxblock/node_modules/web3/index"'.

OK. Next, I tried to override typings with my own. For this reason, I've created a file typings.d.ts with simple stub: `declare module "web3"`.

There are fewer errors with my own typings, but anyway I can't compile it:

    maxblock@mbp t10-web3-typescript *$ npm run build
    
    > t10-web3-typescript@1.0.0 build /Users/maxblock/projects/test/t10-web3-typescript
    > rimraf dist && rimraf node_modules/web3/index.d.ts && rimraf node_modules/web3/types.d.ts && tsc
    
    ../../../node_modules/web3/types.d.ts(1,27): error TS7016: Could not find a declaration file for module 'bn.js'. '/Users/maxblock/node_modules/bn.js/lib/bn.js' implicitly has an 'any' type.
      Try `npm install @types/bn.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'bn.js';`
    ../../../node_modules/web3/types.d.ts(2,21): error TS7016: Could not find a declaration file for module 'underscore'. '/Users/maxblock/node_modules/underscore/underscore.js' implicitly has an 'any' type.
      Try `npm install @types/underscore` if it exists or add a new declaration (.d.ts) file containing `declare module 'underscore';`

I've even tried deleting node_modules/web3/index.d.ts and node_modules/web3/types.d.ts files, but without success.

How do you work with web3.js + TypeScript?

**Comment by Spaider15** [comment]
Same issue, you need to delete first to imports in inside web3 folder types.d.ts, and they uses, BigNumber and underscore.
But this is temporary workaround

**Comment by robrobbins** [comment]
I'm currently spec'ing out a TCR with web3 beta and TS. Feel free to checkout the `spec` directory for some things we are doing at Computable with these 2 (web3/TS).

I'm putting a couple PRs together now for TS corrections...

**Comment by Levino** [comment]
Hey all. I am sorry but I cannot follow. Can someone please reiterate for dummies like me on how to fix this? Thanks you very much in advance.

**Comment by max-block** [comment]
@Levino 

As workaround you can use require syntax: `const Web3 = require("web3");` instead of import.

There will be no typings, but it compiles.

**Comment by jintoppy** [comment]
I am able to solve the above mentioned issue by importing  as default.

`import Web3 from "web3";`

**Comment by max-block** [comment]
@jintoppy Yes, it really compiles with "noImplicitAny": false.

But for me it only compiles, can't run.
Here is a demo code:


```
import Web3 from "web3"
// const Web3 = require("web3")
const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:7545"))

const main = async () => {
  const blockNumber = await web3.eth.getBlockNumber()
  console.log({ blockNumber })
}

main().catch(err => console.error(err))

```

When I run it, there is an error:

```
maxblock@mbp t10-web3-typescript (master)*$ node dist
/Users/maxblock/projects/test/t10-web3-typescript/dist/index.js:13
const web3 = new web3_1.default(new web3_1.default.providers.HttpProvider("http://localhost:7545"));
                                                   ^

TypeError: Cannot read property 'providers' of undefined
    at Object.<anonymous> (/Users/maxblock/projects/test/t10-web3-typescript/dist/index.js:13:52)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
```

Here is a link on repo with this example. Can you please check, does it work for you?

https://github.com/max-block/t10-web3-typescript

**Comment by Levino** [comment]
The correct syntax to import Web3 is
```ts
import Web3 = require('web3')
```
because the module uses
```js
module.exports = Web3;
```
However the type definitions are incorrect:
https://github.com/ethereum/web3.js/blob/c0e727eac7c16826c39fd43a03a4930b5ff6fff8/packages/web3/index.d.ts#L27
which should be
```ts
export = Web3;
```

**Comment by Levino** [comment]
Here is the commit breaking the type definitions c0a4f0a5bec80301bc45c41782a95af3bfd9babe

**Comment by max-block** [comment]
@Levino 
`import Web3 = require('web3')`

This doesn't work for me, when I compile it, there is an error:
```
maxblock@mbp t10-web3-typescript (master)*$ npm run build

> t10-web3-typescript@1.0.0 build /Users/maxblock/projects/test/t10-web3-typescript
> rimraf dist && tsc

src/index.ts(3,14): error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
src/index.ts(3,32): error TS2339: Property 'providers' does not exist on type 'typeof "/Users/maxblock/projects/test/t10-web3-typescript/node_modules/web3/index"'.

```

**Comment by Levino** [comment]
Which type definitions are you using? The ones from here are broken, as I am saying. I cannot work. You have to fix them by hand.

**Comment by Levino** [comment]
Okay I "fixed" it for me locally until this madness is resolved properly.
First you have to add a postinstall script in your `package.json` like so:
```json
{
  "postinstall": "rm node_modules/web3/index.d.ts"
}
```
This will remove the incorrect type definitions shipped with web3.
Then you need to add [these two module augmentation files](https://gist.github.com/Levino/8bb6f7ccc9a4becdfe025f814f18ee61) to your codebase and make sure typescript loads it. For example put them in a folder `typings` and add to your `tsconfig.json`:
```json
{
  "typeRoots": [
    "./node_modules/@types/",
    "./typings/"
  ]
}
```

**Comment by wmira** [comment]
my web3 typescript project works fine.. https://github.com/wmira/ethereum-notification/blob/master/src/index.ts#L2

**Comment by Levino** [comment]
What does your tsconfig look like?

**Comment by wmira** [comment]
have you tried? 
import { default as Web3 } from "web3" 

my tsconfig is on that repo.

**Comment by wmira** [comment]
@Levino  use the declaration below:

declare module 'bn.js' {
    
  import { Buffer } from 'buffer'

  type Endianness = 'le'|'be'

  class BN {
    constructor(number: number|string|number[]|Buffer, base?: number, endian?: Endianness)
    clone(): BN
    toString(base?: number, length?: number): string
    toNumber(): number
    toJSON(): string
    toArray(endian?: Endianness, length?: number): number[]
    toBuffer(endian?: Endianness, length?: number): Buffer
    bitLength(): number
    zeroBits(): number
    byteLength(): number
    isNeg(): boolean
    isEven(): boolean
    isOdd(): boolean
    isZero(): boolean
    cmp(b: any): number
    lt(b: any): boolean
    lte(b: any): boolean
    gt(b: any): boolean
    gte(b: any): boolean
    eq(b: any): boolean
    isBN(b: any): boolean

    neg(): BN
    abs(): BN
    add(b: BN): BN
    sub(b: BN): BN
    mul(b: BN): BN
    sqr(): BN
    pow(b: BN): BN
    div(b: BN): BN
    mod(b: BN): BN
    divRound(b: BN): BN

    or(b: BN): BN
    and(b: BN): BN
    xor(b: BN): BN
    setn(b: number): BN
    shln(b: number): BN
    shrn(b: number): BN
    testn(b: number): boolean
    maskn(b: number): BN
    bincn(b: number): BN
    notn(w: number): BN

    gcd(b: BN): BN
    egcd(b: BN): { a: BN, b: BN, gcd: BN }
    invm(b: BN): BN
  }

  export type BigNumber = BN

}


Taken from https://github.com/indutny/bn.js/blob/master/lib/bn.js .
I have changed export to BigNumber as expected by web3

**Comment by Levino** [comment]
Dear @wmira, [above](https://github.com/ethereum/web3.js/issues/1597#issuecomment-392722168) I suggested a solution for the problem by replacing the non-working type definitions from the `web3` package with **working ones** (which must obviously include type definitions for `bn.js`). Please also check the gist that I linked.

I also have been running around this repo trying to point the problems out. Seems everybody is sleeping. While I wait for someone to wake up I opened a [PR to DefinitelyTyped](https://github.com/ethereum/web3.js/issues/1597#issuecomment-392722168) to have high quality, linted and tested type definitions for `web3` in the future.

I appreciate your follow up on the matter but I think we might also have a little bit of a misunderstanding here. I think the issue at hand is resolved. As for your repo, try removing this [line](https://github.com/wmira/ethereum-notification/blob/a7263b1b815ea5f187234d6ba70550bebd766ce4/tsconfig.json#L4). You then have to import Web3 via `import web3 = require('web3')` but this will break because the type defintions are incorrect as explained above.

Also if you have to add typings for a dependency of `web3`/ namely`bn.js` by hand (by copying and pasting have baked type definitions from somewhere in the web) this is a - excuse my bluntness - **shit setup**. This is why I also included the types you referenced in the PR to DefinitelyTyped so in the future `bn.js` type defintions will also be available via `@types/bn.js`.

I see that you know what you are doing when it comes to typescript. I would really appreciate a review or some further contributions (like more test code) to the PR in DefinitelyTyped and some support for my move to [remove the type definitions from here](https://github.com/ethereum/web3.js/pull/1660).

**Comment by wmira** [comment]
@Levino i know where you are coming from but sometimes we need to get things going as we need to move and write code. The copy paste of the BN typings is not for the sake of doing so -- obviously a better type can be created but that is not the point here. 

I'm sure the people here are busy and so are you so lets take it easy please.

**Comment by Levino** [comment]
I am taking it easy. I did not mean any offense. I understand that everyone is busy and I have no problem to wait until the this topic is picked up by a maintainer. I am merely offering my help. BTW `@types/bn.js` has [been merged](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26120) into master of DT so it is available soon.

**Comment by Levino** [comment]
Also type definitions for `web-eth-abi` have been [merged](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26127). This is going to be a clusterf**k if nobody comes up with a consistent plan soon.

**Comment by Levino** [comment]
Also highlighting @LogvinovLeon to get his view on the matter.

**Comment by wmira** [comment]
@Levino are you able to just do a pull request to fix the type definitions here?

**Comment by LogvinovLeon** [comment]
@Levino Correct me if I'm wrong, but as far as I know - web3 maintainers don't see a value in using/supporting typescript. They can sporadically accept some PR's but don't have the expertice/motivation to do that. I think it will make more sense to keep the typings separately in that case (in DT) so that a review process is much more quick (DT maintainers are much faster). I'm now migrating our [typings repository](https://github.com/0xProject/0x-monorepo/tree/v2-prototype/packages/typescript-typings/types) from 0x monorepo to DT. We have full web3 types that us and a bunch of other projects have been using for more than a year. https://github.com/0xProject/0x-monorepo/blob/v2-prototype/packages/typescript-typings/types/web3/index.d.ts

I'm planning to introduce `ethereum-types` as a general typings package that contains package/agnostic things (like Provider, Block, Unit), because it can be shared later between all ethereum-related packages.

The only downside is that it supports only the latest stable version of web3. I think the beta branch is too immature.

**Comment by Levino** [comment]
@wmira Yes, I could. But I do not want to. [I think it is better to stop providing type definitions here](https://github.com/ethereum/web3.js/issues/1658).

> Correct me if I'm wrong, but as far as I know - web3 maintainers don't see a value in using/supporting typescript. They can sporadically accept some PR's but don't have the expertice/motivation to do that.

They do accept PRs without understanding the consquences and without proper review. Also no linting is been applied, not to even thinnk about tests for the type definitions. This repo is currently following an anti pattern. This is why I am pushing for the removal of the type definitions.

**Off topic:** What are your issues with `web3-1.0.0`?

**Comment by Levino** [comment]
[Here](https://github.com/ethereum/web3.js/issues/1658#issuecomment-395662469) is an instruction on how to use `web3@1.x` with typescript correctly. This issue right here should be closed as resolved. Whether or not type definitions should remain part of this package should be resolved via https://github.com/ethereum/web3.js/issues/1658

**Comment by krzkaczor** [comment]
Btw. if anyone is curious how to work with smart contracts in a type-safe manner, [TypeChain](https://github.com/krzkaczor/TypeChain) supports it! Just use: `web3-1.0.0` target.

**Comment by kael-shipman** [comment]
Note: Per the comment at the very end of the chain that @Levino has linked above ([here](https://github.com/ethereum/web3.js/issues/1658#issuecomment-476477117)), it appears as though type definitions are now once again shipped with web3? @Levino , feel free to correct me if I'm wrong....

**Comment by lucasrcosta** [comment]
In case someone can't use `esModuleInterop` and would like to keep typings, I'm using a hack like this:
```js
import Web3 from 'web3'
const _Web3 = Web3 || require('web3')
const web3 = new _Web3(provider)
```

**Comment by vaneeckhoutnicolas** [comment]
The best is to create a plugin to share through your components.
Anyway if in a specific component you can add this for web3 (same for window.ethereum if needed, e.g. authorize metamask)
declare global {
  interface Window { web3: any; }
}

window.web3 = window.web3 || {};

**Comment by levino** [comment]
Or you just use JavaScript if you do not need types...

**Comment by nvegater** [comment]
Anyone has experience with the [Typechain](https://github.com/ethereum-ts/TypeChain)? 
Does it keep up with w3 changes?

**Comment by levino** [comment]
Typechain does not solve this problem. It is for something else (typing the methods of the Contract instance from web3).

I personally recommend `ethers` these days. It is not perfect but much better than web3.

**Comment by trieulethe** [comment]
"esModuleInterop": true in tsconfig.json and import Web3 from 'web3';
i use this and it work :+1:

**Comment by SalamandraDevs** [comment]
> Okay I "fixed" it for me locally until this madness is resolved properly. First you have to add a postinstall script in your `package.json` like so:
> 
> ```json
> {
>   "postinstall": "rm -f node_modules/web3/index.d.ts"
> }
> ```
> 
> This will remove the incorrect type definitions shipped with web3. Then you need to add [these two module augmentation files](https://gist.github.com/Levino/8bb6f7ccc9a4becdfe025f814f18ee61) to your codebase and make sure typescript loads them. For example put them in a folder `typings` and add to your `tsconfig.json`:
> 
> ```json
> {
>   "typeRoots": [
>     "./node_modules/@types/",
>     "./typings/"
>   ]
> }
> ```

This workaround is currently working for Web3.js v1.9.0, in times when the web3.js team are preparing their v4.0.0 to be relased soon. I tested v4 and the problems are worst in Typescript with ESM, I do not know what to think, but I am using web3 instead of ethers because actually web3 retreives data from JsonRPC faster than ethers v5.

@levino thanks you for this contribution.
