### ISSUE TITLE
web3.shh.post broken?

### ISSUE THREAD

**Issue by karalabe** [ethereum/web3.js#161]
I was trying to run the Whisper example from here: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3shhpost, but I get hit with this error:

```
> web3.shh.post(message);
TypeError: Object function (post) {

    post.payload = utils.toHex(post.payload);
    post.ttl = utils.fromDecimal(post.ttl);
    post.priority = utils.fromDecimal(post.priority);

    if(!utils.isArray(post.topics)) {
        post.topics = [post.topics];
    }

    // format the following options
    post.topics = post.topics.map(function(topic){
        return utils.fromAscii(topic);
    });

    return post; 
} has no method 'map'
    at Method.formatInput (/usr/lib/node_modules/web3/lib/web3/method.js:85:32)
    at Method.toPayload (/usr/lib/node_modules/web3/lib/web3/method.js:130:23)
    at Method.send (/usr/lib/node_modules/web3/lib/web3/method.js:148:24)
    at repl:1:10
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
```

I've installed the latest web3 via npm. Is this a js API issue or a server side issue?

**Comment by debris** [comment]
js api issue. I will fix and add appropriate test in few minutes. Thanks for reporting!

**Comment by debris** [comment]
should be fixed in latest develop
