### ISSUE TITLE
web3@1.0.0-beta.34 ERR_OUT_OF_RANGE ?

### ISSUE THREAD

**Issue by rhals000327** [ethereum/web3.js#1613]
I'm connecting to Infura with WebSocket and it keeps throwing below error
`internal/buffer.js:35
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -133860784
    at checkInt (internal/buffer.js:35:11)
    at writeU_Int32BE (internal/buffer.js:625:3)
    at Buffer.writeUInt32BE (internal/buffer.js:638:10)
    at WebSocketFrame.toBuffer (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/websocket/lib/WebSocketFrame.js:257:24)
    at WebSocketConnection.sendFrame (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/websocket/lib/WebSocketConnection.js:852:43)
    at WebSocketConnection.fragmentAndSend (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/websocket/lib/WebSocketConnection.js:788:14)
    at WebSocketConnection.sendUTF (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/websocket/lib/WebSocketConnection.js:728:10)
    at W3CWebSocket.send (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/websocket/lib/W3CWebSocket.js:116:26)
    at WebsocketProvider.send (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/web3-providers-ws/src/index.js:251:21)
    at Timeout._onTimeout (/Users/rohjaehyeong/Documents/asomethings_lab/explorerrr/crawler/node_modules/web3-providers-ws/src/index.js:232:19)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)`

Currently I'm using latest Node.js (Which is 10.0.0).

Any fixes coming soon? Or anybody found a fix for it?

**Comment by rhals000327** [comment]
Thanks! Fixed by @reanox

**Comment by jooray** [comment]
Shouldn't we fix this upstream? Same error with Ganache 1.1.0. I think we should either reopen or create an issue to upgrade upstream websocket.

**Comment by BransonGitomeh** [comment]
should be fixed upstream because i wasted A WHOLE DAY trying to figure out why im getting 

`RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1930500535` 

randomly!!

**Comment by jooray** [comment]
@frozeman could you either update your fork or just depend on upstream?

This is the patch that fixes the negative value problem that we've been having that your fork does not have.

https://github.com/theturtle32/WebSocket-Node/commit/12ed73d77c1762e24ae1ad6b206d1671e3c0fd5a

It seems that you don't have any patches that upstream does not have, so maybe just using upstream is a better idea.

**Comment by frozeman** [comment]
I just checked: I made my own version, to fix this problem for browserify: https://github.com/frozeman/WebSocket-Node/commit/7004c39c42ac98875ab61126e5b4a925430f592c

I merged upstream master to the #browserifyCompatible branch, which is the one used in the web3.js. If you remove your node_modules folder from the ws provider package and run `npm install` again, it should be fixed.

**Comment by BransonGitomeh** [comment]
works perfect!! thanks alot @frozeman
