### ISSUE TITLE
web3.shh.filter.watch broken?

### ISSUE THREAD

**Issue by karalabe** [ethereum/web3.js#162]
Similar to the previous report, post now worked, but when I created an empty filter and started watching it, the API crashed once again:

```javascript
var filter = web3.shh.filter({});
filter.watch(function(res) {
    console.log(res);
});
```

```
/usr/lib/node_modules/web3/lib/web3/formatters.js:195
    post.topics = post.topics.map(function(topic){
                              ^
TypeError: Cannot call method 'map' of undefined
    at outputPostFormatter [as formatter] (/usr/lib/node_modules/web3/lib/web3/formatters.js:195:31)
    at /usr/lib/node_modules/web3/lib/web3/filter.js:123:50
    at Array.map (native)
    at Object.callback (/usr/lib/node_modules/web3/lib/web3/filter.js:122:36)
    at /usr/lib/node_modules/web3/lib/web3/method.js:152:21
    at /usr/lib/node_modules/web3/lib/web3/requestmanager.js:104:9
    at request.onreadystatechange (/usr/lib/node_modules/web3/lib/web3/httpprovider.js:59:13)
    at dispatchEvent (/usr/lib/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/usr/lib/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
```

**Comment by debris** [comment]
ahh... there are still missing tests for shh. :/ I will fix this soon.

**Comment by karalabe** [comment]
Do you have an estimate on this? It's kind of blocking my work on whisper in go-ethereum. Thanks :)

**Comment by frozeman** [comment]
probably same issue as the other one. we expect topics to be there. but its a bug you're right.

**Comment by karalabe** [comment]
Even if I specify the topics, the same crash occurs. Here's a similar dump, but different calls.

```
var filter = web3.shh.filter({topics: ["test"]})
filter.watch(function(msg){console.log(msg);})
web3.shh.post({payload: "hi", topics: ["test"]})
```

```
/usr/lib/node_modules/web3/lib/web3/formatters.js:195
    post.topics = post.topics.map(function(topic){
                              ^
TypeError: Cannot call method 'map' of undefined
    at outputPostFormatter [as formatter] (/usr/lib/node_modules/web3/lib/web3/formatters.js:195:31)
    at /usr/lib/node_modules/web3/lib/web3/filter.js:82:45
    at Array.forEach (native)
    at Object.onMessage [as callback] (/usr/lib/node_modules/web3/lib/web3/filter.js:81:18)
    at /usr/lib/node_modules/web3/lib/web3/requestmanager.js:213:20
    at Array.forEach (native)
    at /usr/lib/node_modules/web3/lib/web3/requestmanager.js:212:12
    at request.onreadystatechange (/usr/lib/node_modules/web3/lib/web3/httpprovider.js:59:13)
    at dispatchEvent (/usr/lib/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/usr/lib/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
```

**Comment by frozeman** [comment]
its probably because go doesn't return a topic array. which is expected.

**Comment by frozeman** [comment]
Actually i think go returns `topic` not `topics`, which was changed back and forth a few month back.

**Comment by frozeman** [comment]
But your PR is still valid, if you fix the comments i posted :)
