### ISSUE TITLE
web3.eth.contract is not a function

### ISSUE THREAD

**Issue by quantumproducer** [ethereum/web3.js#1628]
Documentation states this is valid:

let c2 = web3.eth.contract(abi).at(keyaddress);
                  ^

TypeError: web3.eth.contract is not a function
    at Object.<anonymous> (/root/scan/server.js:12:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

I have to use capital C Contract like this:

let c = new web3.eth.Contract(abi, keyaddress);

**Comment by idotial** [comment]
i got the same problem too, but web3 project have a test abount contract function, it should be passed

**Comment by quantumproducer** [comment]
I'm sorry, I couldn't understand what you said.
"Test about contract function"
and "it should be passed"
Can you explain?

**Comment by idotial** [comment]
https://github.com/ethereum/web3.js/blob/develop/test/contract.js @quantumproducer

**Comment by idotial** [comment]
https://github.com/ethereum/web3.js/issues/985

**Comment by quantumproducer** [comment]
Good catch

**Comment by quantumproducer** [comment]
Closable, I see the documentation is edited to show it's for 0.2XX
This is very confusing that the documentation link from Github links to old documentation when 1.0.0.beta-34 is on the main page. Leaving unclosed so a maintainer can review this.
