### ISSUE TITLE
Unable to install web 3: permission denied

### ISSUE THREAD

**Issue by whitneygriffith** [ethereum/web3.js#1690]
33 verbose node v8.11.2
34 verbose npm  v5.6.0
35 error code 1
36 error Command failed: /usr/local/bin/git clone -q https://github.com/frozeman/bignumber.js-nolookahead.git /Users/t-whgri/.npm/_cacache/tmp/git-clone-1e15a942
36 error /Users/t-whgri/.npm/_cacache/tmp/git-clone-1e15a942/.git: Permission denied
37 verbose exit [ 1, true ]

**Comment by whitneygriffith** [comment]
npm install web3-eth gives the following error

464 verbose stack Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /Users/t-whgri/.npm/_cacache/tmp/git-clone-d2886902
464 verbose stack /Users/t-whgri/.npm/_cacache/tmp/git-clone-d2886902/.git: Permission denied
464 verbose stack
464 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
464 verbose stack     at emitTwo (events.js:126:13)
464 verbose stack     at ChildProcess.emit (events.js:214:7)
464 verbose stack     at maybeClose (internal/child_process.js:925:16)
464 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
465 verbose cwd /Users/t-whgri/Desktop/casino
466 verbose Darwin 17.5.0
467 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-D" "web3-eth"
468 verbose node v8.11.2
469 verbose npm  v5.6.0
470 error code 1
471 error Command failed: /usr/local/bin/git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /Users/t-whgri/.npm/_cacache/tmp/git-clone-d2886902
471 error /Users/t-whgri/.npm/_cacache/tmp/git-clone-d2886902/.git: Permission denied
472 verbose exit [ 1, true ]

**Comment by nivida** [comment]
This error has nothing todo with web3. Please be sure you set up your development environment correctly.
