### ISSUE TITLE
`npm install web3@1.0.0-beta.x` fails when `21 ≤ x ≤ 34`

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#1698]
Here is the error message:
```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR!
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No such file or directory
npm ERR! github.com[1: 192.30.253.112]: errno=No such file or directory
npm ERR!
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Roaming\npm-cache\_logs\2018-06-11T15_32_53_475Z-debug.log
```

Here is the end of the log file mentioned in the previous section:
```
800 verbose stack Error: exited with error code: 128
800 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\util\finished.js:12:19)
800 verbose stack     at emitTwo (events.js:126:13)
800 verbose stack     at ChildProcess.emit (events.js:214:7)
800 verbose stack     at maybeClose (internal/child_process.js:925:16)
800 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
801 verbose cwd C:\Users\username\...
802 verbose Windows_NT 10.0.16299
803 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\username\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3@1.0.0-beta.34"
804 verbose node v8.11.2
805 verbose npm  v6.1.0
806 error Error while executing:
806 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
806 error
806 error fatal: unable to connect to github.com:
806 error github.com[0: 192.30.253.113]: errno=No such file or directory
806 error github.com[1: 192.30.253.112]: errno=No such file or directory
806 error
806 error
806 error exited with error code: 128
807 verbose exit [ 1, true ]
```

OS: Windows 10
node version: 8.11.2
npm version: 6.1.0

**Comment by Levino** [comment]
I suspect your `git` install is misconfigured. `npm` tries to download a dependency from `github` via `git`. It looks like that `git` cannot connect to `github.com`. This is a problem of configuration. Are you sure you can install other dependencies which are hosted on github?

**Comment by nivida** [comment]
I close it because it looks like a configuration problem which has nothing to do with web3.
