### ISSUE TITLE
atob/btoa undefined

### ISSUE THREAD

**Issue by jesobreira** [ethereum/web3.js#1706]
Some platforms such as Node do not bundle window.atob/btoa. This should not be a problem, since [web3-providers-ws](https://www.npmjs.com/package/web3-providers-ws) checks for the existence of the window object and uses 3rd-party polyfills if it does not exist.

The problem is that some environments do define `window`, but not `atob`/`btoa`, which are browser standards. Good examples are React-Native (not sure if actual version does define it) and proton-native. In this case, it throws:

```
    _btoa = btoa;
    ^

ReferenceError: btoa is not defined
    at Object.<anonymous> (/Users/user/dev/node_modules/web3-providers-ws/src/index.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/dev/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/user/dev/node_modules/web3-core-requestmanager/src/index.js:53:24)
```

I think this part on web3-providers-ws/src/index.js:

```javascript
if (typeof window !== 'undefined') {
    Ws = window.WebSocket;
    _btoa = btoa;
    parseURL = function(url) {
        return new URL(url);
    };
} else {
    Ws = require('websocket').w3cwebsocket;
    _btoa = function(str) {
      return Buffer(str).toString('base64');
    };
    // Web3 supports Node.js 5, so we need to use the legacy URL API
    parseURL = require('url').parse;
}
```

Should rather be kind of:

```
if (typeof window !== 'undefined') {
    if (window.hasOwnProperty('WebSocket'))
        Ws = window.WebSocket;
    else
        Ws = require('websocket').w3cwebsocket;
    
    if (window.hasOwnProperty('btoa'))
        _btoa = btoa;
    else
        _btoa = function(str) {
      return Buffer(str).toString('base64');
    };
    
    if (window.hasOwnProperty('URL'))
        parseURL = function(url) {
            return new URL(url);
        };
    else
        parseURL = require('url').parse;
} else {
    Ws = require('websocket').w3cwebsocket;
    _btoa = function(str) {
      return Buffer(str).toString('base64');
    };
    // Web3 supports Node.js 5, so we need to use the legacy URL API
    parseURL = require('url').parse;
}
```

However I could not find the package repo to send a PR.

Note: populating/defining  `window.btoa` did not work due to ```_btoa = btoa;```. If it was ```btoa = window.btoa;```, then it would work. If the above change is not a good idea, then this last one would not cause any issue and do the trick (although additional work - defining `window.btoa` - is needed).

**Comment by Levino** [comment]
What is the actual issue you encounter?

**Comment by jesobreira** [comment]
The main issue is that web3-providers-ws/src/index.js relies on "btoa" on the default scope if `window` is not undefined (i.e. this is a browser, not NodeJS). This works well on browsers since they all implement `window.btoa` method.

However, in some environments such as React Native, `window` is not undefined (and therefore, w3-providers-ws will believe it is a browser, while it is not). For not being a browser, `window.btoa` is undefined. But, well, it's ok, we can just implement `window.btoa` somewhere else.

The actual problem here is that, in order to obtain `window.btoa`, the file "web3-providers-ws/src/index.js" relies on:

```javascript
_btoa = btoa;
```

While this works well in browsers (since browsers' standard scope is `window`), this does not work well on Node-like environments that define `window`, since in these environments, the module code is wrapped around a function (and therefore, the default scope is not `window`, but the module itself. In other words, if you run the line above in React-Native, it would try to find a "btoa" variable on the module code/scope, which is undefined, causing an error for trying to call an undefined function.

For a better compatibility for these environments, this line should be:

```javascript
_btoa = window.btoa;
```

**Comment by nivida** [comment]
"However the repo link on npm is broken and I could not find the right repo to file a PR" 
You can submit here an PR and select 1.0 as base branch. :)

**Comment by nivida** [comment]
Already fixed: https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers-ws/src/index.js#L41
