### ISSUE TITLE
getGasPrice not working

### ISSUE THREAD

**Issue by prographo** [ethereum/web3.js#1721]
Copy and paste direct from the official documentation:
```
> web3.eth.getGasPrice().then(console.log);
TypeError: Cannot read property 'then' of undefined
> TypeError: callback is not a function
    at /home/ubuntu/node_modules/web3/lib/web3/property.js:119:13
    at /home/ubuntu/node_modules/web3/lib/web3/requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/node_modules/web3/lib/web3/httpprovider.js:128:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/ubuntu/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/node_modules/xhr2/lib/xhr2.js:509:12)
```

**Comment by cleathers** [comment]
It looks like `getGasPrice` doesn't expose a Promise interface, but requires a callback.

https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgasprice

I'm super new to web3, is there a way to "turn on" promises with web3? If there is, maybe that initialization logic is missing. If not, then just pass in your callback to `getGasPrice` like this

`web3.eth.getGasPrice(console.log)`

**Comment by nivida** [comment]
<img width="321" alt="screen shot 2018-08-10 at 09 55 48" src="https://user-images.githubusercontent.com/1699173/43945808-a4ea140c-9c83-11e8-946b-4a650f20182a.png">

In works with the latest version of Web3.js :)
