### ISSUE TITLE
Calling solidity functions and passing in 2d arrays as parameters doesn't work

### ISSUE THREAD

**Issue by mbeylin** [ethereum/web3.js#1738]
Suppose we have a solidity function `function example(uint[][] numbers)` which accepts a 2d array of integers (as allowed by the `Experimental ABIEncoderV2`). If I wish to call this function using web3, I get the error: 
```
TypeError: Cannot read property '0' of undefined
      at SolidityCoder.encodeWithOffset (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/solidity/coder.js:155:1)
      at /Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/solidity/coder.js:115:1
      at Array.forEach (<anonymous>)
      at SolidityCoder.encodeMultiWithOffset (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/solidity/coder.js:112:1)
      at SolidityCoder.encodeParams (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/solidity/coder.js:103:1)
      at SolidityFunction.toPayload (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:92:1)
      at SolidityFunction.sendTransaction (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
      at SolidityFunction.execute (/Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at /Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at /Users/Mark/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:155:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Is there an intention to support this functionality soon? I wanted to document this bug here incase it wasn't already known.

**Comment by mbeylin** [comment]
https://github.com/ethereum/web3.js/blob/cd1cfd9db6cacb494884a1824f8562c6440f85df/lib/solidity/coder.js#L122 notes that this doesn't yet exist but still needs to be completed.

**Comment by nivida** [comment]
I'll test it with the new ABICoder.
