### ISSUE TITLE
Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by soodakshay** [ethereum/web3.js#1775]
Hi All,

I am trying to execute a transaction that will transfer some tokens to other account. I am using `Ropsten TestNet`.

While executing, I am getting the following error:
`"Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/akshay/WS/ethereum/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/home/akshay/WS/ethereum/node_modules/web3-providers-http/src/index.js:73:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/akshay/WS/ethereum/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/akshay/WS/ethereum/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/akshay/WS/ethereum/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/akshay/WS/ethereum/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)"`

I am using the following URL `https://ropsten.infura.io/<api-key here>`

and the following code:
`router.post('/transfer', (req, res, next)=>{
  contractInstance.methods.transfer(req.body.address, req.body.amount).send({from:ownerAccountAddress},(err, txHash)=>{
    if(err){
      console.error(err)
      res.send(err)
    }else{
      res.send({status:'OK', tx:txHash})
    }
  })
})`

Any help/suggetion would be appreciated

**Comment by soodakshay** [comment]
I am using the following web3js version `1.0.0-beta.34`

**Comment by nivida** [comment]
Can you please show all of your code? :)

**Comment by damianobarbati** [comment]
+1. same problem

**Comment by SVDotsenko** [comment]
> +1. same problem

http://www.dappuniversity.com/articles/web3-js-intro

#5 · Calling Smart Contract Functions with Web3.js

**Comment by webees** [comment]
+1. same problem

electron-vue + web3.js

```
const web3 = new Web3()
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'))
var balance = web3.eth.getBalance('0x407d73d8a49eeb85d32cf465507dd71d507100c1')
```
![_20181003031348](https://user-images.githubusercontent.com/5155291/46371202-4f36ac80-c6ba-11e8-999e-d47eba329e2d.png)

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
