### ISSUE TITLE
web3.eth.personal.unlockAccount call failed

### ISSUE THREAD

**Issue by Akagi201** [ethereum/web3.js#1904]
```
~/Downloads/tmp
❯ yarn list web3
yarn list v1.9.4
warning package.json: No license field
warning No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ web3@1.0.0-beta.35
   Done in 0.23s.

~/Downloads/tmp
❯ node
> var Web3 = require("web3");
undefined
> var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
undefined
> web3.eth.defaultAccount = "0x1f256d9fd1fbb4b514784584557751b0e2f81185";
'0x1f256d9fd1fbb4b514784584557751b0e2f81185'
> web3.eth.personal.unlockAccount(web3.eth.defaultAccount, "aktest123", 6000).then(console.log('Account unlocked!')).catch(err => console.log(err));
Account unlocked!
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> Error: Returned error: Method not found
    at Object.ErrorResponse (/Users/akagi201/Downloads/tmp/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/akagi201/Downloads/tmp/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/akagi201/Downloads/tmp/node_modules/web3-providers-http/src/index.js:79:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/akagi201/Downloads/tmp/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/akagi201/Downloads/tmp/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/akagi201/Downloads/tmp/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/akagi201/Downloads/tmp/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:460:23)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Akagi201** [comment]
It is not related to the web3.

**Comment by eyebrown** [comment]
I encountered a similar problem，could you please help me solve this problem？
