### ISSUE TITLE
Error: Invalid JSON RPC response: "" calling method getTransactionCount(address)

### ISSUE THREAD

**Issue by oscar-ordonez** [ethereum/web3.js#1919]
I am trying to call the method "getTransactionCount(address)" but it's returning ' Error: Invalid JSON RPC response: "" ' 
This is a piece of my code:

```javascript
var Web3 = require('web3');
// create an instance of web3 using the HTTP provider.                
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
web3.eth.getTransactionCount("0x7f037a1063071c34bd6bf36cb24328e6309e8bf7").then(result=>{       
     console.log(result);                  
});
```

**Comment by Eugnis** [comment]
Are you using pure nodejs or something like browserify?
For me this error appearing on beta34+. On beta33 all ok

**Comment by oscar-ordonez** [comment]
Pure nodejs...

**Comment by oscar-ordonez** [comment]
@Eugnis I recently try v1.0.0-beta.32 and its also showing the same error

**Comment by nivida** [comment]
Closed due to inactivity and also because I tested it and it works.

**Comment by gzelda** [comment]
i have the same problem with the code:
web3.eth.getTransactionCount(fromAddress).then(nonce=>{
		console.log(nonce);
});

and the error:
(node:4880) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/web3-providers-http/src/index.js:75:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/Users/Gavin/Documents/nodejs/ethWallet/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:4880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
