### ISSUE TITLE
Error: no suitable peers available

### ISSUE THREAD

**Issue by tony-stark001** [ethereum/web3.js#2036]
When I tried to send a transaction, it throws the following error message.

My code
```
web3.eth.sendTransaction({from:fromaddress, to:address,value:send_amount,gas:gaslimit,gasPrice:getGasPrice},function(trasn_err,txid){
  if(!trasn_err){
  console.log(txid);
  } else {
  console.log(trasn_err);
  }
  });
```

```
Error: Returned error: no suitable peers available
      at Object.ErrorResponse (/var/www/html/node_modules/web3-core-helpers/src/errors.js:29:16)
      at /var/www/html/node_modules/web3-core-requestmanager/src/index.js:140:36
      at XMLHttpRequest.request.onreadystatechange (/var/www/html/node_modules/web3-providers-http/src/index.js:91:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/var/www/html/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
      at XMLHttpRequest._setReadyState (/var/www/html/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
      at XMLHttpRequest._onHttpResponseEnd (/var/www/html/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
      at IncomingMessage. (/var/www/html/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
      at IncomingMessage.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by dmihal** [comment]
This is an issue with your geth node, not with web3.

You may be able to fix this by running a full node instead of a light node, or by manually adding peers.

**Comment by nivida** [comment]
Closed because of the ongoing clean up of the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
