### ISSUE TITLE
string "genesis" not accepted as parameter identifying the block

### ISSUE THREAD

**Issue by gsalzer** [ethereum/web3.js#2068]
I use web3 1.0.0-beta.36 to connect to the parity JSON RPC interface.

According to the docs, blocks can be identified by the number or by one of the strings `"genesis"`, `"latest"`, `"pending"`.
It seems that `"genesis"` is not working:
```

> web3.eth.getBlock("genesis").then(console.log);
Error: Given input "genesis" is not a number.
    at Object.numberToHex (/home/ethereum/extract/node_modules/web3-utils/src/utils.js:264:15)
    at Method.inputBlockNumberFormatter (/home/ethereum/extract/node_modules/web3-core-helpers/src/formatters.js:62:125)
    at /home/ethereum/extract/node_modules/web3-core-method/src/index.js:144:38
    at Array.map (<anonymous>)
    at Method.formatInput (/home/ethereum/extract/node_modules/web3-core-method/src/index.js:142:32)
    at Method.toPayload (/home/ethereum/extract/node_modules/web3-core-method/src/index.js:177:23)
    at Eth.send [as getBlock] (/home/ethereum/extract/node_modules/web3-core-method/src/index.js:467:30)
> 
```
Using `"latest"` or `"pending"` instead of `"genesis"` works, however.

**Comment by nivida** [comment]
Thanks for submitting this issue! I’ll fix it in the next release. You should be able to pass 0 to have the same behavior as you would pass ‚genesis‘.

**Comment by Meabo** [comment]
@nivida I made a PR (as it's an easy one)

**Comment by nivida** [comment]
Sorry I just checked the JSON RPC API of parity and geth:
https://wiki.parity.io/JSONRPC-eth-module
https://github.com/ethereum/wiki/wiki/JSON-RPC

The string genesis is not supported it's called earliest. This is an issue of the documentation.

**Comment by jvmaia** [comment]
Where it should be fixed? as seen it's already fixed => https://github.com/ethereum/wiki/wiki/JavaScript-API#values-1

**Comment by nivida** [comment]
@jvmaia Thanks! I was moving this issue wrongly in the project and it should be closed.
