### ISSUE TITLE
BigNumber Error: new BigNumber() not a base 16 number

### ISSUE THREAD

**Issue by MakeHoney** [ethereum/web3.js#2087]
I got a weird error.
___developing environment: truffle + geth (latest stable version)___

1. deploy my contract to geth private network via truffle
```
brian@brian:~/Desktop/jajup/truffle$ truffle migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xa60ec329a5111f64581355c8867dcd3caa2c7b7e8f9c5765721b7aa6d8bdd926
  Migrations: 0x192f692048cb5fd4b434042b9c0ddb3ad51fb344
Saving successful migration to network...
  ... 0x9cf9b1d8f6d74601a3c8d4ca292ea09a3af8f1717017644e3928c437718e2983
Saving artifacts...
Running migration: 2_deploy_song_manager.js
  Deploying SongManager...
  ... 0x19a52ec6204b0e0dc1879454b570e5a58a52af75d5c82893eabeaa12ed839406
  SongManager: 0xc5fb859b80b3fd6a463a542d3a16e105a2771454
Saving successful migration to network...
  ... 0xe50f0f585656c38e50af5b3bca024a24f5b10ae8df8fd23c3ce869131fc403f9
Saving artifacts...

```
as you see, 
SongManager contract instance's address is __0xc5fb859b80b3fd6a463a542d3a16e105a2771454__
plus, my account address is __0xead8112407df0c21d4af93a5632bcdd069f57063__

2. To use contract's methods in truffle console environment, load my contract
```
1 | truffle(development)> let sm = SongManager.at('0xc5fb859b80b3fd6a463a542d3a16e105a2771454')
2 | truffle(development)> sm.registerArtist('zico')
3 | truffle(development)> sm.getArtistByAcc('0xead8112407df0c21d4af93a5632bcdd069f57063')
```

here is point.
__when executing third line, the error occurred__

```
1 | truffle(development)> let sm = SongManager.at('0xc5fb859b80b3fd6a463a542d3a16e105a2771454')
2 | truffle(development)> sm.registerArtist('zico')
3 | truffle(development)> sm.getArtistByAcc('0xead8112407df0c21d4af93a5632bcdd069f57063')

BigNumber Error: new BigNumber() not a base 16 number: 
    at XMLHttpRequest._onHttpResponseEnd (/home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at XMLHttpRequest._setReadyState (/home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest.request.onreadystatechange (/home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at /home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at /home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at Object.callback (/home/brian/.npm-global/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:145:1)
...
```

___SongManager extends Manager (Songmanager is Manager)___
```solidity
pragma solidity ^0.4.23;

import "./Ownable.sol";
import "./Artist.sol";
import "./Listener.sol";
import "./SongLib.sol";

contract Manager is Ownable {
    event ListenerCreated(address listenerAccount, address listenerAddr, string name);
    event ArtistCreated(address artistAccount, address artistAddr, string name);

    mapping (address => address) public accountToArtistAddr;
    mapping (address => address) public accountToListenerAddr;
    mapping (string => address) artistNameToArtistAccount;

    address[] public allArtistsAddrs;

 . . .
 . . .
 . . .

    function registerArtist(string _name) external {
        accountToArtistAddr[msg.sender] = new Artist(_name, allArtistsAddrs.length);
        allArtistsAddrs.push(accountToArtistAddr[msg.sender]);
        artistNameToArtistAccount[_name] = msg.sender;
        emit ArtistCreated(msg.sender, accountToArtistAddr[msg.sender], _name);
    }

    function getArtistByAcc(address _acc) public view returns (
        string name,
        uint id
    ) {
        address artistAddr = accountToArtistAddr[_acc];
        Artist artist = Artist(artistAddr);
        return (artist.getName(), artist.getID());
    }

 . . .
 . . .
 . . .
}
```
The most weird and somewhat important thing is that it is __perfectly fine when executed on ganache + truffle (not geth + truffle) environment with exactly same contracts.__

__ganache-cli + truffle: fine__
__geth + truffle: error__
__ganache-cli + remix: fine__
__geth + remix: error__

so I assumed the problem is in web3 used in rpc API of geth,
or my contract code might be wrong.

Is there anybody who know what's the problem?

**Comment by levino** [comment]
Not actionable / too difficult to reproduce. Should be closed.

**Comment by nivida** [comment]
Closed due to no reaction of the creator after the comment of Levino.
