### ISSUE TITLE
Type: Error: cannot destructure property of "hash" of undefined or null

### ISSUE THREAD

**Issue by Genysys** [ethereum/web3.js#2170]
web3 version: 1.0.0-beta.36

Code;

```
const Web3 = require('web3')
const web3s = [
 'http://10.4.55.15:8545',
 'http://10.4.55.16:8545',
 'http://10.4.55.17:8545',
 'http://10.4.55.18:8545'
].map(url => new Web3(url))
;(async () => {
 const latestBlocks = await Promise.all(web3s.map(web3 => web3.eth.getBlock('latest')))
 const minLatest = Math.min(...latestBlocks.map(({ number }) => number))
 const maxLatest = Math.max(...latestBlocks.map(({ number }) => number))
 console.log({ minLatest, maxLatest })
 for (let i = minLatest; i > 0; i--) {
   const blocks = await Promise.all(web.map(web3 => web3.eth.getBlock(i)))
   const hashes = blocks.map(({ hash }) => hash)
   if (hashes.every(hash => hash === hashes[0])) {
     console.log(i, hashes[0], 'same')
     break
   }
   console.log(i, ...hashes)
 }
})()
```

Error:
```
(node:79462) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `hash` of 'undefined' or 'null'.
    at blocks.map (/home/ethaccadmin/findhash.js:15:30)
    at Array.map (<anonymous>)
    at /home/ethaccadmin/findhash.js:15:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:79462) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79462) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Any clues why I am getting this?

**Comment by dev1644** [comment]
I am unable to reproduce this, I have tested the code with my node URL and its properly destructuring the hash. I think your connection to your node might not got established.

**Comment by Genysys** [comment]
That was the case. It's working fine now
