### ISSUE TITLE
Error: Returned error: Non-200 status code

### ISSUE THREAD

**Issue by adityagoel19** [ethereum/web3.js#2210]
Hi,

I have a test nodejs api set up which uses web3.js to send transactions to a contract. I am just testing my api with the same api call sent every few seconds. I keep getting this error every 20-30 requests, not sure what the problem is. It is not consistent and not able to reproduce with a single call.

> Error: Returned error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 22 Jan 2019 09:45:00 GMT] Server:[Warp/3.2.13]] Body:0xc43c1b4a40 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc43e581100 TLS:<nil>}
     at Object.ErrorResponse (/home/streamsource/streamsource/node_modules/web3-eth/node_modules/web3-core-helpers/src/errors.js:29:16)
     at Object.<anonymous> (/home/streamsource/streamsource/node_modules/web3-eth/node_modules/web3-core-requestmanager/src/index.js:140:36)
     at /home/streamsource/streamsource/node_modules/web3-providers-ws/src/index.js:111:44
     at Array.forEach (<anonymous>)
     at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/streamsource/streamsource/node_modules/web3-providers-ws/src/index.js:88:36)
     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/streamsource/streamsource/node_modules/yaeti/lib/EventTarget.js:107:17)
     at W3CWebSocket.onMessage (/home/streamsource/streamsource/node_modules/websocket/lib/W3CWebSocket.js:234:14)
     at WebSocketConnection.<anonymous> (/home/streamsource/streamsource/node_modules/websocket/lib/W3CWebSocket.js:205:19)
     at emitOne (events.js:116:13)
     at WebSocketConnection.emit (events.js:211:7)
     at WebSocketConnection.processFrame (/home/streamsource/streamsource/node_modules/websocket/lib/WebSocketConnection.js:552:26)
     at /home/streamsource/streamsource/node_modules/websocket/lib/WebSocketConnection.js:321:40
     at _combinedTickCallback (internal/process/next_tick.js:132:7)
     at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**Comment by dev1644** [comment]
Can you post the code snippet?

**Comment by nivida** [comment]
I'm closing this issue because the creator of the issue didn't answer. Thanks @dev1644 for helping!
