### ISSUE TITLE
1.0.0-beta38 doesn't support `HDWalletProvider`?

### ISSUE THREAD

**Issue by studioTeaTwo** [ethereum/web3.js#2229]
#### Expected behavior

`"truffle-hdwallet-provider": "0.0.6"` work.

#### Actual behavior

`Error: Please provide an valid Web3 provider`

#### Steps to reproduce the behavior

```
import HDWalletProvider from 'truffle-hdwallet-provider';
import Web3 from 'web3';

const provider = new HDWalletProvider(ENV.MNEMONIC, ENV.URL);

console.log(provider.constructor.name)
// HDWalletProvider

const web3 = new Web3(provider);
```

#### Error Logs

```
/server/node_modules/web3-providers/dist/web3-providers.cjs.js:720
      throw new Error('Please provide an valid Web3 provider');
            ^
Error: Please provide an valid Web3 provider
    at ProviderResolver.resolve (/server/node_modules/web3-providers/dist/web3-providers.cjs.js:720:13)
    at Web3.AbstractWeb3Module (/server/node_modules/web3-core/dist/web3-core.cjs.js:26:51)
    at new Web3 (/server/node_modules/web3/dist/web3.cjs.js:30:68)
    at Object.<anonymous> (/server/src/blockchains/eth.ts:14:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/server/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/server/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/server/src/blockchains/action.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/server/node_modules/ts-node/src/index.ts:439:23)
```

#### Versions

"web3": "1.0.0-beta.38",
"truffle-hdwallet-provider": "0.0.6",
"typescript": "^3.1.6",
Node v10.14.2

**Comment by nivida** [comment]
Thanks for creating this issue!

As it looks like is the truffle hdwallet provider package using his own provider which is not supported by the public API of Web3.js. 

There is currently no workaround for this, please open an issue in the truffle-hdwallet-provider package. 

We did expose a ``extend()`` method before the ``v1.0.0-beta.38`` release and do now provide a Web3 Modules API as explained in the [Medium post](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) and later in the documentation ([branch](https://github.com/ethereum/web3.js/tree/documentation/web3-modules)) for extending the behavior of the Web3.js library.

We do currently support the following providers:
- HttpProvider
- WebsocketProvider
- IpcProvider
- MetamaskInpageProvider
- EthereumProvider
