### ISSUE TITLE
web3 v1.0.0-beta.38 or higher cannot find module '@babel/runtime/helpers/typeof'

### ISSUE THREAD

**Issue by barakman** [ethereum/web3.js#2249]
#### Expected behavior

`require('web3-utils')` should work

#### Actual behavior

`require('web3-utils')` throws `Error: Cannot find module '@babel/runtime/helpers/typeof'`

#### Steps to reproduce the behavior

1. Create file `package.json`:
```
{
  "devDependencies": {
    "web3": "1.0.0-beta.38"
  }
}
```
2. Create file `test.js`:
```
const web3Utils = require('web3-utils')
console.log(web3Utils.asciiToHex("test"));
```
3. Run `npm install`
4. Run `node test.js`

#### Error Logs
```
module.js:549
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/typeof'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\...\Test\node_modules\web3-utils\dist\web3-utils.cjs.js:15:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
This error can be resolved by downgrading web3 to version 1.0.0-beta.37 or lower.
I have also posted a related problem at https://github.com/bancorprotocol/contracts/issues/268.

#### Versions
- node 8.11.2
- npm 6.4.1
- windows 10

Thanks

**Comment by nivida** [comment]
@barakman Thanks for opening this issue! 

This got already fixed with: https://github.com/ethereum/web3.js/pull/2244

**Comment by wjmelements** [comment]
I have also experienced this issue (https://github.com/trusttoken/scripts/pull/19) but with `@babel/runtime/helpers/classCallCheck`.

Please deprecate versions beta.38 and beta.39.
