### ISSUE TITLE
Error when getPastEvents called without options

### ISSUE THREAD

**Issue by dmihal** [ethereum/web3.js#2343]
#### Expected behavior

`.getPastEvents('allEvents')` returns an array of events.

#### Actual behavior

`TypeError: Cannot read property 'fromBlock' of undefined`

Method works fine if called with an empty object: `.getPastEvents('allEvents', {})`

#### Steps to reproduce the behavior

1. Construct a Web3 contract
2. Call `contract.getPastEvents('allEvents')`

#### Error Logs

```
(node:9157) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fromBlock' of undefined
    at Object.inputLogFormatter (.../node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:173:15)
    at AllPastEventLogsMethod.beforeExecution (.../node_modules/web3-core-method/dist/web3-core-method.cjs.js:1280:44)
    at AllPastEventLogsMethod._callee$ (.../node_modules/web3-core-method/dist/web3-core-method.cjs.js:445:22)
```

#### Versions
Node: 8.11.4
Web3: 1.0.0-beta.43

**Comment by nivida** [comment]
Thanks for creating this issue! But this got already fixed and will be released in version beta.44. (https://github.com/ethereum/web3.js/pull/2338)
