### ISSUE TITLE
1.0.0-beta.43 when execute`contractInstance.methods.myMethod.send`, metamask throw exception

### ISSUE THREAD

**Issue by BigMurry** [ethereum/web3.js#2349]
#### Expected behavior
`contractInstance.methods.myMethod(...args).send({from, value})` should work.

#### Actual behavior
metamask throw exception
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function (error, response) {
              _this2.removeAllListeners(payload.id);
              if (!error) {
 ...<omitted>... } could not be cloned.
    at i._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:114963)
    at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:133809)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136921
    at i.g.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136948)
    at e.exports.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:126198)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37110
    at e.exports.s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37180)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121037)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:120852)
    at e.exports.b.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121663)
    at a._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:109371)
    at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:133809)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136921
    at a.g.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136948)
    at l.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:126198)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37110
    at l.s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37180)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121037)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:120852)
    at l.b.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121663)
    at middleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:100110)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9921)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9723
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10513
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108390
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:103239
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9921)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9723
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10513
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108390
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:106745
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10037
    at Mt (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10458)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10612
    at Object.mapSeries (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10126)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108305)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107826
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25057)
    at Object.Gr [as waterfall] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25153)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107794)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107695)
```
#### Steps to reproduce the behavior

The same code worked in version `1.0.0-beta.36`
```javascript
const Web3 = require('web3');
const web3 = new Web3(window.web3.currentProvider);
const abi = [...];
const addr = '0x....';
const myMethodArgs = [...];
const contractInstance = new web3.eth.Contract(abi, addr);
contractInstance.methods.myMethod(...myMethodArgs).send({from, value}, (err, txHash) => {
  if (err) {
    console.log(err);
  } else {
    console.log(txHash);
  }
});

// result is the following error log from metamask
```

#### Error Logs
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function (error, response) {
              _this2.removeAllListeners(payload.id);
              if (!error) {
 ...<omitted>... } could not be cloned.
    at i._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:114963)
    at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:133809)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136921
    at i.g.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136948)
    at e.exports.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:126198)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37110
    at e.exports.s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37180)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121037)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:120852)
    at e.exports.b.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121663)
    at a._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:109371)
    at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:133809)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136921
    at a.g.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:136948)
    at l.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:126198)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37110
    at l.s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:37180)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121037)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:120852)
    at l.b.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:121663)
    at middleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:100110)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9921)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9723
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10513
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108390
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:103239
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9921)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:9723
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10513
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108390
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:106745
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108362
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10488
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10013)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10037
    at Mt (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10458)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10612
    at Object.mapSeries (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:10126)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:108305)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107826
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25057)
    at Object.Gr [as waterfall] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:25153)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107794)
    at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:107695)
```
#### Versions
NPM: v6.4.1
Node: v10.14.0
MacOS

**Comment by BigMurry** [comment]
@nivida The same error still exists at 1.0.0-beta.44.

**Comment by wardoost** [comment]
Experiencing the same error on 1.0.0-beta.46 here, 1.0.0-beta.36 works though

**Comment by nivida** [comment]
I've tested it with version 1.0.0-beta.46 and it worked for me. I think the fastest way to solve this will be if you could quickly create a small GitHub repo where this error occurs and I can test it with this. I apologize for the troubles and give my best to fix anything asap.

**Comment by BigMurry** [comment]
1.0.0-beta.46 fixed this issue for me.

**Comment by justinkook** [comment]
The same error still exists at 1.0.0-beta.48. Unfortunately I cannot change web3 versions. If possible is there an MR that fixes this issue that I can look at?
