### ISSUE TITLE
Running tests locally fails with error: Could not locate module Utils mapped as: web3-utils

### ISSUE THREAD

**Issue by ahoppen** [ethereum/web3.js#2354]
I'm trying to clone and run the tests of web3.js locally, however when running the tests, either the `web3-eth-iban` or the `web3-eth-abi` module fails with the error message:

```
Could not locate module Utils mapped as:
web3-utils.
```

#### Steps to reproduce the behavior

```
$ git clone https://github.com/ethereum/web3.js.git
$ cd web3.js/
$ npm install
$ npm run clean
$ npm run bootstrap
$ npm run test
```

Running `npm run test` results in the following output

<details><summary>Show output</summary>

```
> web3@1.0.0-beta.38 test /Users/alex/Desktop/web3.js
> lerna run test

lerna info version 2.11.0
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "web3-core-helpers", "web3-core-method", "web3-core-subscriptions", "web3-core", "web3-eth-accounts", "web3-eth-contract", "web3-eth-ens", "web3-eth-personal", "web3-eth", "web3-net", "web3-providers", "web3-shh", "web3"
lerna WARN ECYCLE Encountered a cycle in the dependency graph.This may cause instability! Packages in cycle are: "web3-core-helpers", "web3-core-method", "web3-core-subscriptions", "web3-core", "web3-eth-accounts", "web3-eth-contract", "web3-eth-ens", "web3-eth-personal", "web3-eth", "web3-net", "web3-shh", "web3"

> web3-core-promievent@1.0.0-beta.43 test /Users/alex/Desktop/web3.js/packages/web3-core-promievent
> jest


> web3-utils@1.0.0-beta.43 test /Users/alex/Desktop/web3.js/packages/web3-utils
> jest

lerna ERR! test Errored while running script in 'web3-eth-iban'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run test
lerna ERR! FAIL tests/src/IbanTest.js
lerna ERR!   ● Test suite failed to run
lerna ERR! 
lerna ERR!     Configuration error:
lerna ERR! 
lerna ERR!     Could not locate module Utils mapped as:
lerna ERR!     web3-utils.
lerna ERR! 
lerna ERR!     Please check your configuration for these entries:
lerna ERR!     {
lerna ERR!       "moduleNameMapper": {
lerna ERR!         "/Utils/": "web3-utils"
lerna ERR!       },
lerna ERR!       "resolver": null
lerna ERR!     }
lerna ERR! 
lerna ERR!       4 | 
lerna ERR!       5 | // Mocks
lerna ERR!     > 6 | jest.mock('Utils');
lerna ERR!         |      ^
lerna ERR!       7 | 
lerna ERR!       8 | /**
lerna ERR!       9 |  * Iban test
lerna ERR! 
lerna ERR!       at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/index.js:411:17)
lerna ERR!       at Object.mock (tests/src/IbanTest.js:6:6)
lerna ERR! 
lerna ERR! Test Suites: 1 failed, 1 total
lerna ERR! Tests:       0 total
lerna ERR! Snapshots:   0 total
lerna ERR! Time:        0.873s
lerna ERR! Ran all test suites.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! web3-eth-iban@1.0.0-beta.43 test: `jest`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the web3-eth-iban@1.0.0-beta.43 test script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/alex/.npm/_logs/2019-02-08T16_09_39_914Z-debug.log
lerna ERR! 
lerna ERR! > web3-eth-iban@1.0.0-beta.43 test /Users/alex/Desktop/web3.js/packages/web3-eth-iban
lerna ERR! > jest
lerna ERR! 
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/alex/Desktop/web3.js/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! test Errored while running script in 'web3-eth-abi'
{ Error: Command failed: npm run test
FAIL tests/src/IbanTest.js
  ● Test suite failed to run

    Configuration error:

    Could not locate module Utils mapped as:
    web3-utils.

    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/Utils/": "web3-utils"
      },
      "resolver": null
    }

      4 | 
      5 | // Mocks
    > 6 | jest.mock('Utils');
        |      ^
      7 | 
      8 | /**
      9 |  * Iban test

      at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/index.js:411:17)
      at Object.mock (tests/src/IbanTest.js:6:6)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.873s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3-eth-iban@1.0.0-beta.43 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3-eth-iban@1.0.0-beta.43 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2019-02-08T16_09_39_914Z-debug.log

> web3-eth-iban@1.0.0-beta.43 test /Users/alex/Desktop/web3.js/packages/web3-eth-iban
> jest


    at Promise.all.then.arr (/Users/alex/Desktop/web3.js/node_modules/execa/index.js:236:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  code: 1,
  killed: false,
  stdout:
   '\n> web3-eth-iban@1.0.0-beta.43 test /Users/alex/Desktop/web3.js/packages/web3-eth-iban\n> jest\n\n',
  stderr:
   'FAIL tests/src/IbanTest.js\n  ● Test suite failed to run\n\n    Configuration error:\n\n    Could not locate module Utils mapped as:\n    web3-utils.\n\n    Please check your configuration for these entries:\n    {\n      "moduleNameMapper": {\n        "/Utils/": "web3-utils"\n      },\n      "resolver": null\n    }\n\n      4 | \n      5 | // Mocks\n    > 6 | jest.mock(\'Utils\');\n        |      ^\n      7 | \n      8 | /**\n      9 |  * Iban test\n\n      at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/index.js:411:17)\n      at Object.mock (tests/src/IbanTest.js:6:6)\n\nTest Suites: 1 failed, 1 total\nTests:       0 total\nSnapshots:   0 total\nTime:        0.873s\nRan all test suites.\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! web3-eth-iban@1.0.0-beta.43 test: `jest`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the web3-eth-iban@1.0.0-beta.43 test script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/alex/.npm/_logs/2019-02-08T16_09_39_914Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm run test',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.38 test: `lerna run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.38 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2019-02-08T16_09_40_203Z-debug.log
```
</details>

I'm running on macOS 10.14.2

**Comment by OFRBG** [comment]
Try running this but with `lerna` commands. That should work. Alternatively, use `npm run travis`.

**Comment by ahoppen** [comment]
Thanks! It works with the `lerna` commands.

**Comment by OFRBG** [comment]
Hey, here's how Samuel runs the build: https://github.com/ethereum/web3.js/pull/2358#issuecomment-462047698. This should be the "official" way.
