### ISSUE TITLE
Cannot find module web 3

### ISSUE THREAD

**Issue by Tayyib-A60** [ethereum/web3.js#2380]
Help

**Comment by Tayyib-A60** [comment]
Hi, I got this error while trying to install web3
`npm i web3@1.0.0-beta.38
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/frozeman/WebSocket-Node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

Then when I tried this fix npm i ethereum/web3.js it was successfull
But when I try to run my test I keep getting this 
`Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\users\ADESOKAN\Downloads\ethereum-and-solidity-the-complete-developers-guide [FreeTutorials.Us]\inbox-project\test\inbox.test.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\ADESOKAN\Downloads\ethereum-and-solidity-the-complete-developers-guide [FreeTutorials.Us]\inbox-project\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\ADESOKAN\Downloads\ethereum-and-solidity-the-complete-developers-guide [FreeTutorials.Us]\inbox-project\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\ADESOKAN\Downloads\ethereum-and-solidity-the-complete-developers-guide [FreeTutorials.Us]\inbox-project\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\ADESOKAN\Downloads\ethereum-and-solidity-the-complete-developers-guide [FreeTutorials.Us]\inbox-project\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inbox-project@1.0.0 test: `mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inbox-project@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADESOKAN\AppData\Roaming\npm-cache\_logs\2019-02-15T10_13_08_797Z-debug.log`
Please help

**Comment by nivida** [comment]
Closed this issue because it was not created with the issue template.
