### ISSUE TITLE
Error: Invalid JSON RPC response: "basic auth failure\n"

### ISSUE THREAD

**Issue by karinchechik** [ethereum/web3.js#2427]
I am trying to depoly my app to Heroku and I get the error - Error: Invalid JSON RPC response: "basic auth failure\n" with status 500.
The code works locally.
I use infura to connect to Rinkeby and MetaMask provider.

#### Expected behavior
The code works locally.

#### Actual behavior
On Heroku I get 500 - Internal Server Error. with the following errors.

#### Error Logs
2019-02-26T23:40:25.099819+00:00 app[web.1]: Error: Invalid JSON RPC response: "basic auth failure\n"
2019-02-26T23:40:25.099826+00:00 app[web.1]: at Object.InvalidResponse (/app/node_modules/web3-core-helpers/src/errors.js:42:16)
2019-02-26T23:40:25.099828+00:00 app[web.1]: at XMLHttpRequest.request.onreadystatechange (/app/node_modules/web3-providers-http/src/index.js:75:32)
2019-02-26T23:40:25.099831+00:00 app[web.1]: at XMLHttpRequestEventTarget.dispatchEvent (/app/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2019-02-26T23:40:25.099833+00:00 app[web.1]: at XMLHttpRequest._setReadyState (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2019-02-26T23:40:25.099834+00:00 app[web.1]: at XMLHttpRequest._onHttpResponseEnd (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2019-02-26T23:40:25.099835+00:00 app[web.1]: at IncomingMessage.<anonymous> (/app/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2019-02-26T23:40:25.099837+00:00 app[web.1]: at IncomingMessage.emit (events.js:194:15)
2019-02-26T23:40:25.099839+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1103:12)
2019-02-26T23:40:25.099842+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:63:19)

#### Steps to reproduce the behavior

This is the related code:

1. index -> getInitialProps contains this code:
```
const accounts = await web3.eth.getAccounts();
const deployedPosts = await factory.methods.getDeployedPosts().call();
```

2.ethereum/web3.js
```
require('dotenv').config({ path: '../.env'});
import Web3 from 'web3';
// New instance of Web3 with the provider that is automatically provided by MetaMask.
let web3;
if (typeof window !== 'undefined' && typeof window.web3 !== 'undefined') {
    web3 = new Web3(window.web3.currentProvider);
} else {
    // We are on the server *OR* the user is not running MetaMask.
    // Create our own provider:
    const provider = new Web3.providers.HttpProvider(
        // Pass the URL of some remote node that we have excess to (such as Infura node).
        'https://rinkeby.infura.io/v3/' + process.env.INFURA_API_KEY
    );
    web3 = new Web3(provider);
}

export default web3;
```

3. ethereum/factory.js
```
require('dotenv').config({ path: '../.env'}); // Keep the private data in a dotenv file.
import web3 from './web3';
import PostFactory from './build/PostFactory.json';

const instance = new web3.eth.Contract(
    JSON.parse(PostFactory.interface),
    process.env.ADDRESS
);

export default instance;
```

4. ethereum/post.js
```
import web3 from './web3';
import Post from './build/Post.json';

export default (address) => {
    return new web3.eth.Contract(
        // The interface from the build/Post:
        JSON.parse(Post.interface),
        address
    );
};
```

#### Versions
npm: 6.4.1
"next": "^8.0.3",
"next-routes": "^1.4.2",
"react": "^16.8.3",
"react-dom": "^16.8.3",
"solc": "^0.4.25",
"truffle-hdwallet-provider": "0.0.3",
"web3": "^1.0.0-beta.35"

Any ideas on how to fix it?

**Comment by MazzaWill** [comment]
Did you solve this error?  How to solve it? Thanks!

**Comment by karinchechik** [comment]
Yes. 

I didn't set the env variables in Heroku as config vars. so, my contract's address and my wallet details were undefined.
