### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: invalid json request [1.0.0-beta.47]

### ISSUE THREAD

**Issue by imthatcarlos** [ethereum/web3.js#2447]
As was mentioned briefly in this [comment](https://github.com/ethereum/web3.js/issues/2446#issuecomment-469125776), `eth.getAccounts()` fails with the latest release of web3 and truffle-hdwallet-provider

#### Expected behavior
Code didn't change, only updated packages, and `eth.getAccounts()` should return accounts

#### Actual behavior
Fails.

#### Steps to reproduce the behavior

```
const Web3 = require('web3');
const HDWalletProvider = require('truffle-hdwallet-provider');
let provider = new HDWalletProvider(process.env.MNEMONIC, infuraNodeURL(false, network));
let web3 = new Web3(provider);
const accounts = await web3.eth.getAccounts();
// see error below
```

#### Error Logs
```
(node:31402) UnhandledPromiseRejectionWarning: Error: invalid json request
    at /Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:15:620862
    at e.i.onreadystatechange (/Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:15:775522)
    at e.t.dispatchEvent (/Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:1:152983)
    at e._setReadyState (/Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:15:780284)
    at e._onHttpResponseEnd (/Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:15:783369)
    at IncomingMessage.<anonymous> (/Users/carlos/Desktop/helbiz/hbz-listen/node_modules/truffle-hdwallet-provider/dist/index.js:15:782627)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Versions
npm: 6.8.0
node: v10.11.0
web3: 1.0.0-beta.47
truffle-hdwallet-provider: 1.0.5

**Comment by OFRBG** [comment]
Here is the relevant override: https://github.com/trufflesuite/truffle/blob/f646574a793bdca895b0cc9fb556a263fb70a6c2/packages/truffle-hdwallet-provider/src/index.js#L63-L71.

**Comment by sebayaki** [comment]
I'm having the same issue with this.
Is there any work-around until beta.48 out?

**Comment by nivida** [comment]
@sydneyitguy  I will release this fix today.
