### ISSUE TITLE
getPastEvents fails when called with 'allEvents'

### ISSUE THREAD

**Issue by marcscherer** [ethereum/web3.js#2467]
when using the following code in beta.48 returns the error below. It worked fine in beta.47. Changing "allEvents" to a certain event will also work. 

    ```web3Contract.getPastEvents('allEvents', {
            fromBlock: startBlock,
            toBlock: endBlock,
        });
    ```

```
Error: Empty outputs array given!
    at AbiCoder.decodeParameters (C:\Projects\myproj\node_modules\web3-eth-abi\dist\web3-eth-abi.cjs.js:61:15)
    at AbiCoder.decodeLog (C:\Projects\myproj\node_modules\web3-eth-abi\dist\web3-eth-abi.cjs.js:123:27)
    at AllEventsLogDecoder.decode (C:\Projects\myproj\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:246:45)
    at AllEventsLogDecoder.decode (C:\Projects\myproj\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:276:85)
    at C:\Projects\myproj\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:831:43
    at Array.map (<anonymous>)
    at AllPastEventLogsMethod.afterExecution (C:\Projects\myproj\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:830:28)
    at AllPastEventLogsMethod._callee$ (C:\Projects\myproj\node_modules\web3-core-method\dist\web3-core-method.cjs.js:354:35)
    at tryCatch (C:\Projects\myproj\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Projects\myproj\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Projects\myproj\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\Projects\myproj\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Projects\myproj\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

### Versions 
* web3.js: beta.48

**Comment by nivida** [comment]
There was a similar issue regarding the getPastEvents method. I will check if this already got solved but not released.

**Comment by davekay100** [comment]
I'm getting a similar failure. My error is:
```
(node:97348) UnhandledPromiseRejectionWarning: Error: Empty outputs array given!
    at AbiCoder.decodeParameters (/Users/davidkajpust/coding-no-icloud-backup/thegraph/research/soho-token-contracts/contracts/subgraph/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:61:15)
    at AbiCoder.decodeLog (/Users/davidkajpust/coding-no-icloud-backup/thegraph/research/soho-token-contracts/contracts/subgraph/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:123:27)
.....
```
For me, I am making a pretty typical web3 transaction:
```
let test = gns.methods.registerDomain('Compound', governor).send({ from: governor })
```
And it actually works, and the tx is successful as seen in ganache logs. The solidity function is:
```
    function registerDomain (string calldata _domainName, address _owner) external onlyGovernance {
        gnsDomains[keccak256(abi.encodePacked(_domainName))] = Domain({owner: _owner});
        emit domainAdded(_domainName, keccak256(abi.encodePacked(_domainName)), _owner);
    }
```
The abi of the function is:
```
    {
      "constant": false,
      "inputs": [
        {
          "name": "_domainName",
          "type": "string"
        },
        {
          "name": "_owner",
          "type": "address"
        }
      ],
      "name": "registerDomain",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function"
    },
```

I think it has to do with `outputs` of the abi function being an empty array. Is it possible there was an upgrade to the solc compiler, that changed `outputs`, and now this is causing an error in web3js?

**Comment by nivida** [comment]
@davekaj Thanks for the additional information! I will check and fix this asap.

**Comment by nivida** [comment]
This got fixed with PR https://github.com/ethereum/web3.js/pull/2458.
