### ISSUE TITLE
Web3 Error with React app

### ISSUE THREAD

**Issue by aacostarua** [ethereum/web3.js#2483]
### Description 

Can't run web3 on React.js

    Example:
    1. https://github.com/simpletut/Universal-React-Apollo-Registration/
    2. npm i web3

    Please use the code blocks Markdown does provide:

    ```js
      
        console.log('Pretty syntax!');
    
    ```
----------------------------------------------------------------------->

#### Error Logs 

ERROR in ./node_modules/swarm-js/lib/api-browser.js
       Module build failed (from ./node_modules/babel-loader/lib/index.js):
       Error: Couldn't find preset "@babel/preset-env" relative to directory "/tmp/build_d70355339e58797291a3290251af253c/node_modules/swarm-js"
           at /tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
           at Array.map (<anonymous>)
           at OptionManager.resolvePresets (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
           at OptionManager.mergePresets (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
           at OptionManager.mergeOptions (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
           at OptionManager.init (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
           at File.initOptions (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/index.js:212:65)
           at new File (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/index.js:135:24)
           at Pipeline.transform (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
           at transpile (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-loader/lib/index.js:50:20)
           at Object.module.exports (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-loader/lib/index.js:173:20)
        @ ./node_modules/web3-bzz/dist/web3-bzz.umd.js 6:286-305 6:354-511
        @ ./node_modules/web3/dist/web3.umd.js
        @ ./src/pages/dashboard.js
        @ ./src/app.js
        @ ./src/client.js
        @ multi ./src/client.js ./src/assets/scss/styles.scss
       
       ERROR in ./node_modules/ethjs-unit/lib/index.js
       Module build failed (from ./node_modules/babel-loader/lib/index.js):
       ReferenceError: Unknown plugin "transform-es3-member-expression-literals" specified in "/tmp/build_d70355339e58797291a3290251af253c/node_modules/ethjs-unit/package.json" at 18, attempted to resolve relative to "/tmp/build_d70355339e58797291a3290251af253c/node_modules/ethjs-unit"
           at /tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
           at Array.map (<anonymous>)
           at Function.normalisePlugins (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
           at OptionManager.mergeOptions (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
           at OptionManager.init (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
           at File.initOptions (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/index.js:212:65)
           at new File (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/file/index.js:135:24)
           at Pipeline.transform (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
           at transpile (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-loader/lib/index.js:50:20)
           at Object.module.exports (/tmp/build_d70355339e58797291a3290251af253c/node_modules/babel-loader/lib/index.js:173:20)
        @ ./node_modules/web3-utils/dist/web3-utils.umd.js 6:316-337 6:546-813
        @ ./node_modules/web3-eth-personal/dist/web3-eth-personal.umd.js
        @ ./node_modules/web3/dist/web3.umd.js
        @ ./src/pages/dashboard.js
        @ ./src/app.js
        @ ./src/client.js
        @ multi ./src/client.js ./src/assets/scss/styles.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! universal_react_apollo_registration@1.0.0 heroku-postbuild: `webpack --config webpack.server.js && webpack --config webpack.client.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the universal_react_apollo_registration@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.4JsDj/_logs/2019-03-11T03_44_39_274Z-debug.log
-----> Build failed

---
Code for Web3:
(file dashboard.js)

import React, { Component } from 'react';
import withAuth from './../hoc/withAuth';
import { Helmet } from 'react-helmet';
import Web3 from 'web3';

const web3 = new Web3(Web3.givenProvider || "http://localhost:8545");
web3.eth.getAccounts().then(console.log);
class Dashboard extends React.Component {

    constructor(props) {
        super(props);
    }

    head() {
        return (
            <Helmet bodyAttributes={{class: "dashboardPage"}}>
                <title>Dashboard - React Starter Kit</title>
            </Helmet>
        );
    }

    render() {

        return (
            <section className="content_block dashboard">
                {this.head()}
                <div className="grid">

                    <div className="column column_12_12">
                        <div className="content_wrap">
                            <div className="title">What is Lorem Ipsum?</div>
                            <p className="desc">
                                ...
                            </p>
                        </div>
                    </div>
                    <div className="column column_4_12">
                        <div className="content_wrap">
                            <div className="title">What is Lorem Ipsum?</div>
                            <p className="desc">
                                ...
                            </p>
                        </div>
                    </div>

                    <div className="column column_4_12">
                        <div className="content_wrap">
                            <div className="title">What is Lorem Ipsum?</div>
                            <p className="desc">
                               ...
                            </p>
                        </div>
                    </div>
                    <div className="column column_4_12">
                        <div className="content_wrap">
                            <div className="title">What is Lorem Ipsum?</div>
                            <p className="desc">
                                ...
                            </p>
                        </div>
                    </div>

                </div>

            </section>
        );

    }

}

export default withAuth(session => session && session.getCurrentUser)(Dashboard);

**Comment by nivida** [comment]
This is a configuration issue of your dev environment. Could you ask your question on stackoverflow or in our Web3.js gitter channel?
