### ISSUE TITLE
 Error: Returned values aren't valid, did it run Out of Gas?

### ISSUE THREAD

**Issue by princesinha19** [ethereum/web3.js#2492]
When I am executing the transfer method, I am getting this error:  Error: Returned values aren't valid, did it run Out of Gas?

#### Expected behavior
Calling 
`await myContract.methods.transfer(to_wallet, amount).send({from:wallet.w_address}).then(async function(result){ console.log('Token Transferred succesfully!!')});` 
should transfer the token to receiver.

#### Actual behavior
Getting error:  **Error: Returned values aren't valid, did it run Out of Gas?**

#### Steps to reproduce the behavior
    1. Import `web3`
    2. Deploy contract using web3.deploy
    3. Unlock account using web3.eth.personal.unlockAccount()
    3. Call transfer function of deployed ERC20 contract using contract address and ABI

#### Error Logs 
```
(node:13121) UnhandledPromiseRejectionWarning: Error: Returned values aren't valid, did it run Out of Gas?
   at ABICoder.decodeParameters (/home/ubuntu/node_modules/web3-eth-abi/src/index.js:226:15)
   at Contract._decodeMethodReturn (/home/ubuntu/node_modules/web3-eth-contract/src/index.js:465:22)
   at Method.outputFormatter (/home/ubuntu/node_modules/web3-eth-contract/src/index.js:818:46)
   at Method.formatOutput (/home/ubuntu/node_modules/web3-core-method/src/index.js:163:54)
   at sendTxCallback (/home/ubuntu/node_modules/web3-core-method/src/index.js:473:33)
   at Object.<anonymous> (/home/ubuntu/node_modules/web3-core-requestmanager/src/index.js:147:9)
   at /home/ubuntu/node_modules/web3-providers-ws/src/index.js:121:44
   at Array.forEach (<anonymous>)
   at W3CWebSocket.WebsocketProvider.connection.onmessage (/home/ubuntu/node_modules/web3-providers-ws/src/index.js:98:36)
   at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/ubuntu/node_modules/yaeti/lib/EventTarget.js:107:17)
   at W3CWebSocket.onMessage (/home/ubuntu/node_modules/websocket/lib/W3CWebSocket.js:234:14)
   at WebSocketConnection.<anonymous> (/home/ubuntu/node_modules/websocket/lib/W3CWebSocket.js:205:19)
   at WebSocketConnection.emit (events.js:189:13)
   at WebSocketConnection.processFrame (/home/ubuntu/node_modules/websocket/lib/WebSocketConnection.js:552:26)
   at /home/ubuntu/node_modules/websocket/lib/WebSocketConnection.js:321:40
   at process._tickCallback (internal/process/next_tick.js:61:11)
(node:13121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
### Versions 
web3.js: **"^1.0.0-beta.37"**
nodejs: **v10.15.2**
browser: **EC2 Instance**
ethereum node: **1.8.17-stable-8bbe7207**

Please help me out. Thanks.

**Comment by nivida** [comment]
Does this error still occur with v1.0.0-beta.48?

**Comment by princesinha19** [comment]
@nivida Thanks for your quick update. 
`Does this error still occur with v1.0.0-beta.48?
`
I am unable to install version v1.0.0-beta.48. I am getting this error:
```
npm ERR! path /home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386'
npm ERR!  { [Error: EACCES: permission denied, open '/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386']
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, open '/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'open',
npm ERR!      path:
npm ERR!       '/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, open \'/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path:
npm ERR!    '/home/ubuntu/.npm/_cacache/index-v5/dd/f7/12d75814ec6fa0074508c95da962aa381511947f9df5c20889b80e3fc386',
npm ERR!   parent: 'web3' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-13T10_23_46_061Z-debug.log
```
Can I use  **v1.0.0-beta.47**?

**Comment by princesinha19** [comment]
@nvidia I need some time to migrate my code on v1.0.0-beta.48. I will get back to you.
