### ISSUE TITLE
Deploy help

### ISSUE THREAD

**Issue by billtlee** [ethereum/web3.js#2505]
I am trying to deploy a contract but I am getting "Error: The number of arguments is not matching the methods required number. You need to pass 4 arguments." for some reason.
I have tried calling deploy with compiledFactory.evm.bytecode and compiledFactory.evm.bytecode.object.  Both are failing.  The contract constructor doesn't take any arguments.  I don't understand why it's asking me for 4.  Any help is greatly appreciated.

```
contract DataUsageFactory {
  DataUsage[] public deployedDataUsage;
  constructor() public payable {
  }

  function createDataUsage(bytes32 requestorName, bytes32 locationHash, address payable dataOwner) public payable {
    DataUsage newDataUsage = (new DataUsage).value(msg.value)(requestorName, locationHash, msg.sender, dataOwner);
    deployedDataUsage.push(newDataUsage);
  }

  function getDeployedDataUsage() public view returns(DataUsage[] memory){
    return deployedDataUsage;
  }
}
```

```
const provider = new HDWalletProvider(
  process.env.MNEMONIC,
  process.env.PROVIDER_URI
);

const web3 = new Web3(provider);

const deploy = async () => {
    const accounts = await web3.eth.getAccounts();

  console.log('Attempting to deploy from account ', accounts[0]);

  const result = await new web3.eth.Contract(compiledFactory.abi)
    .deploy({ data: compiledFactory.evm.bytecode })
    .send({ gas: '1500000', from: accounts[0] });
```

#### Error Logs 

(node:26775) UnhandledPromiseRejectionWarning: Error: The number of arguments is not matching the methods required number. You need to pass 4 arguments.
    at AbiItemModel.givenParametersLengthIsValid (/Users/Bill/Documents/MyProjects/ethereum-projects/dataUsage/node_modules/web3-eth-contract/dist/web3-eth-contract.cjs.js:124:13)
    at MethodsProxy.createMethod (/Users/Bill/Documents/MyProjects/ethereum-projects/dataUsage/node_modules/web3-eth-contract/dist/web3-eth-contract.cjs.js:566:20)
    at MethodsProxy.executeMethod (/Users/Bill/Documents/MyProjects/ethereum-projects/dataUsage/node_modules/web3-eth-contract/dist/web3-eth-contract.cjs.js:546:23)
    at Function.anonymousFunction.(anonymous function) [as send] (/Users/Bill/Documents/MyProjects/ethereum-projects/dataUsage/node_modules/web3-eth-contract/dist/web3-eth-contract.cjs.js:520:29)
    at deploy (/Users/Bill/Documents/MyProjects/ethereum-projects/dataUsage/deploy.js:21:6)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### Versions 
* web3.js: 1.0.0-beta.48
"truffle-hdwallet-provider": "^1.0.5"
* nodejs: 10.14.1
* browser: 
* ethereum node:

**Comment by nivida** [comment]
Closed because we do currently clean up the issue list. Feel free to ask this in our gitter channel or on stackoverflow.
