### ISSUE TITLE
web3.eth.contract is not a function

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2531]
### Description 

` Contract.at is not a function`

### Code on 0.20.0

```
var eth = require('./web3relay').eth;

var BigNumber = require('bignumber.js');
var etherUnits = require(__lib + "etherUnits.js")

const ABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":t$

const Contract = eth.contract(ABI);


module.exports = function(req, res){
  console.log(req.body)

  var contractAddress = req.body.address;

  var Token = Contract.at(contractAddress);

  if (!("action" in req.body))
    res.status(400).send();
  else if (req.body.action=="info") {
    try {
      var actualBalance = eth.getBalance(contractAddress);
      actualBalance = etherUnits.toEther(actualBalance, 'wei');
      var totalSupply = Token.totalSupply();
      // totalSupply = etherUnits.toEther(totalSupply, 'wei')*100;
      var decimals = Token.decimals();
      var name = Token.name();
      var symbol = Token.symbol();
      var count = eth.getTransactionCount(contractAddress);
      var tokenData = {
        "balance": actualBalance,
        "total_supply": totalSupply,
        "count": count,
        "name": name,
        "symbol": symbol,
        "bytecode": eth.getCode(contractAddress)
      }
      res.write(JSON.stringify(tokenData));
      res.end();
    } catch (e) {
      console.error(e);
    }
  } else if (req.body.action=="balanceOf") {
    var addr = req.body.user.toLowerCase();
    try {
      var tokens = Token.balanceOf(addr);
      // tokens = etherUnits.toEther(tokens, 'wei')*100;
      res.write(JSON.stringify({"tokens": tokens}));
      res.end();
    } catch (e) {
      console.error(e);
    }
  }

};
```

### Code for 1.0.0-beta.36
```
var eth = require('./web3relay').eth;

var BigNumber = require('bignumber.js');
var etherUnits = require(__lib + "etherUnits.js")

const ABI = [{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":t$

const Contract = new eth.Contract(ABI);

module.exports = async (req, res) => {
  console.log(req.body)

  var contractAddress = req.body.address;

  var Token = Contract.at(contractAddress);

  if (!("action" in req.body))
    res.status(400).send();
  else if (req.body.action=="info") {
    try {
      var actualBalance = eth.getBalance(contractAddress);
      actualBalance = etherUnits.toEther(actualBalance, 'wei');
      var totalSupply = Token.totalSupply();
      // totalSupply = etherUnits.toEther(totalSupply, 'wei')*100;
      var decimals = Token.decimals();
      var name = Token.name();
      var symbol = Token.symbol();
      var count = eth.getTransactionCount(contractAddress);
      var tokenData = {
        "balance": actualBalance,
        "total_supply": totalSupply,
        "count": count,
        "name": name,
        "symbol": symbol,
        "bytecode": eth.getCode(contractAddress)
      }
      res.write(JSON.stringify(tokenData));
      res.end();
    } catch (e) {
      console.error(e);
    }
  } else if (req.body.action=="balanceOf") {
    var addr = req.body.user.toLowerCase();
    try {
      var tokens = Token.balanceOf(addr);
      // tokens = etherUnits.toEther(tokens, 'wei')*100;
      res.write(JSON.stringify({"tokens": tokens}));
      res.end();
    } catch (e) {
      console.error(e);
    }
  }

};
```

#### Actual behavior

` Contract.at is not a function`

#### Error Logs 

```
(node:4269) UnhandledPromiseRejectionWarning: TypeError: Contract.at is not a function
    at module.exports (/home/ubuntu/etc-explorer/routes/token.js:21:24)
    at Layer.handle [as handle_request] (/home/ubuntu/etc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/etc-explorer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/etc-explorer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/etc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/ubuntu/etc-explorer/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/ubuntu/etc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/ubuntu/etc-explorer/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/ubuntu/etc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/etc-explorer/node_modules/express/lib/router/index.js:275:10)
    at /home/ubuntu/etc-explorer/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/ubuntu/etc-explorer/node_modules/raw-body/index.js:224:16)
(node:4269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4269) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Versions 
* web3.js: `1.0.0-beta.36`
* nodejs: `8`
* browser:
* ethereum node: `parity`

**Comment by OFRBG** [comment]
Hey, try setting the address with this: https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#options-address.

**Comment by ghost** [comment]
@OFRBG Still same

```
(node:5046) UnhandledPromiseRejectionWarning: TypeError: Contract.options.address is not a function
```

With code 

```
-  var Token = Contract.at(contractAddress);
+  var Token = Contract.options.address(contractAddress);
```

**Comment by avrdan** [comment]
Why was this closed? As in the last comment, neither of the two provided options work...

Edit: Nevermind, it works.. BLA.options.address = "address"
