### ISSUE TITLE
Babel doesn't transpile default function parameter values

### ISSUE THREAD

**Issue by JirkaChadima** [ethereum/web3.js#2537]
### Description 

web3-eth cannot be constructed without seemingly optional parameters because [@babel/plugin-transform-parameters](https://babeljs.io/docs/en/babel-plugin-transform-parameters) is not used.

#### Expected behavior

Calling `new Web3Eth(provider);`

return a new instance of Web3Eth.

#### Actual behavior

Calling `new Web3Eth(provider);` fails with 

```
     TypeError: Cannot read property 'transactionSigner' of undefined
      at new Accounts (node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:184:39)
      at new Accounts$$1 (node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:472:10)
```

Calling `new Web3Eth(provider, null, {});` works

#### Steps to reproduce the behavior

```js
import { Eth as Web3Eth } from 'web3-eth';
const web3Eth = new Web3Eth(provider);
```

#### Error Logs 

```
     TypeError: Cannot read property 'transactionSigner' of undefined
      at new Accounts (node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:184:39)
      at new Accounts$$1 (node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:472:10)
      at new Eth$$1 (node_modules/web3-eth/dist/web3-eth.cjs.js:356:18)
// ... customer code follows
```

### Versions 
* web3.js: 1.0.0-beta.48
* nodejs: v10.15.0
* browser: not tested
* ethereum node: ganache-cli 6.4.1

**Comment by nivida** [comment]
This got fixed with version 1.0.0-beta.50.
