### ISSUE TITLE
web3.eth.abi.encodeParameter not encoding bytes32

### ISSUE THREAD

**Issue by roma-derski** [ethereum/web3.js#2546]
What happened:
    Calling `web3.eth.abi.encodeParameter('bytes32', '0xdf3234');` returns
`Error: invalid bytes32 value ...`

#### Expected behavior:
    Calling `web3.eth.abi.encodeParameter('bytes32', '0xdf3234');` should return
`> "0xdf32340000000000000000000000000000000000000000000000000000000000"`
according to example at: https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html#encodeparameter

#### Actual behavior
    Calling `web3.eth.abi.encodeParameter('bytes32', '0xdf3234');` returns
`Error: invalid bytes32 value (arg="", coderType="bytes32", value="0xdf3234", version=4.0.27)
    at Object.throwError (/home/runner/node_modules/ethers/errors.js:76:17)
    at CoderFixedBytes.encode (/home/runner/node_modules/ethers/utils/abi-coder.js:473:20)
    at /home/runner/node_modules/ethers/utils/abi-coder.js:645:59
    at Array.forEach (<anonymous>)
    at pack (/home/runner/node_modules/ethers/utils/abi-coder.js:644:12)
    at CoderTuple.encode (/home/runner/node_modules/ethers/utils/abi-coder.js:804:16)
    at AbiCoder.encode (/home/runner/node_modules/ethers/utils/abi-coder.js:941:77)
    at AbiCoder.encodeParameters (/home/runner/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:45:34)
    at AbiCoder.encodeParameter (/home/runner/node_modules/web3-eth-abi/dist/web3-eth-abi.cjs.js:40:19)
    at Object.<anonymous> (/home/runner/index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)`

#### Steps to reproduce the behavior
    1. Import `web3`
    2. Set the provider to Infura
    3. Call `web3.eth.abi.encodeParameter('bytes32', '0xdf3234')`

### Versions 
* web3.js: 1.0.0-beta.50
* nodejs: 11.10.0

**Comment by nivida** [comment]
You have to pass a valid bytes32 string. The padding of the bytes32 is missing.

Fix: 
``
web3.eth.abi.encodeParameter('bytes32', web3.utils.rightPad('0xdf3234', 64));
``

**Comment by cnasikas** [comment]
> You have to pass a valid bytes32 string. The padding of the bytes32 is missing.
> 
> Fix:
> `web3.eth.abi.encodeParameter('bytes32', web3.utils.rightPad('0xdf3234', 64));`

Why you pass 64 in `rightPad` instead of 32 ?

I am asking because I had the same problem. I was right padding with `32`. When I switched to `64` my problem was solved.

**Comment by PaulRBerg** [comment]
Because one hex digit is a [nibble][nibble], which is half a byte. 64 nibbles = 32 bytes.

Do note though that the `0x` prefix is excluded from the total byte count. That is, when you use `web3.utils.rightPad(hexValue, 64)`, the actual length in JavaScript characters is 66.

[nibble]: https://en.wikipedia.org/wiki/Nibble

**Comment by cnasikas** [comment]
Oh I see. It makes sense. Nevertheless, I think that the [documentation](https://web3js.readthedocs.io/en/1.0/web3-utils.html#padright) is a bit misleading as it states that the second argument is the number of **characters** the total string should have.

Thanks a lot!

**Comment by cnasikas** [comment]
My mistake the documentation is correct as a 32 bytes hex should have 64 characters (without 0x) as @PaulRBerg mentioned.

**Comment by PaulRBerg** [comment]
Yes, the docs for the padding functions are correct, but that's not true for the abi encoders. A lot of the [examples][abi-encoder-examples] are failing:

```
> web3.eth.abi.encodeParameter('bytes32', '0xdf3234')
> Error: invalid bytes32 value (arg="", coderType="bytes32", value="0xdf3234", version=4.0.27)
```

But you can solve that by applying the fix previously specified by @nivida.

Do note that the web3.js package is still in beta. There is a warning at the start of the documentation:

<img width="695" alt="Screen Shot 2019-05-20 at 15 46 30" src="https://user-images.githubusercontent.com/8782666/58030460-7beae780-7b16-11e9-85c2-afa84e2920b1.png">

[abi-encoder-examples]: https://web3js.readthedocs.io/en/1.0/web3-eth-abi.html
