### ISSUE TITLE
getPastEvents only works about every 10th - 20th time

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#2588]
### Description 
`getPastEvents` works only sometimes

#### Expected behavior
return event logs every time

#### Actual behavior
returns about every 10th to 20th attempt the event logs. The remaining time I get the error below

#### Steps to reproduce the behavior

```js
const Web3 = require('web3')
const web3 = new Web3(new Web3.providers.HttpProvider('projectID')

const contractAddress = '0x...'
const abi = require('./abiFile')
var tokenContract = new web3.eth.Contract(abi, contractAddress)

tokenContract.getPastEvents('Transfer', {
    fromBlock: 7000000,
    toBlock: 'latest',
}, (error, events) => { 
    if (error) console.error(error);
    else console.log(events); }
)
```

#### Error Logs 
```
Error: Node error: {"code":-32603,"message":"request failed or timed out"}
    at Function.validate (/home/pathforname/node_modules/web3-providers/dist/web3-providers.cjs.js:111:18)
    at HttpProvider._callee$ (/home/pathforname/node_modules/web3-providers/dist/web3-providers.cjs.js:674:61)
    at tryCatch (/home/pathforname/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/pathforname/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pathforname/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/pathforname/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/pathforname/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12534) UnhandledPromiseRejectionWarning: Error: Node error: {"code":-32603,"message":"request failed or timed out"}
    at Function.validate (/home/pathforname/node_modules/web3-providers/dist/web3-providers.cjs.js:111:18)
    at HttpProvider._callee$ (/home/pathforname/node_modules/web3-providers/dist/web3-providers.cjs.js:674:61)
    at tryCatch (/home/pathforname/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/pathforname/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/pathforname/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/pathforname/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/pathforname/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:12534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Versions 
* web3.js: 1.0.0-beta.50
* nodejs: 10.15.0
* browser:
* ethereum node: Infura mainnet

**Comment by nivida** [comment]
This is an issue of infura not of Web3.js please open an issue in the repository of infura.

**Comment by ghost** [comment]
Just wanted to add that it works if I set `fromBlock: 7300000`.
