### ISSUE TITLE
Calling new Web3() without a provider breaks

### ISSUE THREAD

**Issue by danoctavian** [ethereum/web3.js#2689]
#### Expected behavior

    Running this should not crash.
```
const Web3 = require('Web3')
const web3 = new Web3()
```

#### Actual behavior

   Crashes With
```
/Users/dan/qiibeework/qb-listener/node_modules/web3-providers/dist/web3-providers.cjs.js:49
      if (provider.sendPayload && provider.subscribe) {
                   ^

TypeError: Cannot read property 'sendPayload' of undefined
    at ProviderResolver.resolve (/Users/dan/qiibeework/qb-listener/node_modules/web3-providers/dist/web3-providers.cjs.js:49:20)
    at Web3.AbstractWeb3Module (/Users/dan/qiibeework/qb-listener/node_modules/web3-core/dist/web3-core.cjs.js:24:51)
    at new Web3 (/Users/dan/qiibeework/qb-listener/node_modules/Web3/dist/web3.cjs.js:30:68)
    at Object.<anonymous> (/Users/dan/qiibeework/qb-listener/junk.js:3:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Process finished with exit code 1```

### Versions 
* web3.js:
1.0.0-beta.52
* nodejs:
v8.15.0

**Comment by nivida** [comment]
Thanks for opening this issue! I‘ll fix and release it asap.

**Comment by danoctavian** [comment]
thanks @nivida

**Comment by raphael-arce** [comment]
I still get this crash (calling web3 without provider) in the 1.0.0-beta.53 version. Exactly the same code and error message as described by @danoctavian. Also getting this crash when trying to call web3 with a provider:  
```
const Web3 = require('web3')
const web3 = new Web3(new Web3.providers.HttpProvider('https://ropsten.infura.io/v3/<mykey>'))
```

Perhaps I am doing something wrong? 

Edit: My bad, the error actually came from somewhere else.
