### ISSUE TITLE
Clean checkout of 1.0 builds, but testing fails

### ISSUE THREAD

**Issue by sshelton76** [ethereum/web3.js#2745]
It appears if you do a clean checkout of 1.0 branch, then do an 

```
npm install && npm run-script build && npm test
```

There are some failures during testing...
```
username@laptop:~/Projects/web3js$ npm install && npm run-script build && npm test
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

Also...
```
> web3-utils@1.0.0-beta.52 test /home/username/Projects/web3js/packages/web3-utils
> jest

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

lerna ERR! npm run test stderr:
FAIL tests/src/SoliditySha3Test.js
  ● Test suite failed to run

    Cannot find module 'bn.js' from 'SoliditySha3Test.js'

      1 | import isArray from 'lodash/isArray';
    > 2 | import BN from 'bn.js';
        | ^
      3 | import {soliditySha3} from '../../src/SoliditySha3';
      4 | 
      5 | /**

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:229:17)
      at Object.<anonymous> (tests/src/SoliditySha3Test.js:2:1)

FAIL tests/src/UtilsTest.js
  ● Test suite failed to run

    Cannot find module 'crypto-js' from 'UtilsTest.js'

    > 1 | import * as CryptoJS from 'crypto-js';
        | ^
      2 | import cjsSha3 from 'crypto-js/sha3';
      3 | import BN from 'bn.js';
      4 | import {

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:229:17)
      at Object.<anonymous> (tests/src/UtilsTest.js:1:1)

FAIL tests/src/BloomFilterTest.js
  ● Test suite failed to run

    Cannot find module 'number-to-bn' from 'Utils.js'

    However, Jest was able to find:
    	'../../src/BloomFilter.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      27 | import isObject from 'lodash/isObject';
      28 | import isNull from 'lodash/isNull';
    > 29 | import numberToBN from 'number-to-bn';
         | ^
      30 | import utf8 from 'utf8';
      31 | import Hash from 'eth-lib/lib/hash';
      32 | import BN from 'bn.js';

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/index.js:229:17)
      at Object.<anonymous> (src/Utils.js:29:1)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        9.151s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3-utils@1.0.0-beta.52 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web3-utils@1.0.0-beta.52 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2019-04-27T07_58_38_702Z-debug.log

lerna ERR! npm run test exited 1 in 'web3-utils'
npm ERR! Test failed.  See above for more details.
```

**Comment by nivida** [comment]
Did you run ``npm run bootstrap``?

**Comment by sshelton76** [comment]
> Did you run `npm run bootstrap`?

No because I didn't see that listed anywhere in the steps to build.  I'll give it a try and let you know.

*update*
Ran that and it fixed the problem.  Is this documented somewhere and I just missed it?

**Comment by nivida** [comment]
Yes, it's documented here: https://github.com/ethereum/web3.js#commands :)
