### ISSUE TITLE
npm show web3 versions is giving npm ERR!

### ISSUE THREAD

**Issue by zemse** [ethereum/web3.js#2761]
### Description 
`$ npm show web3 versions` gives error.

#### Actual behavior

```
$ npm show web3 versions
npm ERR! Unexpected end of JSON input while parsing near '...encies":{"web3-bzz":"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sohamzemse/.npm/_logs/2019-05-01T07_43_10_701Z-debug.log
```

#### Steps to reproduce the behavior

`$ npm show web3 versions`

#### Error Logs 

the log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'show',
1 verbose cli   'web3',
1 verbose cli   'versions' ]
2 info using npm@6.9.0
3 info using node@v11.7.0
4 verbose npm-session feb8fd175a61de90
5 http fetch GET 304 https://registry.npmjs.org/web3 549ms (from cache)
6 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...encies":{"web3-bzz":"'
6 verbose stack     at JSON.parse (<anonymous>)
6 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
6 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
6 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
7 verbose cwd /Users/sohamzemse/soham/workspace/blockchain/ethereum/kickstart2
8 verbose Darwin 18.0.0
9 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "show" "web3" "versions"
10 verbose node v11.7.0
11 verbose npm  v6.9.0
12 error Unexpected end of JSON input while parsing near '...encies":{"web3-bzz":"'
13 verbose exit [ 1, true ]
```

### Versions 
* web3.js:
* nodejs: v11.7.0
* browser:
* ethereum node:

**Comment by nivida** [comment]
I've executed ``npm show web3 versions`` and got the following console output: 
``` javascript 
[ '0.2.5',
  '0.2.6',
  '0.2.7',
  '0.2.8',
  '0.3.0',
  '0.3.1',
  '0.3.2',
  '0.3.3',
  '0.3.4',
  '0.3.6',
  '0.4.0',
  '0.4.1',
  '0.4.2',
  '0.4.3',
  '0.5.0',
  '0.6.0',
  '0.7.0',
  '0.7.1',
  '0.8.0',
  '0.8.1',
  '0.9.0',
  '0.9.1',
  '0.9.2',
  '0.10.0',
  '0.11.0',
  '0.12.0',
  '0.12.1',
  '0.12.2',
  '0.13.0',
  '0.14.0',
  '0.14.1',
  '0.15.0',
  '0.15.1',
  '0.15.2',
  '0.15.3',
  '0.16.0',
  '0.17.0-alpha',
  '0.17.0-beta',
  '0.18.0',
  '0.18.1',
  '0.18.2',
  '0.18.4',
  '0.19.0',
  '0.19.1',
  '0.20.1',
  '0.20.2',
  '0.20.3',
  '0.20.4',
  '0.20.5',
  '0.20.6',
  '0.20.7',
  '1.0.0-beta.1',
  '1.0.0-beta.2',
  '1.0.0-beta.3',
  '1.0.0-beta.4',
  '1.0.0-beta.5',
  '1.0.0-beta.6',
  '1.0.0-beta.7',
  '1.0.0-beta.9',
  '1.0.0-beta.10',
  '1.0.0-beta.11',
  '1.0.0-beta.12',
  '1.0.0-beta.13',
  '1.0.0-beta.14',
  '1.0.0-beta.15',
  '1.0.0-beta.16',
  '1.0.0-beta.17',
  '1.0.0-beta.18',
  '1.0.0-beta.19',
  '1.0.0-beta.20',
  '1.0.0-beta.21',
  '1.0.0-beta.22',
  '1.0.0-beta.23',
  '1.0.0-beta.24',
  '1.0.0-beta.25',
  '1.0.0-beta.26',
  '1.0.0-beta.27',
  '1.0.0-beta.28',
  '1.0.0-beta.29',
  '1.0.0-beta.30',
  '1.0.0-beta.31',
  '1.0.0-beta.32',
  '1.0.0-beta.33',
  '1.0.0-beta.34',
  '1.0.0-beta.35',
  '1.0.0-beta.36',
  '1.0.0-beta.37',
  '1.0.0-beta.38',
  '1.0.0-beta.39',
  '1.0.0-beta.40',
  '1.0.0-beta.41',
  '1.0.0-beta.42',
  '1.0.0-beta.43',
  '1.0.0-beta.44',
  '1.0.0-beta.46',
  '1.0.0-beta.47',
  '1.0.0-beta.48',
  '1.0.0-beta.49',
  '1.0.0-beta.50',
  '1.0.0-beta.51',
  '1.0.0-beta.52',
  '1.0.0-beta.53',
  '1.0.0-beta1',
  '1.0.0-beta2' ]
```

**Comment by zemse** [comment]
I'm sorry! That was probably some issue with npm on my machine.
`npm cache clean --force` solved it.
