### ISSUE TITLE
Loading a contract instance throws error in web3

### ISSUE THREAD

**Issue by rogergangawork** [ethereum/web3.js#2769]
### Description 
Trying to load a contract instance. Throws an error. Haven't encountered this error before

#### Expected behavior

`web3= new Web3(new Web3.providers.HttpProvider(rpc));`
`var contractInstance = new web3.eth.Contract(contractABI, contractAddress, { from: contractExecutor });
console.log(contractInstance)`

The above code should work fine and return a contract instance.

#### Actual behavior

**Error**

TypeError: Cannot assign to read only property 'constant' of object '#<Object>'
    at C:\path\to\dir\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:293:26
    at Array.forEach (<anonymous>)
    at AbiMapper.map (C:\path\to\dir\node_modules\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:292:11)...

#### Steps to reproduce the behavior

1. Import web3
2. Define contract ABI (array type)
3. Define contract address
4. Load contractInstance using contract function

#### Error Logs 

TypeError: Cannot assign to read only property 'constant' of object '#<Object>'
    at C:\path\to\dir\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:293:26
    at Array.forEach (<anonymous>)
    at AbiMapper.map (C:\path\to\dir\node_modules\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:292:11)...

### Versions 
* web3.js: 1.0.0-beta.53
* nodejs: v8.11.2

#

**Comment by nivida** [comment]
Could you add the ABI your importing?

**Comment by rogergangawork** [comment]
Hi @nivida !

I used the ERC20 ABI json which can be found [here](https://gist.github.com/veox/8800debbf56e24718f9f483e1e40c35c). 

Upon drilling down further, I realized that this error occurs only if I try to read the ABI from the using config dependency.

**Folder Structure**:

* main
  * config
    * develop.json
  * app.js

**Code in develop.json :**

````
{
 "erc_contract": {
    "abi": [
    {
      "constant": true,
      "inputs": [],
      "name": "owner",
      "outputs": [
        {
          "name": "",
          "type": "address"
        }
      ],
      "payable": false,
      "stateMutability": "view",
      "type": "function",
      "signature": "0x8da5cb5b"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "newOwner",
          "type": "address"
        }
      ],
      "name": "transferOwnership",
      "outputs": [],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function",
      "signature": "0xf2fde38b"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "total",
          "type": "uint256"
        },
        {
          "indexed": false,
          "name": "tokenAddress",
          "type": "address"
        }
      ],
      "name": "Multisended",
      "type": "event",
      "signature": "0x04afd2ce457d973046bd54f5d7d36368546da08b88be1bca8ae50e32b451da17"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "_dataVendor",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "_joules",
          "type": "uint256"
        }
      ],
      "name": "QuadsPaid",
      "type": "event",
      "signature": "0xd0dd136c24b432fe458dd01c94b9485028d1c83563e09297ade497dc802a688c"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "_dataVendor",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "_joules",
          "type": "uint256"
        }
      ],
      "name": "QuadsWithdrawn",
      "type": "event",
      "signature": "0xa1eeef7907e8825aa9b3a9370f9645cd0e543596b3324ee0f386f439adb85dc0"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "name": "_dataBuyer",
          "type": "address"
        },
        {
          "indexed": false,
          "name": "_joules",
          "type": "uint256"
        }
      ],
      "name": "ExcessQuadsReturned",
      "type": "event",
      "signature": "0x00c68626184570456ecdc1cf67a99ab0bef8914f159a09bdedccacf372e9b57d"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "name": "previousOwner",
          "type": "address"
        },
        {
          "indexed": true,
          "name": "newOwner",
          "type": "address"
        }
      ],
      "name": "OwnershipTransferred",
      "type": "event",
      "signature": "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_dataVendors",
          "type": "address[]"
        },
        {
          "name": "_joules",
          "type": "uint256[]"
        }
      ],
      "name": "payQuads",
      "outputs": [],
      "payable": true,
      "stateMutability": "payable",
      "type": "function",
      "signature": "0xe1c7902f"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_joules",
          "type": "uint256"
        }
      ],
      "name": "withdrawQuads",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function",
      "signature": "0x8e73419b"
    },
    {
      "constant": false,
      "inputs": [
        {
          "name": "_receiver",
          "type": "address"
        },
        {
          "name": "_joules",
          "type": "uint256"
        }
      ],
      "name": "withdrawQuadsToAddress",
      "outputs": [
        {
          "name": "",
          "type": "bool"
        }
      ],
      "payable": false,
      "stateMutability": "nonpayable",
      "type": "function",
      "signature": "0x7a44d7f6"
    }
  ]
  }
}
````

**Code in App.js :**

````
var config = require('config');
var erc_contract = config.get('erc_contract');
var Web3 = require('web3');

var contractAddress = '0xCONTRACTADDRESS';
var contractExecutor = '0xCONTRACTEXECUTOR';
var contractABI = erc_contract.abi;

web3= new Web3(new Web3.providers.HttpProvider(rpc));
var contractInstance = new web3.eth.Contract(contractABI, contractAddress, { from: contractExecutor });
console.log(contractInstance );
````

**Output:**

TypeError: Cannot assign to read only property 'constant' of object '#'
at C:\path\to\dir\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:293:26
at Array.forEach ()
at AbiMapper.map (C:\path\to\dir\node_modules\node_modules\web3-eth-contract\dist\web3-eth-contract.cjs.js:292:11)...

**If I define the ABI directly in app.js, it works fine. But when defined in develop.json and tried to read from the config directory, it returns an error.**

This used to work smooth before but it returns an error now. Tried on the web3 js older versions as well and it still returns an error.

**Comment by nivida** [comment]
I've tested it with the ABI placed in a separate file and with the usage of a  ``var`` in the same file and both solutions do work.
