### ISSUE TITLE
Web3js error https://infura.io/

### ISSUE THREAD

**Issue by VerilogR** [ethereum/web3.js#2797]
### Description 
hi there. I try to use some code for https://infura.io/

#### Expected behavior
---------------------------------------------------------------------------------------->
   const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider("https://main-rpc.linkpool.io"));

let privateKey = "privatekey";

let tx = {
    from: '0xb5fcc962b61Ea40d22a012ab0cF94341DDb7f68F',
    to: '0x15AE271790e8A0a4aC0D4C0dAA16adc3B72c72D5',
    value: '0x0',
    gas: 350000,
    gasPrice: 10000000000,
    data: '0xe2f8b619',
    nonce: 1,
};

web3.eth.accounts.signTransaction(tx, privateKey).then(signed => {
    let tran = web3.eth.sendSignedTransaction(signed.rawTransaction);

    tran.on('transactionHash', hash => {
        console.log('hash');
        console.log(hash);
    });

    tran.on('confirmation', (confirmationNumber, receipt) => {
        console.log('confirmation: ' + confirmationNumber);
    });

    tran.on('receipt', receipt => {
        console.log('reciept');
        console.log(receipt);
    });

    tran.on('error', console.error);
});
----------------------------------------------------------------------->

But it make an error. Please explain what i do wrong

#### Error Logs 
hash
0x3e91427e15075c27234f65cbc3949b5e1c9567244dbc3aa14395230452627caa
{ error:
   Error: Node error: {"code":-32042,"message":"Bad response on request: [ TransactionIndex ]. Error cause was EmptyResponse, (majority count: 69 / total: 69)"}
       at Function.validate (/home/dmitriy/Projects/SignedTransactionETH/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
       at HttpProvider._callee$ (/home/dmitriy/Projects/SignedTransactionETH/node_modules/web3-providers/dist/web3-providers.cjs.js:710:61)
       at tryCatch (/home/dmitriy/Projects/SignedTransactionETH/node_modules/regenerator-runtime/runtime.js:45:40)
       at Generator.invoke [as _invoke] (/home/dmitriy/Projects/SignedTransactionETH/node_modules/regenerator-runtime/runtime.js:271:22)
       at Generator.prototype.(anonymous function) [as next] (/home/dmitriy/Projects/SignedTransactionETH/node_modules/regenerator-runtime/runtime.js:97:21)
       at asyncGeneratorStep (/home/dmitriy/Projects/SignedTransactionETH/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
       at _next (/home/dmitriy/Projects/SignedTransactionETH/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
       at process._tickCallback (internal/process/next_tick.js:68:7),
  receipt: false,
  confirmations: 0,
  confirmationChecks: 0 } undefined undefined

### Versions 
* web3.js: 1.0.0-beta.54
* nodejs: v10.15.3
* browser: console
* ethereum node: https://main-rpc.linkpool.io

**Comment by nivida** [comment]
Could you update your issue to a more readable version of it? :)

**Comment by VerilogR** [comment]
> Could you update your issue to a more readable version of it? :)

What information is needed?

**Comment by eggplantzzz** [comment]
@deque666 I assume indentation would be a good first step :)

**Comment by sshelton76** [comment]
Also can you please update the topic?  The endpoint you are using is from linkpool.io that's not infura.  Nor is it Ethereum at all.  Looks like it's for the LINK token.

**Comment by nivida** [comment]
I've closed this issue because it isn't formatted and in a readable way. Feel free to open a new issue if the error still occurs.
