### ISSUE TITLE
meteor package files not added on server

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/web3.js#281]
https://github.com/ethereum/web3.js/blob/master/package.js#L17-L20

even though the API exports `web3` on both the client and server, the package files are actually only added on the client side. expected is them to be added on both.

**Comment by debris** [comment]
@frozeman :)

**Comment by frozeman** [comment]
Hahah. Sure

**Comment by jorisbontje** [comment]
When trying to patch this in a local package, I am running into:
```
W20150730-15:08:51.084(2)? (STDERR) /Users/mids/.meteor/packages/meteor-tool/.1.1.3.sm1hd0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150730-15:08:51.084(2)? (STDERR) 						throw(ex);
W20150730-15:08:51.084(2)? (STDERR) 						      ^
W20150730-15:08:51.084(2)? (STDERR) TypeError: object is not a function
W20150730-15:08:51.085(2)? (STDERR)     at [object Object].HttpProvider.send (packages/ethereum:web3/dist/web3.js:3370:1)
W20150730-15:08:51.085(2)? (STDERR)     at [object Object].RequestManager.send (packages/ethereum:web3/dist/web3.js:4342:1)
W20150730-15:08:51.085(2)? (STDERR)     at [object Object].Property.get (packages/ethereum:web3/dist/web3.js:4226:1)
W20150730-15:08:51.085(2)? (STDERR)     at app/server/01_embark/embark.js:1:145
W20150730-15:08:51.085(2)? (STDERR)     at app/server/01_embark/embark.js:3:3
W20150730-15:08:51.085(2)? (STDERR)     at /Users/mids/Projects/Powr/powr-pilot/.meteor/local/build/programs/server/boot.js:222:10
W20150730-15:08:51.085(2)? (STDERR)     at Array.forEach (native)
W20150730-15:08:51.085(2)? (STDERR)     at Function._.each._.forEach (/Users/mids/.meteor/packages/meteor-tool/.1.1.3.sm1hd0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150730-15:08:51.085(2)? (STDERR)     at /Users/mids/Projects/Powr/powr-pilot/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
```

This probably has something to do with the `xmlhttprequest` override in web3's `package.json`

**Comment by frozeman** [comment]
Its fixed in develop, can you try?
@debris i had to add this line to the httpprovider.js

```js
var npmRequire = (typeof Meteor !== 'undefined' && Meteor.isServer) ? Npm.require : require;
```

Its not required for the other dependencies like crypto-js and BigNumber

**Comment by frozeman** [comment]
See https://github.com/ethereum/web3.js/commit/f9b735ea8b0608590af16abf42094fa7d3b6eb98

The line changes in the compiled files is only as i tested the other nom modules as well. i removed the lines, but may removed one empty line to much. Nothing to worry about

**Comment by jorisbontje** [comment]
@frozeman thanks, fixed in develop!
