### ISSUE TITLE
'syncing' event subscription crash the code

### ISSUE THREAD

**Issue by Jonas121** [ethereum/web3.js#2833]
### Description 

After web3 update from beta 37 to 55 version I have issue to run the code

#### Expected behavior
Node should send 'syncing' event and listener function of the event should catch and process it

#### Actual behavior
Code is starting and running for some time. Later after couple of hours all code crashing with the error message below

#### Steps to reproduce the behavior

I made peace of test code which reproduce the error:

``` javascript
var Web3 = require('web3');
var ROPSTEN_WSS = 'ws://35.x.x.x:x';

function getProvider() {
    var provider = new Web3.providers.WebsocketProvider(ROPSTEN_WSS)
    provider.on('connect', () => {
     console.log('WS Connected')
    })	
    provider.on('error', e => {
	 console.error('WS Error ' + new Date().toISOString())
    })
    provider.on('end', async e => {
		console.log('WS End')
		await web3.setProvider(getProvider())
    })
    return provider
}

web3 = new Web3(getProvider())

var subscription1 = web3.eth.subscribe('syncing', function (error, result) {
	console(error+" "+result)
	if (error) {
		console.log("Sync event error")
	} else {
		if (result == false) {
			console.log("Node is Synced")
		} else { 
			console.log("Node is NOT Synced")			
		}
	}
	})
	.on("data", function(sync){
	console.log('Sync event Data: ' + sync)
	})
	.on("changed", function(isSyncing){
		if(isSyncing) {
			console.log('Data - is syncing')
		} else {
			console.log('Data - ready')
		}	
	}) 	
```

#### Error Logs 

Error log on node console:

WS Connected
/home/ec2-user/node_modules/web3/node_modules/web3-core-subscriptions/dist/web3-core-subscriptions.cjs.js:195
      var isSyncing = subscriptionItem.result.syncing;
                                              ^

TypeError: Cannot read property 'syncing' of undefined
    at SyncingSubscription.onNewSubscriptionItem (/home/ec2-user/node_modules/web3/node_modules/web3-core-subscriptions/dist/web3-core-subscriptions.cjs.js:195:47)
    at WebsocketProvider.<anonymous> (/home/ec2-user/node_modules/web3/node_modules/web3-core-subscriptions/dist/web3-core-subscriptions.cjs.js:65:40)
    at WebsocketProvider.emit (/home/ec2-user/node_modules/web3-providers/node_modules/eventemitter3/index.js:181:35)
    at WebsocketProvider.onMessage (/home/ec2-user/node_modules/web3-providers/dist/web3-providers.cjs.js:304:12)
    at WebsocketProvider.onMessage (/home/ec2-user/node_modules/web3-providers/dist/web3-providers.cjs.js:404:77)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/ec2-user/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/ec2-user/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/ec2-user/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:188:13)
    at WebSocketConnection.processFrame (/home/ec2-user/node_modules/websocket/lib/WebSocketConnection.js:554:26)

### Versions 
* web3.js: web3@1.0.0-beta.55
* nodejs: v11.6.0
* ethereum node: Geth Version: 1.8.27-stable

**Comment by nivida** [comment]
Thanks for opening this issue! I will fix this with PR https://github.com/ethereum/web3.js/pull/2838

Btw.: The following code is no longer required because the ``WebsocketProvider`` has reconnecting implemented: 

``` javascript 
provider.on('end', async e => {
		console.log('WS End')
		await web3.setProvider(getProvider())
    })
```

**Comment by pizzarob** [comment]
@nivida which version has reconnecting implemented?
