### ISSUE TITLE
web3-core-promievent package exports unexpected value

### ISSUE THREAD

**Issue by liamaharon** [ethereum/web3.js#2849]
### Description 
Following the example in https://www.npmjs.com/package/web3-core-promievent throws an error due to `import PromiEvent from 'web3-core-promievent';` exporting something like an object with a PromiEvent property, instead of PromiEvent.  

#### Expected behavior
```javascript
import PromiEvent from 'web3-core-promievent';

const promiEvent = new PromiEvent()
```
should create a promiEvent

#### Actual behavior
```javascript
import PromiEvent from 'web3-core-promievent';

const promiEvent = new PromiEvent()
```
throws an error because PromiEvent is not a PromiEvent class. Instead, you need to do something like 
```javascript
import PromiEventLib from 'web3-core-promievent';

const promiEvent = new PromiEventLib.PromiEvent()
```

Note `import { PromiEvent } from 'web3-core-promievent';` doesn't work, throws

```
(node:2446) UnhandledPromiseRejectionWarning: Error: 'PromiEvent' is not exported by node_modules/web3-core-promievent/dist/web3-core-promievent.umd.js
    at error (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:12726:29)
    at FunctionScope.Scope.findVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:4022:68)
    at FunctionScope.Scope.findVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:4022:68)
    at MemberExpression$$1.bind (/home/liam/git/assist/node_modules/rollup/dist/rollup.js:11244:50)
```

#### Steps to reproduce the behavior
1. `yarn add web3-core-promievent`
2. 
```javascript
import PromiEvent from 'web3-core-promievent';

const promiEvent = new PromiEvent()
```

### Versions 
* web3.js: 1.0.0-beta.37
* nodejs: 10.15.3

**Comment by nivida** [comment]
Please use the PromiEvent object from the web3-core-method module.
