### ISSUE TITLE
Web3 call json rpc method error

### ISSUE THREAD

**Issue by northeusunshine** [ethereum/web3.js#2875]
I need to use web3 to call json rpc method, for example, get balance of a account.
but I got an error like below, please help，many thanks.

**web3 version**
`'1.0.0-beta.55'`
**Error message**
```
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      [Object: null prototype] {
        removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> (node:7635) UnhandledPromiseRejectionWarning: Error: Node error: {"code":-32700,"message":"json: cannot unmarshal object into Go struct field jsonRequest.method of type string"}
    at Function.validate (/root/sw/node-modules/node_modules/web3-providers/dist/web3-providers.cjs.js:114:18)
    at HttpProvider._callee$ (/root/sw/node-modules/node_modules/web3-providers/dist/web3-providers.cjs.js:710:61)
    at tryCatch (/root/sw/node-modules/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/root/sw/node-modules/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/root/sw/node-modules/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/root/sw/node-modules/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/root/sw/node-modules/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7635) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7635) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**the web3 call code lines:**
```
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.HttpProvider("http://xxxxxx:8545"));
web3.currentProvider.send({
    jsonrpc: "2.0",
    method: "eth_getBalance",
    params: ['0x3c46b43e683b5addd7e66b3d1d958854ffb58361','latest'],
    id: 8
} ,function (error, result) {console.log(result)})
```

**Comment by nivida** [comment]
The internal provider interface did change. ([HttpProvider](https://github.com/ethereum/web3.js/blob/1.0/packages/web3-providers/src/providers/HttpProvider.js))

**Comment by northeusunshine** [comment]
thanks, I can call use new interface to get balance of an account. however when I call "clique_getSignersAtHash", there is an error message. I checked the method should exist.
`UnhandledPromiseRejectionWarning: Error: Node error: {"code":-32601,"message":"The method getSignersAtHash_ does not exist/is not available"}`

```
		new web3._extend.Method({
			name: 'getSignersAtHash',
			call: 'clique_getSignersAtHash',
			params: 1
		}),
```

[https://github.com/ethereum/go-ethereum/blob/master/internal/web3ext/web3ext.go](url)
