### ISSUE TITLE
Batch requests over web socket fails for batch sizes larger than 197

### ISSUE THREAD

**Issue by swyngaard** [ethereum/web3.js#2908]
### Description 
I tried to use `web3.BatchRequest` to fetch blocks using the `WebsocketProvider` but it fails with a `TypeError`. The code works as expected when the batch request size is less than 198. It also works when using the `HttpProvider` for the same batch request size.

#### Expected behavior

Calling `await batch.execute()` should produce an object with the batch request results.

#### Actual behavior

Calling `await batch.execute()` produces the following error:
```
TypeError: Cannot read property 'subscription' of undefined
```

#### Steps to reproduce the behavior

1. Start and sync a `geth` peer node with the web socket interface enabled, .e.g add the following flags `--ws --wsaddr "0.0.0.0" --wsorigins "*"`. For testing purposes, you can setup a peer node in development mode by enabling the `--dev` flag and create 200+ transactions.
2. Import `web3` and create an instance using the `WebsocketProvider`.
4. Create a `BatchRequest` instance and add 250 requests.
5. Fetch the batch request results.

The code snippet below demonstrates what I'm trying to do:
```javascript
const Web3 = require('web3');
const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8546'));
//const latestBlock = await web3.eth.getBlockNumber();
const latestBlock = 250
const latestSavedBlock = -1;
const batch = new web3.BatchRequest();
for (let currentBlock = latestSavedBlock + 1; currentBlock <= latestBlock; currentBlock++) {
  batch.add(web3.eth.getBlock.request(currentBlock, false, () => {}));
}
const batchResults = await batch.execute();
batchResults.response.forEach(block => console.log(JSON.stringify(block)));
```

#### Error Logs 
```
/home/swyngaard/.nvm/versions/node/v10.16.0/bin/node --use-openssl-ca /home/swyngaard/blockchain-listener/sync.js
/home/swyngaard/blockchain-listener/node_modules/web3-providers/dist/web3-providers.cjs.js:298
        event = this.getSubscriptionEvent(response.params.subscription);
                                                          ^

TypeError: Cannot read property 'subscription' of undefined
    at WebsocketProvider.onMessage (/home/swyngaard/blockchain-listener/node_modules/web3-providers/dist/web3-providers.cjs.js:298:59)
    at WebsocketProvider.onMessage (/home/swyngaard/blockchain-listener/node_modules/web3-providers/dist/web3-providers.cjs.js:404:77)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/swyngaard/blockchain-listener/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/swyngaard/blockchain-listener/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/swyngaard/blockchain-listener/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.processFrame (/home/swyngaard/blockchain-listener/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /home/swyngaard/blockchain-listener/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at process._tickCallback (internal/process/next_tick.js:61:11)

Process finished with exit code 1
```

### Versions 
* web3.js: `1.0.0-beta.55`
* nodejs: `v10.16.0`
* ethereum node: `Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9`

**Comment by nivida** [comment]
Thanks for opening this issue! I've updated the ``BatchRequest`` for the next release and will check your case asap.

**Comment by benediamond** [comment]
I'm getting identical errors for _any_ websocket communication which transfers large payloads back and forth (i.e. not just batching); I can try to give reproduction instructions if necessary. The cutoff appears to be around 10 kilobytes.

Interestingly, I'm also getting errors in the same circumstances when using IPC provider, but with a different error message:

```javascript
> Transfer failed: Error: Connection error: Couldn't write on the socket with Socket.write(payload)
(node:36699) UnhandledPromiseRejectionWarning: Error: Connection error: Couldn't write on the socket with Socket.write(payload)
    at /Users/benediamond/anonymous-zether/node_modules/web3-providers/dist/web3-providers.cjs.js:636:23
    at new Promise (<anonymous>)
    at IpcProvider.sendPayload (/Users/benediamond/anonymous-zether/node_modules/web3-providers/dist/web3-providers.cjs.js:619:14)
    at IpcProvider._callee$ (/Users/benediamond/anonymous-zether/node_modules/web3-providers/dist/web3-providers.cjs.js:185:29)
    at tryCatch (/Users/benediamond/anonymous-zether/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/benediamond/anonymous-zether/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/benediamond/anonymous-zether/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/benediamond/anonymous-zether/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/benediamond/anonymous-zether/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/benediamond/anonymous-zether/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
(node:36699) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:36699) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Thanks for your attention on this. I can try to provide more detail if needed.
