### ISSUE TITLE
Error: could not decode, invalid type on field : not a number or string when putting event.get() inside a function.

### ISSUE THREAD

**Issue by tymat** [ethereum/web3.js#296]
Given a wrapper function:

```
var setTruthEventScanner = function() {
  var evt = mySuperContractInstance.SetTruthEvent(null, {fromBlock: 0, toBlock: 'latest'});
  evt.get();
}
```

Gets this when running:

```
Error: could not decode, invalid type on field : not a number or string
    at Object.module.exports.InvalidResponse (/Users/aeufemio/projects/digixglobal/ethereum/go-ethereum/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/Users/aeufemio/projects/digixglobal/ethereum/go-ethereum/node_modules/web3/lib/web3/requestmanager.js:76:22)
    at Method.send (/Users/aeufemio/projects/digixglobal/ethereum/go-ethereum/node_modules/web3/lib/web3/method.js:168:59)
    at Filter.get (/Users/aeufemio/projects/digixglobal/ethereum/go-ethereum/node_modules/web3/lib/web3/filter.js:200:40)
    at setTruthEventScanner (repl:3:5)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
```

Running this from node/geth console works:

```
  var evt = mySuperContractInstance.SetTruthEvent(null, {fromBlock: 0, toBlock: 'latest'});
  evt.get();
```

```
[ { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 6,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0xcc172643967e0aa1e4ce8ccff80a8c2c3cad62560e489b2e755eadb2ae825465',
    transactionIndex: 3,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0x8581374283b226d58dd3355b88475b494e915015',
       t: true } },
  { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 8,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0x97a1aeacf305d124d20e6dfb1fa538d326bbb7f6dc378886e2dea4362842f612',
    transactionIndex: 4,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0x21867a4a33298c0e216ef8c4706f518bdbba48fb',
       t: true } },
  { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 10,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0xd44ae2c53094b5fe321fa5d43c30f596be82e684349af9c0f6e07f371921a046',
    transactionIndex: 5,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0xd53d4d51b9b59bc20d566925c23572736fa71407',
       t: true } },
  { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 0,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0x3b21c4494d53ef3df2ab93ecf3ffbf8864c9887101023b81b807ca02eca28ae3',
    transactionIndex: 0,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0x532555dcc9d327936cbcf4d0a2166bf72741af64',
       t: true } },
  { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 2,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0x0dd92a560836225845099ebd97391a9a5a322da2c23305425ac15ff8f7174da4',
    transactionIndex: 1,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0xfd469317bb25904b3fa08db07e9471f72974f900',
       t: true } },
  { address: '0xe5bc2343f2b7a24c02106dc276926eb0d02ed55d',
    blockNumber: 481,
    logIndex: 4,
    blockHash: '0x1fa517c21e7025069092a766c1ce537f8156de4955f4f70f917853e979ce1d3c',
    transactionHash: '0x410e7f4d57d224fe0cbc4e3d1be656c530a120bf5b079c45d5251ef184a59e80',
    transactionIndex: 2,
    event: 'SetTruthEvent',
    args:
     { newaddress: '0x84b571ae3e1d61d0ec6b3ad81b2022bd6eec44c0',
       t: true } } ]
```

**Comment by debris** [comment]
same as #250. I wil take care of it.
