### ISSUE TITLE
Cannot find module 'Web3' in truffle console 

### ISSUE THREAD

**Issue by sahil839** [ethereum/web3.js#2984]
### Description 
I am using truffle development env. I am using a test directory for sending a transaction using azure blockchain service. 
When I run `var web3 = require('Web3');` I get the error that Web3 module not found even though I have installed web3 version 1.0.0-beta.37.

#### Expected behavior

Running `var web3 = require('Web3');` in truffle console should just initaialize the variable web3.

#### Actual behavior

Running `var web3 = require('Web3');` in truffle console gives error `Cannot find module 'Web3' `

#### Steps to reproduce the behavior

1. Open node console or shell.
2. `mkdir demo`
3. `cd demo`
4. `truffle init`
5. `npm install web3@1.0.0-beta.37`
6. `truffle develop`
7. `var web3 = require('Web3');`

#### Error Logs 
```
Thrown:
{ internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'Web3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at evalmachine.<anonymous>:0:12
    at Script.runInContext (vm.js:133:20)
    at runScript (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:379643:21)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:379658:21)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:380499:18)
    at bound (domain.js:402:14)
    at REPLServer.runBound [as eval] (domain.js:415:12)
    at REPLServer.onLine (repl.js:642:10)
    at REPLServer.emit (events.js:198:13)
    at REPLServer.EventEmitter.emit (domain.js:448:20)
    at REPLServer.Interface._onLine (readline.js:308:10)
    at REPLServer.Interface._line (readline.js:656:8)
    at REPLServer.Interface._ttyWrite (readline.js:937:14)
    at REPLServer.self._ttyWrite (repl.js:715:7)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:198:13)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at emitKeys (internal/readline.js:424:14) code: 'MODULE_NOT_FOUND' }
```

### Versions 
* web3.js: v1.0.0-beta.37
* nodejs: v10.16.0
* solidity: v0.5.0(solc-js)
* truffle: v5.0.28

**Comment by nivida** [comment]
Your require statement isn't correct. ``var web3 = require('Web3');``  should be ``var Web3 = require('web3');`` . Any further issues related to Truffle should get opened in the [Truffle repository](https://github.com/trufflesuite/truffle).
