### ISSUE TITLE
Version 1.2.0 shows different error message when rpc endpoint can't be reached: Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by gpersoon** [ethereum/web3.js#2988]
### Description
When running a mini test program and no RPC endpoint is accessible i get the error message:
```js
Error: Invalid JSON RPC response: ""
```
While both beta 0.55 and alpha 2.0.0 show the message:
```js
Error: Connection refused or URL couldn't be resolved: http://localhost:8545
```
The latter message is a better indicator of the underlying problem.

#### Expected behavior
```js
Error: Connection refused or URL couldn't be resolved: http://localhost:8545
    at XMLHttpRequest.request.onreadystatechange (C:\blockchain_test\web3_2.0\node_modules\web3-providers\dist\web3-providers.cjs.js:776:22)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\blockchain_test\web3_2.0\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\blockchain_test\web3_2.0\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (C:\blockchain_test\web3_2.0\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (C:\blockchain_test\web3_2.0\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) null
```

#### Actual behavior
```js
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\web3-core-helpers\src\errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\web3-providers-http\src\index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (C:\Users\gerar\AppData\Roaming\npm\node_modules\web3\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

#### Steps to reproduce the behavior

test.js contains:
```js
Web3 = require("web3");
web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
web3.eth.getAccounts(console.log);
```
run
```js
node test.js
```

### Versions 
* web3.js: 1.2.0 // 2.0.0-alpha // 1.0.0-beta.55
* nodejs: v10.16.0
* ethereum node: { not running }

**Comment by cgewecke** [comment]
Closing in favor of #3425
