### ISSUE TITLE
Error: Failed to check for transaction receipt

### ISSUE THREAD

**Issue by Aniket-Engg** [ethereum/web3.js#3145]
Related to issue #1534

I am still getting this error while calling function of a contract: 
`Error: Failed to check for transaction receipt`

Function is being used in a loop which calls smart contract function max 5 times and wait to complete each step. Sometimes, It got successful but seldom it throws this error in iteration.

#### Error Logs 
```
 message=Failed to check for transaction receipt:
{}, stack=Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/project/node_modules/web3-utils/src/index.js:56:17)
    at /project/node_modules/web3-core-method/src/index.js:260:23
    at <anonymous>
```

### Versions 
* web3.js: 1.2.1
* nodejs: 8.12.0 & 11.15.0
* browser: In Node.js
* ethereum node: Infura with mnemonic (using ropsten network)

**Comment by ilyakmet** [comment]
Related to issue [#1534](https://github.com/ethereum/web3.js/issues/1534)

The same problem with Rinkeby deploys.

I am still getting this error while deploying a contract:
`Error: Failed to check for transaction receipt`

```js
const deploy = async () => {
  const accounts = await web3.eth.getAccounts();

  console.log('Attempting to deploy from account', accounts[0]);

  const result = await new web3.eth.Contract(JSON.parse(interface))
    .deploy({ data: bytecode})
    .send({ gas: '1000000', from: accounts[0] });

  console.log('Contract deployed to', result.options.address);
};
```

## Error Logs
```
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/Users/ilya/Documents/GitHub/solidity-lottery/node_modules/web3-utils/src/index.js:56:17)
    at /Users/ilya/Documents/GitHub/solidity-lottery/node_modules/web3-core-method/src/index.js:260:23
Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/Users/ilya/Documents/GitHub/solidity-lottery/node_modules/web3-utils/src/index.js:56:17)
    at /Users/ilya/Documents/GitHub/solidity-lottery/node_modules/web3-core-method/src/index.js:260:23
```

## Versions 
* web3.js: 1.2.1
* nodejs: 12.2.0
* browser: In Node.js
* ethereum node: Infura with mnemonic (using rinkeby network)

**Comment by nivida** [comment]
Thanks for opening this issue! @Aniket-Engg 
Is it possible to add the value of the ``data`` property of the returned error to the issue description? 

On the first view is something wrong with the node you are connected and not with web3.js but the missing ``data`` property value will tell us the exact reason for this behaviour.

**Comment by Aniket-Engg** [comment]
Thanks for your response @nivida . I have pasted the complete error object in issue description. I see there is no `data` property.

**Comment by beginnerJq** [comment]
I have same problem, is there any progress?

**Comment by DanielHH** [comment]
I share this problem with you and I am suspecting it's a problem with infura. If you are sending multiple requests in a short time frame, you will get rate limited. To determine if this is the case you can go into this file `node_modules\web3-core-method\src\index.js:261:23` and add a `console.log(err)`.
```javascript
 .catch(function (err) {
                sub.unsubscribe();
                promiseResolved = true;
                console.log(err);
                utils._fireError({message: 'Failed to check for transaction receipt:', data: err}, defer.eventEmitter, defer.reject);
            })
```
If you then get `Error: project ID request rate exceeded` in your terminal, this is it.

**Comment by mwaeckerlin** [comment]
I get this error in a local ganache test environment, so not related to infura, @DanielHH:

```
#### ERROR IN TRANSACTION:  Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/marc/git/digitalgv/node_modules/web3/node_modules/web3-utils/src/index.js:57:17)
    at /home/marc/git/digitalgv/node_modules/web3/node_modules/web3-core-method/src/index.js:275:27
    at <anonymous>
```

web3: tested in 1.2.6, then updated to 1.2.8, both fail.

Situation: I start 200 transactions at once, then wait for them to terminate. Some succeed and some fail. In the ganache output, I don't see any problem.

E.g.:
```
...
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt

  Transaction: 0x7529d161d25102bb244e8b303f9897d9ae5529e28ecccd97c7633fefe84e510c
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xdfe9d268f69d6964feeee1127989d95b37d6fb73b9399f81db3e447c9a017b27
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x1f10334fa95fa327411cbe2df4d632231886ad3c44443b1e1b488e1229e2619c
  Gas usage: 98909
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xb53eb61d95a61f4600a37781bc0cc068f2439273ac675d7705b123a74385dc0a
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xd306a7400cd70ac4f2d0b7f5f29e3c2f032200dfb86bd2852260a8aaa4fad637
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x502c481a28fa5191589a5080e23c5920ec039449da89bdc574fd8f5658016d32
  Gas usage: 98909
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xae3edb0963aa652c0e4771a717f35733550fb03d93a8dc644f29d41a2c5095a0
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x3c614ed0f47e16b880a47bde71d4d9f6a4c8b4eb74bb804d61048629a4cd82f2
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x0e3dee452248a12a83215f9a03b931849a014aee40112c252f1d3548365b6339
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x33115dceb501462c0fcfa2212227a0097bb5afcc0e4b5e20e99fad946ce13adb
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x9ec0309879c2b88b7b3eb45c833b13d2d5ae091160f4e27de17cb7f3b6554bd7
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x33fcb5f489006291726b5e2136cd81762e840e758d7dd56f2ffbe6a5a2a5bdf7
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x9643dd6def768c7107296678c46fdb2f132b8357d4617fd21137e5bf11e7b447
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x2ca7bdd172cdcac2fad0104b87e2fa77ee34f8d90b56088c22db8e72c395eb25
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x64d917fe420afb37d189e340cffc07fa6643b1ad73f722a51f995a7963c77d52
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x00375b22625fdb49c7b2a9f01a6b2369dee38122334652f775b9c64651d62e6a
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x3f33f48ab6fd81aeef3e4fd8f4479cebc2af5153a45da17eff71544206077716
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xa628ab0f81ff06549c2635d915db5feff81b6b2dec0468a9d9d864e23e6a4e04
  Gas usage: 98909
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x67636540ecb8b525724f352905f34e16001f238b208328f16b2c4df703d39bae
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x0601e790355b38ab678a0a3dacbf4aa1a478500d68f532eb0eb2254dfc974c95
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x5de8d61bc609e48a3237f68fc5ac16237a9c3cd0ce3e16732073e7e785d13fe9
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x56b5271ddec1aa9d28ea9a7c57d0e815f2dda8359b09fef2951a5917b28b0b32
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xe7961b1f6e2df05bc6ec74817052e7b8b055a0ec5a72094341ae62a70de790dc
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x804c86cbd2a45cde213b9855fb98e91a7b3d04ded3687ca5afe408b395830337
  Gas usage: 98933
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x082f2996835a24874badaeb5e756f17c653cd5ad44e473c7869c445b668c9ee3
  Gas usage: 98921
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0xdc18e85ee910c8d09ff992631e64013f01a312185a2e5710f8ebc4c0669e491d
  Gas usage: 98897
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)


  Transaction: 0x3719f90ebaaea534a3cfc0613f17d3e3573c4021e4f57ac2809b81c9ebe6aff9
  Gas usage: 98897
  Block Number: 68478
  Block Time: Sat May 30 2020 13:00:53 GMT+0200 (CEST)

eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
eth_getTransactionReceipt
...
```

**Comment by mwaeckerlin** [comment]
I have only 7 of these errors in 201 transactions, all errors just directly following each other in the log file. So 194 transactions succeed and 7 fail with this error. On another run, I had 4 failures instead of 7. It's a bit random.

And before I had test runs that completely succeeded. Currently, i can't get it pass successfully, it currently always fails — on the same tests it used to pass.

What is the solution? Migrate to ethers.js?

[EDIT: I migrated to ethers.js, that solved the problem for me. My suggestion for a solution in web3.js: Just retry a number of times!]

**Comment by cgewecke** [comment]
Closing in favor of #3255

**Comment by jiaruifeng07** [comment]
I enconter this problem in my iphone app, what should I do？
Besh wishes！

**Comment by sfncook** [comment]
Adding my experience with this error for posterity.  I received this error while using Infura as my remote provider and the error was specifically:
`Error:  Failed to check for transaction receipt:
{
  "data": {
    "rate": {
      "allowed_rps": 1,
      "backoff_seconds": 30,
      "current_rps": 1.0333333333333334
    },
    "see": "https://infura.io/dashboard"
  }
}`

Turns out the setting on my Infura project named "PER SECOND REQUESTS RATE-LIMITING" was set to '1'.  By increasing this value I was able to resolve the issue.

**Comment by GrinOleksandr** [comment]
> Adding my experience with this error for posterity. I received this error while using Infura as my remote provider and the error was specifically: `Error: Failed to check for transaction receipt: { "data": { "rate": { "allowed_rps": 1, "backoff_seconds": 30, "current_rps": 1.0333333333333334 }, "see": "https://infura.io/dashboard" } }`
> 
> Turns out the setting on my Infura project named "PER SECOND REQUESTS RATE-LIMITING" was set to '1'. By increasing this value I was able to resolve the issue.

thanks!!! increasing the rate helped!
