### ISSUE TITLE
Add more error details of net or other

### ISSUE THREAD

**Issue by TamirTian** [ethereum/web3.js#3201]
I think the logic can't hide actual error.

 `Error: Invalid JSON RPC response: “"` is not nice to understand,  [this code of web3-providers-http](https://github.com/ethereum/web3.js/blob/22df832303e349f8ae02f0392e56abe10e1dfaac/packages/web3-providers-http/src/index.js#L96) didn't handle error when other statuses of `xhr2-cookies`

Also [this code of xhr2-cookies](https://github.com/souldreamer/xhr2-cookies/blob/master/xml-http-request.ts#L374) couldn't return the error

#### Expected behavior
Should be i get the real error
```js
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } 'request'
```
#### Actual behavior
I always get the unknown error(can't understand)
```js
Error: Invalid JSON RPC response: ""
```

#### Steps to reproduce the behavior
1. Mock limit about HTTP, i set the 1024 sort limit of Linux Ethereum Node
2. Mock many requests, it will be easy to get the error if you loop call getPastLog from multi clients

##### web3
```js
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/web3-core-helpers/src/errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/web3-providers-http/src/index.js:93:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/tamir/Projects/spider/data/spiderdata-asset-aggregation/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
##### xml-http-request.js
I got this error when i added a printing logic to help me see the details
```js
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' } 'request'
```
```js
XMLHttpRequest.prototype._onHttpRequestError = function (request, error) {
        if (this._request !== request) {
            return;
        }
        // A new line
        console.log(error, 'request')
        this._setError();
        request.abort();
        this._setReadyState(XMLHttpRequest.DONE);
        this._dispatchProgress('error');
        this._dispatchProgress('loadend');
    };
```
#### Versions
* Node: 10.16.0
* Web3: 1.2.2
* Device: Ubuntu16 LTS
* Ethereum node: v1.9.3
* Linux soft limit(Ethereum node): 1024(now it's changed)

**Comment by nivida** [comment]
Thanks for opening this issue! Could you please use the issue template we provide and add all the required information?

**Comment by TamirTian** [comment]
@nivida I added the details, do you think I should add what else.

**Comment by cgewecke** [comment]
Closing in favor of #3425
