### ISSUE TITLE
Undesired behaviour and unexpected error when `toBlock` is passed to `myContract.events.<eventName>` or `myContract.events.allEvents`

### ISSUE THREAD

**Issue by nachomazzara** [ethereum/web3.js#3207]
### Intro

Right now if you want to use `myContract.events.<eventName>` or `myContract.events.allEvents` with the option `toBlock`, **which is not in the documentation**, different from `latest`. The call ends up in an undesired behaviour.

If you set `fromBlock` different from `latest`, a [`eth_getLogs` call will be done](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-subscriptions/src/subscription.js#L221) to get the past events from `fromBlock` to `latest` without using `toBlock` -> Almost ok!. But later, `fromBlock` is [removed from the options](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-core-subscriptions/src/subscription.js#L246) and a subscription is made with `{ fromBlock: undefined, toBlock: 100}`.  Based on the [subscribe implementation](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L200) of _go-ethereum_, if `fromBlock === null` (bacically, if it is not set), will set `fromBLock` as `later`.

This will finally check `fromBlock: 'latest'` and `toBlock: 100` returning, obviously, [invalid from and to block combination: from > to](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L231)

#### Expected behavior

Throw an error saying that `toBlock` is not a valid option.

#### Actual behavior

Error with `invalid from and to block combination: from > to` which is not an error from web3. But a  [go-ethereum](https://github.com/ethereum/go-ethereum/blob/d42ce0f2c1b52e26cce475e411d97165fb975577/eth/filters/filter_system.go#L231) one

#### Steps to reproduce the behavior

1. Call `myContract.events.MyEvent({ fromBlock: 0,  toBlock: 'latest' })` or `myContract.events.allEvents({ fromBlock: 0,  toBlock: '100' })`

#### Versions
Web3.js 1.X

Thanks @fmiras for the heads up.

**Comment by wbt** [comment]
I am also seeing [this error](https://github.com/ethereum/web3.js/issues/1930) when using `myContract.events.<eventName>` with `toBlock` set to anything other than `'latest'`, even if the value is greater than `fromBlock`.
```
Got error back from event:  Error: Returned error: invalid from and to block combination: from > to
    at Object.ErrorResponse (my:\project\node_modules\@truffle\interface-adapter\node_modules\web3-core-helpers\src\errors.js:29:16)
    at Object.callback (my:\project\node_modules\@truffle\interface-adapter\node_modules\web3-core-requestmanager\src\index.js:140:36)
    at my:\project\node_modules\web3-providers-ws\src\index.js:133:41
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (my:\project\node_modules\web3-providers-ws\src\index.js:118:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (my:\project\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onMessage (my:\project\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (my:\project\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:159:13)
    at WebSocketConnection.processFrame (my:\project\node_modules\@web3-js\websocket\lib\WebSocketConnection.js:554:26)
    at my:\project\node_modules\@web3-js\websocket\lib\WebSocketConnection.js:323:40
    at process._tickCallback (internal/pro5cess/next_tick.js:150:11)
```
