### ISSUE TITLE
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!

### ISSUE THREAD

**Issue by ketan18710** [ethereum/web3.js#3395]
This my delpoy.js file:
```javascript
const HDWalletProvider = require('truffle-hdwallet-provider');
const Web3 = require('web3');
const {abi , bytecode} = require('./compile');
const provider = new HDWalletProvider(
    'december blossom school two brief lunar siren truth purse violin car submit',
    'https://rinkeby.infura.io/v3/737d5964ada94e2a8d812f1414c89c4e'
)
const web3 = new Web3(provider)
const deploy = async() =>{
    const accounts = await web3.eth.getAccounts();
    console.log('attempting to deploy from account',accounts[0])
    const result = await new web3.eth.Contract(abi)
    .deploy({data: bytecode , arguments: ['Hii there']})
    .send({gas: 1500000, from: accounts[0]})
    .on('error', function(error){ console.log("err :" + error) })
    .on('transactionHash', function(transactionHash){ console.log("th : "+ transactionHash) })
    .on('receipt', function(receipt){
       console.log(receipt.contractAddress) // contains the new contract address
    })
    console.log('contract deployed to', result.options.address);
}
deploy()
```
Output:
```
 node deploy.js
attempting to deploy from account 0x010Ff624891610c8538824AB6F5AF4abfD1c3bfd
th : 0x4e43c10ffcd52f537e148089124f10429c14d6071133d9aa49374cd21c45b874
err :Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be
mined!
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be
mined!
C:\Users\Ketan Verma\Desktop\blockchain\solidity-etherium\index\node_modules\solc\soljson.js:1
(function (exports, require, module, __filename, __dirname) { "use strict";var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_HAS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_HAS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_NODE=ENVIRONMENT_HAS_NODE&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locat

RuntimeError: abort(Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\Ketan Verma\Desktop\blockchain\solidity-etherium\index\node_modules\solc\soljson.js:1:14506)
    at process.emit (events.js:189:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

**Comment by cgewecke** [comment]
@ketan18710 Yes, I see the transaction was broadcast on [etherscan here][1]. Not sure what happened, maybe Rinkeby is having some network difficulties. 

Closing because there's no question here and it's not clear Web3 is directly at issue. 

Please feel free to ping after reformatting your opening comment using the issue template and I will re-open if it seems like there's a bug Web3 can address.

[1]: https://rinkeby.etherscan.io/tx/0x4e43c10ffcd52f537e148089124f10429c14d6071133d9aa49374cd21c45b874
