### ISSUE TITLE
ReferenceError: unescape is not defined

### ISSUE THREAD

**Issue by sleepaloner** [ethereum/web3.js#3430]
ReferenceError: unescape is not defined
	at web3.js:8360:42(10)
	at web3.js:8398:35(11)
	at web3.js:8563:30(8)
	at web3.js:8589:54(8)
	at web3.js:1839:16(46)
	at web3.js:4070:16(6)
	at web3.js:4059:41(48)
	at web3.js:4098:33(42)
	at web3.js:4227:60(38)
	at <eval>:1:1(2)

 in geth smartcontract

**Comment by cgewecke** [comment]
@sleepaloner Could you provide?

+ all the relevant version information requested in the issue template
+ a set of simple steps to reproduce this error.

Closing for now - please ping if you're able to reformat this issue so it can be investigated.
