### ISSUE TITLE
Ethereum token subscribe exception

### ISSUE THREAD

**Issue by developer2belfrics** [ethereum/web3.js#3514]
I am subscribing to the token with parameter start block and end block (200 block subscribing each time). I am creating a cron job for each token at the runtime. I have 10 tokens in my application. I built this approach to subscribe each token separately but when more than one token runs at the same time. I am getting the below exception,

2020-05-12 18:00:21.369 ERROR 16194 --- [pool-3-thread-2] org.web3j.protocol.core.filters.Filter : Error sending request

org.web3j.protocol.core.filters.FilterException: Invalid request: filter not found
at org.web3j.protocol.core.filters.Filter.throwException(Filter.java:152) ~[core-3.4.0.jar:na]
at org.web3j.protocol.core.filters.Filter.pollFilter(Filter.java:113) ~[core-3.4.0.jar:na]
at org.web3j.protocol.core.filters.Filter.lambda$run$0(Filter.java:75) ~[core-3.4.0.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_231]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_231]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_231]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_231]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]

**Comment by cgewecke** [comment]
@developer2belfrics 

This repository is for `web3.js` (javascript). 

From your stacktrace, it looks like you're using [web3.j, the java lang repo][1]. Do you want to close here and re-open there?

[1]: https://github.com/web3j/web3j

**Comment by cgewecke** [comment]
Closing: duplicate issue in relevant repo [here][1]

[1]: https://github.com/web3j/web3j/issues/1209
