### ISSUE TITLE
Maker token and Web3 ERC20 name, symbol error

### ISSUE THREAD

**Issue by Wyctus** [ethereum/web3.js#3791]
I was getting into a really strange issue today. I was querying a some basic data about ERC20 tokens when I got an error thrown by `bignumber`. It was complaining about some overflow and gave a really strange number I've never intended to use.

After some debugging I found out, that Maker token has its name and symbol defined as `bytes32` instead of `string`. Also found out, that the overflown number `bignumber` complained about was simply the tokens `bytes32` name converted to decimals. Later also realized if I convert these `bytes32`s to strings then I got the real name and symbol.

You can check it this behaviour here: https://etherscan.io/address/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2#readContract

Is this a problem with Maker token or with Web3? I thought name and symbol should be `string`.

#### Expected behavior
Being able to request the token's name and symbol.

#### Actual behavior
Throws a `bignumber` overflow error.

#### Steps to reproduce the behavior
```javascript
require("dotenv").config();
const erc20 = require("erc-20-abi");
const Web3 = require("web3");

const provider = new Web3.providers.WebsocketProvider(process.env.INFURA_WS_URL);
const web3 = new Web3(provider);

// According to these, the name and the symbol must be strings
console.log(erc20[0]);
console.log(erc20[1]);

const token_address = "0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2"; // Maker token address

const token_contract = new web3.eth.Contract(erc20, token_address);

async function main() {
    const token_name = await token_contract.methods.name().call();
    const token_symbol = await token_contract.methods.symbol().call();
    const token_decimals = await token_contract.methods.decimals().call();
    
    console.log(token_name);
    console.log(token_symbol);
    console.log(token_decimals);
}

main().catch(err => {
    console.error(err);
});
```
This gives the error below:

#### Logs

```
Error: overflow (fault="overflow", operation="toNumber", value="35000214728014336407470934256024915466671168103574785725052718905953538277376", code=NUMERIC_FAULT, version=bignumber/5.0.8)
    at Logger.makeError (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at throwFault (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/bignumber/lib/bignumber.js:278:19)
    at BigNumber.toNumber (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/bignumber/lib/bignumber.js:146:13)
    at /home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/abi/lib/coders/array.js:75:60
    at Array.forEach (<anonymous>)
    at Object.unpack (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/abi/lib/coders/array.js:71:12)
    at TupleCoder.decode (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/abi/lib/coders/tuple.js:39:49)
    at AbiCoder.decode (/home/zoli/dev/mine/crypto/defi_arb/node_modules/@ethersproject/abi/lib/abi-coder.js:93:22)
    at ABICoder.decodeParameters (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-eth-abi/lib/index.js:292:30)
    at Contract._decodeMethodReturn (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-eth-contract/lib/index.js:470:22)
    at Method.outputFormatter (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-eth-contract/lib/index.js:760:42)
    at Method.formatOutput (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-core-requestmanager/lib/index.js:293:9)
    at /home/zoli/dev/mine/crypto/defi_arb/node_modules/web3-providers-ws/lib/index.js:114:45 {
  reason: 'overflow',
  code: 'NUMERIC_FAULT',
  fault: 'overflow',
  operation: 'toNumber',
  value: '35000214728014336407470934256024915466671168103574785725052718905953538277376'
}
```

The contained number in the error is the name of the token, so the followings mean the same:
```
0x4d616b6572000000000000000000000000000000000000000000000000000000 
35000214728014336407470934256024915466671168103574785725052718905953538277376 
Maker
```

#### Environment
node v15.0.1
npm v6.14.8
OS: Manjaro

Seems independent of the environment.

**Comment by Wyctus** [comment]
I found some other similar token:
`0x9469D013805bFfB7D3DEBe5E7839237e535ec483`

**Comment by GregTheGreek** [comment]
Sorry i just saw this, since the token doesn't follow the erc20 standard, you are using the wrong ABI thus its not an issue with web3.js

**Comment by Wyctus** [comment]
Thanks, you are right, later I realized  that it isn't ERC20.
