### ISSUE TITLE
Web3 v2.0.0 toChecksumAddress's chainId is not work.

### ISSUE THREAD

**Issue by AmazingBeerBelly** [ethereum/web3.js#3798]
Code:
```
const Web3 = require('web3');
const web3 = new Web3('https://public-node.rsk.co');
const chainId = 30;
const address = '0xE62278ac258BDA2aE6E8eCA32D01d4Cb3b631257'.toLocaleLowerCase();
const web3ChecksumAddress = web3.utils.toChecksumAddress(address, chainId);

web3.eth.estimateGas({
    from: web3ChecksumAddress,
    to: web3ChecksumAddress,
    value: '0x0',
  }).then(res => {
    console.log('web3 res: ', res);
  }).catch(error => {
    console.log('web3 error: ', error);
  })
```

Using web3 v1.3.0, the code is working.

But using web3 v2.0.0 the code will get an error.
```
web3 error:  Error: Provided address "0xE62278ac258BDA2aE6E8eCA32D01d4Cb3b631257" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
    at inputAddressFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:263:9)
    at txInputFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:40:19)
    at Object.inputCallFormatter (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-helpers/dist/web3-core-helpers.cjs.js:63:14)
    at EstimateGasMethod.beforeExecution (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1492:44)
    at EstimateGasMethod._callee$ (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/web3-core-method/dist/web3-core-method.cjs.js:88:22)
    at tryCatch (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/shizhongwei/app/project/contract/rnsDemo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by GregTheGreek** [comment]
This is being closed since 2.x is deprecated.
