### ISSUE TITLE
number overflow

### ISSUE THREAD

**Issue by guotie** [ethereum/web3.js#3829]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Logs

```
"stack":"Error: overflow (fault=\"overflow\", operation=\"toNumber\", value=\"29552863752176386703968378516918486365868501552295265006012618974855157514240\", code=NUMERIC_FAULT, version=bignumber/5.0.12)\n    at Logger.makeError 
(e:\\guotie\\project\\clover\\expoler\\node_modules\\@ethersproject\\logger\\lib\\index.js:179:21)\n
    at Logger.throwError (e:\\guotie\\project\\clover\\expoler\\node_modules\\@ethersproject\\logger\\lib\\index.js:188:20)\n
    at throwFault (e:\\guotie\\project\\clover\\expoler\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:295:19)\n
    at BigNumber.toNumber (e:\\guotie\\project\\clover\\expoler\\node_modules\\@ethersproject\\bignumber\\lib\\bignumber.js:152:13)\n
    at e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:89:60\n
    at Array.forEach (<anonymous>)\n
    at Object.unpack (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\node_modules\\@ethersproject\\abi\\lib\\coders\\array.js:85:12)\n
    at TupleCoder.decode (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\node_modules\\@ethersproject\\abi\\lib\\coders\\tuple.js:39:49)\n
    at AbiCoder.decode (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\node_modules\\@ethersproject\\abi\\lib\\abi-coder.js:93:22)\n
    at ABICoder.decodeParametersWith (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\lib\\index.js:304:30)\n
    at ABICoder.decodeParameters (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-abi\\lib\\index.js:285:17)\n
    at Contract._decodeMethodReturn (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-contract\\lib\\index.js:470:22)\n
    at Method.outputFormatter (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-eth-contract\\lib\\index.js:760:42)\n
    at Method.formatOutput (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-core-method\\lib\\index.js:147:54)\n
    at sendTxCallback (e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-core-method\\lib\\index.js:523:33)\n
    at e:\\guotie\\project\\clover\\expoler\\node_modules\\web3-core-requestmanager\\lib\\index.js:296:9",
	"error":{"reason":"overflow","code":"NUMERIC_FAULT","fault":"overflow","operation":"toNumber","value":"29552863752176386703968378516918486365868501552295265006012618974855157514240"}}
```

#### Environment

1.3.1

**Comment by Spacesai1or** [comment]
Hi there, could you provide a code snippet or test repository for this?
