### ISSUE TITLE
Subscribe logs error: Cannot read property 'fromBlock' of undefined

### ISSUE THREAD

**Issue by ngugcx** [ethereum/web3.js#3882]
The following code failed to run.
```
var Web3 = require('web3')
var web3 = new Web3(Web3.givenProvider || 'wss://mainnet.infura.io/ws/v3/xxxxxxxxxxxxxxxxxx');

var subscription = web3.eth.subscribe('logs', function(error, result){
    if (!error)
        console.log(result);
})
.on("data", function(log){
    console.log(log);
});

// unsubscribes the subscription
subscription.unsubscribe(function(error, success){
    if(success)
        console.log('Successfully unsubscribed!');
});
```

#### Expected behavior
No error and logs are retrieved.

#### Actual behavior
Failed with:
```
/root/monitor/node_modules/web3-core-helpers/lib/formatters.js:292
    if (options.fromBlock || options.fromBlock === 0)
                ^

TypeError: Cannot read property 'fromBlock' of undefined
    at inputLogFormatter (/root/monitor/node_modules/web3-core-helpers/lib/formatters.js:292:17)
    at /root/monitor/node_modules/web3-core-subscriptions/lib/subscription.js:87:28
    at Array.map (<anonymous>)
    at Subscription._formatInput (/root/monitor/node_modules/web3-core-subscriptions/lib/subscription.js:86:53)
    at Subscription._toPayload (/root/monitor/node_modules/web3-core-subscriptions/lib/subscription.js:120:31)
    at Subscription.subscribe (/root/monitor/node_modules/web3-core-subscriptions/lib/subscription.js:158:24)
    at Eth.subscribe (/root/monitor/node_modules/web3-core-subscriptions/lib/index.js:55:39)
    at Object.<anonymous> (/root/monitor/main1.js:4:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

#### Steps to reproduce the behavior
Replace xxx with infura project id.
Then run the above code using node.

#### Environment

npm: 6.14.10
node: v14.15.4
web3js: 1.3.3

**Comment by GregTheGreek** [comment]
Thank you for reporting, we're looking into this. For the time being, applying the options with a startblock does solve the issue:
```
var subscription = web3.eth.subscribe('logs', 
    {fromBlock: `latest` }, // Or a specific block number 
    function(error, result){ ... }
```
