### ISSUE TITLE
Random bug Error: Invalid JSON RPC response: "Error: socket hang up

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#390]
I try use web3+meteor

My code at meteor side:

``` js
GetNumberInstance.SetTimeperiod({},{fromBlock: 0, toBlock: 'latest'}).watch(function(e, log) {
    if(!e) {
    console.log("Timeperiod: " + log.args.value + " blockNumber: " + log.blockNumber + " transactionHash: " + log.transactionHash); 
    } else {
        console.log("GetNumberInstance.SetTimeperiod call with error: " + e);
    }
});

This code is absolutely unpredictable ways sometimes run without error
I20160217-15:03:04.258(0)? Timeperiod: 120 blockNumber: 415092 transactionHash: 0x29f1e4d3610d5cead6936c9870aa26060bfeec1d8fd0a6a924fd4538be716665
I20160217-15:03:04.305(0)? Timeperiod: 240 blockNumber: 415146 transactionHash: 0xeb09e07e9329d70e6c20ee893be40c5a527aa764a84e11a04cf7a9f826c14f25

, sometimes with errors:

I20160217-15:23:18.861(0)? GetNumberInstance.SetTimeperiod call with error: Error: Invalid JSON RPC response: "Error: socket hang up\n    at createHangUpError (http.js:1473:15)\n    at Socket.socketOnEnd [as onend] (http.js:1569:23)\n    at Socket.g (events.js:180:16)\n    at Socket.emit (events.js:117:20)\n    at _stream_readable.js:944:16\n    at process._tickCallback (node.js:448:13)"
```

Geth/v1.3.3/linux/go1.5.1
Running at localhost:8545
Firewall off.

How to catch the source of the error?

**Comment by frozeman** [comment]
I never saw this error. Its seems like a meteor (?) request error which sneaked in the HTTP response.
We are not creating a socket here yet, so i have  no idea where this comes from.

**Comment by frozeman** [comment]
Please try again with the web3.js 1.0.0, and reopen if its still an issue.
