### ISSUE TITLE
web3.eth.getBlock() throw Error: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by kevin-leptons** [ethereum/web3.js#3912]
#### Expected behavior

Call function `web3.eth.getBlock(number, true)` without error.

#### Actual behavior

Call function `web3.eth.getBlock(number, true)` throw error `Error: Number can only safely store up to 53 bits`.

#### Steps to reproduce the behavior

```js
let provider = new Web3.providers.WebsocketProvider('ws://somewhere.com')
let web3 = new Web3(provider)
let block = await web3.eth.getBlock(595091, true)
```
#### Logs

```bash
Error: Number can only safely store up to 53 bits
    at assert (/home/kevin/package/bsc-txs-crawler/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/kevin/package/bsc-txs-crawler/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/home/kevin/package/bsc-txs-crawler/node_modules/web3-utils/lib/utils.js:208:24)
    at outputTransactionFormatter (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:205:20)
    at /home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:269:24
    at Array.forEach (<anonymous>)
    at Method.outputBlockFormatter [as outputFormatter] (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-helpers/lib/formatters.js:267:28)
    at Method.formatOutput (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/kevin/package/bsc-txs-crawler/node_modules/web3-core-requestmanager/lib/index.js:308:9)
    at /home/kevin/package/bsc-txs-crawler/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/kevin/package/bsc-txs-crawler/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/kevin/package/bsc-txs-crawler/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/kevin/package/bsc-txs-crawler/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/kevin/package/bsc-txs-crawler/node_modules/websocket/lib/W3CWebSocket.js:205:19)
```

#### Environment

* Ubuntu 18.04.5 LTS
* Node.js v14
* web3js v1.3.4, also tried with versions v1.3.1 and v1.3.2.

**Comment by razzbee** [comment]
I am having the same issue using web3 with Binance Smart Chain, I have tried extending with quorum-js but still error doesnt seem to go

**Comment by fernandezpaco** [comment]
Same error here

**Comment by ferjep** [comment]
Is there any workaround to this error in `1.x`?

**Comment by dnavamosler** [comment]
same error here

**Comment by Mehranh** [comment]
Same error, any thoughts?

**Comment by Mehranh** [comment]
Could you please telll us how we should fix this error ?

**Comment by ra-sun-god** [comment]
I created a new function to do a direct RPC call with axios to get the block, seems it's web3js kinda error..

**Comment by Mehranh** [comment]
could you please share your code? @big-zak

**Comment by imharvol** [comment]
**Option 1**: Update to 3.x where the issue has been fixed (#3976)
Edit: I'm unsure of how stable 3.x is, so be careful with that

---

**Option 2**: Modify your node_modules web3 version:
Look for this line in your `node_modules/web3-core-helpers/lib/formatters.js`
https://github.com/ChainSafe/web3.js/blob/8783f4d64e424456bdc53b34ef1142d0a7cee4d7/packages/web3-core-helpers/src/formatters.js#L244

Replace with 
```js
if (tx.gas) tx.gas = outputBigNumberFormatter(tx.gas);
```
---

Note that either of the options will be breaking changes: `gas` property of a transaction will be a BN instance instead of a JS Number

@Mehranh

**Comment by Mehranh** [comment]
@imharvol  how we can install the 3.x version?

**Comment by imharvol** [comment]
> @imharvol how we can install the 3.x version?

You can use:
- `npm i web3@3.0.0-rc.5` for the npm version
- `npm i https://github.com/ChainSafe/web3.js.git#3.x` for the github version

Again: I'm unsure of how stable it is (I asked here https://discord.com/channels/593655374469660673/719602820801888337/928225379498459176)

**Comment by Mehranh** [comment]
@imharvol  Thanks I will test it,

also I found another solutuon :

`sed -i "s|assert(false, 'Number can only safely store up to 53 bits')|ret = Number.MAX_SAFE_INTEGER|g" ./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js`

for now, I use this and it works for me, but it's not  a good solution

**Comment by lucaspiressimao** [comment]
check this, same here https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613

**Comment by legaciespanda** [comment]
**Ultimate Solution**

Simple install web3 latest version which is version 4

`npm install web3@v4.0.1-alpha.1`

That solved my problem

**Comment by james4171** [comment]
Here's an example of doing the same request with a json-rpc call if anyone needs it, it's what I ended up using

```
const blockNumber = 23591590;
			
const response = await fetch("https://bsc-dataseed.binance.org", {    
  method: "POST",
  headers: { "Content-type": "application/json" },
  body: JSON.stringify({
    id: "1",
    jsonrpc: "2.0",
    method: "eth_getBlockByNumber",
    params: [
      "0x" + blockNumber.toString(16),
      true
    ]
  })
});

const data = await response.json();

console.log(data.result);
```

the full json-rpc api is here
https://ethereum.org/en/developers/docs/apis/json-rpc
