### ISSUE TITLE
Error: invalid BigNumber value - when passing bn.js values inside structs or arrays

### ISSUE THREAD

**Issue by DanielZlotin** [ethereum/web3.js#3920]
Calling contract functions expecting numeric arguments and passing BN values (from bn.js) works as expected in all cases, except when inside arrays or struct fields.

#### Expected behavior

Should work normally.

#### Actual behavior

fails with error:
```
Error: invalid BigNumber value (argument="value", value="3039", code=INVALID_ARGUMENT, version=bignumber/5.0.14)
    at Logger.makeError (/dev/temp/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/dev/temp/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/dev/temp/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at Function.BigNumber.from (/dev/temp/node_modules/@ethersproject/bignumber/lib/bignumber.js:231:23)
    at NumberCoder.encode (/dev/temp/node_modules/@ethersproject/abi/lib/coders/number.js:30:39)
    at /dev/temp/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at pack (/dev/temp/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at ArrayCoder.encode (/dev/temp/node_modules/@ethersproject/abi/lib/coders/array.js:195:16)
    at /dev/temp/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/dev/temp/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/dev/temp/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/dev/temp/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/dev/temp/node_modules/web3-eth-abi/lib/index.js:121:27)
```

#### Steps to reproduce the behavior

I narrowed down the problem to `ethers`' `abi-coder`, [this code snippet reproduces the issue](https://gist.github.com/DanielZlotin/8cc7fa1c1073feb3d37e68cbcf03dc29)

#### Environment
web3: 1.3.4
node: 12.19.1

**Comment by jjhesk** [comment]
@DanielZlotin here I want to follow up this issue because I am facing the same thing now. Please also refer to this https://github.com/MikeMcl/bignumber.js/issues/305
