### ISSUE TITLE
BSC - certain tx values break web3

### ISSUE THREAD

**Issue by eyooooo** [ethereum/web3.js#3936]
#### Expected behavior

this tx: https://bscscan.com/vmtrace?txhash=0xea6d2f025d6c2135b93d2c74a2a992c2ed80aac780298c1288b1addc2b6eb4d2&type=gethtrace2

i expect no errors when calling web3.eth.getTransaction(txhash)

#### Actual behavior

```
> web3.eth.getTransaction('0xea6d2f025d6c2135b93d2c74a2a992c2ed80aac780298c1288b1addc2b6eb4d2')
Promise { <pending> }
> (node:1992) UnhandledPromiseRejectionWarning: Error: Number can only safely store up to 53 bits
    at assert (/home/user/doodoocrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:7:21)
    at BN.toNumber (/home/user/doodoocrap/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:508:7)
    at Object.hexToNumber (/home/user/doodoocrap/node_modules/web3-utils/lib/utils.js:209:24)
    at Method.outputTransactionFormatter [as outputFormatter] (/home/user/doodoocrap/node_modules/web3-core-helpers/lib/formatters.js:204:20)
    at Method.formatOutput (/home/user/doodoocrap/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/user/doodoocrap/node_modules/web3-core-method/lib/index.js:523:33)
    at Object.callback (/home/user/doodoocrap/node_modules/web3-core-requestmanager/lib/index.js:308:9)
    at /home/user/doodoocrap/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/home/user/doodoocrap/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/user/doodoocrap/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/user/doodoocrap/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/user/doodoocrap/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.EventEmitter.emit (domain.js:529:15)
    at WebSocketConnection.processFrame (/home/user/doodoocrap/node_modules/websocket/lib/WebSocketConnection.js:554:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce the behavior

try to run the getTransaction() listed above

#### Logs

the number-to-bn lib has this func

```
  BN.prototype.toNumber = function toNumber () {
    //console.log(this)
    var ret = this.words[0];
    if (this.length === 2) {
      ret += this.words[1] * 0x4000000;
    } else if (this.length === 3 && this.words[2] === 0x01) {
      // NOTE: at this stage it is known that the top bit is set
      ret += 0x10000000000000 + (this.words[1] * 0x4000000);
    } else if (this.length > 2) {
      assert(false, 'Number can only safely store up to 53 bits');
    }
    return (this.negative !== 0) ? -ret : ret;
  };
```

which is called in some utils.js from web3

```
var hexToNumber = function (value) {
    //console.log(toBN(value).toNumber())
    if (!value) {
        return value;
    }
    if (_.isString(value) && !isHexStrict(value)) {
        throw new Error('Given value "' + value + '" is not a valid hex string.');
    }
    return toBN(value).toNumber();
};
```

that tx value returns a len of 3

```
> numberToBN(0x1db4679213a080)
BN {
  negative: 0,
  words: [ 34840704, 57481700, 1, <1 empty item> ],
  length: 3,
  red: null
}
```

so that error gets throw and web3 ignores that tx

#### Environment

ubuntu 18
node 14
latest web3

**Comment by GregTheGreek** [comment]
@spacesailor24 / @frankiebee I think this might be because the gas limit is set to [9223372036854775807](https://bscscan.com/tx/0xea6d2f025d6c2135b93d2c74a2a992c2ed80aac780298c1288b1addc2b6eb4d2). Which obviously exceeds the the max safe number in javascript...

Proof:
```
9223372036854775807 > Number.MAX_SAFE_INTEGER
> true
```

**Comment by eyooooo** [comment]
@GregTheGreek i believe you are correct. I was just reading issue 3745 which brings up the gas thing.

**Comment by koraykoska** [comment]
I'll take a look

**Comment by alstjd0921** [comment]
> I'll take a look

@koraykoska Please review this pr #3948

**Comment by alstjd0921** [comment]
@eyooooo  This could be a temporary solution.

```javascript
/* eslint-disable no-param-reassign */
import utils from 'web3-utils';
import { formatters } from 'web3-core-helpers';

const bigGasLimitTransactionFormatter = (tx) => {
  if (tx.blockNumber !== null) {
    tx.blockNumber = utils.hexToNumber(tx.blockNumber);
  }
  if (tx.transactionIndex !== null) {
    tx.transactionIndex = utils.hexToNumber(tx.transactionIndex);
  }
  tx.nonce = utils.hexToNumber(tx.nonce);
  tx.gas = formatters.outputBigNumberFormatter(tx.gas);
  tx.gasPrice = formatters.outputBigNumberFormatter(tx.gasPrice);
  tx.value = formatters.outputBigNumberFormatter(tx.value);
  if (tx.to && utils.isAddress(tx.to)) { // tx.to could be `0x0` or `null` while contract creation
    tx.to = utils.toChecksumAddress(tx.to);
  } else {
    tx.to = null; // set to `null` if invalid address
  }
  if (tx.from) {
    tx.from = utils.toChecksumAddress(tx.from);
  }
  return tx;
};

export default bigGasLimitTransactionFormatter;
```

declare this formatter anywhere in your project

```javascript
web3.extend({
    methods: [{
        name: 'getBigGasLimitTransaction',
        call: 'eth_getTransactionByHash',
        params: 1,
        inputFormatter: [null],
        outputFormatter: bigGasLimitTransactionFormatter
    }]
});
```

Import the formatter created in the above process and extend web3 modules with it

```javascript
web3.getBigGasLimitTransaction(txHash);
```

then you can get transaction info with no errors by using this custom method

**Comment by norasotanext** [comment]
I have the same problem with this transaction `0x43706033826758d7b22e515b8e17d68da41e29cdf14c8cded0924d1aa9163661`
