### ISSUE TITLE
Tests fail on v1.x

### ISSUE THREAD

**Issue by uluhonolulu** [ethereum/web3.js#3946]
I'm about to submit a PR for the 1.x branch, but the unit tests fail even without my changes (see the output at the bottom).

#### Expected behavior
All tests should pass

#### Actual behavior
The following tests are failing (note that all of them are related to WebSocketProvider):
```
 1) web.providers.givenProvider (ganache)
       "before all" hook:
     Uncaught Error: Callback was already called.
 2) subscription connect/reconnect
       "before each" hook in "subscription connect/reconnect":
     Error: connection not open on send()
3) subscription connect/reconnect
       "before each" hook in "subscription connect/reconnect":
     Error: connection not open on send()
```
#### Steps to reproduce the behavior

1. Clone the repository
2. `npm install`
3. `npm run build`
4. `npm run test:unit`.

#### Logs
```
 1) web.providers.givenProvider (ganache)
       "before all" hook:
     Uncaught Error: Callback was already called.
      at /home/dev/web3.js/node_modules/ganache-cli/build/ganache-core.node.cli.js:25:273
      at f.<anonymous> (node_modules/ganache-cli/build/ganache-core.node.cli.js:25:2225)
      at f.destroy (node_modules/ganache-cli/build/ganache-core.node.cli.js:37:1079391)
      at finish (internal/streams/writable.js:670:14)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  2) subscription connect/reconnect
       "before each" hook in "subscription connect/reconnect":
     Error: connection not open on send()
      at Object.ConnectionError (packages/web3-core-helpers/src/errors.js:21:12683)
      at Object.ConnectionNotOpenError (packages/web3-core-helpers/src/errors.js:21:11604)
      at /home/dev/web3.js/packages/web3-providers-ws/src/index.js:59:739
      at Map.forEach (<anonymous>)
      at WebsocketProvider._onClose (packages/web3-providers-ws/src/index.js:59:640)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (packages/web3-providers-ws/node_modules/yaeti/lib/EventTarget.js:115:12)
      at W3CWebSocket.onConnectFailed (packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:219:14)
      at WebSocketClient.<anonymous> (packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:59:25)
      at ClientRequest.handleRequestError (packages/web3-providers-ws/node_modules/websocket/lib/WebSocketClient.js:227:14)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  3) subscription connect/reconnect
       "before each" hook in "subscription connect/reconnect":
     Error: connection not open on send()
      at Object.ConnectionError (packages/web3-core-helpers/src/errors.js:21:12683)
      at Object.ConnectionNotOpenError (packages/web3-core-helpers/src/errors.js:21:11604)
      at /home/dev/web3.js/packages/web3-providers-ws/src/index.js:59:739
      at Map.forEach (<anonymous>)
      at WebsocketProvider._onClose (packages/web3-providers-ws/src/index.js:59:640)
      at W3CWebSocket._dispatchEvent [as dispatchEvent] (packages/web3-providers-ws/node_modules/yaeti/lib/EventTarget.js:115:12)
      at W3CWebSocket.onConnectFailed (packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:219:14)
      at WebSocketClient.<anonymous> (packages/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:59:25)
      at ClientRequest.handleRequestError (packages/web3-providers-ws/node_modules/websocket/lib/WebSocketClient.js:227:14)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

#### Environment

Ubuntu, Node v.14.15.5.

**Comment by koraykoska** [comment]
@frankiebee I see provider. Are there any changes in the 1.x branch already?
