### ISSUE TITLE
web3 getPastEvents with filter return invalid argument 0: hex has invalid length 96 after decoding; expected 32 for topic

### ISSUE THREAD

**Issue by andresudi** [ethereum/web3.js#3983]
This relates to https://github.com/ChainSafe/web3.js/issues/3680 
This relates to https://github.com/MetaMask/metamask-extension/issues/6394

#### Expected behavior
It should return filtered data

#### Actual behavior
return error 
Error: Returned error: invalid argument 0: hex has invalid length 96 after decoding; expected 32 for topic

#### Steps to reproduce the behavior

1. Here's the relevant part of the ABI for the contract:

```
   [
   {
   	"anonymous": false,
   	"inputs": [
   		{
   			"indexed": true,
   			"internalType": "address",
   			"name": "previousOwner",
   			"type": "address"
   		},
   		{
   			"indexed": true,
   			"internalType": "address",
   			"name": "newOwner",
   			"type": "address"
   		}
   	],
   	"name": "OwnershipTransferred",
   	"type": "event"
   },
   {
   	"anonymous": false,
   	"inputs": [
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "eventType",
   			"type": "string"
   		},
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "userId",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "email",
   			"type": "string"
   		},
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "userAgent",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "ip",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "data",
   			"type": "string"
   		}
   	],
   	"name": "UserLogin",
   	"type": "event"
   },
   {
   	"anonymous": false,
   	"inputs": [
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "eventType",
   			"type": "string"
   		},
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "userId",
   			"type": "string"
   		},
   		{
   			"indexed": true,
   			"internalType": "string",
   			"name": "email",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "username",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "hashedPassword",
   			"type": "string"
   		},
   		{
   			"indexed": false,
   			"internalType": "string",
   			"name": "data",
   			"type": "string"
   		}
   	],
   	"name": "UserRegister",
   	"type": "event"
   },
   {
   	"inputs": [],
   	"name": "owner",
   	"outputs": [
   		{
   			"internalType": "address",
   			"name": "",
   			"type": "address"
   		}
   	],
   	"stateMutability": "view",
   	"type": "function"
   },
   {
   	"inputs": [],
   	"name": "renounceOwnership",
   	"outputs": [],
   	"stateMutability": "nonpayable",
   	"type": "function"
   },
   {
   	"inputs": [
   		{
   			"internalType": "address",
   			"name": "newOwner",
   			"type": "address"
   		}
   	],
   	"name": "transferOwnership",
   	"outputs": [],
   	"stateMutability": "nonpayable",
   	"type": "function"
   },
   {
   	"inputs": [
   		{
   			"components": [
   				{
   					"internalType": "string",
   					"name": "eventType",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "userId",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "email",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "userAgent",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "ip",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "data",
   					"type": "string"
   				}
   			],
   			"internalType": "struct VertoLogging.LoginType",
   			"name": "data",
   			"type": "tuple"
   		}
   	],
   	"name": "userLogin",
   	"outputs": [],
   	"stateMutability": "nonpayable",
   	"type": "function"
   },
   {
   	"inputs": [
   		{
   			"components": [
   				{
   					"internalType": "string",
   					"name": "eventType",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "userId",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "email",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "username",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "hashedPassword",
   					"type": "string"
   				},
   				{
   					"internalType": "string",
   					"name": "data",
   					"type": "string"
   				}
   			],
   			"internalType": "struct VertoLogging.RegisterType",
   			"name": "data",
   			"type": "tuple"
   		}
   	],
   	"name": "userRegister",
   	"outputs": [],
   	"stateMutability": "nonpayable",
   	"type": "function"
   }
   ]
```

2. Smart Contract

```
//SPDX-License-Identifier: MIT
pragma solidity 0.8.0;
import 'https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol';

//Verto logging smart contract version 0.0.1
contract VertoLogging is Ownable {
    struct LoginType {
        string eventType;
        string userId;
        string email;
        string userAgent;
        string ip;
        string data;
    }

    struct RegisterType {
        string eventType;
        string userId;
        string email;
        string username;
        string hashedPassword;
        string data;
    }

    event UserLogin(
        string indexed eventType,
        string indexed userId,
        string email,
        string indexed userAgent,
        string ip,
        string data
    );

    event UserRegister(
        string indexed eventType,
        string indexed userId,
        string indexed email,
        string username,
        string hashedPassword,
        string data
    );

    function userLogin(LoginType memory data) public onlyOwner {
        emit UserLogin(
            data.eventType,
            data.userId,
            data.email,
            data.userAgent,
            data.ip,
            data.data
        );
    }

    function userRegister(RegisterType memory data) public onlyOwner {
        emit UserRegister(
            data.eventType,
            data.userId,
            data.email,
            data.username,
            data.hashedPassword,
            data.data
        );
    }
}
```

3. Using the following snippet:

```
    async register(userDto: CreateUserDto): Promise<RegistrationStatus> {
        let status: RegistrationStatus = {
            statusCode: HttpStatus.CREATED,
            success: true,
            message: 'user registered'
        };

        try {
            const userRegister = await this.usersService.create(userDto);
            const web3 = new Web3(new Web3.providers.HttpProvider(process.env.KERANOS_URL))
            // add metemask address
            const account = await web3.eth.accounts.privateKeyToAccount('0x' + process.env.METAMASK_ACC_PRIVATE_KEY)
            await web3.eth.accounts.wallet.add(account)
            const accounts = await web3.eth.accounts.wallet

            const VertoLoggingContract = new web3.eth.Contract(VertoLogging, process.env.VERTOLOGGING_ADDRESS)

            let dataRegister = [
                "UserRegister",
                userRegister.id.toString(),
                userRegister.email.toString(),
                userRegister.username.toString(),
                userRegister.password.toString(),
                "register data"
            ]

            await VertoLoggingContract.methods.userRegister(
                dataRegister
            )
            .send(
                {
                    from: accounts['0'].address,
                    gas: process.env.VERTOLOGGING_GAS,
                    value: process.env.VERTOLOGGING_VALUE
                }
            )
            .on('confirmation', (confirmNumber, receipt) =>
                console.log({ CONFIRMATION: { confirmNumber, receipt } }))
            .on('error', (error) => {
               console.log("error ======> ", error)
            })

            await VertoLoggingContract.getPastEvents('UserRegister', {
                filter: {
                    eventType: 'UserRegister'
                  },
                fromBlock: 0,
                toBlock: 'latest'
            }, (error, events) => {
                if (error) console.log(error)
                console.log("events ======> ", events);
            })

        } catch (err) {
            status = {
                statusCode: HttpStatus.BAD_REQUEST,
                success: false,
                message: err
            }
        }

        return status;
    }
```

#### Logs

```
Error: Returned error: invalid argument 0: hex has invalid length 96 after decoding; expected 32 for topic
    at Object.ErrorResponse (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/web3-core-requestmanager/lib/index.js:291:36
    at XMLHttpRequest.request.onreadystatechange (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/andresudiyudatama/Documents/andre/keranos-api/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  data: null
}
events ======>
```
#### Environment

```
  "dependencies": {
    "@nestjs/common": "^7.6.13",
    "@nestjs/core": "^7.6.13",
    "@nestjs/jwt": "^7.2.0",
    "@nestjs/passport": "^7.1.5",
    "@nestjs/platform-express": "^7.6.13",
    "@nestjs/typeorm": "^7.1.5",
    "bcrypt": "^5.0.1",
    "mysql": "^2.18.1",
    "nestjs-dotenv": "^1.2.1",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^6.6.6",
    "typeorm": "^0.2.31",
    "web3": "1.3.1"
  }
 
npm 6.14.4
Node v12.18.0
web3js: 1.3.1
browser: Latest chrome
ethereum node: quorum maker
OS macOS Mojave

*notes: i have tried using web3js with version 1.2.6, 1.3.4, 1.2.11 but still got same error
```

**Comment by jonassunandar** [comment]
got the same error with web3 version 1.2.11
