### ISSUE TITLE
Calling function from web3 fails, calling it from truffle console works

### ISSUE THREAD

**Issue by pichikadev** [ethereum/web3.js#4002]
Calling function from web3 fails, calling it from truffle console works

My environment:

- NodeJS v10.19.0
- NPM 6.14.4
- OS Linux Mint kernel version 5.4.0-40-generic
- Brave Browser 1.18.70

I have the following JS code to call a contract:

```javascript
const txHash = await timelockContract.methods.executeTransaction(
      "0x71c1179e3C351De2641845cDAe537aCFC1808Fd2",
      0,
      "",
      "0x84e82a3300000000000000000000000000000000000000000000000000000000000003e800000000000000000000000031f2d666066d02953184ccb749946ed9a4a2218a00000000000000000000000000000000000000000000000000000000000000c80000000000000000000000000000000000000000000000000000000000000000",
      1253215,
      ).send({from: "0xfa2c2284804D9Cb83BE7fEcCf7c171619F9915bF"}, (error, transactionHash) => {
        console.log(error);
        console.log(transactionHash);
    });
```

This way I encode the fourth parameter (encoded parameters to make call from smart contract to another one):

```javascript
let b = web3.eth.abi.encodeFunctionCall({
    type: 'function',
    name: 'add',
    inputs: [
      {
        name: '1',
        type: 'uint256',
      },
      {
        name: '2',
        type: 'address',
      },
      {
        name: '3',
        type: 'uint16',
      },
      {
        name: '4',
        type: 'bool',
      },
    ],
  },
  [
    '1000',
    '0x9cBbdB6Ad6379D793ffa4Cb7A3643F3442f1836A',
    '200',
    false
  ]
);
```

This is the contract I'm calling (contract 1):

```solidity
function executeTransaction(address 1, uint 2, string memory 3, bytes memory 4, uint eta) public payable returns (bytes memory) {
        emit Called("called");
 
        ...
       
        (bool success, bytes memory returnData) = 1.call{value: 2}(3);
        require(success, "Timelock::executeTransaction: Transaction execution reverted.");

        ...
    }
```

This contract calls another function in another contract (contract 2):

```solidity
    function add(uint256 1, address 2, uint16 3, bool 4) public /*onlyOwnernonDuplicated*/ returns (bool) {
        
        
        IBEP20 _lpToken = IBEP20(2);
        
        uint256 lastRewardBlock = block.number > startBlock ? block.number : startBlock;
        totalAllocPoint = totalAllocPoint.add(3);
        poolExistence[_lpToken] = true;
        
        PoolInfo memory pI = PoolInfo({
            a : _lpToken,
            b : _allocPoint,
            c : lastRewardBlock,
            d : 0,
            e : _depositFeeBP
        });
        
        poolInfo.push(pI);

        return true;
    }
```

From executing the node.js script I get the following:

```javascript
(node:154714) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x2b14a9d5c104775159962aa777439f8609b326e9c3ac092fdcd9c22030dffc4e",
  "blockNumber": 8006112,
  "contractAddress": null,
  "cumulativeGasUsed": 151440,
  "from": "0x96122617199a33fd297cbba77bec8eac0a745d67",
  "gasUsed": 99263,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xbf37c65775baa015ee08ace1f4b301f0088efc77",
  "transactionHash": "0x5ec690d615ecd5eaf0e4b225b5dc9a185d80a3ba42983c99ff9627120377de74",
  "transactionIndex": 2,
  "events": {}
}
    at Object.TransactionError (/home/jordi/Projects/farm/goose-api/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/home/jordi/Projects/x/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /home/jordi/Projects/x/node_modules/web3-core-method/lib/index.js:394:57
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:154714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

So the issue comes from contract 1 line:

```solidity
require(success, "Timelock::executeTransaction: Transaction execution reverted.");
```

When debugging with truffle debug, I can see that the second contract is reached, and where it fails is at this line:

```
poolInfo.push(pI);
```

Seems like its failing when pushing the new object to the array.

So, when executing the same call in truffle console,(same call as in the nodejs script with exact same parameters), it works, I execute the following way:

```solidity
t.executeTransaction("0x0b8Be1A0EE58cBb0db3e1Ea0bA7A788874a4C9d7", 0, "", "0x84e82a3300000000000000000000000000000000000000000000000000000000000003e800000000000000000000000094d06aa1e067230cc4edffab7e57174cd707298500000000000000000000000000000000000000000000000000000000000000c80000000000000000000000000000000000000000000000000000000000000000", 1253215);
```

Executing the command above in the truffle console works perfectly fine. 
I compared both transactions, failed and succeeded when debuging, class state, local variables are both are the same.

I also deployed to BSC test net, same behaviour, from the node.js script it doesnt work, but from truffle console it works fine.

Appreciate any help, thank you.

**Comment by GregTheGreek** [comment]
When using the truffle console are you connecting to a local ganche instance or an actual testnet?

**Comment by pichikadev** [comment]
I tested both. When I deployed to ganache, in truffle I connected to the ganache instance. And when I deployed to BSC testnet, I connected to the BSC network in truffle. Btw, I didn't run the nodejs script in the browser, but in the console.

**Comment by pichikadev** [comment]
Issue was: Insufficient gas, mainly. Seems like the push operation requires a lot more gas than I was expecting. Truffle CLI seems like to mask this issue because probably it's sending enough gas. On my frontend APP I wasn't setting enough gas.
