### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by bourkefloyd** [ethereum/web3.js#4006]
#### Expected behavior
It works

#### Actual behavior

```bash
(node:96607) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at signed (node_modules/web3-eth-accounts/lib/index.js:149:62)
    at node_modules/web3-eth-accounts/lib/index.js:206:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async test (src/test.js:30:21)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:43
(node:96607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
<node_internals>/internal/process/warning.js:43
(node:96607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce the behavior

```javascript
import Web3 from 'web3';

const web3 = new Web3('wss://ropsten.infura.io/ws/v3/myinfruraproject');

// Test Address 1
const sourceAddr = '0xXXXXXXAddr';
const sourcePk = Buffer.from('XXXXXXPrivateKey', 'hex');
// Test Address 2
const destinationAddr = '0xYYYYYYAddr'

const txCount = await web3.eth.getTransactionCount(sourceAddr);
const networkType = await web3.eth.net.getNetworkType()

const customCommon = {
   baseChain: networkType,
   harfork: 'berlin'
};

const txRaw = {
   nonce:    web3.utils.toHex(txCount),
   to:       destinationAddr,
   value:    web3.utils.toHex(web3.utils.toWei('0.1', 'ether')),
   gasLimit: web3.utils.toHex(21000),
   gasPrice: web3.utils.toHex(web3.utils.toWei('10', 'gwei')),
   common: customCommon
};

const test = async () => {
   const txSigned = await web3.eth.accounts.signTransaction(txRaw, sourcePk);
   console.log(txSigned);


   // const txReceipt = await web3.eth.sendSignedTransaction(txSigned.rawTransaction);
   // console.log(txReceipt);
}

test();

```

#### Logs

See above

#### Environment

FYI I'm using NodeJs w/ these dependencies

node --version
v14.16.0
npm --version
6.14.11

```json
"dependencies": {
    "@openzeppelin/contracts": "3.4.1",
    "@truffle/contract": "4.3.13",
    "sha3": "2.1.4",
    "web3": "1.3.5"
  }
```

also posted here, but seems to be a web3 issue
https://github.com/ethereumjs/ethereumjs-monorepo/issues/1223

**Comment by GregTheGreek** [comment]
We're working on this right now to get this included into a release, thank you for pointing this out
