### ISSUE TITLE
eth_sendRawTransaction call error [-32000] insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by zeleniy** [ethereum/web3.js#4122]
Sometimes it work fine, but sometime i got the error. Code for tx signing:
```
const trxOptions = {
  to:    properties.getRaw('blockchain.target_address'),
  value: web3.utils.toHex(web3.utils.toWei('0', 'ether')),
  gas:   1509915,
  data:  web3.utils.toHex(message)
};

account.signTransaction(trxOptions)
  .then(signedTx => {
    console.log(signedTx.rawTransaction);
    process.exit(0);
  }).catch((ex) => {
    console.error(ex);
    process.exit(1);
  });
```
Code refactoring below doesn't help:
```
web3.eth.getGasPrice().then((gasPrice) => {
  web3.eth.getBlock('latest').then((block) => {

    const gasLimit = block.gasLimit;

    const trxOptions = {
      to:    properties.getRaw('blockchain.target_address'),
      value: web3.utils.toHex(web3.utils.toWei('0', 'ether')),
      gasPrice: gasPrice,
      gas: gasLimit,
      data:  web3.utils.toHex(message)
    };

    account.signTransaction(trxOptions)
      .then(signedTx => {
        console.log(signedTx.rawTransaction);
        process.exit(0);
      }).catch((ex) => {
        console.error(ex);
        process.exit(1);
      });
  });
});
```
So looks like utility methods (i mean `getGasPrice` and getting `gasLimit` from latest block) has no sense. How to sign tx in such way it will be accepted without the error?

**Comment by zeleniy** [comment]
Anybody knows here how web3.js works?

**Comment by zeleniy** [comment]
There is thousands of questions on [ethereum.stackexchange.com](https://www.google.com/search?q=%22Insufficient%20funds%20for%22%20site%3Aethereum.stackexchange.com). So may be someone of developers can explain how to calculate sufficient values for `gas` and `price` in formula `gas * price + value`. I modified code above adding balance fetching and have next code now:
```
...
web3.eth.getBalance(properties.getRaw('blockchain.source_address')).then((balance) => {
  web3.eth.getGasPrice().then((gasPrice) => {
    web3.eth.getBlock('latest').then((block) => {

    const gasLimit = block.gasLimit;

    const trxOptions = {
      to:    properties.getRaw('blockchain.target_address'),
      value: web3.utils.toHex(web3.utils.toWei('0', 'ether')),
      gasPrice: gasPrice,
      gas: gasLimit,
      data:  web3.utils.toHex(message)
    };

    const logData = sprintf('%s\n%s', moment().format('YYYY-MM-DD HH:mm:ss'), JSON.stringify({
      balance: balance,
      trxOptions: trxOptions
    }));

    fs.writeFileSync(logFile, logData, {
      flag: 'a'
    });

    account.signTransaction(trxOptions)
      .then(signedTx => {
        console.log(signedTx.rawTransaction);
        process.exit(0);
      }).catch((ex) => {
        console.error(ex);
        process.exit(1);
      });
    });
  });
});
...
```
Then in logs i see next data:
```
{
  "balance":"15004702212720236",
  "trxOptions":{
    "to":"0x603D1EdA7fAbF389BbEA5b2baDE70ED39e555D44",
    "value":"0x0",
    "gasPrice":"36050000000",
    "gas":14970720,
    "data":"0x486173683a20633936663466636665653865313434336133343964666234353430366133343533333163336665636437363266663230313338376264313831666665646635630a55524c3a2068747470733a2f2f75646961722e6e65742f636174616c6f672f3134392d372d32303231303333312d30312d30302d31343037"
  }
}
```
My balance is 15004702212720236 what equal to **$37.67**:
![Screenshot from 2021-08-03 17-00-22](https://user-images.githubusercontent.com/2780617/128029142-8c89aef5-7c1a-4e2c-ba71-98ebfc76ea73.png)

But `gas * price = 14970720 * 36050000000 = 5.396945e+17` what is really much more than 15004702212720236. If i don't forget school-level math it means:
```
balance / 37.67 = (gas * price) / x
15004702212720236 / 37.67 = (14970720 * 36050000000) / x
15004702212720236 / 37.67 = 5.396945e+17 / x
x = (37.67 * 5.396945e+17) / 15004702212720236
x = 1354.928
```
So Ethereum tell me that it want **$1354** fee per tx. What's going on?

**Comment by Spacesai1or** [comment]
When you do

```javascript
web3.eth.getBlock('latest').then((block) => {
    const gasLimit = block.gasLimit;
    ...
```

You're setting the `gasLimit` of your transaction to the total amount of `gas` allowed to be used by **all the transactions** in the previous block - probably where the `$1354` transaction fee came from, and is why you don't have enough to pay for the transaction

You can make use of the [web3.eth.estimateGas](https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html#estimategas) function to determine the amount of gas your transaction should use:

```javascript
const trxOptions = {
    to:    properties.getRaw('blockchain.target_address'),
    data:  web3.utils.toHex(message)
};
  
web3.eth.estimateGas(trxOptions).then(gas => {
    trxOptions.gas = gas;
    account.signTransaction(trxOptions).then(signedTx => {
        web3.eth.sendSignedTransaction(signedTx.rawTransaction).then(txReceipt => {
            console.log(txReceipt);
            process.exit(0);
        })
    })
}).catch(ex => {
    console.error(ex);
    process.exit(1);
})
```

I'm going to close this issue though as there doesn't seem to be any bugs to fix. Please comment if the above solution doesn't work for you, or you run into any other related errors

**Comment by zeleniy** [comment]
@spacesailor24 thank you very much for your code example. Now it works. So full code is:
```
const moment = require('moment');
const PropertiesReader = require('properties-reader');
const Web3 = require('web3');


try {

  const properties = PropertiesReader('ethereum.properties');

  const web3 = new Web3(new Web3.providers.HttpProvider(properties.get('blockchain.endpoint_url')));
  const account = web3.eth.accounts.privateKeyToAccount(properties.getRaw('blockchain.private_key'));
  const trxOptions = {
    to:    properties.getRaw('blockchain.target_address'),
    value: web3.utils.toHex(web3.utils.toWei('0', 'ether')),
    data:  web3.utils.toHex('Hello Kitty; ' + moment().format('YYYY-MM-DD HH:mm:ss'))
  };

  web3.eth.estimateGas(trxOptions).then(gas => {

    trxOptions.gas = gas;
    console.log([ 'trxOptions', trxOptions ]);

    account.signTransaction(trxOptions).then(signedTx => {

        console.log([ 'rawTransaction', signedTx.rawTransaction ]);

        web3.eth.sendSignedTransaction(signedTx.rawTransaction).then(txReceipt => {
          console.log(txReceipt);
        }).catch((ex) => {
          console.error(ex);
          process.exitCode = 1;
        });

      }).catch((ex) => {
        console.error(ex);
        process.exitCode = 1;
      });
  });

} catch (ex) {
  console.error(ex);
  process.exitCode = 1;
}
```
First run was not successfull:
```
# node src/sign.js                                     
(node:102) Warning: N-API is an experimental feature and could change at any time.
[ 'trxOptions',
  { to: '0x603d1eda7fabf389bbea5b2bade70ed39e555d44',
    value: '0x0',
    data: '0x48656c6c6f204b697474793b20323032312d31302d31312031343a32383a3435',
    gas: 21512 } ]
Error: Signer Error: gas limit is too low. Need at least 23176
    at signed (/root/ethereum-app/node_modules/web3-eth-accounts/lib/index.js:171:23)
    at /root/ethereum-app/node_modules/web3-eth-accounts/lib/index.js:206:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Ok, i've multiplied estimated gas in next way:
```
trxOptions.gas = gas * 1.5;
```
And then run app again:
```
# node src/sign.js
(node:112) Warning: N-API is an experimental feature and could change at any time.
[ 'trxOptions',
  { to: '0x603d1eda7fabf389bbea5b2bade70ed39e555d44',
    value: '0x0',
    data: '0x48656c6c6f204b697474793b20323032312d31302d31312031343a32393a3132',
    gas: 32268 } ]
[ 'rawTransaction',
  '0xf8868204828510681af1af827e0c94603d1eda7fabf389bbea5b2bade70ed39e555d4480a048656c6c6f204b697474793b20323032312d31302d31312031343a32393a313225a0d830793310ca39c7f011883e11e98d99fd8a648113f86f721bb25497bd76ec28a00f11dd766cd3bb00385fe51c5746773df92dde0019a7c667724a3e1bd7cf14a6' ]
{ blockHash: '0x05626c02eecb28d2ff3f07f5049450ce3a18b9d00778c425bd25bbdffe1787a9',
  blockNumber: 13397838,
  contractAddress: null,
  cumulativeGasUsed: 10588632,
  effectiveGasPrice: '0x10681af1af',
  from: '0x94405871483c94e86df030006b3be9e9debf82ed',
  gasUsed: 21512,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  status: true,
  to: '0x603d1eda7fabf389bbea5b2bade70ed39e555d44',
  transactionHash: '0x12fd99da0090520014ac75a19fbd3baa21499770460a849c8ef0c44a41c35f07',
  transactionIndex: 133,
  type: '0x0' }
```
Very good, [here it is](https://etherscan.io/tx/0x12fd99da0090520014ac75a19fbd3baa21499770460a849c8ef0c44a41c35f07). But the price! **Transaction Fee** is **$5.45**. So much for 0-value transaction with text message `Hello Kitty; 2021-10-11 14:29:12`. It is still too hight.
