### ISSUE TITLE
feeHistory triggers BigNumber limitation

### ISSUE THREAD

**Issue by brg8** [ethereum/web3.js#4212]
#### Expected behavior
Calling the `eth_feeHistory` method should handle the response without error.

#### Actual behavior
```
benjamingodlove web3-test % node web3-test.js
/Users/benjamingodlove/Developer/web3-test/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Number can only safely store up to 53 bits
    at assert (/Users/benjamingodlove/Developer/web3-test/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/benjamingodlove/Developer/web3-test/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at hexToNumber (/Users/benjamingodlove/Developer/web3-test/node_modules/web3-utils/lib/utils.js:207:24)
    at Method.toNumber (/Users/benjamingodlove/Developer/web3-test/node_modules/web3-utils/lib/utils.js:466:48)
    at /Users/benjamingodlove/Developer/web3-test/node_modules/web3-core-method/lib/index.js:128:38
    at Array.map (<anonymous>)
    at Method.formatInput (/Users/benjamingodlove/Developer/web3-test/node_modules/web3-core-method/lib/index.js:126:32)
    at Method.toPayload (/Users/benjamingodlove/Developer/web3-test/node_modules/web3-core-method/lib/index.js:159:23)
    at Eth.send [as getFeeHistory] (/Users/benjamingodlove/Developer/web3-test/node_modules/web3-core-method/lib/index.js:497:61)
    at Object.<anonymous> (/Users/benjamingodlove/Developer/web3-test/web3-test.js:8:10)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

#### Steps to reproduce the behavior
I've created a minimal reproduction here: https://github.com/brg8/web3-bn-repro.
#### Environment

```
npm -v
7.4.0
```
```
node -v
v15.6.0
```
Macbook Pro running Catalina 10.15.7.

Thanks for the help!

**Comment by brg8** [comment]
Resolved by switching input types.
```
web3.eth.getFeeHistory([4, "0xa3cdc1", []]).then((fh) => {
  console.log(fh);
});
```
Should be
```
web3.eth.getFeeHistory(4, "0xa3cdc1", []).then((fh) => {
  console.log(fh);
});
```

**Comment by lucaspiressimao** [comment]
Check this https://github.com/ChainSafe/web3.js/issues/3936#issuecomment-797342613
