### ISSUE TITLE
Dumping to error console rather than throwing exception

### ISSUE THREAD

**Issue by mining-visualizer** [ethereum/web3.js#4239]
I use Infura for my web3 needs, and as can be expected, there are the occassional timeouts, bad gateway, and other such errors that occur due to their infrastructure not being perfect.  In almost all cases, web3 responds by throwing an exception which my code can catch, but there are some times when it just dumps an error message to the error console, which makes it very difficult to know where the error came from, especially as it is often a timeout.  Mostly it is annoying because I have an alerting system that triggers on error console output, and I would prefer to be able to ignore those situations, as my code has the necessary robustness to deal with it.

Here is an example of what I see on the error console:

```
Error: Invalid JSON RPC response: "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
    at Object.InvalidResponse (/home/mvis/projects/tokenpool/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/home/mvis/projects/tokenpool/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/mvis/projects/tokenpool/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/mvis/projects/tokenpool/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/mvis/projects/tokenpool/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/mvis/projects/tokenpool/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Any suggestions as to how I can track that down, and catch it as an exception?

#### Expected behavior

Throw an exception where there is an error.  Don't dump text to error console.

#### Actual behavior

The opposite of the expected behaviour.

#### Steps to reproduce the behavior

Errors are random and infrequent.

#### Environment

Node 10
web3 v1.5.0
ubuntu 18.04

**Comment by mining-visualizer** [comment]
To be completely honest, there are some calls to web3 functions in my code that are not wrapped in try/catch blocks.  But I don't think that is the problem, although my knowledge of javascript is not exhaustive.  After all, it's not as if the dependent function would be able to tell that my code is not going to handle the exception, and then go "Oh, I see the user doesn't have a try/catch block, so I guess I'll just dump to error console".  Or am I wrong?

**Comment by GregTheGreek** [comment]
Is there anyway to provide a reproducible snippet?

**Comment by mining-visualizer** [comment]
Unfortunately, no.  I have no idea which part of my code is generating this.  I make numerous web3 calls in my application.

**Comment by Spacesai1or** [comment]
Hello, thank you for bringing this to our attention!

The team is currently working on a rewrite of the code base (`4.x` branch) that will have better error handling. Due to the complexity of hunting down where this error is coming from, we most likely won't address it for `1.x`

You're invited to debug and open a pull request to fix this, we will review and merge it

**Comment by philknows** [comment]
If you are able to reproduce and provide instructions, please reopen.
