### ISSUE TITLE
TypeError: web3_1.default is not a constructor

### ISSUE THREAD

**Issue by ziaukhan** [ethereum/web3.js#4257]
[step21_web3_node_getbalance.zip](https://github.com/ChainSafe/web3.js/files/7023560/step21_web3_node_getbalance.zip)

I attaching a Typescript Node.js Web3 project. It compiles, but when I run it, it given the following error:

node index
/Users/ZiaKhan/Documents/GitHub/defi-dapps-solidity-smart-contracts/step21_web3_node_getbalance/EthereumAccount.js:48
        this.web3 = new web3_1["default"]("https://mainnet.infura.io/v3/b56ef5c27bca4880844888e6a12a16ef");
                    ^

TypeError: web3_1.default is not a constructor
    at new EthereumAccount (/Users/ZiaKhan/Documents/GitHub/defi-dapps-solidity-smart-contracts/step21_web3_node_getbalance/EthereumAccount.js:48:21)
    at Object.<anonymous> (/Users/ZiaKhan/Documents/GitHub/defi-dapps-solidity-smart-contracts/step21_web3_node_getbalance/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

In the generated EthereumAccount.js file it is adding an [default] attribute which is causing the issue. When I remove the [default] in the js file manually, it runs perfectly.

I am using:
Node: v14.16.1
TypeScript: Version 4.3.5

**Comment by ziaukhan** [comment]
Resolved the issue by changing { module:"es2020" } to { module:"commonjs" } 
and instead to compiling tsc index.ts, just gave tsc command

**Comment by Cheny-chen** [comment]
I still have the same problem.
It is not solve.

I did { module:"commonjs" } in tsconfig


import Web3 from 'web3';
  web3 = new Web3( RPC_PROVIDER );


I still get the same error
TypeError: web3_1.default is not a constructor
