### ISSUE TITLE
Promise failed: Error: Given input "[object Promise]" is not a number.

### ISSUE THREAD

**Issue by MAhmedSaeedi** [ethereum/web3.js#4328]
#### Expected behavior
Mint nft token on polygon testnet mumbai
#### Actual behavior
Promise failed: Error: Given input "[object Promise]" is not a number.
#### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/25788516/133238545-166d081a-f8df-4734-b19e-bd8e0de798f4.png)

#### Logs
**********************************************************************
Promise failed: Error: Given input "[object Promise]" is not a number.
    at Object.numberToHex (C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-utils\lib\utils.js:236:15)
    at C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-core-helpers\lib\formatters.js:145:30
    at Array.forEach (<anonymous>)
    at _txInputFormatter (C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-core-helpers\lib\formatters.js:144:8)
    at Object.inputCallFormatter (C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-core-helpers\lib\formatters.js:157:15)
    at signed (C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-eth-accounts\lib\index.js:139:50)
    at C:\Users\Ahmed\Documents\nft_apis\node_modules\web3-eth-accounts\lib\index.js:224:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by luu-alex** [comment]
Hey, it seems like your promise is not being completed, `web3.eth.accounts.signTransaction` returns a callback function

so instead of doing:
`const signPromise = web3.eth.accounts.signTransaction(tx, process.env.PRIVATE_KEY);`

This should work 
`web3.eth.accounts.signTransaction(tx, process.env.PRIVATE_KEY).then(signedTx) => { ...`

I don't think this is an issue with web3.js so i'll close up this issue.
