### ISSUE TITLE
Error: invalid type thrown with no obvious reasons

### ISSUE THREAD

**Issue by hungdoansy** [ethereum/web3.js#4536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I created a simple smart contract, which just echoes back. The source code you can found [here](https://github.com/hungdoansy/test-web3/blob/master/src/TestUniswap.sol): https://github.com/hungdoansy/test-web3
I deployed it to Ropsten ([link](https://ropsten.etherscan.io/address/0x87AF7c9A4980EC414361203Ba3112b33DAa9F7Be#code))

I tried the Read Contract function in the explorer and it worked fine. However, I wrote a script in my local and it didn't work. The log was not so helpful

```
Error: invalid type (argument="type", value="s", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at Logger.throwArgumentError (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/logger/lib/index.js:211:21)
    at AbiCoder._getCoder (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/abi/lib/abi-coder.js:66:23)
    at /Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/abi/lib/abi-coder.js:43:34
    at Array.map (<anonymous>)
    at AbiCoder._getCoder (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/abi/lib/abi-coder.js:42:72)
    at /Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/abi/lib/abi-coder.js:91:63
    at Array.map (<anonymous>)
    at AbiCoder.decode (/Users/hung/Desktop/Code/test-web3/node_modules/@ethersproject/abi/lib/abi-coder.js:91:28)
    at ABICoder.decodeParametersWith (/Users/hung/Desktop/Code/test-web3/node_modules/web3-eth-abi/lib/index.js:303:30)
    at ABICoder.decodeParameters (/Users/hung/Desktop/Code/test-web3/node_modules/web3-eth-abi/lib/index.js:284:17)
    at Contract._decodeMethodReturn (/Users/hung/Desktop/Code/test-web3/node_modules/web3-eth-contract/lib/index.js:469:22)
    at Method.outputFormatter (/Users/hung/Desktop/Code/test-web3/node_modules/web3-eth-contract/lib/index.js:759:42)
    at Method.formatOutput (/Users/hung/Desktop/Code/test-web3/node_modules/web3-core-method/lib/index.js:146:54)
    at sendTxCallback (/Users/hung/Desktop/Code/test-web3/node_modules/web3-core-method/lib/index.js:522:33) {
  reason: 'invalid type',
  code: 'INVALID_ARGUMENT',
  argument: 'type',
  value: 's'
}
```
I googled but found no results, so I got my hands dirty by digging deep into the node_modules folder and printed what I could in lines mentioned in the log.

Something weird then appeared at 
```
param {
    "name": "type",
    "type": "tuple",
    "indexed": null,
    "components": [
        {
            "name": "0",
            "type": "s",
        },
        {
            "name": "1",
            "type": "t",
        },
        {
            "name": "2",
            "type": "r",
        },
        {
            "name": "3",
            "type": "i",
        },
        {
            "name": "4",
            "type": "n",
        },
        {
            "name": "5",
            "type": "g",
        }
    ],
}
```
It's "string". I digged deeper to this function: mapStructToCoderFormat ([link](https://github.com/ChainSafe/web3.js/blob/v1.6.0/packages/web3-eth-abi/src/index.js#L215)). 

I tried a small JS script
```js
const struct = "string";

Object.keys(struct).forEach(function (key) {
  console.log(key);
});

// "0", "1", "2", "3", "4", "5"
```

Maybe this is a bug or I had typo somewhere. This took me an afternoon to resort to this issue report.

### Expected Behavior

The smart contract's functions should be called just fine

### Steps to Reproduce

1. Clone this repo: https://github.com/hungdoansy/test-web3/, please use node v12 and yarn v1
2. `yarn && yarn start`

### Web3.js Version

1.6.0

### Environment

- Operating System: MacOS 11.2.3
- Browser: Chrome
- Node.js Version: v12.22.5
- NPM Version: 6.14.14

**Comment by hungdoansy** [comment]
Sorry my bad. 

I used hardhat for my development and I used

`
const contractData = {
    address: contract.address,
    abi: JSON.parse(contract.interface.format("json")),
  };
` 

to get address and the abi of the contract. This ABI somehow was not the same as the one you see in the explorer and this caused the problem.
