### ISSUE TITLE
web3-providers-ws undefined `window` in web workers 

### ISSUE THREAD

**Issue by prevostc** [ethereum/web3.js#4745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The web3-providers-ws/lib/helpers.js uses `window` which is not supported inside web workers and yields an error

```
Uncaught ReferenceError: window is not defined
    at Object.<anonymous> (helpers.js:23:1)
    at Object../node_modules/web3-providers-ws/lib/helpers.js (helpers.js:28:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/web3-providers-ws/lib/index.js (index.js:24:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/web3-core-requestmanager/lib/index.js (index.js:44:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/web3-core/lib/index.js (index.js:22:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/web3/lib/index.js (index.js:29:1)
```

### Expected Behavior

Should not yield an error

### Steps to Reproduce

```javascript
// main.js
import * as Comlink from "comlink";

async function init() {
  const worker = new Worker("worker.js");
  const obj = Comlink.wrap(worker);
  const results = await obj.test();
  console.log(results);
}
init();
```

```javascript
// worker.js
import * as Comlink from "comlink";
import Web3 from 'web3';
import { MultiCall } from 'eth-multicall';
import myAbi from "./abi.json"

Comlink.expose({
  test: async () => {
      const web3 = new Web3('https://bsc-dataseed.binance.org');
      const contract =  new web3.eth.Contract(myAbi, "0xXXXXXX");
      const calls = []
      const calls.push({
        balance: contract.methods.balance(),
      })

      const mc = new MultiCall(web3, "0xYYYYYY");
      const [results] = await mc.all([calls]);
      return results
  },
});
```

### Web3.js Version

1.3.4

### Environment

- Operating System: macOS Big Sur 11.05
- Browser: Brave 1.34
- Node.js Version: v16.13.1
- NPM Version: 8.1.2

### Anything Else?

I added a PR to use globalThis instead: https://github.com/ChainSafe/web3.js/pull/4744

**Comment by prevostc** [comment]
Looks fixed by a recent and unrelated change https://github.com/ChainSafe/web3.js/commit/ed825d2b260a249b01c3a55c822a9ca2588e961f
