### ISSUE TITLE
Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by linkocrn** [ethereum/web3.js#4793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I am just starting out with Web3 and I am encountering an error. I do not know what it means and I googled it but it seems to mean many different things. I found similar errors on this github but since it's a generic error, it didn't help my case.

### Expected Behavior

no error

### Steps to Reproduce

```
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (...\node_modules\web3-core-helpers\lib\errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (...\node_modules\web3-providers-http\lib\index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (...\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (...\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (...\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (...\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:520:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Web3.js Version

1.7.0

### Environment

- Operating System: Windows 10
- Browser: Chrome
- Node.js Version: 16.14.0
- NPM Version: 8.3.1

**Comment by Spacesai1or** [comment]
Hi there, if you could provide the code you're using that receives this error (a repository with runnable code would be even better), we could better assist you. With just the error message, there's not much we can do to help you debug

**Comment by linkocrn** [comment]
Hello, here is the code that I used

```
const Web3 = require('web3')

class TransactionChecker {
    web3;
    account;

    constructor(projectId, account) {
        this.web3 = new Web3(new Web3.providers.HttpProvider('https://rinkeby.infuria.io/v3/' + projectId));
        this.account = account.toLowerCase();
    }

    async checkBlock() {
        let block = await this.web3.eth.getBlock('latest');
        let number = block.number;
        console.log('Searching block ' + number);

        if (block != null && block.transactions != null) {
            for (let txHash of block.transactions) {
                let tx = await this.web3.eth.getTransactions(txHash);
                if (this.account = tx.to.toLowerCase()) {
                    console.log('Transaction found on block: ' + number);
                    console.log({address: tx.from, value: this.web3.utils.fromWei(tx.value, 'ether'), timestamp: new Date()});
                }
            }
        }
    }
}

var web3 = new Web3('http://rinkeby.infuria.io/v3/' + '8116e17c869942ceb3cdbe04cf7c7248');
web3.eth.getBlockNumber()
.then(console.log);
```

**Comment by luu-alex** [comment]
Hey there, I was able to sucessfully call `getBlockNumber` using an infura project that i just created now. There might be an issue on how u configured your infura project

**Comment by nazarhussain** [comment]
@alexisdavidson  Normally any response `Error: Invalid JSON RPC response` meant the node you are connected with is not responding correctly. Probably some configuration issue from your side. As @luu-alex was able to verify `getBlockNumber` is working fine with Infura, I am closing this issue for now. 

If you find more details which leads you to believe there is bug, please reopen this issue with more details.

**Comment by Ciao-2** [comment]
Have you solved this problem? I also encountered the same mistake,And the question comes up randomly

**Comment by arthur-lbchn** [comment]
I have exactly the same issue with geth, it randomly caused:

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/worker/node_modules/web3-core-helpers/lib/errors.js:43:16)
    at XMLHttpRequest.request.onreadystatechange (/worker/node_modules/web3-providers-http/lib/index.js:95:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/worker/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/worker/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (/worker/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (/worker/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketOnEnd (node:_http_client:478:9)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by ilijapet** [comment]
Same here :)

**Comment by hovanhoa** [comment]
Have anyone solved this problem?

**Comment by jjmr007** [comment]
Why an issue on a non solved bug report is closed?

**Comment by Kolobamanacas** [comment]
At least one certain scenario of reproduction this bug is having response object with very big number of nesting. In my case, I've mocked the response and if I have nesting level about 4000 it fails 100% times.

**Comment by luu-alex** [comment]
@Kolobamanacas what version of web3js are you using and do u have a code snippet to cause this issue?

**Comment by Kolobamanacas** [comment]
> @Kolobamanacas what version of web3js are you using and do u have a code snippet to cause this issue?

Aaah, I've noticed we are still using ancient version 1.7.1, so before I create a repo with reproduction, we probably need to survive a migration to the latest version first.
