### ISSUE TITLE
ES6 Module Consumption

### ISSUE THREAD

**Issue by jeffscottward** [ethereum/web3.js#490]
When attempting you use a modern bundler (in my case its Rollup http://rollupjs.org/).
I cannot import individual modules that I need because they aren't exported correctly. 

```
Module MY_PROJECT/node_modules/web3-provider-engine/subproviders/rpc.js does not export default (imported by MY_PROJECT/lib/index.js)

Error: Module MY_PROJECT/node_modules/web3-provider-engine/subproviders/rpc.js does not export default (imported by MY_PROJECT/lib/index.js)

    at Module.trace (MY_PROJECT/node_modules/rollup/src/Module.js:683:30)
    at MY_PROJECT/node_modules/rollup/src/Module.js:265:30
    at Array.forEach (native)
    at MY_PROJECT/node_modules/rollup/src/Module.js:263:25
    at Array.forEach (native)
    at Module.bindReferences (MY_PROJECT/node_modules/rollup/src/Module.js:256:19)
    at MY_PROJECT/node_modules/rollup/src/Bundle.js:104:44
    at Array.forEach (native)
    at MY_PROJECT/node_modules/rollup/src/Bundle.js:104:18
```

**Comment by jeffscottward** [comment]
Wrong library :) closing
