### ISSUE TITLE
web3.personal.newAccount() Doesn't work

### ISSUE THREAD

**Issue by AlexanderKozhevin** [ethereum/web3.js#494]
I'm running a very simple code and it's giving me an error.
```javascript
var Web3 = require('web3');
var web3 = new Web3();
web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

var newAccount = web3.personal.newAccount("yo");
console.log(newAccount)
```

```bash
/home/info/open-ethereum-pool/node_modules/web3/lib/web3/requestmanager.js:61
        throw errors.InvalidResponse(result);
        ^

Error: The method personal_newAccount does not exist/is not available
    at Object.InvalidResponse (/home/info/open-ethereum-pool/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/home/info/open-ethereum-pool/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Personal.send [as newAccount] (/home/info/open-ethereum-pool/node_modules/web3/lib/web3/method.js:145:58)
    at Object.<anonymous> (/home/info/open-ethereum-pool/test.js:7:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

```

**Comment by AlexanderKozhevin** [comment]
Amm. Well. It's working.
if I use following parameters when I start geth.
```bash
--rpcapi="db,eth,net,web3,personal,web3"
```

**Comment by sagargohil** [comment]
![errorfatal](https://cloud.githubusercontent.com/assets/24582440/22589641/496b9ac0-ea31-11e6-8a2b-8d96a4074240.png)

I am getting this error when i am executing --rpcapi="db,eth,net,web3,personal,web3" this command

**Comment by Grashias** [comment]
1.  Run " geth attach  ".
2. Then in Javascript console itself run " admin.startRPC(address, port, "*", "web3,personal,admin,debug,db,net,eth,miner,rpc,txpool") ".

Works fine. 

Can use " web3.personal.newAccount("password"); " and " web3.personal.unlockAccount(address, "password", 0) " at the client side using rpc api itself.

**Comment by dongsam** [comment]
geth 1.7.3 now, you should like this `geth --rpc --rpcapi db,eth,net,web3,personal,web3` without `" "`

**Comment by zjt3939** [comment]
if I  connect to the test network such as kovan test network or main network , how to deal with this problom
