### ISSUE TITLE
Jest has detected the following 1 open handle potentially keeping Jest from exiting

### ISSUE THREAD

**Issue by oliviera9** [ethereum/web3.js#4999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Executing `web3.eth.getBlock` using an HttpProvider let Jest complain about an open handle.
I also tried disconnecting from the HttpProvider, but with no success.
The same happens with `getTransactionCount`.
```
 PASS  test/get-block.test.ts
  getBlock
    ✓ aaa (1126 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.2 s, estimated 5 s
Ran all test suites matching /test\/get-block.test.ts/i.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPWRAP

       6 |     const currentProvider = new Web3.providers.HttpProvider('https://mainnet.infura.io/v3/xxxxxxxxxxx')
       7 |     const web3 = new Web3(currentProvider)
    >  8 |     const info = await web3.eth.getBlock('latest')
         |                                 ^
       9 |     expect(info.gasLimit).toBeGreaterThan(0)
      10 |     const prov = web3.currentProvider as HttpProvider
      11 |     prov.disconnect()

      at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._sendHxxpRequest (node_modules/xhr2-cookies/xml-http-request.ts:253:19)
      at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest._sendHttp (node_modules/xhr2-cookies/xml-http-request.ts:238:8)
      at XMLHttpRequest.Object.<anonymous>.XMLHttpRequest.send (node_modules/xhr2-cookies/xml-http-request.ts:165:16)
      at HttpProvider.Object.<anonymous>.HttpProvider.send (node_modules/web3-providers-http/lib/index.js:106:17)
      at RequestManager.Object.<anonymous>.RequestManager.send (node_modules/web3-core-requestmanager/lib/index.js:159:23)
      at sendRequest (node_modules/web3-core-method/lib/index.js:624:42)
      at Eth.send [as getBlock] (node_modules/web3-core-method/lib/index.js:656:13)
      at Object.<anonymous> (test/ptokens-utils-getblock.test.ts:8:33)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

### Expected Behavior

There should be no open handle left after test execution.

### Steps to Reproduce

```typescript
import Web3 from 'web3'
import { HttpProvider } from 'web3-core'

describe('getBlock', () => {
  test('aaa', async () => {
    const currentProvider = new Web3.providers.HttpProvider('https://mainnet.infura.io/v3/xxxxxxxxxxxx')
    const web3 = new Web3(currentProvider)
    const info = await web3.eth.getBlock('latest')
    expect(info.gasLimit).toBeGreaterThan(0)
    const prov = web3.currentProvider as HttpProvider
    prov.disconnect()
  })
})
```

### Web3.js Version

1.7.3

### Environment

- Operating System: macOS 12.12.1
- Browser: -
- Node.js Version: v16.14.0
- NPM Version: 8.3.1
- ts-jest: ^27.1.4
- jest: 27.5.1

### Anything Else?

Another user complaining about the same behavior:
https://stackoverflow.com/questions/70099089/jest-complains-when-using-web3-eth-open-handle-error

**Comment by luu-alex** [comment]
Thank you for reporting this issue, in your jest command you are running can you try adding the `--forceExit` flag and see if you still get the error? Even though you are doing the disconnect method I dont believe that does [anything](https://github.com/ChainSafe/web3.js/blob/1.x/packages/web3-providers-http/src/index.js#L128) 
Let me know if this fixes things :)

**Comment by oliviera9** [comment]
Thanks for your reply indeed. I have tried the `--forceExit` but still jest returns
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
```
from `_sendHxxpRequest`.

**Comment by cleverocheck** [comment]
any updates? I want to write my own tests without using Truffle :(

**Comment by antonydenyer** [comment]
I got round the problem with the following..

```

const infura = new Web3.providers.HttpProvider("https://goerli.infura.io/v3/TOKEN");
const web3 = new Web3(infura)

describe('Can send transaction', () => {
    afterAll(() => {
        infura.disconnect()
    });

  test('do things', () => {
    const gasPrice = await web3.eth.getGasPrice()
  })

}
```
