### ISSUE TITLE
`JSON.stringify(contract)` crashes

### ISSUE THREAD

**Issue by SCBuergel** [ethereum/web3.js#512]
I am deploying a contract via web3 (`"web3": "^0.17.0-beta"`):
```
var testContract = web3.eth.contract(testContractAbi).new({data: "0x606060405260088060106000396000f36060604052600256", gas: 3000000, from: accounts[4]}, (err, contract) => {
    if (err) {
        console.log('failed deploying contract: ' + err);
    }
    if (contract && contract.address) {
        console.log('deployed contract! ' + JSON.stringify(contract));
    }
});
```
The command `JSON.stringify(contract)` leads to the following crash:
```
/root/workspace/Test/node_modules/web3/lib/web3/requestmanager.js:61
        throw errors.InvalidResponse(result);
        ^

Error: Method not found
    at Object.module.exports.InvalidResponse (/root/workspace/Test/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/root/workspace/Test/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.get [as syncing] (/root/workspace/Test/node_modules/web3/lib/web3/property.js:107:62)
    at Object.stringify (native)
    at /root/workspace/Test/index.js:18:50
    at Object.callback (/root/workspace/Test/node_modules/web3/lib/web3/contract.js:143:37)
    at /root/workspace/Test/node_modules/web3/lib/web3/method.js:142:25
    at /root/workspace/Test/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/root/workspace/Test/node_modules/web3/lib/web3/httpprovider.js:110:13)
    at dispatchEvent (/root/workspace/Test/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
```
EDIT: the same crash happens when using an already deployed contract. The above code thus simplyfies to:
```
var testContract = web3.eth.contract(testContractAbi).at(testContractAddress);
console.log(JSON.stringify(testContract));
```
note that I am deploying an entirely empty contract that contains no function or variables.

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
