### ISSUE TITLE
Promise never resolves for contract revert returned from RPC

### ISSUE THREAD

**Issue by ghost** [ethereum/web3.js#5129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Related issues: https://www.google.com/search?q=web3.js+never+resolve+promise

#5127, #4891, 

I think this is bad since it would block the IO operation forever for async functions that people code,

For my case I did `await web3.eth.estimateGas` that would return the reverted call from node,

What the console output was

```
Error: Returned error: invalid argument 0: json: cannot unmarshal hex string of odd length into Go struct field TransactionArgs.data of type hexutil.Bytes
    at Object.ErrorResponse (node_modules\web3-core-helpers\lib\errors.js:28:19)
    at node_modules\web3-core-requestmanager\lib\index.js:300:36
    at XMLHttpRequest.request.onreadystatechange (node_modules\web3-providers-http\lib\index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: null
}
```

And it wouldn't resolve, forever.

### Expected Behavior

"error" object from the node should produce either revert or `resolve()` that would return undefined result, not just log the error to the console and hang the whole async process forever.

### Steps to Reproduce

```js
const test = async () => {
  try {
     const result = await web3.eth.estimateGas({
      to: "0xff50ed3d0ec03aC01D4C79aAd74928BFF48a7b2b",
      data: "0x111"
    });
    console.log(result);
  } catch (e) {
    console.error(e);
  }
}

test();
```

### Web3.js Version

latest

**Comment by ghost** [comment]
Could not reproduce this issue with fresh install so closing it.
