### ISSUE TITLE
Decoding Opensea Seaport Events (OrderFulfilled) causes Out Of Gas

### ISSUE THREAD

**Issue by dsgriffin** [ethereum/web3.js#5149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're trying to monitor sales events directly and, in a similar way as we were for Wyvern/LooksRare etc, decode the event logs of a Seaport transaction.

Event signature: 

```
event OrderFulfilled(bytes32 orderHash, address offerer, address zone, address recipient, struct SpentItem[] offer, struct ReceivedItem[] consideration)
```

ABI Method:

```
  {
    "anonymous": false,
    "inputs": [
      { "indexed": false, "internalType": "bytes32", "name": "orderHash", "type": "bytes32" },
      { "indexed": true, "internalType": "address", "name": "offerer", "type": "address" },
      { "indexed": true, "internalType": "address", "name": "zone", "type": "address" },
      { "indexed": false, "internalType": "address", "name": "recipient", "type": "address" },
      {
        "components": [
          { "internalType": "enum ItemType", "name": "itemType", "type": "uint8" },
          { "internalType": "address", "name": "token", "type": "address" },
          { "internalType": "uint256", "name": "identifier", "type": "uint256" },
          { "internalType": "uint256", "name": "amount", "type": "uint256" }
        ],
        "indexed": false, "internalType": "struct SpentItem[]", "name": "offer", "type": "tuple[]"
      },
      {
        "components": [
          { "internalType": "enum ItemType", "name": "itemType", "type": "uint8" },
          { "internalType": "address", "name": "token", "type": "address" },
          { "internalType": "uint256", "name": "identifier", "type": "uint256" },
          { "internalType": "uint256", "name": "amount", "type": "uint256" },
          { "internalType": "address payable", "name": "recipient", "type": "address" }
        ], 
        "indexed": false, "internalType": "struct ReceivedItem[]", "name": "consideration", "type": "tuple[]"
      }
    ],
    "name": "OrderFulfilled",
    "type": "event"
  },
  ```

The new contract is using a couple of `Structs` for `offer` and `consideration`. How are we able to decode these structs for event monitoring? Neither of the following are working:

```
web3.eth.abi.decodeLog([{
  type: 'bytes32',
  name: 'orderHash',
},
{
  type: 'address',
  name: 'offerer',
},
{
  type: 'address',
  name: 'zone',
},
{
  type: 'address',
  name: 'recipient',
},
{
  type: '(uint8,address,uint256,uint256)[]', // also tried: SpentItem[], as well as: tuple[]
  name: 'offer',
},
{
  type: '(uint8,address,uint256,uint256,address)[]', // also tried: RecievedItem[], as well as: tuple[]
  name: 'consideration',
}]
```

Causes:

```
2022-06-21T07:51:51.979518+00:00 app[worker.1]: /app/node_modules/web3-eth-abi/lib/index.js:297
2022-06-21T07:51:51.979541+00:00 app[worker.1]:         throw new Error('Returned values aren\'t valid, did it run Out of Gas? ' +
2022-06-21T07:51:51.979542+00:00 app[worker.1]:               ^
2022-06-21T07:51:51.979542+00:00 app[worker.1]: 
2022-06-21T07:51:51.979551+00:00 app[worker.1]: Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParametersWith (/app/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParameters (/app/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-06-21T07:51:51.979552+00:00 app[worker.1]:     at ABICoder.decodeParameter (/app/node_modules/web3-eth-abi/lib/index.js:273:17)
2022-06-21T07:51:51.979553+00:00 app[worker.1]:     at /app/node_modules/web3-eth-abi/lib/index.js:341:25
2022-06-21T07:51:51.979553+00:00 app[worker.1]:     at Array.forEach (<anonymous>)
2022-06-21T07:51:51.979554+00:00 app[worker.1]:     at ABICoder.decodeLog (/app/node_modules/web3-eth-abi/lib/index.js:337:12)
2022-06-21T07:51:51.979555+00:00 app[worker.1]:     at Subscription.<anonymous> (/app/app.js:92:47)
2022-06-21T07:51:51.979555+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected Behavior

Need to decode event logs for OpenSea Seaport Events

### Steps to Reproduce

...

### Web3.js Version

1.7.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version:

**Comment by nazarhussain** [comment]
@dsgriffin That seems needed further investigation. Can you share some reproducible code or valid binary data that you used in the `decodeLog` which caused this error.

**Comment by dsgriffin** [comment]
@nazarhussain is there no `processReceipt` equivalent in web3.js that web3.py has? I believe that automatically parses logs without having to try and decode like this.

example of it causing the error:

```
web3.eth.abi.decodeLog([{
  type: 'bytes32',
  name: 'orderHash',
},
{
  type: 'address',
  name: 'offerer',
},
{
  type: 'address',
  name: 'zone',
},
{
  type: 'address',
  name: 'recipient',
},
{
  type: '(uint8,address,uint256,uint256)[]', // also tried: SpentItem[], as well as: tuple[]
  name: 'offer',
},
{
  type: '(uint8,address,uint256,uint256,address)[]', // also tried: RecievedItem[], as well as: tuple[]
  name: 'consideration',
}]
``` 

```
[
      { "indexed": false, "internalType": "bytes32", "name": "orderHash", "type": "bytes32" },
      { "indexed": true, "internalType": "address", "name": "offerer", "type": "address" },
      { "indexed": true, "internalType": "address", "name": "zone", "type": "address" },
      { "indexed": false, "internalType": "address", "name": "recipient", "type": "address" },
      {
        "components": [
          { "internalType": "enum ItemType", "name": "itemType", "type": "uint8" },
          { "internalType": "address", "name": "token", "type": "address" },
          { "internalType": "uint256", "name": "identifier", "type": "uint256" },
          { "internalType": "uint256", "name": "amount", "type": "uint256" }
        ],
        "indexed": false, "internalType": "struct SpentItem[]", "name": "offer", "type": "tuple[]"
      },
      {
        "components": [
          { "internalType": "enum ItemType", "name": "itemType", "type": "uint8" },
          { "internalType": "address", "name": "token", "type": "address" },
          { "internalType": "uint256", "name": "identifier", "type": "uint256" },
          { "internalType": "uint256", "name": "amount", "type": "uint256" },
          { "internalType": "address payable", "name": "recipient", "type": "address" }
        ], 
        "indexed": false, "internalType": "struct ReceivedItem[]", "name": "consideration", "type": "tuple[]"
      }
    ]
```
