### ISSUE TITLE
getTransactionReceipt: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by WizardsOrb** [ethereum/web3.js#5153]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

```shell
.../node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
                    ^
Error: Number can only safely store up to 53 bits
```

### Expected Behavior

-

### Steps to Reproduce

```ts
// chain ETC (61)

web3.eth.getTransactionReceipt('0x84e8b73c5f9e5f1fdd6e3482022f3c65ceb92d95c4ea92075c04d1a22f6b3152').then(console.log)
```

gasPrice is 10mio GWEI.

representing `effectiveGasPrice` as string would solve the problem (currently typeof number)

https://blockscout.com/etc/mainnet/tx/0x84e8b73c5f9e5f1fdd6e3482022f3c65ceb92d95c4ea92075c04d1a22f6b3152

### Web3.js Version

1.7.3

### Environment

- Operating System: OSX 12.4 (21F79)
- Browser: 
- Node.js Version: 16
- NPM Version: 

### Anything Else?

thanks.

**Comment by nikoulai** [comment]
Hi @WizardsOrb , thanks for the issue.

We are into it.

**Comment by mishabunte** [comment]
@nikoulai error appears again on web3@1.8.1 when I am trying to get receipt for a specific transaction on goerli network, i suppose it's because of this transaction huge fee at 6,764.3 eth

https://goerli.etherscan.io/tx/0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d 

```
> var goerli = new Web3('ws://localhost:40002');
undefined
> t = '0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
'0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
> await goerli.eth.getTransactionReceipt(t)
Uncaught Error: Number can only safely store up to 53 bits
    at assert (/Users/misha/prj/bitstat/db/workers/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/Users/misha/prj/bitstat/db/workers/node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (/Users/misha/prj/bitstat/db/workers/node_modules/web3-utils/lib/utils.js:207:24)
    at Method.outputTransactionReceiptFormatter [as outputFormatter] (/Users/misha/prj/bitstat/db/workers/node_modules/web3-core-helpers/lib/formatters.js:246:47)
    at Method.formatOutput (/Users/misha/prj/bitstat/db/workers/node_modules/web3-core-method/lib/index.js:148:54)
    at sendTxCallback (/Users/misha/prj/bitstat/db/workers/node_modules/web3-core-method/lib/index.js:536:33)
    at Object.callback (/Users/misha/prj/bitstat/db/workers/node_modules/web3-core-requestmanager/lib/index.js:305:9)
    at /Users/misha/prj/bitstat/db/workers/node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (/Users/misha/prj/bitstat/db/workers/node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Users/misha/prj/bitstat/db/workers/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/Users/misha/prj/bitstat/db/workers/node_modules/websocket/lib/W3CWebSocket.js:234:14)
> 

```


`npm list | grep web3
└── web3@1.8.1
`

**Comment by mishabunte** [comment]
@nikoulai error appears again on web3@1.8.1 when I am trying to get receipt for a specific transaction on goerli network, i suppose it's because of this transaction huge fee at 6,764.3 eth

https://goerli.etherscan.io/tx/0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d

Solution:
```bash
> vi +207 ./node_modules/web3-utils/lib/utils.js
```
```javascript
207     //return toBN(value).toNumber();                                            
208     return toBN(value).toString();             

```

log
```
> var goerli = new Web3('ws://localhost:40002');
undefined
> t = '0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
'0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
> await goerli.eth.getTransactionReceipt(t)
Uncaught Error: Number can only safely store up to 53 bits
    at assert (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (./node_modules/web3-utils/lib/utils.js:207:24)
    at Method.outputTransactionReceiptFormatter [as outputFormatter] (./node_modules/web3-core-helpers/lib/formatters.js:246:47)
    at Method.formatOutput (./node_modules/web3-core-method/lib/index.js:148:54)
    at sendTxCallback (./node_modules/web3-core-method/lib/index.js:536:33)
    at Object.callback (./node_modules/web3-core-requestmanager/lib/index.js:305:9)
    at ./node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (./node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (./node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (./node_modules/websocket/lib/W3CWebSocket.js:234:14)
> 

```
`npm list | grep web3 └── web3@1.8.1`
