### ISSUE TITLE
Ropsten 1.x testing

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#5173]

**Comment by jdevcs** [comment]
Post merge ommers, ommersHash, difficulty and nonce will be set to 0, and these will not be removed.  https://eips.ethereum.org/EIPS/eip-3675#block-structure

- ommers:	[]

- ommersHash:	0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347	

- difficulty:	0	 

- nonce:	0x0000000000000000	

- mixHash: 0x0000000000000000000000000000000000000000000000000000000000000000

proof of stake does not naturally produce uncle blocks and there will be no POW so difficulty and nonce are  0.


In POS blocks mining time will be exactly 12 seconds, exception is when slot will be missed due to offline validator.


In POW there are always chances of re org and apps waits for several blocks to be mined on top of new block for treating it conformed. In POS there are finalized and safe block tags.

https://github.com/ChainSafe/web3.js/issues/5199

**Comment by jdevcs** [comment]
Tested 1.x Eth package on infura ropsten geth node (Geth/v1.10.18-omnibus-dcc34350) , and some observations  : 

`web3.eth.getUncle("latest", 0).then(console.log);`
//will return null

```
web3.eth.getBlockUncleCount("latest").then(console.log);
```
//will always be 0

`web3.eth.getWork().then(console.log);`
//Error: Returned error: no mining work available yet

**Comment by jdevcs** [comment]
This Ropsten node was not accepting `safe` tag. 

```
{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x407d73d8a49eeb85d32cf465507dd71d507100c1", "safe"],"id":1}
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32602,
        "message": "invalid argument 1: hex string without 0x prefix"
    }
}
```

**Comment by jdevcs** [comment]
This Ropsten node was  supporting `finalized`

```
{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x407d73d8a49eeb85d32cf465507dd71d507100c1", "finalized"],"id":1}

{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x565636a0e98e4000"
}
```

but web3.js error:

```
/tmp/web3ELCLMerge/node_modules/web3-utils/lib/utils.js:236
        throw new Error('Given input "' + value + '" is not a number.');
        ^

Error: Given input "finalized" is not a number.
    at Object.numberToHex (/tmp/web3ELCLMerge/node_modules/web3-utils/lib/utils.js:236:15)
    at inputBlockNumberFormatter (/tmp/web3ELCLMerge/node_modules/web3-core-helpers/lib/formatters.js:109:133)
    at Method.inputDefaultBlockNumberFormatter (/tmp/web3ELCLMerge/node_modules/web3-core-helpers/lib/formatters.js:90:12)
    at /tmp/web3ELCLMerge/node_modules/web3-core-method/lib/index.js:130:38
    at Array.map (<anonymous>)
    at Method.formatInput (/tmp/web3ELCLMerge/node_modules/web3-core-method/lib/index.js:128:32)
    at Method.toPayload (/tmp/web3ELCLMerge/node_modules/web3-core-method/lib/index.js:161:23)
    at Eth.send [as getBalance] (/tmp/web3ELCLMerge/node_modules/web3-core-method/lib/index.js:506:61)
    at Object.<anonymous> (/tmp/web3ELCLMerge/index.js:20:11)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by jdevcs** [comment]
https://github.com/ethereum/execution-apis/blob/773ffd230ae5cd037e32415855cf8d4f1e729b2d/src/schemas/block.yaml#L92

**Comment by jdevcs** [comment]
https://github.com/ethereum/execution-apis/blob/773ffd230ae5cd037e32415855cf8d4f1e729b2d/src/schemas/block.yaml#L92
