### ISSUE TITLE
contract.new.getData.apply(contract, params) fails

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/web3.js#522]
I need a way to get the contract creation data given an array of parameters. However, when I try I get an error. I think its because `getData` is bound to some non-exposed object. How can I accomplish? 

```
Warning: Cannot read property 'from' of undefined Use --force to continue.
TypeError: Cannot read property 'from' of undefined
    at inputCallFormatter (/Users/aakilfernandes/projects/safemarket/dapp/node_modules/grunt-solc-output-deploy/node_modules/web3/lib/web3/formatters.js:68:27)
    at /Users/aakilfernandes/projects/safemarket/dapp/node_modules/grunt-solc-output-deploy/node_modules/web3/lib/web3/method.js:89:28
    at Array.map (native)
    at Method.formatInput (/Users/aakilfernandes/projects/safemarket/dapp/node_modules/grunt-solc-output-deploy/node_modules/web3/lib/web3/method.js:88:32)
    at Method.toPayload (/Users/aakilfernandes/projects/safemarket/dapp/node_modules/grunt-solc-output-deploy/node_modules/web3/lib/web3/method.js:114:23)
    at Object.send (/Users/aakilfernandes/projects/safemarket/dapp/node_modules/grunt-solc-output-deploy/node_modules/web3/lib/web3/method.js:139:30)
```

**Comment by aakilfernandes** [comment]
And perhaps move away from "bind" all together?

http://stackoverflow.com/questions/14307264/what-object-javascript-function-is-bound-to-what-is-its-this

**Comment by aakilfernandes** [comment]
I believe this can be solved by adding `execute.solidityFunction = this`

https://github.com/ethereum/web3.js/blob/e4eb9606aa0aa10fd3eeb0a5e5d67c4fff43e814/lib/web3/function.js#L232-L244

**Comment by frozeman** [comment]
Could you give a proper example?
Also which version are you talking about? in both i don't know a `contract.new` function.

**Comment by frozeman** [comment]
I assume this issue is an old one. closing. Please reopen if its still an issue.
