### ISSUE TITLE
Error with contract creation using https

### ISSUE THREAD

**Issue by louisabraham** [ethereum/web3.js#525]
Hello,

I have a RPC server which I use with ncat to have SSL.
I have no problem with new or sendRawTransaction, but when I try and create a contract, with the new method or with a signed sendRawTransaction with my ncat, using the command (this is the greeter example) :

```
var greeter = greeterContract.new(_greeting,{from:web3.eth.accounts[0], data: greeterCompiled.greeter.code, gas: 1000000}, function(e, contract){
  if(!e) {

    if(!contract.address) {
      console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");

    } else {
      console.log("Contract mined! Address: " + contract.address);
      console.log(contract);
    }

  }
  else {console.log("error: "+e)}
})
```

I get the error : 
```
error: Error: Invalid JSON RPC response: "Error: socket hang up\n    at createHangUpError (_http_client.js:254:15)\n    at TLSSocket.socketOnEnd (_http_client.js:346:23)\n    at emitNone (events.js:91:20)\n    at TLSSocket.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"
```

If I try in a synchronous manner :
```
var greeter = greeterContract.new(_greeting,{from:web3.eth.accounts[0], data: greeterCompiled.greeter.code, gas: 1000000})
```

I get the error :

```
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/Users/louisabraham/node_modules/web3/lib/web3/errors.js:35:16)
    at HttpProvider.send (/Users/louisabraham/node_modules/web3/lib/web3/httpprovider.js:83:22)
    at RequestManager.send (/Users/louisabraham/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.send [as sendTransaction] (/Users/louisabraham/node_modules/web3/lib/web3/method.js:145:58)
    at ContractFactory.new (/Users/louisabraham/node_modules/web3/lib/web3/contract.js:216:33)
    at repl:1:34
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
```

I don't think ncat is the problem…

**Comment by louisabraham** [comment]
I don't know what was the matter, anyway it works now :) (just stumbled on this old issue now)
