### ISSUE TITLE
Calling sendSignedTransaction signed with ethereumjs-tx

### ISSUE THREAD

**Issue by IvoBiaus** [ethereum/web3.js#5372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `npm run start` (or `node index.js`), im getting:

```
(node:19079) UnhandledPromiseRejectionWarning: Error: Returned error: Cannot wrap a "object" as a json-rpc type
    at Object.ErrorResponse (/home/[...]/bcd-project-2/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/[...]/bcd-project-2/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /home/[...]/bcd-project-2/node_modules/web3-providers-http/lib/index.js:124:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior

When running `npm run start` (or `node index.js`), i should not get anything at the terminal, and the transaction should be sent.

### Steps to Reproduce

Global libraby: `ganache-cli v0.5.1`

Commands to run:
`npm i`
`npm run emule` // terminal 1
`npm run start` // terminal 2

Having the files:

` index.js`
```javascript
import Web3 from "web3";
import { Transaction } from "ethereumjs-tx";

// ganache-cli 0.5.1 localchain 
const url = "HTTP://127.0.0.1:8545";

const web3 = new Web3(url);

// User 0
const address0 = "0x99ac522be50ec92dc4b864a42f70bdef9b52e65c";
const address0PK =
  "71825efc84b47016a8357237938b3980c10ebf0d55fb9e7ff22c3cc25e495351";
const hexPK0 = Buffer.from(address0PK, "hex");

// User 1
const address1 = "0x4DbDb1a71fAc9aFBe07B0Fd1e861fcfbbd80EB45";

// Transaction
const rawTx = {
  nonce: Web3.utils.toHex(web3.eth.getTransactionCount(address0)),
  to: address1,
  gasPrice: Web3.utils.toHex(20000000),
  gasLimit: Web3.utils.toHex(30000),
  value: Web3.utils.toHex(1),
  data: 0x000,
  chainId: 1337,
};

const tx = new Transaction(rawTx);
tx.sign(hexPK0);

const serializedTx = tx.serialize();
web3.eth.sendSignedTransaction(serializedTx);

```

`package.json`
```json
{
  "name": "bcd-project-2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "emule": "ganache-cli --seed='ripple scissors kick mammal hire column oak again sun offer wealth tomorrow wagon turn fatal'"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ethereumjs-tx": "^2.1.2",
    "web3": "^1.7.5"
  },
  "type": "module"
}

```

### Web3.js Version

1.7.5

### Environment

- Operating System:  WSL2
- Browser: none?
- Node.js Version: 14.19.3
- NPM Version: 6.14.17

**Comment by Muhammad-Altabba** [comment]
Hello @IvoBiaus,
There are many async calls in your code that you should handle with `await` or `.then(...).catch(...)`. And one of them is `web3.eth.getTransactionCount(address0)`.
So, please update your code to fix those issues and then try again. If the problem still exists feel free to re-open this issue.

**Comment by IvoBiaus** [comment]
I have to re open a new one? or if i update the code as you asked its re-opened?
I did try what you said by the way, im still stuck with the same error, it has to be some kind of mistake in my side and not a bug, but i cannot see it, i asked in other places too, no one know how to get it to work so far.

**Comment by IvoBiaus** [comment]
well, in any case, i just re-open it here: https://github.com/ChainSafe/web3.js/issues/5376
