### ISSUE TITLE
Calling sendSignedTransaction signed with ethereumjs-tx (2)

### ISSUE THREAD

**Issue by IvoBiaus** [ethereum/web3.js#5376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `npm run start` (or `node index.js`), im getting:

```
> node index.js

1000000000000000000000
1000000000000000000000
(node:15979) UnhandledPromiseRejectionWarning: Error: Returned error: Cannot wrap a "object" as a json-rpc type
    at Object.ErrorResponse (/home/[...]/bcd-project-2/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/[...]/bcd-project-2/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /home/[...]/bcd-project-2/node_modules/web3-providers-http/lib/index.js:124:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15979) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15979) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior

When running `npm run start` (or `node index.js`), i should get the balances console.logs, and the transaction should be sent.

### Steps to Reproduce

Global library: `ganache-cli v0.5.1`

Commands to run:
`npm i`
`npm run emule` // terminal 1
`npm run start` // terminal 2

Having the files:

` index.js`
```javascript
import Web3 from "web3";
import { Transaction } from "ethereumjs-tx";

const url = "HTTP://127.0.0.1:8545";
const web3 = new Web3(url);

// User 0
const address0 = "0x99AC522bE50ec92Dc4b864a42F70BDeF9B52e65c";
const address0PK =
  "71825efc84b47016a8357237938b3980c10ebf0d55fb9e7ff22c3cc25e495351";
const hexPK0 = Buffer.from(address0PK, "hex");

// User 1
const address1 = "0x4DbDb1a71fAc9aFBe07B0Fd1e861fcfbbd80EB45";

// just to check network is working
web3.eth.getBalance(address0).then(console.log);
web3.eth.getBalance(address1).then(console.log);

// Transaction
const rawTx = {
  nonce: "0x0", // 0x0342
  to: address1,
  gasPrice: "0x20000000",
  gasLimit: "0x30000",
  value: "0x01",
  data: "0x000",
  chainId: 1337,
};

const tx = new Transaction(rawTx);
tx.sign(hexPK0);

const serializedTx = tx.serialize();
//const serializedTx = `0x${tx.serialize().toString("hex")}`;

web3.eth.sendSignedTransaction(serializedTx);
```

`package.json`
```json
{
  "name": "bcd-project-2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "emule": "ganache-cli --seed='ripple scissors kick mammal hire column oak again sun offer wealth tomorrow wagon turn fatal'"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ethereumjs-tx": "^2.1.2",
    "web3": "^1.7.5"
  },
  "type": "module"
}

```

### Web3.js Version

1.7.5

### Environment

- Operating System:  WSL2
- Browser: none?
- Node.js Version: 14.19.3
- NPM Version: 6.14.17

### Anything Else?

RPC server given by ganache-cli:

```
> ganache-cli --seed='ripple scissors kick mammal hire column oak again sun offer wealth tomorrow wagon turn fatal'

ganache v7.4.1 (@ganache/cli: 0.5.1, @ganache/core: 0.5.1)
Starting RPC server

Available Accounts
==================
(0) 0x99AC522bE50ec92Dc4b864a42F70BDeF9B52e65c (1000 ETH)
(1) 0x4DbDb1a71fAc9aFBe07B0Fd1e861fcfbbd80EB45 (1000 ETH)
(2) 0xaA7Bf399A14b02e9fe7f39d0b04bFA815AC627df (1000 ETH)
(3) 0x4Ec244718690004d433C9C24637366d09D537DDA (1000 ETH)
(4) 0xbd45035De85889Cc2e8c103075f8ad5eCa4895B1 (1000 ETH)
(5) 0x8e4B3E4611ADb025bc893A9D818FF22b6dd496B4 (1000 ETH)
(6) 0xF26a537Ef0829E834243aF63c7c80176758f2b0d (1000 ETH)
(7) 0xBd36f6c1EfE2f6f841A98cd1db2eade7f0997d77 (1000 ETH)
(8) 0xFe9Fad49BB678FA574A2546696706684Aa515460 (1000 ETH)
(9) 0x44B545528D447b6D9e17104dB41CFE727c127d6B (1000 ETH)

Private Keys
==================
(0) 0x71825efc84b47016a8357237938b3980c10ebf0d55fb9e7ff22c3cc25e495351
(1) 0x1caee51153d3511bad8264bed6f219cbb3e9dd28843eedfc53f24b5a37a0ee8c
(2) 0x9fe662ddda626466d35c2a2114821e0321be9349c143d4a04d7f3c48105e0558
(3) 0x1535a52769db7db1c75888ddfdd445c49364731ad467779bb34528938ca4510c
(4) 0x4a639e8dc357ef3ec2fbb86ed003d0d50ed26938383ccc6d3c31e4268ee29e9d
(5) 0x85fb2d2ef9eaab82bcce64bbb7561cab3974ab9f861f53aaeda92e854c7a361d
(6) 0xaf29652d09406a06fc940d7d7e5a22eb295389c528f8076082fe22b6559239e2
(7) 0xa70353675527dfe61cc7dad64e186e4d80a6b951bc69579498bef60229640905
(8) 0x6b0457012ea18ffec021daf8b8e4f7fbbf7401aab2a24a7747b3ceba24a34780
(9) 0xa46666471ae419d690a9da0b193ecdb51867d64bc9a5a81c48c91b515268cb5e

HD Wallet
==================
Mnemonic:      ranch shift foster cook giraffe loud phone fatigue process enough congress artist
Base HD Path:  m/44'/60'/0'/0/{account_index}

Default Gas Price
==================
2000000000

BlockGas Limit
==================
30000000

Call Gas Limit
==================
50000000

Chain Id
==================
1337

RPC Listening on 127.0.0.1:8545
```

**Comment by IvoBiaus** [comment]
nothing?

**Comment by RockyNiu** [comment]
~@IvoBiaus how did you resolve this?~

I found it. Use the latest version, it would throw the real error. `docker run --detach --publish 8545:8545 trufflesuite/ganache-cli:latest --accounts 10 --debug`
