### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by ravenflores** [ethereum/web3.js#5379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

D:\PROJECTS_JULY_2022\server\node_modules\web3-providers-ws\lib\index.js:260
        id = payload[0].id;
                        ^

TypeError: Cannot read properties of undefined (reading 'id')
    at WebsocketProvider.send (D:\PROJECTS_JULY_2022\server\node_modules\web3-providers-ws\lib\index.js:260:25)
    at RequestManager.sendBatch (D:\PROJECTS_JULY_2022\server\node_modules\web3-core-requestmanager\lib\index.js:177:66)
    at Batch.execute (D:\PROJECTS_JULY_2022\server\node_modules\web3-core-requestmanager\lib\batch.js:46:25)
    at D:\PROJECTS_JULY_2022\server\indexBSCs.js:70:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Expected Behavior

I'm trying to make a project that listen on all tx  per new block

I did subscribing for new blocks headers
make batch request the transactions hash list on blocks from getblock (blocks headers)
but it shows an error for long run
nothing comes to internet when I search on the issue
infura node has rps limit 
so I used a private node in batch request

I'm trying to make a monitoring tool per block

### Steps to Reproduce

var Web3 = require("web3");
var Web3s = require("web3");
var url = "<wss address>";
var url2 = "<wss address>";
var options = {
  timeout: 30000,
  clientConfig: {
    maxReceivedFrameSize: 100000000,
    maxReceivedMessageSize: 100000000,
  },
  reconnect: {
    auto: true,
    delay: 5000,
    maxAttempts: 15,
    onTimeout: false,
  },
};

### Web3.js Version

^1.7.4

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

thats it

**Comment by ravenflores** [comment]
![image](https://user-images.githubusercontent.com/66240114/186508081-cece94d1-cf49-40a0-8782-096000fc13e3.png)
works fine but dies in long run

**Comment by ravenflores** [comment]
I've fixed it now just some missing parameters request hehehe at call
