### ISSUE TITLE
Setting the provider at the constructor of `Contract` does not always work

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In some cases, setting the provider at the constructor of `Contract` does not work (possibly there are other related cases when setting it outside the constructor of `Contract`.

```
web3-eth-contract:       ProviderError: Provider not available. Use `.setProvider` or `.provider=` to initialize the provider.
web3-eth-contract:           at Web3RequestManager.<anonymous> (/home/maltabba/repos/web3v4.x/packages/web3-core/src/web3_request_manager.ts:153:10)
web3-eth-contract:           at Generator.next (<anonymous>)
web3-eth-contract:           at /home/maltabba/repos/web3v4.x/packages/web3-core/dist/web3_request_manager.js:8:71
web3-eth-contract:           at new Promise (<anonymous>)
web3-eth-contract:           at Object.<anonymous>.__awaiter (/home/maltabba/repos/web3v4.x/packages/web3-core/dist/web3_request_manager.js:4:12)
web3-eth-contract:           at Web3RequestManager._sendRequest (/home/maltabba/repos/web3v4.x/packages/web3-core/dist/web3_request_manager.js:95:16)
web3-eth-contract:           at Web3RequestManager.<anonymous> (/home/maltabba/repos/web3v4.x/packages/web3-core/src/web3_request_manager.ts:129:31)
web3-eth-contract:           at Generator.next (<anonymous>)
web3-eth-contract:           at /home/maltabba/repos/web3v4.x/packages/web3-core/dist/web3_request_manager.js:8:71
web3-eth-contract:           at new Promise (<anonymous>) {
web3-eth-contract:         code: 600
```

### Expected Behavior

To have the provider set with no errors.

### Steps to Reproduce

```
const addr = '0xbd0B4B009a76CA97766360F04f75e05A3E449f1E';
const abi = [
	{
		inputs: [
			{ internalType: 'address', name: 'addr', type: 'address' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'TestError1',
		type: 'error',
	},
	{
		inputs: [
			{ internalType: 'bool', name: 'pass', type: 'bool' },
			{ internalType: 'address', name: 'addr', type: 'address' },
			{ internalType: 'uint256', name: 'value', type: 'uint256' },
		],
		name: 'testError1',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'pure',
		type: 'function',
	},
] as const;
const contract = new Contract(abi, addr, {
	provider: 'https://ropsten.infura.io/v3/49a0efa3aaee4fd99797bfa94d8ce2f1',
});
The following like makes it work!
// contract.setProvider('https://ropsten.infura.io/v3/49a0efa3aaee4fd99797bfa94d8ce2f1');

await contract.methods.testError1(false, addr, 42).call(sendOptions);
```

### Web3.js Version

4.x

**Comment by Muhammad-Altabba** [comment]
I could confirm that the issue still exists.
