### ISSUE TITLE
Contract instantiated with `Web3Context` should update when `.link` is used on plugin

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5492]
The following code should be sufficient enough for linking the `Web3Context` needed for an instance of `Contract`

```typescript
export class ChainlinkPlugin extends Web3PluginBase {
	public pluginNamespace = 'chainlink';

	protected readonly _contract: Contract<typeof AggregatorV3InterfaceABI>;

	public constructor(abi: ContractAbi, address: Address) {
		super();
		this._contract = new Contract(abi, address, this); // NOTE this is referring to the Web3Context inherited from Web3PluginBase
	}

	public async getPrice() {
		return this._contract.methods.latestRoundData().call() as unknown as Promise<Price>;
	}
}
```

but instead when calling the `getPrice` method we get the error

```bash
ProviderError: Provider not available. Use `.setProvider` or `.provider=` to initialize the provider.

      157 |
      158 | 		if (isNullish(provider)) {
    > 159 | 			throw new ProviderError(
          | 			      ^
      160 | 				'Provider not available. Use `.setProvider` or `.provider=` to initialize the provider.',
      161 | 			);
      162 | 		}

      at Web3RequestManager.<anonymous> (../web3-core/src/web3_request_manager.ts:159:10)
      at ../web3-core/dist/web3_request_manager.js:8:71
      at Object.<anonymous>.__awaiter (../web3-core/dist/web3_request_manager.js:4:12)
      at Web3RequestManager._sendRequest (../web3-core/dist/web3_request_manager.js:95:16)
      at Web3RequestManager.<anonymous> (../web3-core/src/web3_request_manager.ts:135:31)
      at ../web3-core/dist/web3_request_manager.js:8:71
```

It would be expected that when the user does the following

```typescript
const web3 = new Web3('http://127.0.0.1:8545');
web3.registerPlugin(new ChainlinkPlugin(AggregatorV3InterfaceABI, aggregatorAddress));
const price = await web3.chainlink.getPrice();
```

`web3.registerPlugin` should set the configured `requestManager` (using the `provider` `'http://127.0.0.1:8545'`) for the `ChainlinkPlugin` instance which should update the context for the `Contract` instance that was passed `this` in the `ChainlinkPlugin` constructor

**Comment by Spacesai1or** [comment]
So the reason why

```typescript
this._contract = new Contract(abi, address, this);
```

is not enough to set the provider of `this._contract`'s `requestManager` is because when the `Contract` instance is instantiated and passed `this` (`this` is referring to the `Web3Context` that is apart of `ContractMethodWrappersPlugin`) `this.requestManager.provider` is `undefined` because when the user does:

```typescript
web3 = new Web3('http://127.0.0.1:8545');
web3.registerPlugin(new ContractMethodWrappersPlugin(ERC20TokenAbi, contractAddress));
```

the provider (in this case `'http://127.0.0.1:8545'`) is not set for the instance of `ContractMethodWrappersPlugin` until `registerPlugin` is executed which is happening **after** the execution of `ContractMethodWrappersPlugin`'s constructor (which instantiates `Contract`). Hence why overriding `Web3Context`'s `link` method like so:

```typescript
public link(parentContext: Web3Context) {
    super.link(parentContext);
    this._contract.link(parentContext);
}
```

solves the issue because [link](https://github.com/web3/web3.js/blob/7b7e5b0088340b84375ffa842a1f513550ee26a6/packages/web3-core/src/web3_context.ts#L222-L223) gets called as a part of `registerPlugin` and `this._contract` will be given `web3`'s `requestManager` and `provider`.

I think there is a way to solve this so that when a `Contract` instance is given a `Web3Context` it treats it as a pointer instead of [spreading the Web3Context object](https://github.com/web3/web3.js/blob/7b7e5b0088340b84375ffa842a1f513550ee26a6/packages/web3-eth-contract/src/contract.ts#L379-L383), but I wasn't able to easily accomplish this. The refactoring started to get out of hand and I'm deeming it not worth the risk of unintended side effects by refactoring so much code when there's a readily available fix (overriding the `link` method within the plugin). Perhaps it'll be worth revisiting this if we'd like to not force the plugin authors to have to override the `link` method when using web3 packages that require the `Web3Context` within their plugins
