### ISSUE TITLE
Add support for `newPendingTransactions` new subscription type

### ISSUE THREAD

**Issue by geomad** [ethereum/web3.js#5548]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

go-ethereum added a new type of `newPendingTransactions` subscription that returns the full transaction instead of the hash if an additional argument is provided. Please check https://github.com/ethereum/go-ethereum/commit/5b1a04b9c749d804b51159fe12246c56de8515c1

Right now the subscription throws as it fails validation
```
Error: Invalid number of parameters for "undefined". Got 1 expected 0!
    at Object.InvalidNumberOfParams (C:\web3\node_modules\web3-core-helpers\lib\errors.js:33:16)
    at Subscription._validateArgs (C:\web3\node_modules\web3-core-subscriptions\lib\subscription.js:70:22)
    at Subscription._toPayload (C:\web3\node_modules\web3-core-subscriptions\lib\subscription.js:123:14)
    at Subscription.subscribe (C:\web3\node_modules\web3-core-subscriptions\lib\subscription.js:160:24)
    at Eth.subscribe (C:\web3\web3-core-subscriptions\lib\index.js:55:39)
```

### Expected Behavior

New subscription type is supported

### Steps to Reproduce

```
    let sub = web3.eth.subscribe('newPendingTransactions', true, async function (error, result) {
        console.log(result)
    })
```

### Web3.js Version

1.8.0

### Environment

- Node.js Version: v18.10.0

**Comment by geomad** [comment]
There is an update in geth, now the method returns RPC transactions type, filling in sender and chainid aswell.
https://github.com/ethereum/go-ethereum/commit/8c5ce1107b3110c7cb735d8dfa91c9c701393c85
