### ISSUE TITLE
[4.x] Transaction sending does not work with Ganache's EthereumProvider

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/web3.js#5591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Runtime error about missing method
```
/home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/dist/utils/reject_if_block_timeout.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
TypeError: provider.supportsSubscriptions is not a function
    at /home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/src/utils/reject_if_block_timeout.ts:169:12
    at Generator.next (<anonymous>)
    at fulfilled (/home/mpetrunic/Projects/ChainSafe/@web3.js/repro/ganache-provider/node_modules/web3-eth/dist/utils/reject_if_block_timeout.js:5:58)
```

### Expected Behavior

Should work.
Probably this: https://github.com/web3/web3.js/blob/4.x/packages/web3-eth/src/utils/reject_if_block_timeout.ts#L169
should not expect every provider to have this method.

### Steps to Reproduce

```typescript
import Web3 from "web3"
import {LegacySendProvider} from "web3-types"
import ganache from "ganache";

(async function() {
    const LOCAL_PREFUNDED_MNEMONIC =
  "pioneer casual canoe gorilla embrace width fiction bounce spy exhibit another dog";
    
    const server = ganache.server({
        wallet: {
            mnemonic: LOCAL_PREFUNDED_MNEMONIC,
            defaultBalance: 100,
        },
    });
    const provider = server.provider;

    const web3 = new Web3(provider as LegacySendProvider)

    const accounts = await web3.eth.getAccounts();

    await web3.eth.sendTransaction({to: accounts[1], from: accounts[0], value: "100000"})
})()
```

### Web3.js Version

4.0.1-alpha.1

### Environment

- Operating System: 
- Browser: 
- Node.js Version: 
- NPM Version: 

### Anything Else?

#5309 would detect those things.

**Comment by jdevcs** [comment]
https://github.com/web3/web3.js/pull/5652/files#diff-56116a720b3243384a647da52d1409a56641aeb8a0b6e2e31d833589de814f8e 

Is it fixed in this ?

**Comment by mpetrunic** [comment]
Yes
