### ISSUE TITLE
Sometimes the test `contract › deploy › should emit the "transactionHash" event` timeout

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#5634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes the test `contract › deploy › should emit the "transactionHash" event` timeout at the pipeline.

1. I tried to increase the timeout from 35 seconds to 60 seconds. But still, it fails sometimes. This indicates that the issue is not related to how long we wait. It seems that under some conditions the event, that is waited, never happens, no matter how long the test waits.

### Expected Behavior

To have the test pass all the times

### Steps to Reproduce

https://github.com/web3/web3.js/actions/runs/3490273003/jobs/5841670011 

### Web3.js Version

4.x

### Environment

At the pipeline

**Comment by luu-alex** [comment]
Very similar error also occuring in contract > deploy > should emit the "confirmation" event
```
web3-eth-contract: FAIL test/integration/contract_deploy.test.ts (42.474 s)
[680](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:681)
web3-eth-contract:   ● contract › deploy › should emit the "confirmation" event
[681](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:682)
web3-eth-contract:     thrown: "Exceeded timeout of 35000 ms for a test.
[682](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:683)
web3-eth-contract:     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
[683](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:684)
web3-eth-contract:       147 | 		});
[684](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:685)
web3-eth-contract:       148 |
[685](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:686)
web3-eth-contract:     > 149 | 		it('should emit the "confirmation" event', async () => {
[686](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:687)
web3-eth-contract:           | 		^
[687](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:688)
web3-eth-contract:       150 | 			const confirmationHandler = jest.fn();
[688](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:689)
web3-eth-contract:       151 |
[689](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:690)
web3-eth-contract:       152 | 			await contract
[690](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:691)
web3-eth-contract:       at test/integration/contract_deploy.test.ts:149:3
[691](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:692)
web3-eth-contract:       at test/integration/contract_deploy.test.ts:32:2
[692](https://github.com/web3/web3.js/actions/runs/3914282982/jobs/6691242140#step:4:693)
web3-eth-contract:       at Object.<anonymous> (test/integration/contract_deploy.test.ts:31:1)
```
