### ISSUE TITLE
getTransactionReceipt: Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by mishabunte** [ethereum/web3.js#5672]
@nikoulai error appears again on web3@1.8.1 when I am trying to get receipt for a specific transaction on goerli network, i suppose it's because of this transaction huge fee at 6,764.3 eth

https://goerli.etherscan.io/tx/0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d

Solution:
```bash
> vi +207 ./node_modules/web3-utils/lib/utils.js
```
```javascript
207     //return toBN(value).toNumber();                                            
208     return toBN(value).toString();             

```

log
```
> var goerli = new Web3('ws://localhost:40002');
undefined
> t = '0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
'0x2e9c7587a80d33e801ad76b62e3c27f1f263955e02f870e6c01b3ad4b0b4aa3d'
> await goerli.eth.getTransactionReceipt(t)
Uncaught Error: Number can only safely store up to 53 bits
    at assert (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (./node_modules/web3-utils/lib/utils.js:207:24)
    at Method.outputTransactionReceiptFormatter [as outputFormatter] (./node_modules/web3-core-helpers/lib/formatters.js:246:47)
    at Method.formatOutput (./node_modules/web3-core-method/lib/index.js:148:54)
    at sendTxCallback (./node_modules/web3-core-method/lib/index.js:536:33)
    at Object.callback (./node_modules/web3-core-requestmanager/lib/index.js:305:9)
    at ./node_modules/web3-providers-ws/lib/index.js:114:45
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage (./node_modules/web3-providers-ws/lib/index.js:102:69)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (./node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (./node_modules/websocket/lib/W3CWebSocket.js:234:14)
> 

```
`npm list | grep web3 └── web3@1.8.1`

_Originally posted by @mishabunte in https://github.com/web3/web3.js/issues/5153#issuecomment-1332831732_

**Comment by Spacesai1or** [comment]
Hi there, thank you for bringing this to our attention!

**Comment by luu-alex** [comment]
Hi there, thank you for submitting this issue. I just tried the exact same code and got the same error on the goerli network.
To fix this, make sure to specify `hex` in the second parameter.
`await Web3.eth.getTransactionReceipt(t,'hex')` 
Hope this helps, if you run into any other issue feel free to comment and ill reopen this.

**Comment by anthony-zhan** [comment]
Got the same error on polygon when using `web3@1.8.1`. 

And `getTransactionReceipt` doesn't support `string` as its second parameter, according  to the TypeScript function signature. cc @luu-alex 

```ts
// node_modules/web3-eth/types/index.d.ts 
    getTransactionReceipt(
        hash: string,
        callback?: (
            error: Error,
            transactionReceipt: TransactionReceipt
        ) => void
    ): Promise<TransactionReceipt>;
```

Sample code that throws the error when fetching receipt for hash `0xa2cc703cecbff27465914bbb36e7cda1b217026853efbe2c91d1a59e43fb2d21`.

```ts
import Web3 from "web3";

const polygon_rpc_url = "https://polygon-rpc.com/";
const web3 = new Web3(polygon_rpc_url);

const receipt = await web3.eth.getTransactionReceipt(
  '0xa2cc703cecbff27465914bbb36e7cda1b217026853efbe2c91d1a59e43fb2d21'
);
console.log(receipt);
```

Error log
```
./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
                    ^
Error: Number can only safely store up to 53 bits
    at assert (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (./node_modules/number-to-bn/node_modules/bn.js/lib/bn.js:506:7)
    at Object.hexToNumber (./node_modules/web3-utils/lib/utils.js:207:24)
    at Method.outputTransactionReceiptFormatter [as outputFormatter] (./node_modules/web3-core-helpers/lib/formatters.js:246:47)
    at Method.formatOutput (./node_modules/web3-core-method/lib/index.js:148:54)
    at sendTxCallback (./node_modules/web3-core-method/lib/index.js:536:33)
    at ./node_modules/web3-core-requestmanager/lib/index.js:305:9
    at ./node_modules/web3-providers-http/lib/index.js:127:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Could help to take a look again?

Many thanks.

**Comment by nikoulai** [comment]
> To fix this, make sure to specify `hex` in the second parameter.
> `await Web3.eth.getTransactionReceipt(t,'hex')`

Hi there @anthony-zhan 
Could you please pas `hex` as the second parameter and try again?
```ts
await Web3.eth.getTransactionReceipt(tx,'hex')
```

**Comment by anthony-zhan** [comment]
Hi @nikoulai , it doesn't work for TypeScript.  It will raise the compile error as below
```
❯ npx ts-node src/index.ts
./node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:10:126 - error TS2345: Argument of type 'string' is not assignable to parameter of type '(error: Error, transactionReceipt: TransactionReceipt) => void'.

10   const receipt = await web3.eth.getTransactionReceipt('0xa2cc703cecbff27465914bbb36e7cda1b217026853efbe2c91d1a59e43fb2d21', 'hex');
                                                                                                                                ~~~~~

    at createTSError (./node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (./node_modules/ts-node/src/index.ts:863:19)
    at getOutput (./node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (./node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (./node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2345 ]
}

```
