### ISSUE TITLE
Unable to use `4.x` packages in browser tests for `web3.js-plugin-chainlink`

### ISSUE THREAD

**Issue by Spacesai1or** [ethereum/web3.js#5706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to execute [this browser test](https://github.com/ChainSafe/web3.js-plugin-chainlink/pull/9/files#diff-e50296399d3fc48af8a3130f090d1d7fe8ccd18de2103f095c835fce2b63a040) for `web3.js-plugin-chainlink`, the following error is received:

When running in electron environment:

```bash
web3.js-chainlink-plugin$ yarn test:e2e:electron
yarn run v1.22.19
warning ../../../../../package.json: No license field
$ npx cypress run --headless --browser electron

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        11.2.0                                                                         │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v18.12.1 (/home/anon/.nvm/versions/node/v18.12.1/bin/node)                     │
  │ Specs:          1 found (chainlink_plugin.test.ts)                                             │
  │ Searched:       test/e2e/**/**/*.test.ts                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  chainlink_plugin.test.ts                                                        (1 of 1)


  1) An uncaught error was detected outside of a test

  0 passing (50ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read properties of undefined (reading 'isHexStrict')

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at ./node_modules/web3-utils/dist/validation.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-utils/dist/validation.js:6:19)
      at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
      at ./node_modules/web3-utils/dist/index.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-utils/dist/index.js:31:13)
      at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
      at ./node_modules/web3-core/dist/web3_config.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-core/dist/web3_config.js:5:21)
      at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
      at ./node_modules/web3-core/dist/index.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-core/dist/index.js:30:13)
      at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
      at ./test/e2e/chainlink_plugin.test.ts (webpack://@chainsafe/web3.js-chainlink-plugin/./test/e2e/chainlink_plugin.test.ts:2:0)
      at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     chainlink_plugin.test.ts                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  chainlink_plugin.test.ts                  49ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                      49ms        1        -        1        -        -  

error Command failed with exit code 1.

```

When running in Firefox environment:

```bash
web3.js-chainlink-plugin$ yarn test:e2e:firefox
yarn run v1.22.19
warning ../../../../../package.json: No license field
$ npx cypress run --headless --browser firefox

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        11.2.0                                                                         │
  │ Browser:        Firefox 107 (headless)                                                         │
  │ Node Version:   v18.12.1 (/home/anon/.nvm/versions/node/v18.12.1/bin/node)                     │
  │ Specs:          1 found (chainlink_plugin.test.ts)                                             │
  │ Searched:       test/e2e/**/**/*.test.ts                                                       │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  chainlink_plugin.test.ts                                                        (1 of 1)


  1) An uncaught error was detected outside of a test

  0 passing (48ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > web3_validator_1 is undefined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
  at ./node_modules/web3-utils/dist/validation.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-utils/dist/validation.js:6:0)
  at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
  at ./node_modules/web3-utils/dist/index.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-utils/dist/index.js:31:13)
  at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
  at ./node_modules/web3-core/dist/web3_config.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-core/dist/web3_config.js:5:29)
  at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
  at ./node_modules/web3-core/dist/index.js (webpack://@chainsafe/web3.js-chainlink-plugin/./node_modules/web3-core/dist/index.js:30:13)
  at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
  at ./test/e2e/chainlink_plugin.test.ts (webpack://@chainsafe/web3.js-chainlink-plugin/./test/e2e/chainlink_plugin.test.ts:2:0)
  at __webpack_require__ (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/bootstrap:19:0)
  at <unknown> (webpack://@chainsafe/web3.js-chainlink-plugin/webpack/startup:4:0)
  at <unknown> (http://localhost:38767/__cypress/tests?p=test/e2e/chainlink_plugin.test.ts:73636:12)
  at ../driver/src/cypress/script_utils.ts/evalScripts (http://localhost:38767/__cypress/runner/cypress_runner.js:165963:23)
  at tryCatcher (http://localhost:38767/__cypress/runner/cypress_runner.js:11327:23)
  at gotValue (http://localhost:38767/__cypress/runner/cypress_runner.js:10469:18)
  at gotAccum (http://localhost:38767/__cypress/runner/cypress_runner.js:10458:25)
  at tryCatcher (http://localhost:38767/__cypress/runner/cypress_runner.js:11327:23)
  at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromiseFromHandler (http://localhost:38767/__cypress/runner/cypress_runner.js:9262:31)
  at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise (http://localhost:38767/__cypress/runner/cypress_runner.js:9319:18)
  at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromise0 (http://localhost:38767/__cypress/runner/cypress_runner.js:9364:10)
  at ../../node_modules/bluebird/js/release/promise.js/</module.exports/Promise.prototype._settlePromises (http://localhost:38767/__cypress/runner/cypress_runner.js:9444:18)
  at _drainQueueStep (http://localhost:38767/__cypress/runner/cypress_runner.js:6034:12)
  at _drainQueue (http://localhost:38767/__cypress/runner/cypress_runner.js:6027:24)
  at ../../node_modules/bluebird/js/release/async.js/</Async.prototype._drainQueues (http://localhost:38767/__cypress/runner/cypress_runner.js:6043:16)
  at ../../node_modules/bluebird/js/release/async.js/</Async/this.drainQueues (http://localhost:38767/__cypress/runner/cypress_runner.js:5913:14)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     chainlink_plugin.test.ts                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  chainlink_plugin.test.ts                  43ms        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                      43ms        1        -        1        -        -  

error Command failed with exit code 1.
```

### Expected Behavior

The tests would pass

### Steps to Reproduce

1. `git clone git@github.com:ChainSafe/web3.js-plugin-chainlink.git`
2. `git checkout -b wyatt/7-init-browser-tests`
3. `yarn`
4. `yarn test:e2e:electron`
5. `yarn test:e2e:firefox`

### Web3.js Version

4.0.1-alpha.2

### Environment

- Operating System: `Ubuntu`
- Browser: `electron` and `firefox`
- Node.js Version: `v18.12.1`
- NPM Version: `8.19.2`

### Anything Else?

I can replicate the issue when publishing the packages to a local NPM registry **if** I run the `yarn build:web` script before publishing all the web3 packages. Publishing the packages to the local registry without running `yarn build:web`, and then running through the reproduction steps mentioned above yields passing tests

**Comment by jdevcs** [comment]
Renaming minified build from `index.min.js` to some other name in web3-validator fixes the issue. https://github.com/web3/web3.js/blob/6c166b9fbfeab4c8f6467cd9b8aefe40bc001df8/packages/web3-validator/webpack.config.js#L20

**Comment by jdevcs** [comment]
I was also able to reproduce your issue with alpha.3 as shared on slack, but [with this renamed](https://github.com/web3/web3.js/blob/c2a845747032bfb22492f22634f0644b4774ecf9/packages/web3-validator/webpack.config.js#L22) to :
```
module.exports = getWebPackConfig(
    __dirname,
    'web3-validator-web.min.js',
    'web3-validator-web',
    'src/index.ts',
);
```
Plugin browser tests pass.
Seems current minified build of validator interferes with  https://github.com/web3/web3.js/blob/4.x/packages/web3-validator/src/web3_validator.ts file.

Pls can you check this fix on your local sys as well .
