### ISSUE TITLE
1.8.2 Rc.0 tests

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#5760]
Syntherix tests are failing as [reported](https://github.com/web3/web3.js/pull/5740#issuecomment-1379427607) by @luu-alex :
This should be investigated before release. 
```
  3) Contract: EtherCollateral
       when opening a Loan
         when creating multiple loans
           then opening & closing from 10 different accounts:
     Uncaught Error: no matching function (argument="sighash", value="0x", code=INVALID_ARGUMENT, version=abi/5.0.12)
      at Logger.makeError (node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:205:28)
      at Logger.throwError (node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:217:20)
      at Logger.throwArgumentError (node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:221:21)
      at Interface.getFunction (node_modules/ethers/node_modules/@ethersproject/abi/src.ts/interface.ts:186:20)
      at Contract.contract._smockit (node_modules/@eth-optimism/smock/src/smockit/smockit.ts:101:31)
      at VM.<anonymous> (node_modules/@eth-optimism/smock/src/smockit/binding.ts:77:43)
      at /Users/alexluu/synthetix/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:48:12
      at /Users/alexluu/synthetix/node_modules/async/internal/withoutIndex.js:9:16
      at replenish (node_modules/async/internal/eachOfLimit.js:66:17)
      at /Users/alexluu/synthetix/node_modules/async/internal/eachOfLimit.js:71:9
      at eachLimit (node_modules/async/eachLimit.js:43:36)
      at /Users/alexluu/synthetix/node_modules/async/internal/doLimit.js:9:16
      at VM.AsyncEventEmitter.emit (node_modules/async-eventemitter/lib/AsyncEventEmitter.js:42:3)
      at node:internal/util:364:7
      at new Promise (<anonymous>)
      at VM.bound  [as _emit] (node:internal/util:350:12)


  9) Contract: EtherCollateral
       when opening a Loan
         when creating multiple loans
           then opening & closing from 10 different accounts:
     done() called multiple times in test <Contract: EtherCollateral when opening a Loan when creating multiple loans then opening & closing from 10 different accounts> of file /Users/alexluu/synthetix/test/contracts/EtherCollateral.js; in addition, done() received error: Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
    at Context.<anonymous> (/Users/alexluu/synthetix/test/contracts/EtherCollateral.js:1010:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  receipt: undefined,
  hijackedStack: 'Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!\n' +
    '    at Object.TransactionError (/Users/alexluu/synthetix/node_modules/web3-core-helpers/lib/errors.js:87:21)\n' +
    '    at /Users/alexluu/synthetix/node_modules/@truffle/interface-adapter/node_modules/web3-core-method/lib/index.js:417:49\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
  Error: done() called multiple times in test <Contract: EtherCollateral when opening a Loan when creating multiple loans then opening & closing from 10 different accounts> of file /Users/alexluu/synthetix/test/contracts/EtherCollateral.js; in addition, done() received error: Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
      at Context.<anonymous> (test/contracts/EtherCollateral.js:1010:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    receipt: undefined,
    hijackedStack: 'Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!\n' +
      '    at Object.TransactionError (/Users/alexluu/synthetix/node_modules/web3-core-helpers/lib/errors.js:87:21)\n' +
      '    at /Users/alexluu/synthetix/node_modules/@truffle/interface-adapter/node_modules/web3-core-method/lib/index.js:417:49\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  }
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  10) Contract: SynthetixState
       lastDebtLedgerEntry()
         should correctly report lastDebtLedgerEntry:
     AssertionError: expected 'Transaction reverted without a reason' to include 'invalid opcode'
      at Object.assertInvalidOpcode [as invalidOpcode] (test/utils/index.js:497:11)
      at Context.<anonymous> (test/contracts/SynthetixState.js:166:4)
```

**Comment by Muhammad-Altabba** [comment]
When I run the tests, I got only one error (that could be just because the tests take a long time)

>   4435 passing (43m)
  71 pending
  1 failing

```
  1) Contract: SupplySchedule
       functions and modifiers
         Given inflation amount of 800,000 - mintable supply
           should calculate the mintable supply as 0 within 1st week of inflation start date:
     Error: Time parameter (Thu Mar 07 2019 05:00:00 GMT+0100 (Central European Standard Time)) is less than now Thu Mar 07 2019 05:10:51 GMT+0100 (Central European Standard Time). You can only fast forward to times in the future.
      at fastForwardTo (test/utils/index.js:111:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/contracts/SupplySchedule.js:205:5)
      
```

**Comment by Muhammad-Altabba** [comment]
However, there is another error that came just 1 time out of many runs. And it is a timeout error as below:

> 4380 passing (3h)
  71 pending
  2 failing

```
  1) Contract: Exchanger (spec tests)
       With Direct Integration overrides configuration (Synthetix, ExchangerWithFeeRecAlternatives, ExchangeRatesWithDexPricing)
         "before each" hook for "when called with a synth with no rate (i.e. 0), returns true":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/maltabba/repos/synthetix/test/contracts/Exchanger.spec.js)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) Contract: SupplySchedule
       functions and modifiers
         Given inflation amount of 800,000 - mintable supply
           should calculate the mintable supply as 0 within 1st week of inflation start date:
     Error: Time parameter (Thu Mar 07 2019 05:00:00 GMT+0100 (Central European Standard Time)) is less than now Thu Mar 07 2019 05:09:56 GMT+0100 (Central European Standard Time). You can only fast forward to times in the future.
      at fastForwardTo (test/utils/index.js:111:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Context.<anonymous> (test/contracts/SupplySchedule.js:206:5)
```

And this happens whether updating to `1.8.2-rc.0` or keepet using the version already used by Syntherix (web3 v`1.7.0`).

**Comment by luu-alex** [comment]
Looked into it, made a comment on the 1.8.2-rc page https://github.com/web3/web3.js/pull/5740#issuecomment-1397291006 
Will be closing as these issues are not coming from any new code merges.
