### ISSUE TITLE
Error value out of range when decoding Transfer event

### ISSUE THREAD

**Issue by longhoangwkm** [ethereum/web3.js#5762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
null: value out of range (argument="value", value=20, code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at hexZeroPad (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/bytes/src.ts/index.ts:323:16)
    at AddressCoder.decode (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/abi/src.ts/coders/address.ts:28:37)
    at /Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/abi/src.ts/coders/array.ts:108:31
    at Array.forEach (<anonymous>)
    at unpack (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/abi/src.ts/coders/array.ts:89:12)
    at TupleCoder.decode (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:58:47)
    at AbiCoder.decode (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:118:22)
    at ABICoder.decodeParametersWith (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/web3-eth-abi/lib/index.js:310:30)
    at ABICoder.decodeParameters (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/web3-eth-abi/lib/index.js:291:17)
    at ABICoder.decodeParameter (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/web3-eth-abi/lib/index.js:280:17)
    at /Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/web3-eth-abi/lib/index.js:348:25
    at Array.forEach (<anonymous>)
    at ABICoder.decodeLog (/Users/tobi/Projects/avacuscc/avacuscc-events-mq/node_modules/web3-eth-abi/lib/index.js:344:12) {
  reason: 'value out of range',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: 20,
  baseType: 'address',
  type: 'address'
}
```

### Expected Behavior

Return event json payload

### Steps to Reproduce

```typescript
import Web3EthAbi from 'web3-eth-abi';

async function main() {
  const log = {
    address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000009b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7',
      '0x0000000000000000000000007445de16041026093421a1dc70a19f8a71b22226'
    ],
    data: '0x000000000000000000000000000000000000000000000000000000004f60e768',
    blockNumber: 38147130,
    transactionHash: '0x545e88a896dd3190436ecb13e85e082a9bf98345863cd68835c03a61cba406f1',
    transactionIndex: 0,
    blockHash: '0xb90685d01cf70c02b9071a69927a292eb2394f68762a3bee4cecf64e260497f9',
    logIndex: 0,
    removed: false,
    id: 'log_b4dc3ba4'
  };

  const eventABI = {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      }
    ],
    "name": "Transfer",
    "type": "event"
  };

  const payload = Web3EthAbi.decodeLog(
       eventABI.inputs,
       log.data,
       log.topics,
  );
  console.log(payload);
}
main().catch((error) => {
  console.log(error);
});

```

### Web3.js Version

1.8.0

### Environment

- Operating System: Mac OS
- Browser: 
- Node.js Version: v16.16.0
- NPM Version: 8.11.0

**Comment by longhoangwkm** [comment]
Oh, I upgraded to version `v4` and error has gone

**Comment by longhoangwkm** [comment]
But I still wanna use 1.x version due to required project

**Comment by Muhammad-Altabba** [comment]
Thanks @longhoangwkm for opening the issue.
Actually, I tried the code and the error start to come in version `1.2.8-rc.0` and all the later versions of 1.x. However, the latest version where this issue was not present is `1.2.7`. 
We will investigate this issue further. And in the meantime, if you could not upgrade to v4.x. You may try to downgrade to version `1.2.7`.

**Comment by Muhammad-Altabba** [comment]
I debugged the error and detected that the issue seems to be because of incorrect data provided for the first topic. The provided data is `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef` but I think it should be something like the second topic that also represents an address. I tried replacing it with the following:  `0x000000000000000000000000fc378daa952ba7f163c4a11628f55a4df523b3ef`. And the error is no longer present and the code output is as follows:
```shell
{
  '0': '0xFC378dAA952ba7f163c4a11628f55a4df523b3EF',
  '1': '0x9B08288C3Be4F62bbf8d1C20Ac9C5e6f9467d8B7',
  '2': '1331750760',
  __length__: 3,
  from: '0xFC378dAA952ba7f163c4a11628f55a4df523b3EF',
  to: '0x9B08288C3Be4F62bbf8d1C20Ac9C5e6f9467d8B7',
  value: '1331750760'
}
```

So, could you please tell me whether the value `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef` was mistakenly written or if it was read by another code (in this case please share that code with the full context)?   

Thanks,

**Comment by longhoangwkm** [comment]
That is correct event log. The first one is signature of function (sha3 of Transfer event )
topic['event signature', 'address from', 'address to'], data: 'amount' (because amount is no index)

I will attach code to get log soon

**Comment by Muhammad-Altabba** [comment]
> That is correct event log. The first one is signature of function (sha3 of Transfer event ) topic['event signature', 'address from', 'address to'], data: 'amount' (because amount is no index)
> 
> I will attach code to get log soon

Thanks @longhoangwkm, 
Waiting for your code.

**Comment by longhoangwkm** [comment]
Hi, I attached code how can get the log

```js
import Web3 from 'web3';

async function main() {
  const web3 = new Web3(new Web3.providers.HttpProvider('https://rpc.ankr.com/polygon'));
  const fromBlockHex = '0x' + 38147130..toString(16);
  const toBlockHex = '0x' + 38147130..toString(16);
  const transferEventTopic = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
  const filters = {
    fromBlock: fromBlockHex,
    toBlock: toBlockHex,
    topics: [[transferEventTopic]],
  }
  // console.info(filters);
  const logs = await web3.eth.getPastLogs(filters);
  for (const log of logs) {
    if (log['transactionHash'] === '0x545e88a896dd3190436ecb13e85e082a9bf98345863cd68835c03a61cba406f1') {
      console.log(log);
    }
  }
}
main().catch((error) => {
  console.log(error);
});
```

Outputs:
```
{
  address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
  topics: [
    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    '0x0000000000000000000000009b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7',
    '0x0000000000000000000000007445de16041026093421a1dc70a19f8a71b22226'
  ],
  data: '0x000000000000000000000000000000000000000000000000000000004f60e768',
  blockNumber: 38147130n,
  transactionHash: '0x545e88a896dd3190436ecb13e85e082a9bf98345863cd68835c03a61cba406f1',
  transactionIndex: 0n,
  blockHash: '0xb90685d01cf70c02b9071a69927a292eb2394f68762a3bee4cecf64e260497f9',
  logIndex: 0n,
  removed: false
}
{
  address: '0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270',
  topics: [
    '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
    '0x0000000000000000000000007445de16041026093421a1dc70a19f8a71b22226',
    '0x0000000000000000000000009b08288c3be4f62bbf8d1c20ac9c5e6f9467d8b7'
  ],
  data: '0x000000000000000000000000000000000000000000000048a6e92d302d489fbb',
  blockNumber: 38147130n,
  transactionHash: '0x545e88a896dd3190436ecb13e85e082a9bf98345863cd68835c03a61cba406f1',
  transactionIndex: 0n,
  blockHash: '0xb90685d01cf70c02b9071a69927a292eb2394f68762a3bee4cecf64e260497f9',
  logIndex: 1n,
  removed: false
}
```

**Comment by mconnelly8** [comment]
@longhoangwkm, we checked with our latest v4 production release and this isn't an issue.  We suggest upgrading to that.

https://docs.web3js.org/
https://docs.web3js.org/guides/web3_upgrade_guide/x/
https://www.npmjs.com/package/web3/v/4.0.1
https://github.com/web3/web3.js/releases/tag/v4.0.1
