### ISSUE TITLE
Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)

### ISSUE THREAD

**Issue by waqaarali** [ethereum/web3.js#5923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Error:**
```
/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/array.js:96
                    throw error;
                    ^

Error: data out-of-bounds (length=0, offset=32, code=BUFFER_OVERRUN, version=abi/5.0.7)
    at Logger.makeError (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Reader._peekBytes (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:149:24)
    at Reader.readBytes (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:161:26)
    at Reader.readValue (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:167:48)
    at DynamicBytesCoder.decode (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/bytes.js:30:40)
    at StringCoder.decode (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/string.js:27:63)
    at /home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/array.js:91:31
    at Array.forEach (<anonymous>)
    at Object.unpack (/home/user1/ba-sc-tester/server/node_modules/@ethersproject/abi/lib/coders/array.js:85:12) {
  reason: 'data out-of-bounds',
  code: 'BUFFER_OVERRUN',
  length: 0,
  offset: 32
}
```

### Expected Behavior

It should revert the custom error, works in Remix VM but not with Web3+Truffle in Node.js, tested on a local Ganache network and Avalanche Testnet. Only seems to be able to revert string-based custom errors, if I pass an integer or something that is not a string it gives me the out of bounds error.

### Steps to Reproduce

```solidity

// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.4;


contract TestToken {
    error InsufficientBalance(uint256 withdrawAmount);

    function transfer(uint256 amount) pure public {
        if (amount > 1000)
            revert InsufficientBalance({ withdrawAmount: amount });
    }
}
```

### Web3.js Version

1.8.2

### Environment

- Operating System: Ubuntu 20.04 LTS
- Browser: Chrome
- Node.js Version: v18.13.0
- NPM Version: 8.19.3

**Comment by Muhammad-Altabba** [comment]
Thanks @waqaarali for opening this issue.
Actually, changing the way an error is produced would cause a breaking change. So, doing this change is not possible in version 1.x. But this would be a good case to handle if it is present in the 4.x which will be the next version. Version 4.x is a complete rewrite in typescript with bug fixing and many enhancements. So, I encourage you to check version 4.x as the [RC0](https://www.npmjs.com/package/web3/v/4.0.1-rc.0) is now available. And we will be happy to handle any issues like this if they exist in 4.x.
So, I appreciate if you could check this issue with https://www.npmjs.com/package/web3/v/4.0.1-rc.0 and if you faced it, to ping us here. Or if it was not there. We can then close this issue.
Thanks,

**Comment by mconnelly8** [comment]
Hey @waqaarali, this would be a breaking change to update 1.x, so we will not be doing it due to the new 4.x version.  Please look into the new version where the full release will be coming up in the next week or so.
