### ISSUE TITLE
Nodejs REPL require('web3') error

### ISSUE THREAD

**Issue by cool-firer** [ethereum/web3.js#6024]
### This is not a Bug Report, Feature Request, or related to Documentation

- [X] I have searched the existing issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### What's up?

Node.js: v14.6.0
OS: macOS Big Sur 11.4
web3: 1.9.0

REPL require('web3') error: 
```
➜  web3test node
Welcome to Node.js v14.6.0.
Type ".help" for more information.
> require('web3')
Uncaught:
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "/xxx/experiment/web3test/node_modules/web3-eth-accounts/node_modules/uuid/dist/index.js" must not include encoded "/" or "\" characters imported from /xxx/experiment/web3test/node_modules/web3-eth-accounts/node_modules/uuid/
    at resolveExportsTarget (internal/modules/cjs/loader.js:564:15)
    at resolveExportsTarget (internal/modules/cjs/loader.js:601:20)
    at resolveExportsTarget (internal/modules/cjs/loader.js:601:20)
    at applyExports (internal/modules/cjs/loader.js:469:14)
    at resolveExports (internal/modules/cjs/loader.js:522:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1052:27)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

while write a test file test.js is OK
```
// in a file, it is OK
const Web3 = require('web3');
console.log(Web3);
```

is it node version related?

**Comment by avkos** [comment]
@cool-firer , I've tried to reproduce but everything works on my side. Can you please describe step-by-step instructions on how to reproduce this bug? it will help us to investigate the problem.

<img width="310" alt="image" src="https://github.com/web3/web3.js/assets/9366141/3672a07e-fde5-47a3-b519-00f6eff2443f">

Here is my steps:
1. `npm init`
2. `npm i web3`
3.  `node`
4.  `> require('web3')`

**Comment by jdevcs** [comment]
@cool-firer closing this issue as there is no activity and we are not able to reproduce it. Feel free to re open issue if error is still there and you have more info.
