### ISSUE TITLE
transaction type error

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#6065]
Invalid transaction type applied to given tx:
```
const web3 = new Web3("https://goerli.infura.io/v3/......");

web3.eth.wallet?.add("0x0f8592102198f565b00937d2da3cd00475866ebdb18053243355dd6aa0222ab4");

const res = await web3.eth.sendTransaction(
    {
        to: "0x8f3e9c1Bd65EB267d19B176A73217524DC21A5ca",
        nonce: 951,
        gasLimit: "0x67b8bf",
        gasPrice: "0x4617ee7c40",
        from: "0x76D43E68c2aE1084B340f0eDC04C325DD341039B",
      },
    undefined,
    {
        ignoreGasPricing: true,
        checkRevertBeforeSending: false
    },
);
```
[wallet.signTransaction](https://github.com/web3/web3.js/blob/1291d957ef3cccbe916cc9267535804e70980c37/packages/web3-eth/src/rpc_method_wrappers.ts#L567) receives :
```
{
  to: "0x8f3e9c1Bd65EB267d19B176A73217524DC21A5ca",
  nonce: "0x3b7",
  gasPrice: "0x4617ee7c40",
  from: "0x76D43E68c2aE1084B340f0eDC04C325DD341039B",
  gas: "0x67b8bf",
}
```

[defaultTransactionTypeParser](https://github.com/web3/web3.js/blob/1291d957ef3cccbe916cc9267535804e70980c37/packages/web3-eth/src/utils/detect_transaction_type.ts#L24) receives follow and applies type 0x2 :
```
{
  to: "0x8f3e9c1Bd65EB267d19B176A73217524DC21A5ca",
  nonce: 951n,
  gasPrice: 301049216064n,
  from: "0x76D43E68c2aE1084B340f0eDC04C325DD341039B",
  gas: 6797503n,
  value: "0x",
  input: "0x",
  chain: "mainnet",
  hardfork: "london",
  chainId: "0x1",
  networkId: "0x1",
  gasLimit: 6797503n,
}
```
and [validate transaction](https://github.com/web3/web3.js/blob/1291d957ef3cccbe916cc9267535804e70980c37/packages/web3-eth/src/utils/prepare_transaction_for_signing.ts#L139) throws :
```
"Eip1559GasPriceError: Invalid value given \"0x4617ee7c40\". Error: eip-1559 transactions don't support gasPrice."
```
seems due to :
https://github.com/web3/web3.js/blob/1291d957ef3cccbe916cc9267535804e70980c37/packages/web3-eth/src/utils/transaction_builder.ts#L192

**Comment by Spacesai1or** [comment]
So `hardfork` is populated to `london` because it's web3's default if not provided, and this causes [this check](https://github.com/web3/web3.js/blob/1291d957ef3cccbe916cc9267535804e70980c37/packages/web3-eth/src/utils/detect_transaction_type.ts#L29-L35):

```typescript
if (
		!isNullish(tx.maxFeePerGas) ||
		!isNullish(tx.maxPriorityFeePerGas) ||
		tx.hardfork === 'london' ||
		tx.common?.hardfork === 'london'
	)
		return '0x2';
```

to return `0x2` regardless if `gasPrice` is set. So it seems `defaultTransactionTypeParser` should return `0x0` or `0x1` if `gasPrice` is on provided `transaction` object before this check

**Comment by jdevcs** [comment]
Additionally if we remove 2nd gasfilling function call there are many functions in contracts failing with:
```
  ● contract › erc721 › should award item "0x2"
web3-eth-contract:     Eip1559GasPriceError: Invalid value given "0x15aa97b9". Error: eip-1559 transactions don't support gasPrice.
web3-eth-contract:       227 | 	// for the same code executing in 1.x
web3-eth-contract:       228 | 	if (!isNullish(transaction.gasPrice) && transaction.type === '0x2')
web3-eth-contract:     > 229 | 		throw new Eip1559GasPriceError(transaction.gasPrice);
web3-eth-contract:           | 		      ^
web3-eth-contract:       230 | 	if (transaction.type === '0x0' || transaction.type === '0x1')
web3-eth-contract:       231 | 		throw new UnsupportedFeeMarketError({
web3-eth-contract:       232 | 			maxFeePerGas: transaction.maxFeePerGas,
web3-eth-contract:       at validateFeeMarketGas (../web3-eth/src/validation.ts:229:9)
web3-eth-contract:       at validateGas (../web3-eth/src/validation.ts:279:23)
web3-eth-contract:       at validateTransactionForSigning (../web3-eth/src/validation.ts:300:13)
web3-eth-contract:       at ../web3-eth/src/utils/prepare_transaction_for_signing.ts:141:31
web3-eth-contract:       at fulfilled (../web3-eth/lib/commonjs/utils/prepare_transaction_for_signing.js:21:58)

```

and

```
● contract › erc721 › contract instance › methods › should set approve for all item with local wallet [Function signAndSendContractMethodEIP2930]
web3-eth-contract:     MissingGasError: Invalid value given "gas: 0xf4240, gasPrice: undefined, maxPriorityFeePerGas: undefined, maxFeePerGas: undefined". Error: "gas" is missing.
web3-eth-contract:       259 |
web3-eth-contract:       260 | 	if (!legacyGasPresent && !feeMarketGasPresent)
web3-eth-contract:     > 261 | 		throw new MissingGasError({
web3-eth-contract:           | 		      ^
web3-eth-contract:       262 | 			gas: transaction.gas,
web3-eth-contract:       263 | 			gasPrice: transaction.gasPrice,
web3-eth-contract:       264 | 			maxPriorityFeePerGas: transaction.maxPriorityFeePerGas,
web3-eth-contract:       at validateGas (../web3-eth/src/validation.ts:261:9)
web3-eth-contract:       at validateTransactionForSigning (../web3-eth/src/validation.ts:300:13)
web3-eth-contract:       at ../web3-eth/src/utils/prepare_transaction_for_signing.ts:141:31
web3-eth-contract:       at fulfilled (../web3-eth/lib/commonjs/utils/prepare_transaction_for_signing.js:21:58)

```
