### ISSUE TITLE
 ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6186]
While having some sort of specific configuration, importing Web3 object causes an error.
The imports are as simple as:

```ts
import { Web3 } from 'web3';
```

And the error raised is:  `"ReferenceError: TextEncoder is not defined"` with the following stack trace:
```bash
      at utf8ToBytes (node_modules/@noble/hashes/src/utils.ts:91:3)
      at Function.getKey (node_modules/web3-validator/src/validator.ts:157:35)
      at Validator.getOrCreateValidator (node_modules/web3-validator/src/validator.ts:147:25)
      at Validator.validate (node_modules/web3-validator/src/validator.ts:59:30)
      at Web3Validator.validate (node_modules/web3-validator/src/web3_validator.ts:69:26)
      at bytesToUint8Array (node_modules/web3-utils/src/converters.ts:87:12)
      at hexToBytes (node_modules/web3-utils/src/converters.ts:136:27)
      at Object.<anonymous> (node_modules/web3-eth-accounts/src/tx/eip1559Transaction.ts:47:47)
      at Object.<anonymous> (node_modules/web3-eth-accounts/src/tx/transactionFactory.ts:18:1)
      at Object.<anonymous> (node_modules/web3-eth-accounts/src/account.ts:64:1)
      at Object.<anonymous> (node_modules/web3-eth-accounts/src/index.ts:41:1)
      at Object.<anonymous> (node_modules/web3-eth/src/rpc_method_wrappers.ts:53:1)
      at Object.<anonymous> (node_modules/web3-eth/src/web3_eth.ts:46:1)
      at Object.<anonymous> (node_modules/web3-eth/src/index.ts:53:1)
      at Object.<anonymous> (node_modules/web3/src/web3.ts:19:1)
      at Object.<anonymous> (node_modules/web3/src/index.ts:325:1)
      at Object.<anonymous> (test/compile.test.ts:7:1)

```

## Ad Hoc Solution
However, adding the following prior to the import of Web3 caused the error to disappear:
```ts
import { TextEncoder } from 'util';
global.TextEncoder = TextEncoder;
```

## Reproduce
1. Clone the following repository: https://github.com/conx3/web3-plugin-solidity-compiler
2. Comment the mentioned snippet that adds TextEncoder to global. Which you can find here:
https://github.com/conx3/web3-plugin-solidity-compiler/blob/fbc32514119559722b645407d18dca3946a7d978/test/compile.test.ts#L4
3. Run `yarn && yarn test` and you should be able to see the error.

**Comment by mpetrunic** [comment]
@Muhammad-Altabba https://stackoverflow.com/questions/68468203/why-am-i-getting-textencoder-is-not-defined-in-jest
It's the stupid jest and it's jsdom

I will never understand why people choose jest, there is so many landmines in it that it's literally not worth it 😂

**Comment by Muhammad-Altabba** [comment]
> 

Thanks @mpetrunic ,
I got confused because this error comes only when I import web3 and it does not show if it is not imported. Thanks for the clarification. 
And so do you think this issue can be safely closed?

**Comment by mpetrunic** [comment]
Yup. Issue is with jest+jsdom.

**Comment by Muhammad-Altabba** [comment]
Thanks, 
And, so, I am closing this issue. 

And for anyone facing this issue, the solution is to add the following code **prior** to the import of Web3:
```ts
import { TextEncoder } from 'util';
global.TextEncoder = TextEncoder;
```

**Comment by Muhammad-Altabba** [comment]
Thanks, 
And, so, I am closing this issue. 

And for anyone facing this issue, the solution is to add the following code **prior** to the import of Web3:
```ts
import { TextEncoder } from 'util';
global.TextEncoder = TextEncoder;
```

**Comment by jdevcs** [comment]
discussed in last team call, we should not go in direction of jest+jsdom.

**Comment by Muhammad-Altabba** [comment]
Yes, and sorry I tagged this issue by mistake.
This issue is already closed and no work is related to it.
