### ISSUE TITLE
wrong serialization of bigint when using getLastLog. 

### ISSUE THREAD

**Issue by vekexasia** [ethereum/web3.js#6206]
#### Expected behavior
Typescript allows blocknumbers to be passed as bigint. but it's not properly taken into account.

#### Actual behavior
`Do not know how to serialize a BigInt`

#### Steps to reproduce the behavior
```
 const web3 = new Web3(process.env.WS_ADDRESS!);
  const logs = await web3.eth.getPastLogs({
    fromBlock: 17486201n,
    toBlock: 17486201n,

  });

  console.log(logs);
```

#### Logs

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at WebSocketProvider._sendToSocket (/home/me/eth_tests/node_modules/web3-providers-ws/src/index.ts:134:37)
    at WebSocketProvider._sendPendingRequests (/home/me/eth_tests/node_modules/web3-providers-ws/node_modules/web3-utils/src/socket_provider.ts:446:9)
    at WebSocketProvider._onConnect (/home/me/eth_tests/node_modules/web3-providers-ws/node_modules/web3-utils/src/socket_provider.ts:441:8)
    at callListener (/home/me/eth_tests/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onOpen (/home/me/eth_tests/node_modules/ws/lib/event-target.js:237:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at WebSocket.setSocket (/home/me/eth_tests/node_modules/ws/lib/websocket.js:237:10)
    at ClientRequest.<anonymous> (/home/me/eth_tests/node_modules/ws/lib/websocket.js:985:15)
```

#### Environment

node 18.12.0, web3 v4.0.1

**Comment by luu-alex** [comment]
Thank you for reporting this bug, i'll create a PR for this soon and have a fix

**Comment by luu-alex** [comment]
PR has been merged to fix this, it'll be available next release.
