### ISSUE TITLE
erc20 symbol fetch decode crash

### ISSUE THREAD

**Issue by vlad-blana** [ethereum/web3.js#6227]
I'm trying to get get the symbol for many erc20 on ethereum and contracts like '0x9469D013805bFfB7D3DEBe5E7839237e535ec483' fail with 

```
node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:155
        throw new AbiError(`Parameter decoding error: ${err.message}`);
              ^

AbiError: Parameter decoding error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="372191736699279289343430071854649    at decodeParametersWith (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:155:15)
    at decodeParameters (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-eth-abi/lib/esm/api/parameters_api.js:262:49)
    at decodeMethodReturn (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-eth-contract/lib/esm/encoding.js:147:20)
    at ContractBuilder.<anonymous> (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-eth-contract/lib/esm/contract.js:499:24)
    at Generator.next (<anonymous>)
    at fulfilled (file:///I:/work/trading-tools-js/portfolio-tracker/node_modules/web3-eth-contract/lib/esm/contract.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  innerError: undefined,
  code: 205
}
```

One would expect to get 'RING' in this instance.

My original code creates a Contract with the standard erc20 abi and the contract address. Nothing more, nothing less.
But the fastest way to reproduce it is

```
import { eth } from 'web3';
eth.abi.decodeParameter('string', '52494e4700000000000000000000000000000000000000000000000000000000');
```

52494e4700000000000000000000000000000000000000000000000000000000 is the HEX for the 372191736699279289343430071854649 and ignoring the trailing 0s its ASCII equivalent is RING

This contract symbol crashes on other libs too. But the explorers show RING properly. I checked and it's ok on ethereum, eth pow and pulsechain, while this code crashes on all chains with this particular contract.

I don't think it's environment specific, but in case it helps

Node v18.16.0
Web3 v4.0.1
Windows
x86 pc/laptop

**Comment by jdevcs** [comment]
@vlad-blana Thanks for creating issue with details. I checked its due to underlying lib that we are using for abi encoding. 

and abi encoder lib that we are using is on list to be removed soon from web3.js. https://github.com/web3/web3.js/issues/6211
