### ISSUE TITLE
Execution reverted error even though the transaction went through

### ISSUE THREAD

**Issue by NoelJasik** [ethereum/web3.js#6254]
#### Expected behavior
When i send a signed transaction, and it goes through, i should not get any errors

#### Actual behavior
When i send a signed transaction, it goes through, but throws a error: Execution reverted, even though that's not true

#### Steps to reproduce the behavior

Run the following code, where _account is the address we send to, PUBLIC_KEY the address of the sender, and PRIVATE_KEY the private key of the sender, and the NETWORK is the network id
```
async function sendFund(_account) {
    const nonce = web3.eth.getTransactionCount(PUBLIC_KEY);
    const gasPrice = await web3.eth.getGasPrice();

var rawTransaction = {
	from: PUBLIC_KEY,
	to: _account, 
	value: "1000000000000000000", 
        gasLimit: web3.utils.toHex('210000'),
        gasPrice,
        nonce: nonce, 
	data: "0x00",
        chainId: NETWORK 
};

   const signedTx = await web3.eth.accounts.signTransaction(rawTransaction, PRIVATE_KEY)
   console.log(signedTx)
   const receipt = await web3.eth.sendSignedTransaction(signedTx.rawTransaction);
    return await receipt;
}
```

#### Logs
```

{
  messageHash: '0x7d6a0d176d7ede63d7af8cdd647e79a9279308cc3ca8fcd4bdd9586d66ea112f',
  v: '0x43',
  r: '0xe408a314ee59cc69cc77284f50d9604e5aaf3f73b54e37518ec8c8e1d40b9a54',
  s: '0x49c9a06778678db16873402419dca630c60bd06b59493c5c27ae680049ffa930',
  rawTransaction: '0xf86f8203448505d21dba00830334509403b9ac518600dbe51df164afbab7ccb0b194248a880de0b6b3a76400000043a0e408a314ee59cc69cc77284f50d9604e5aaf3f73b54e37518ec8c8e1d40b9a54a049c9a06778678db16873402419dca630c60bd06b59493c5c27ae680049ffa930',
  transactionHash: '0x39f350325469244ded3a0fb477fc5d80aff5431fcad7b9db4cb2b00964c74730'
}

/workspaces/project/node_modules/web3-core-helpers/lib/errors.js:28
        var err = new Error('Returned error: ' + message);
                  ^
Error: Returned error: execution reverted
    at Object.ErrorResponse (/workspaces/project/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /workspaces/project/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /workspaces/project/node_modules/web3-providers-http/lib/index.js:127:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
[Transaction on block explorer](https://coston-explorer.flare.network/tx/0x39f350325469244ded3a0fb477fc5d80aff5431fcad7b9db4cb2b00964c74730)

#### Environment
npm version: 9.6.7 node version: v20.3.0 web3.js version: 1.10.0, i am using github codespace

**Comment by NoelJasik** [comment]
Nevermind, the error message didn't come from this
