### ISSUE TITLE
new Web3(...) throws error when creating a production next build

### ISSUE THREAD

**Issue by Neil3079** [ethereum/web3.js#6313]
#### Expected behavior
When creating a new Web3 object with any provider on client side a next project should be able to compile with next build

#### Actual behavior
The following error is thrown

`thread '<unnamed>' panicked at 'byte index 4 is out of bounds of `0x1`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_utils-0.105.30/src/lib.rs:1575:22`

#### Steps to reproduce the behavior
1. Create a new next project
2. Install web3.js
3. Create a Web3 object with a provider (e.g. window.ethereum)
4. run next build

#### Logs

` thread '<unnamed>' panicked at 'byte index 4 is out of bounds of `0x1`', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_utils-0.105.30/src/lib.rs:1575:22
next-commerce:build: stack backtrace:
next-commerce:build:    0:        0x12371c478 - _wasmer_vm_raise_trap
next-commerce:build:    1:        0x12373af94 - _wasmer_vm_raise_trap
next-commerce:build:    2:        0x123715624 - _wasmer_vm_raise_trap
next-commerce:build:    3:        0x12371c28c - _wasmer_vm_raise_trap
next-commerce:build:    4:        0x12371dc90 - _wasmer_vm_raise_trap
next-commerce:build:    5:        0x12371d9e8 - _wasmer_vm_raise_trap
next-commerce:build:    6:        0x12371e2cc - _wasmer_vm_raise_trap
next-commerce:build:    7:        0x12371e0dc - _wasmer_vm_raise_trap
next-commerce:build:    8:        0x12371c8e0 - _wasmer_vm_raise_trap
next-commerce:build:    9:        0x12371de30 - _wasmer_vm_raise_trap
next-commerce:build:   10:        0x1238333c8 - _wasmer_vm_raise_trap
next-commerce:build:   11:        0x12373f3ac - _wasmer_vm_raise_trap
next-commerce:build:   12:        0x1238336e0 - _wasmer_vm_raise_trap
next-commerce:build:   13:        0x123589728 - _wasmer_vm_raise_trap
next-commerce:build:   14:        0x123406bec - _wasmer_vm_raise_trap
next-commerce:build:   15:        0x1233ef894 - _wasmer_vm_raise_trap
next-commerce:build:   16:        0x1233f1ca4 - _wasmer_vm_raise_trap
next-commerce:build:   17:        0x1233f053c - _wasmer_vm_raise_trap
next-commerce:build:   18:        0x123383c58 - _wasmer_vm_raise_trap
next-commerce:build:   19:        0x1233f053c - _wasmer_vm_raise_trap
next-commerce:build:   20:        0x1233f00bc - _wasmer_vm_raise_trap
next-commerce:build:   21:        0x1233f053c - _wasmer_vm_raise_trap
next-commerce:build:   22:        0x1233f47a8 - _wasmer_vm_raise_trap
next-commerce:build:   23:        0x1233f053c - _wasmer_vm_raise_trap
next-commerce:build:   24:        0x123382598 - _wasmer_vm_raise_trap
next-commerce:build:   25:        0x1233fc200 - _wasmer_vm_raise_trap
next-commerce:build:   26:        0x12341e7bc - _wasmer_vm_raise_trap
next-commerce:build:   27:        0x1233a6628 - _wasmer_vm_raise_trap
next-commerce:build:   28:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   29:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   30:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   31:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   32:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   33:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   34:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   35:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   36:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   37:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   38:        0x1233e7fb4 - _wasmer_vm_raise_trap
next-commerce:build:   39:        0x12382b30c - _wasmer_vm_raise_trap
next-commerce:build:   40:        0x1233f6b3c - _wasmer_vm_raise_trap
next-commerce:build:   41:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   42:        0x1233e2a8c - _wasmer_vm_raise_trap
next-commerce:build:   43:        0x1233f6afc - _wasmer_vm_raise_trap
next-commerce:build:   44:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   45:        0x1233e2a8c - _wasmer_vm_raise_trap
next-commerce:build:   46:        0x1233f6afc - _wasmer_vm_raise_trap
next-commerce:build:   47:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   48:        0x1233e2a8c - _wasmer_vm_raise_trap
next-commerce:build:   49:        0x1233f6afc - _wasmer_vm_raise_trap
next-commerce:build:   50:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   51:        0x1233f6a80 - _wasmer_vm_raise_trap
next-commerce:build:   52:        0x1233a66c4 - _wasmer_vm_raise_trap
next-commerce:build:   53:        0x1233e7fb4 - _wasmer_vm_raise_trap
next-commerce:build:   54:        0x12382b30c - _wasmer_vm_raise_trap
next-commerce:build:   55:        0x1236bc914 - _wasmer_vm_raise_trap
next-commerce:build:   56:        0x1236babc8 - _wasmer_vm_raise_trap
next-commerce:build:   57:        0x1236be750 - _wasmer_vm_raise_trap
next-commerce:build:   58:        0x123722978 - _wasmer_vm_raise_trap
next-commerce:build:   59:        0x1a919a06c - __pthread_deallocate
next-commerce:build: fatal runtime error: failed to initiate panic, error 5
next-commerce:build:  ELIFECYCLE  Command failed.`

#### Environment

npm: 9.6.7
node: 18.17.0
web3.js: 4.0.2 (confirmed on 4.0.1 as well)
OS: Ventura 13.2
Device: Macbook pro
Chip: M1 Pro

**Comment by Muhammad-Altabba** [comment]
Thanks @Neil3079 ,
We will look into that.

**Comment by learning** [comment]
The same error with web3@4.1.1.
Everything works well when I downgrade to web3@1.10.1

**Comment by jdevcs** [comment]
using node v18.17.0 , next 13.4.19

1. npx create-next-app@latest
2. npm i web3@4.1.1
3. modified page.tsx and index.tsx by adding "use client" at top for CSR
4. added following in page.tsx:
```
export default async function Home() {

  const w = new Web3('https://mainnet.infura.io/v3/KEY');
  const result = await w.eth.getBalance('0xc9AC78224469711eCD61bB6c16830b4B56A01c73');
  console.log(result)
  
  ....
  <div>balance is {result.toString()}</div>
  .....
            </p>
        </a>
      </div>
    </main>
  )
}
  
```
5. npx next build
<img width="636" alt="image" src="https://github.com/web3/web3.js/assets/86780488/a2733fca-2298-4d0c-adc3-615f87210979">

with local dev:
<img width="591" alt="image" src="https://github.com/web3/web3.js/assets/86780488/c5cc0207-7121-4fa9-b5db-54d5973fd0c3">

@learning @Neil3079 how can I reproduce error that you shared?

**Comment by jdevcs** [comment]
@Neil3079

**Comment by jdevcs** [comment]
I am closing this issue as issue is not reproducible and there is no activity, feel free to reopen if there is more information.

**Comment by Headaron** [comment]
Just went through this issue myself. I installed the latest Node v21.1.0 and that seems to have cleared everything up for me? Which is odd because I had v20.7. Web3 v 4.2.1, Next 14.0.0, React 18.2.0. Just thought I'd share in case anyone else comes across this like I did.

**Comment by jdevcs** [comment]
@Neil3079 thanks for sharing feedback.
