### ISSUE TITLE
Error: Returned error: cannot query unfinalized data

### ISSUE THREAD

**Issue by 0xBeycan** [ethereum/web3.js#6394]
With a node application running on Heroku, I connect to the websocket of the networks using web3.js and monitor transactions. Everything works smoothly on the desktop. When I try it on a mobile browser, I get the following strange error. I don't get such an error when I try it on BrowserStack. But I don't understand why this happens on mobile device.

#### Running code

```
if (tokenAddress) {
    receiver = receiver.replace('0x', '');
    receiver = receiver.toLowerCase();
    receiver = "0x000000000000000000000000" + receiver;
    let subscription = this.web3ws.eth.subscribe('logs', {
        address: tokenAddress,
        topics: [null, null, receiver]
    });

    subscription.on("data", (data) =>  {
        callback(subscription, this.Transaction(data.transactionHash));
    });
} else {
    let balance = await this.methods.getBalance(receiver);
    let subscription = this.web3ws.eth.subscribe('newBlockHeaders');

    subscription.on("data", async (blockHeader) => {
        let newbalance = await this.methods.getBalance(receiver);
        if (balance < newbalance) {
            balance = await this.methods.getBalance(receiver);
            let currentBlock = await this.methods.getBlock(blockHeader.hash, true);
            currentBlock.transactions.forEach(transaction => {
                if (transaction.to && transaction.to.toLowerCase() == receiver.toLowerCase()) {
                    callback(subscription, this.Transaction(transaction.hash));
                }
            });
        }
    });
}
```

#### Logs

```
Error: Returned error: cannot query unfinalized data
    at Object.ErrorResponse (/app/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /app/node_modules/web3-core-requestmanager/lib/index.js:300:36
    at /app/node_modules/web3-providers-http/lib/index.js:131:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

#### Environment
Heroku App
Node: 18.17.1
NPM: 9.6.7
IOS 16.5
Chrome & Safari

**Comment by Muhammad-Altabba** [comment]
Hello @BeycanDeveloper 
It seems not related specifically to mobile browsers. I suspect something related to your node configuration to accept requests from outside the same computer. So, I recommend opening the same application but from another computer instead of opening it from a mobile.
Also, I am not familiar with Heroco is it only on the cloud or does it have a local version? Could you please share more information about the setup? Where is the application hosted? If it is public. Could you share the link? 
I am assuming you are using web3.js version 4.x, right?
Thanks,

**Comment by 0xBeycan** [comment]
When I look at the Version, I see that I am using Web3.js 1.10.1. It works on the Heroku link below, but the process is running through Socket.io, ie Websocket.

https://qr-verifier-7c7fab6cf733.herokuapp.com/

You can see the issue by testing QR payment on the Avalanche Test Network on this demo site. The strange thing is that there is no problem on the desktop. All data is the same software, the same software that causes the same error always works in the same place, only the communicating device is different. However, while there is no problem on desktop, the same process gives an error on mobile. However, there is no problem with Ethereum QR payment using the same method. The situation is very strange for me.

https://cryptopay.beycanpress.net/

**Comment by jdevcs** [comment]
@BeycanDeveloper can you test with web3.js 4.x ?

**Comment by jdevcs** [comment]
There is no activity on this issue so closing, feel free to reopen if there is more info.
