### ISSUE TITLE
'No Response error' from web3_request_manager.js

### ISSUE THREAD

**Issue by dhayaprabhu** [ethereum/web3.js#7049]
InvalidResponseError: Returned error: no response
    at Web3RequestManager._processJsonRpcResponse (file:///../node_modules/web3-core/lib/esm/web3_request_manager.js:252:23)
    at Web3RequestManager.<anonymous> (file:///../node_modules/web3-core/lib/esm/web3_request_manager.js:150:29)
    at Generator.next (<anonymous>)
    at fulfilled (file:///../node_modules/web3-core/lib/esm/web3_request_manager.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:401:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  innerError: { message: 'no response', code: -32603 },
  code: 101,
  data: undefined,
  request: {
    jsonrpc: '2.0',
    id: '5cc619f1-6fcb-4380-8dc7-05181368fd4c',
    method: 'eth_call',
    params: [
      {
        to: '0xXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        from: '0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
        input: '0xXXXXXXX'
      },
      'latest'
    ]
  }
}
what could be the possible reason for the 'No Response' error ? Can anybody help?

**Comment by mconnelly8** [comment]
Hey @dhayaprabhu, the team will review this soon and get back with you.

**Comment by luu-alex** [comment]
Hi there, what provider url were u using? this doesn't seem to be a web3.js issue but your providers

**Comment by mconnelly8** [comment]
Hey @dhayaprabhu, what provider URL were you using?   As Alex mentioned, this doesn't seem to be a web3.js issue, but we'd like to double check.

**Comment by mconnelly8** [comment]
Hey @dhayaprabhu, since we didn't get a response, I'll be closing this issue.  If you are still experiencing an issue, please open the issue and send over the provider URL you were using.
