### ISSUE TITLE
How to setup a keepalive WebSocket connection with web3-providers-ws 4.x

### ISSUE THREAD

**Issue by yanosh1982** [ethereum/web3.js#7078]
Hi,

I'm struggling on how to setup a WebSocket connection with web3.js with keep alive options. 

I create the provider like the following

```
import { Controller, Inject, LoggerService } from '@nestjs/common';
import { WINSTON_MODULE_PROVIDER } from 'nest-winston';
import Web3, { Contract, EventLog } from 'web3';
import { FdvDigestTrackerType } from "./types/fdv-digest-tracker.type";
import * as FdvDigestTracker from "./types/FdvDigestTracker.json";
import { EventListenerService } from './event-listener-service';
import Web3WsProvider, { ClientOptions, ClientRequestArgs } from 'web3-providers-ws';

  const wsProviderOptions: ClientOptions | ClientRequestArgs = {
      timeout: parseInt(process.env.BLOCKCHAIN_NODE_MS_TIMEOUT), // ms
  };
  
  const reconnectOptions = {
      autoReconnect: (process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT === 'true'),
      delay: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MS_DELAY), // ms
      maxAttempts: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MAX_ATTEMP),
  }

  const provider = new Web3WsProvider(process.env.BLOCKCHAIN_NODE_URL, wsProviderOptions, reconnectOptions);
  this.web3 = new Web3(provider);
```

But after a while events are processed no more. In some [old implementation](https://web3js.readthedocs.io/en/v1.2.7/web3.html#configuration) there were a keepAlive and keepAliveInterval parameters but They seems to have been removed.

I'm using theese library versions:     "web3": "^4.5.0", "web3-providers-ws": "^4.0.7"

Thank you in advance

**Comment by Vishalll07** [comment]
Hey , can you please tell the file in your facing issue with , I can try

**Comment by yanosh1982** [comment]
Hi @Vishalll07, thank you for your message. Can you please elaborate your request? I can't understand exactly what I am supposed to tell you. Anyway in my question I've pasted my cod. I've started by following [this](https://web3js.readthedocs.io/en/v1.2.11/web3.html#configuration) documentation. At the end of the configuration is written: 

"More information for the Http and Websocket provider modules can be found here:

[HttpProvider](https://github.com/ethereum/web3.js/tree/1.x/packages/web3-providers-http#usage)
[WebsocketProvider](https://github.com/ethereum/web3.js/tree/1.x/packages/web3-providers-ws#usage)"

Following the link pointing to WebsocketProvider  I hit this repo, but the 1.x version. Indeed newer version I've installed with 
```
npm install web3-providers-ws 
```
is newer and i can't find anything about a keep alive configuration.

Thank you again

**Comment by Vishalll07** [comment]
hey,
 The WebSocket provider you're using doesn't have built-in keep-alive options as in older versions.
 Have you tried the usage code given in [web3-providers-http](https://github.com/web3/web3.js/tree/1.x/packages/web3-providers-http#usage)

and would suggest to go with command 
npm install web3-providers-http  
along with 
npm install web3-providers-ws 

or else may try out this 

`import Web3 from 'web3';
import { ClientOptions, ClientRequestArgs } from 'web3-providers-ws';
import WebSocket from 'ws'; // Import the ws library

// Configuration options
const wsProviderOptions: ClientOptions | ClientRequestArgs = {
    timeout: parseInt(process.env.BLOCKCHAIN_NODE_MS_TIMEOUT), // ms
};

const reconnectOptions = {
    autoReconnect: (process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT === 'true'),
    delay: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MS_DELAY), // ms
    maxAttempts: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MAX_ATTEMP),
};

// Create a custom WebSocket with heartbeat
function createWebSocketProvider(url) {
    const ws = new WebSocket(url, wsProviderOptions);

    ws.on('open', function open() {
        console.log('WebSocket connection opened.');
        ws.isAlive = true;
    });

    ws.on('pong', function heartbeat() {
        ws.isAlive = true;
    });

    // Heartbeat mechanism
    const interval = setInterval(function ping() {
        if (ws.isAlive === false) {
            console.log('WebSocket connection dead, reconnecting...');
            ws.terminate();
            createWebSocketProvider(url); // Recreate the WebSocket connection
        }
        ws.isAlive = false;
        ws.ping(); // Send a ping to the server
    }, parseInt(process.env.BLOCKCHAIN_WS_KEEP_ALIVE_INTERVAL) || 30000); // Default 30s interval

    ws.on('close', function clear() {
        clearInterval(interval);
    });

    return ws;
}

// Create Web3 instance with custom WebSocket provider
const provider = createWebSocketProvider(process.env.BLOCKCHAIN_NODE_URL);
const web3 = new Web3(provider);

// Use web3 as usual
web3.eth.getBlockNumber().then(console.log).catch(console.error);
`

**Comment by yanosh1982** [comment]
Hi @Vishalll07, thank you for your answer.

I pasted your code in my project. The property isAlive seem to be not present on WebSocket. I Googled and found this solution
```
import { WebSocket } from 'ws';

declare interface FdvWebSocket extends WebSocket { // you can name Socket whatever you want
    isAlive: boolean;
}

const wsProviderOptions: ClientOptions | ClientRequestArgs = {
    timeout: parseInt(process.env.BLOCKCHAIN_NODE_MS_TIMEOUT), // ms
};

const reconnectOptions = {
    autoReconnect: (process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT === 'true'),
    delay: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MS_DELAY), // ms
    maxAttempts: parseInt(process.env.BLOCKCHAIN_WS_PROVIDER_AUTO_RECONNECT_MAX_ATTEMP),
}

// Create a custom WebSocket with heartbeat
function createWebSocketProvider(url) {
    const ws = new WebSocket(url, wsProviderOptions);
    
    ws.on('open', (ws: FdvWebSocket) => {
        console.log('WebSocket connection opened.');
        ws.isAlive = true;
    });
    
    ws.on('pong', (ws: FdvWebSocket) => {
        ws.isAlive = true;
    });
    
    // Heartbeat mechanism
    const interval = setInterval((ws: FdvWebSocket) => {
        if (ws.isAlive === false) {
            console.log('WebSocket connection dead, reconnecting...');
            ws.terminate();
            createWebSocketProvider(url); // Recreate the WebSocket connection
        }
        ws.isAlive = false;
        ws.ping(); // Send a ping to the server
    }, parseInt(process.env.BLOCKCHAIN_WS_KEEP_ALIVE_INTERVAL) || 30000); // Default 30s interval
    
    ws.on('close', function clear() {
        clearInterval(interval);
    });
    
    return ws;
}

@Controller()
export class FdvDigestTrackerEventListener {

    private readonly contractAddress: string;
    private readonly contract: Contract<FdvDigestTrackerType>;
    private readonly web3: Web3 

    constructor(
        @Inject(WINSTON_MODULE_PROVIDER) 
        private readonly logger: LoggerService,
        private readonly appService: EventListenerService
    ) {

        
        
        const provider = createWebSocketProvider(process.env.BLOCKCHAIN_NODE_URL);
        this.web3 = new Web3(provider);
        this.contractAddress = process.env.BLOCKCHAIN_FDV_DIGEST_TRACKER_CONTRACT_ADDRESS;
        const abi: FdvDigestTrackerType = FdvDigestTracker.abi as unknown as FdvDigestTrackerType;
        this.contract = new this.web3.eth.Contract(abi, this.contractAddress);
    }
```

but when I start the project the subscription to the blockchain events fails and I obtain the following:

```
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [NestFactory] Starting Nest application...
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] ClientsModule dependencies initialized +18ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] MongooseModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] WinstonModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] MongooseCoreModule dependencies initialized +102ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] MongooseModule dependencies initialized +1ms
[Nest] 92808  - 06/04/2024, 10:28:55 AM     LOG [InstanceLoader] ModelModule dependencies initialized +0ms
[Nest] 92808  - 06/04/2024, 10:28:56 AM     LOG [InstanceLoader] AppModule dependencies initialized +1678ms
[Nest] 92808  - 06/04/2024, 10:28:56 AM     LOG [RoutesResolver] FdvDigestTrackerEventListener {/}: +3ms
[Nest] 92808  - 06/04/2024, 10:28:56 AM     LOG [RoutesResolver] HealthController {/}: +0ms
[Nest] 92808  - 06/04/2024, 10:28:56 AM     LOG [RouterExplorer] Mapped {/, GET} route +0ms
[Nest] 92808  - 06/04/2024, 10:28:56 AM     LOG [RouterExplorer] Mapped {/liveness, GET} route +1ms
2024-06-04 10:28:57 [info]: Bootstrapping fdv-blockchain-event-listener 
2024-06-04 10:29:00 [error]: Error subscribing NewDigest events: SubscriptionError: Failed to subscribe.
    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: 'SubscriptionError: Failed to subscribe.\n' +
    '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: 'Failed to subscribe.',
  innerError: Error: WebSocket is not open: readyState 0 (CONNECTING)
      at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14
      at new Promise (<anonymous>)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)
      at Generator.next (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71
      at new Promise (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12
      at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31) {
    [stack]: 'Error: WebSocket is not open: readyState 0 (CONNECTING)\n' +
      '    at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12\n' +
      '    at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31)',
    [message]: 'WebSocket is not open: readyState 0 (CONNECTING)'
  },
  name: 'SubscriptionError',
  code: 603
} 
2024-06-04 10:29:00 [error]: Error subscribing DigestUpdated events: SubscriptionError: Failed to subscribe.
    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: 'SubscriptionError: Failed to subscribe.\n' +
    '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: 'Failed to subscribe.',
  innerError: Error: WebSocket is not open: readyState 0 (CONNECTING)
      at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14
      at new Promise (<anonymous>)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)
      at Generator.next (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71
      at new Promise (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12
      at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31) {
    [stack]: 'Error: WebSocket is not open: readyState 0 (CONNECTING)\n' +
      '    at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12\n' +
      '    at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31)',
    [message]: 'WebSocket is not open: readyState 0 (CONNECTING)'
  },
  name: 'SubscriptionError',
  code: 603
} 
2024-06-04 10:29:00 [error]: Error subscribing DigestDeleted events: SubscriptionError: Failed to subscribe.
    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: 'SubscriptionError: Failed to subscribe.\n' +
    '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-eth-contract/src/contract.ts:1462:23\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: 'Failed to subscribe.',
  innerError: Error: WebSocket is not open: readyState 0 (CONNECTING)
      at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14
      at new Promise (<anonymous>)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)
      at Generator.next (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71
      at new Promise (<anonymous>)
      at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12
      at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)
      at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31) {
    [stack]: 'Error: WebSocket is not open: readyState 0 (CONNECTING)\n' +
      '    at WebSocket.send (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:449:13)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:279:14\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:278:11)\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:24:71\n' +
      '    at new Promise (<anonymous>)\n' +
      '    at /Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:20:12\n' +
      '    at Web3RequestManager._sendRequest (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/lib/commonjs/web3_request_manager.js:139:16)\n' +
      '    at Web3RequestManager.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/web3-core/src/web3_request_manager.ts:158:31)',
    [message]: 'WebSocket is not open: readyState 0 (CONNECTING)'
  },
  name: 'SubscriptionError',
  code: 603
} 
[Nest] 92808  - 06/04/2024, 10:29:00 AM     LOG [NestApplication] Nest application successfully started +3043ms
WebSocket connection opened.
/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/src/fdv-digest-tracker/fdv-digest-tracker-event-listener.ts:30
        ws.isAlive = true;
                  ^
TypeError: Cannot set properties of undefined (setting 'isAlive')
    at WebSocket.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/src/fdv-digest-tracker/fdv-digest-tracker-event-listener.ts:30:19)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emit (node:domain:488:12)
    at WebSocket.setSocket (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:244:10)
    at ClientRequest.<anonymous> (/Users/danielevl/projects/mnm/fdv/fdv2/blockchain-event-listener/blockchain-event-listener/node_modules/ws/lib/websocket.js:1009:15)
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:488:12)
    at Socket.socketOnData (node:_http_client:575:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
Waiting for the debugger to disconnect...
```

**Comment by SantiagoDevRel** [comment]
Hi @yanosh1982 , not sure if this is the same error that we are investigating [here](https://github.com/web3/web3.js/issues/6968)

**Comment by yanosh1982** [comment]
Hi Santiago, It seems to be the same.. I'll try to use the code provided in the linked issue. Thank you

**Comment by mconnelly8** [comment]
Closing this issue since it appears to be the same issue as #6968, which we moved into the current sprint.
