### ISSUE TITLE
Transaction processing fails at SolidityTypeAddress.isType

### ISSUE THREAD

**Issue by hiteshjoshi1** [ethereum/web3.js#876]
I am trying to run the Browser solidity ballot code.
When i try run the transaction. via web3 js
`
var BallotContract = web3.eth.contract(abi);
var ballotInstance = BallotContract.at('0xce1d754a51fba6f11880a4ceed015cbbfd43c374');
ballotInstance.giveRightToVote(web3.eth.accounts[1],{from: web3.eth.accounts[0]},function(error,result) {
if(error){
console.log(error);
}
  if(result){
	alert('Transaction Hash '+result);
  }
})
`
I get this

Uncaught TypeError: Cannot read property 'match' of undefined           address.js:23 
    at SolidityTypeAddress.isType (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:539:18)
    at https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:660:18
    at Array.filter (native)
    at SolidityCoder._requireType (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:659:36)
    at https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:850:21
    at Array.map (native)
    at SolidityCoder.getSolidityTypes (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:849:18)
    at SolidityCoder.encodeParams (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:691:30)
    at SolidityFunction.toPayload (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:4017:52)
    at SolidityFunction.sendTransaction (https://cdn.rawgit.com/ethereum/web3.js/develop/dist/web3.js:4088:24)

**Comment by urbanowiczPAWEL** [comment]
+1

**Comment by nivida** [comment]
Version 0.20.x got his last maintenance release with v0.20.7. Please update your code to the latest 1.0 version of Web3.js. Further details about the current project state are explained in the [release announcement](https://medium.com/@samuel_91690/web3-js-v1-0-0-beta-38-8d2bb6e73d0b) of version 1.0.0-beta.38.
