### ISSUE TITLE
Installation with npm fails (beta4)

### ISSUE THREAD

**Issue by vanruch** [ethereum/web3.js#927]
Web3 version: 1.0.0-beta.4 

Installation with npm fails with this message:
```
> web3@1.0.0-beta.4 postinstall /Users/ivan/Documents/node_modules/web3
> lerna bootstrap

sh: lerna: command not found
npm WARN enoent ENOENT: no such file or directory, open '/Users/ivan/Documents/package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! web3@1.0.0-beta.4 postinstall: `lerna bootstrap`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the web3@1.0.0-beta.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
**Logs:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'web3' ]
2 info using npm@5.2.0
3 info using node@v8.1.3
4 verbose npm-session 1a3617f1b44eae7b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/web3 520ms
8 silly pacote tag manifest for web3@latest fetched in 613ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule web3@1.0.0-beta.4 checking installable status
14 silly currentTree Documents
15 silly idealTree Documents
15 silly idealTree └── web3@1.0.0-beta.4
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add web3@1.0.0-beta.4
19 silly decomposeActions action count 8
20 silly decomposeActions fetch web3@1.0.0-beta.4
21 silly decomposeActions extract web3@1.0.0-beta.4
22 silly decomposeActions preinstall web3@1.0.0-beta.4
23 silly decomposeActions build web3@1.0.0-beta.4
24 silly decomposeActions install web3@1.0.0-beta.4
25 silly decomposeActions postinstall web3@1.0.0-beta.4
26 silly decomposeActions finalize web3@1.0.0-beta.4
27 silly decomposeActions refresh-package-json web3@1.0.0-beta.4
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /Users/ivan/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /Users/ivan/.npm/_locks/staging-1e5878cc238e33bc.lock for /Users/ivan/Documents/node_modules/.staging
32 silly doParallel extract 8
33 silly extract web3@1.0.0-beta.4
34 silly doReverseSerial remove 8
35 silly doSerial move 8
36 silly doSerial finalize 8
37 silly finalize /Users/ivan/Documents/node_modules/web3
38 silly doParallel refresh-package-json 8
39 silly refresh-package-json /Users/ivan/Documents/node_modules/web3
40 silly doParallel preinstall 8
41 silly preinstall web3@1.0.0-beta.4
42 info lifecycle web3@1.0.0-beta.4~preinstall: web3@1.0.0-beta.4
43 silly doSerial build 8
44 silly build web3@1.0.0-beta.4
45 info linkStuff web3@1.0.0-beta.4
46 silly linkStuff web3@1.0.0-beta.4 has /Users/ivan/Documents/node_modules as its parent node_modules
47 verbose linkBins web3@1.0.0-beta.4
48 verbose linkMans web3@1.0.0-beta.4
49 silly doSerial global-link 8
50 silly doParallel update-linked 8
51 silly doSerial install 8
52 silly install web3@1.0.0-beta.4
53 info lifecycle web3@1.0.0-beta.4~install: web3@1.0.0-beta.4
54 silly doSerial postinstall 8
55 silly postinstall web3@1.0.0-beta.4
56 info lifecycle web3@1.0.0-beta.4~postinstall: web3@1.0.0-beta.4
57 verbose lifecycle web3@1.0.0-beta.4~postinstall: unsafe-perm in lifecycle true
58 verbose lifecycle web3@1.0.0-beta.4~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ivan/Documents/node_modules/web3/node_modules/.bin:/Users/ivan/Documents/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
59 verbose lifecycle web3@1.0.0-beta.4~postinstall: CWD: /Users/ivan/Documents/node_modules/web3
60 silly lifecycle web3@1.0.0-beta.4~postinstall: Args: [ '-c', 'lerna bootstrap' ]
61 info lifecycle web3@1.0.0-beta.4~postinstall: Failed to exec postinstall script
62 verbose unlock done using /Users/ivan/.npm/_locks/staging-1e5878cc238e33bc.lock for /Users/ivan/Documents/node_modules/.staging
63 warn enoent ENOENT: no such file or directory, open '/Users/ivan/Documents/package.json'
64 verbose enoent This is related to npm not being able to find a file.
65 warn Documents No description
66 warn Documents No repository field.
67 warn Documents No README data
68 warn Documents No license field.
69 verbose stack Error: web3@1.0.0-beta.4 postinstall: `lerna bootstrap`
69 verbose stack spawn ENOENT
69 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
69 verbose stack     at emitTwo (events.js:125:13)
69 verbose stack     at ChildProcess.emit (events.js:213:7)
69 verbose stack     at maybeClose (internal/child_process.js:897:16)
69 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
70 verbose pkgid web3@1.0.0-beta.4
71 verbose cwd /Users/ivan/Documents
72 verbose Darwin 16.6.0
73 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "install" "web3"
74 verbose node v8.1.3
75 verbose npm  v5.2.0
76 error file sh
77 error code ELIFECYCLE
78 error errno ENOENT
79 error syscall spawn
80 error web3@1.0.0-beta.4 postinstall: `lerna bootstrap`
80 error spawn ENOENT
81 error Failed at the web3@1.0.0-beta.4 postinstall script.
81 error This is probably not a problem with npm. There is likely additional logging output above.
82 verbose exit [ 1, true ]
```

**Comment by H-KE** [comment]
I'm having the same issue

**Comment by vdrg** [comment]
+1

**Comment by cnasikas** [comment]
I'm also having the same issue

**Comment by iMuzz** [comment]
Run `npm i -g lerna` and try again!

**Comment by admazzola** [comment]
I have the same issue

**Comment by vanruch** [comment]
> Run npm i -g lerna and try again!

Yep, this helps.

**Comment by frozeman** [comment]
I will point to the local lerna in the next beta release.

**Comment by frozeman** [comment]
Should be fixed in beta.6
