### ISSUE TITLE
`_extend`ed method fails if response does not contain `result`.

### ISSUE THREAD

**Issue by xavierlepretre** [ethereum/web3.js#928]
In order to control TestRPC I declared the following:

```javascript
web3._extend({
    property: 'evm',
    methods: [
        new web3._extend.Method({
            name: 'mine',
            call: 'evm_mine',
            params: 0
        })
    ]
});
```
Then, when I call `web3.evm.mine(myCallback)`, I get the error:

```
Error: Invalid JSON RPC response: {"id":58,"jsonrpc":"2.0"}
      at Object.InvalidResponse (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
      at /usr/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:86:36
      at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

-------------

* Notice how the response does not contain any `result:` field.
* Note that, if I declare the same `web3.evm.mine` function the following way, it works as expected and does not have any error:

```javascript
web3.evm.mine = function(callback) {
    web3.currentProvider.sendAsync(
        {
            jsonrpc: "2.0",
            method: "evm_mine",
            params: [],
            id: new Date().getTime()
        },
        (error, result) => {
            console.log(error, result);
            callback(error, error ? undefined : result.result);
        });
};
```

* Note too, that if I declare an extended method that expects a value, as the following example, it works as expected too:

```javascript
web3._extend({
    property: 'evm',
    methods: [
        new web3._extend.Method({
            name: 'increaseTime',
            call: 'evm_increaseTime',
            params: 1,
            outputFormatter: web3._extend.formatters.outputBigNumberFormatter
        })
    ]
});
```

**Comment by frozeman** [comment]
The problem is that the result object in your response is missing: `{id":58,"jsonrpc":"2.0"}` which is not valid JSONRPC

**Comment by frozeman** [comment]
We do check for the result object, which would you leave it out?

**Comment by xavierlepretre** [comment]
Thank you. I will post that in TestRPC, then.
