### ISSUE TITLE
Cannot install web3@1.0.0-beta7 on Windows 10

### ISSUE THREAD

**Issue by songsb13** [ethereum/web3.js#941]
I tried to install web3 with npm

`npm install web3`

> web3@1.0.0-beta.7 postinstall C:\WINDOWS\system32\node_modules\web3
> ./node_modules/lerna/bin/lerna.js bootstrap

On windows, it says 

.' is not recognized as an internal or external command operable program or batch file

Here's error log

```
74 verbose stack Error: web3@1.0.0-beta.7 postinstall: `./node_modules/lerna/bin/lerna.js bootstrap
74 verbose stack Exit status 1
74 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
74 verbose stack     at emitTwo (events.js:125:13)
74 verbose stack     at EventEmitter.emit (events.js:213:7)
74 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
74 verbose stack     at emitTwo (events.js:125:13)
74 verbose stack     at ChildProcess.emit (events.js:213:7)
74 verbose stack     at maybeClose (internal/child_process.js:921:16)
74 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
75 verbose pkgid web3@1.0.0-beta.7
76 verbose cwd C:\WINDOWS\system32
77 verbose Windows_NT 10.0.14393
78 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "web3"
79 verbose node v8.2.1
80 verbose npm  v5.3.0
81 error code ELIFECYCLE
82 error errno 1
83 error web3@1.0.0-beta.7 postinstall: `./node_modules/lerna/bin/lerna.js bootstrap`
83 error Exit status 1
```

Is it fixable by changing setting/system variables on Windows?

**Comment by MichalZalecki** [comment]
Duplicate: https://github.com/ethereum/web3.js/issues/938

**Comment by frozeman** [comment]
web3@1.0.0-beta.10 should fix that
