### ISSUE TITLE
Unable to install web3 on macOS and Ubuntu 

### ISSUE THREAD

**Issue by PavelSheremetev** [ethereum/web3.js#964]
Hi!
For several days it has not been possible to install web 3 on Mac OS and Ubuntu:

macOS Seirra 10.12.6 (16G29)
npm -   5.3.0
node -   8.2.1

```
$ sudo npm install -g web3
Password:

> web3@1.0.0-beta.13 postinstall /usr/local/lib/node_modules/web3
> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! installInDir Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir  problem backing up package.json { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! installInDir   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! installInDir   errno: -13,
lerna ERR! installInDir   code: 'EACCES',
lerna ERR! installInDir   syscall: 'rename',
lerna ERR! installInDir   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! installInDir   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
lerna ERR! execute Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json' -> '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup'
lerna ERR! execute   stack: 'Error: EACCES: permission denied, rename \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json\' -> \'/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup\'',
lerna ERR! execute   errno: -13,
lerna ERR! execute   code: 'EACCES',
lerna ERR! execute   syscall: 'rename',
lerna ERR! execute   path: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json',
lerna ERR! execute   dest: '/usr/local/lib/node_modules/web3/packages/web3-eth-iban/package.json.lerna_backup' }
/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:132
    throw err
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/web3/lerna-debug.log.3223652852'
    at Object.fs.openSync (fs.js:652:18)
    at Function.writeFileSync [as sync] (/usr/local/lib/node_modules/web3/node_modules/write-file-atomic/index.js:117:17)
    at writeLogFile (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/utils/writeLogFile.js:43:29)
    at BootstrapCommand._complete (/usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:310:36)
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/Command.js:292:20
    at /usr/local/lib/node_modules/web3/node_modules/lerna/lib/commands/BootstrapCommand.js:140:11
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/web3/node_modules/async/lib/async.js:44:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web3@1.0.0-beta.13 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pavelseremetev/.npm/_logs/2017-07-31T12_29_47_448Z-debug.log
```

Ubuntu 16.04.2 LTS
npm - 3.5.2
node - v4.2.6

```
~/tmp#` npm install -g web3

> web3@1.0.0-beta.13 postinstall /usr/local/lib/node_modules/web3
> lerna bootstrap

lerna info version 2.0.0
lerna info Bootstrapping 19 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! addLocal Could not install /usr/local/lib/node_modules/web3/packages/web3-eth-abi
lerna ERR! execute npm ERR! Linux 4.4.0-83-generic
lerna ERR! execute npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
lerna ERR! execute npm ERR! node v4.2.6
lerna ERR! execute npm ERR! npm  v3.5.2
lerna ERR! execute
lerna ERR! execute npm ERR! No name provided in package.json
lerna ERR! execute npm ERR!
lerna ERR! execute npm ERR! If you need help, you may report this error at:
lerna ERR! execute npm ERR!     <https://github.com/npm/npm/issues>
lerna ERR! execute
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /usr/local/lib/node_modules/web3/packages/web3-eth-abi/npm-debug.log
lerna ERR! execute
lerna ERR! execute     at /usr/local/lib/node_modules/web3/node_modules/execa/index.js:210:11
lerna ERR! execute     at process._tickCallback (node.js:368:9)
lerna ERR! execute  callback with error
lerna ERR! execute  { [Error: Command failed: npm install
lerna ERR! execute npm ERR! addLocal Could not install /usr/local/lib/node_modules/web3/packages/web3-eth-abi
lerna ERR! execute npm ERR! Linux 4.4.0-83-generic
lerna ERR! execute npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
lerna ERR! execute npm ERR! node v4.2.6
lerna ERR! execute npm ERR! npm  v3.5.2
lerna ERR! execute
lerna ERR! execute npm ERR! No name provided in package.json
lerna ERR! execute npm ERR!
lerna ERR! execute npm ERR! If you need help, you may report this error at:
lerna ERR! execute npm ERR!     <https://github.com/npm/npm/issues>
lerna ERR! execute
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /usr/local/lib/node_modules/web3/packages/web3-eth-abi/npm-debug.log
lerna ERR! execute ]
lerna ERR! execute   stack: 'Error: Command failed: npm install\nnpm ERR! addLocal Could not install /usr/local/lib/node_modules/web3/packages/web3-eth-abi\nnpm ERR! Linux 4.4.0-83-generic\nnpm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"\nnpm ERR! node v4.2.6\nnpm ERR! npm  v3.5.2\n\nnpm ERR! No name provided in package.json\nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /usr/local/lib/node_modules/web3/packages/web3-eth-abi/npm-debug.log\n\n    at /usr/local/lib/node_modules/web3/node_modules/execa/index.js:210:11\n    at process._tickCallback (node.js:368:9)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm ERR! addLocal Could not install /usr/local/lib/node_modules/web3/packages/web3-eth-abi\nnpm ERR! Linux 4.4.0-83-generic\nnpm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"\nnpm ERR! node v4.2.6\nnpm ERR! npm  v3.5.2\n\nnpm ERR! No name provided in package.json\nnpm ERR! \nnpm ERR! If you need help, you may report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /usr/local/lib/node_modules/web3/packages/web3-eth-abi/npm-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "web3"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! web3@1.0.0-beta.13 postinstall: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web3@1.0.0-beta.13 postinstall script 'lerna bootstrap'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna bootstrap
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls web3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/tmp/npm-debug.log
```

**Comment by chainhead** [comment]
@PavelSheremetev curious to know, how you resolved this.

I am facing the same issue. On my Mac, the following worked. 
`sudo npm install -g web3@0.20.1`

However, it fails on Ubuntu.
```
sudo npm install -g web3@0.20.1
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/frozeman/bignumber.js-nolookahead.git /home/ubuntu/.npm/_cacache/tmp/git-clone-a4ffc1b8
npm ERR! /home/ubuntu/.npm/_cacache/tmp/git-clone-a4ffc1b8/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-08-24T07_22_35_596Z-debug.log
```

**Comment by PavelSheremetev** [comment]
Нi @chainhead. 
Ubuntu 16.04.2 LTS \n \l

ubuntu@host:~$ sudo npm install -g web3@0.20.1
/usr/local/lib
└─┬ web3@0.20.1
  ├── bignumber.js@2.0.7  (git+https://github.com/frozeman/bignumber.js-nolookahead.git#57692b3ecfc98bbdd6b3a516cb2353652ea49934)
  ├── crypto-js@3.1.8
  ├── utf8@2.1.2
  ├── xhr2@0.1.4
  └── xmlhttprequest@1.8.0

ubuntu@host:~$


The new OS is installed without problems. Check the rights and owner of the directory and subdirectories /home/ubuntu/.npm/
