### ISSUE TITLE
IpcProvider does not work in Web3 1.0.0-beta16

### ISSUE THREAD

**Issue by onbjerg** [ethereum/web3.js#987]
Using the IpcProvider throws the following error:

```
/Users/onbjerg/Workspace/[redacted]/node_modules/web3/packages/web3-providers-ipc/src/index.js:36
    this.connection = net.connect({path: this.path});
                         ^

TypeError: Cannot read property 'connect' of undefined
    at new IpcProvider (/Users/onbjerg/Workspace/[redacted]/node_modules/web3/packages/web3-providers-ipc/src/index.js:36:26)
    at Object.<anonymous> (/Users/onbjerg/Workspace/[redacted]/sandbox/mess.js:6:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by onbjerg** [comment]
Never mind, just needed to pass in the net module from Node.js. My bad.
